[server]
headless = true
port = 8501
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

# Rejtett menü – a Streamlit natív téma váltó ne írja felül a saját Megjelenésünket
[client]
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#e7e5e4"
backgroundColor = "#fafaf9"
secondaryBackgroundColor = "#f5f5f4"
textColor = "#1a1a1a"
font = "sans serif" 