# Becenevek, ragadványnevek kérdések a quiz alkalmazáshoz
# Történelmi személyiségek híres becenevei/ragadványnevei – kortárs válaszopciókkal

_TOPIC = "becenevek"


def _q(question, correct, options, explanation, topic=_TOPIC):
    "''Segédfüggvény: kompakt kérdés létrehozása.''"
    return {"question": question, "options": options, "correct": correct, "explanation": explanation, "topic": topic}


BECENEVEK_QUESTIONS = [
    _q(
        "Kit neveztek 'Isten Ostorá'-nak? Hun uralkodó, akit a magyarok népi hagyomány szerint őseikként tartottak számon.",
        0,
        ["Attila", "Alarik", "Genserik", "Theodorik"],
        "Attila (406–453) hun király, 'Isten Ostora' (Flagellum Dei). A hunokat a magyar népi hagyomány a magyarok őseiként tartotta számon.",
    ),
    _q(
        "Kit neveztek 'Világverő'-nek, más néven az 'Isteni Büntetés'-nek? Mongol uralkodó, akinek utódai 1241-ben pusztították Magyarországot.",
        0,
        ["Dzsingisz kán", "Batu kán", "Kublaj kán", "Timur Lenk"],
        "Dzsingisz kán (1162–1227) a Mongol Birodalom alapítója, a 'Világverő'. Unokája, Batu kán vezette a tatárjárást Magyarország ellen.",
    ),
    _q(
        "Kit neveztek 'Nyugat Pusztítójá'-nak? Mongol hadvezér, a tatárjárás (1241–42) közvetlen vezére Magyarországon.",
        0,
        ["Batu kán", "Dzsingisz kán", "Ögödej kán", "Möngke kán"],
        "Batu kán (1207–1255) Dzsingisz kán unokája, az Arany Horda alapítója. Ő vezette a mongol hadjáratot Kelet-Európa és Magyarország ellen.",
    ),
    _q(
        "Kit neveztek a 'Győzhetetlen Hadvezér'-nek? Mongol tábornok, a muhi csata (1241) valódi stratégája.",
        0,
        ["Szübotaj", "Batu kán", "Dzsebe", "Dzsingisz kán"],
        "Szübotaj (1175–1248) Dzsingisz kán és Batu kán legtehetségesebb hadvezére. A muhi csatában ő tervezte meg a magyar sereg bekerítését.",
    ),
    _q(
        "Kit neveztek 'a Nagyszerű'-nek és 'a Hódító'-nak? Oszmán szultán, aki 1526-ban Mohácsnál legyőzte a magyar sereget, majd 1541-ben elfoglalta Budát.",
        0,
        ["I. (Hódító) Szulejmán", "II. Mehmed", "I. Szelim", "II. Bajezid"],
        "I. Szulejmán (1494–1566) az Oszmán Birodalom leghatalmasabb szultánja. Mohács 1526 és Buda elfoglalása 1541 a nevéhez fűződik.",
    ),
    _q(
        "Kit neveztek 'a Hódító'-nak (Fatih)? Oszmán szultán, akit Nándorfehérvárnál Hunyadi János megvert 1456-ban.",
        0,
        ["II. Mehmed", "I. Szulejmán", "I. Bajezid", "II. Murád"],
        "II. Mehmed (1432–1481) 'Fatih' (a Hódító), Konstantinápoly meghódítója 1453-ban. Nándorfehérvárnál (1456) Hunyadi János és Kapisztrán János verte meg.",
    ),
    _q(
        "Kit neveztek 'a Bosszúálló'-nak? Oszmán szultán, aki a várnai csatában (1444) legyőzte I. Ulászló magyar királyt.",
        0,
        ["II. Murád szultán", "II. Mehmed", "I. Bajezid", "I. Szelim"],
        "II. Murád (1404–1451) oszmán szultán. A várnai csatában (1444) legyőzte és megölte I. Ulászló magyar és lengyel királyt.",
    ),
    _q(
        "Kit neveztek 'Bécs Ostromlójá'-nak? Oszmán nagyvezír, aki 1683-ban ostromolta Bécset, de vereséget szenvedett és kivégezték.",
        0,
        ["Kara Musztafa", "Köprülü Mehmed", "Szokollú Mehmed", "Ibrahim pasa"],
        "Kara Musztafa (1634–1683) oszmán nagyvezír. 1683-ban ostromolta Bécset, de Jan Sobieski és a szövetségesek felmentették. Kudarcáért a szultán kivégeztette.",
    ),
    _q(
        "Kit neveztek 'a Kegyetlen Pasá'-nak? Oszmán-albán hadvezér, Eger vidékének rettegett rablója.",
        0,
        ["Ali pasa (Arnaut)", "Ibrahim pasa", "Kara Musztafa", "Szinán pasa"],
        "Arnaut Ali pasa oszmán-albán hadvezér, akit kegyetlenségéről ismertek. Eger és környéke rettegett rablója volt a török hódoltság idején.",
    ),
    _q(
        "Kit neveztek 'Buda Felszabadítójá'-nak? Lotaringiai herceg, aki 1686-ban visszafoglalta Budát a törököktől.",
        0,
        ["Lotaringiai Károly", "Savoyai Jenő herceg", "Jan Sobieski", "Rüdiger von Starhemberg"],
        "Lotaringiai Károly (1643–1690) a Szent Liga hadvezére, aki 1686-ban visszafoglalta Budát 145 év török uralom után.",
    ),
    _q(
        "Kit neveztek 'a Nemes Lovag'-nak és 'a Törökverő herceg'-nek? Savoyai származású hadvezér, aki a zentai csatában (1697) döntő győzelmet aratott.",
        0,
        ["Savoyai Jenő herceg", "Lotaringiai Károly", "Jan Sobieski", "Rüdiger von Starhemberg"],
        "Savoyai Jenő herceg (1663–1736) a Habsburg Birodalom legnagyobb hadvezére. A zentai csata (1697) és a törökök kiűzése az ő nevéhez fűződik.",
    ),
    _q(
        "Kit neveztek 'Bécs Megmentőjé'-nek és 'a Kereszténység Pajzsá'-nak? Lengyel király, aki 1683-ban felmentette Bécset a török ostrom alól.",
        0,
        ["Jan Sobieski", "Lotaringiai Károly", "Savoyai Jenő herceg", "Rüdiger von Starhemberg"],
        "III. (Jan) Sobieski (1629–1696) lengyel király. 1683-ban a bécsi felmentő csata vezetőjeként döntő győzelmet aratott Kara Musztafa felett.",
    ),
    _q(
        "Kit neveztek 'Bécs Védőjé'-nek? Osztrák katonai parancsnok, aki 1683-ban tartotta Bécs ostromát a felmentő sereg megérkezéséig.",
        0,
        ["Rüdiger von Starhemberg", "Jan Sobieski", "Lotaringiai Károly", "Savoyai Jenő herceg"],
        "Rüdiger von Starhemberg (1638–1701) osztrák tábornok. 1683-ban Bécs katonai parancsnoka, aki két hónapig tartotta a várost Kara Musztafa ostroma ellen.",
    ),
    _q(
        "Kit neveztek 'a Törökverő Ispán'-nak, más néven 'Pipo da Ozorá'-nak? Firenzei származású hadvezér, Zsigmond király temesi ispánja, a déli végvárvonal kiépítője.",
        0,
        ["Ozorai Pipo (Filippo Scolari)", "Hunyadi János", "Kinizsi Pál", "Szilágyi Mihály"],
        "Ozorai Pipo (Filippo Scolari, 1369–1426) firenzei születésű, Zsigmond király hadvezére és temesi ispán. A déli végvárvonal kiépítésében kulcsfontosságú szerepet játszott.",
    ),
    _q(
        "Kit neveztek 'a Törökverő Császár'-nak és 'a Visszafoglaló'-nak? Osztrák uralkodó, akinek idején foglalták vissza Budát a törököktől.",
        0,
        ["I. Lipót", "I. Ferenc József", "II. József", "Mária Terézia"],
        "I. Lipót (1640–1705) Habsburg császár és magyar király. Az ő uralkodása alatt zajlott Buda visszafoglalása (1686) és a törökök kiűzése Magyarországról.",
    ),
    _q(
        "Kit neveztek 'a Jó Királynéasszony'-nak? Osztrák uralkodónő, akihez a 'Vitam et sanguinem!' felkiáltás kötődik – a magyar nemesség mögé állt a poroszok ellen.",
        0,
        ["Mária Terézia", "I. Lipót", "II. József", "I. Ferenc József"],
        "Mária Terézia (1717–1780) Habsburg királynő. 1741-ben Pozsonyban a magyar rendek 'Vitam et sanguinem!' (Életünket és vérünket!) felkiáltással ajánlották fel támogatásukat.",
    ),
    _q(
        "Kit neveztek 'a Kalapos király'-nak? Osztrák uralkodó, aki nem koronáztatta meg magát, de sok reformot hozott.",
        0,
        ["II. József", "I. Lipót", "Mária Terézia", "I. Ferenc József"],
        "II. József (1741–1790) 'a Kalapos király', mert nem koronáztatta meg magát a Szent Koronával. Felvilágosult abszolutista reformokat vezetett be.",
    ),
    _q(
        "Kit neveztek 'az Öreg Császár'-nak? Osztrák uralkodó, aki 68 évig uralkodott, és az 1867-es kiegyezés kötődik a nevéhez.",
        0,
        ["I. Ferenc József", "II. József", "I. Lipót", "Mária Terézia"],
        "I. Ferenc József (1830–1916) 68 évig uralkodott. Az 1867-es kiegyezéssel létrehozta az Osztrák–Magyar Monarchiát.",
    ),
    _q(
        "Kit neveztek 'Európa Kocsisá'-nak és 'a Reakció Mesteré'-nek? Rajnai-osztrák herceg, a magyar reformmozgalmak elnyomója.",
        0,
        ["Metternich herceg", "Haynau tábornok", "Windisch-Grätz herceg", "Bismarck"],
        "Klemens von Metternich (1773–1859) osztrák kancellár, a bécsi kongresszus szervezője. A restauráció és a cenzúra jelképe, a magyar reformmozgalmak legfőbb akadálya.",
    ),
    _q(
        "Kit neveztek 'a Bresciai Hiéná'-nak? Osztrák tábornok, az 1849 utáni megtorlás végrehajtója, az aradi vértanúk kivégzésének elrendelője.",
        0,
        ["Haynau tábornok", "Windisch-Grätz herceg", "Metternich herceg", "Jelacic bán"],
        "Julius Jacob von Haynau (1786–1853) osztrák tábornok. A szabadságharc leverése után a megtorlás végrehajtója, az aradi vértanúk kivégzését 1849. október 6-án rendelte el.",
    ),
    _q(
        "Kit neveztek 'a Reakciós Herceg'-nek? Osztrák hadvezér, aki 1848-ban visszafoglalta Pest-Budát.",
        0,
        ["Windisch-Grätz herceg", "Haynau tábornok", "Metternich herceg", "Jelacic bán"],
        "Alfred Windisch-Grätz herceg (1787–1862) osztrák tábornagy. 1848 decemberében foglalta el Pest-Budát, de 1849 tavaszán a magyar honvédsereg visszaverte.",
    ),
    _q(
        "Kit neveztek 'az Eperjesi Mészáros'-nak? Olasz-nápolyi tábornok, aki az 1687-es eperjesi vértörvényszéken protestáns polgárokat és nemeseket végeztetett ki koholt vádak alapján.",
        0,
        ["Caraffa Antonio", "Haynau tábornok", "Windisch-Grätz herceg", "Metternich herceg"],
        "Antonio Caraffa (1646–1693) nápolyi származású Habsburg tábornok. Az 1687-es eperjesi vértörvényszéken 24 protestáns nemest és polgárt végeztetett ki.",
    ),
    _q(
        "Kit neveztek 'az Első Esztergomi Érsek'-nek? Cseh-bencés szerzetes, aki István király koronáját Rómából hozta.",
        0,
        ["Astrik (Anastasius) érsek", "Szent Adalbert", "Szent Gellért", "Pilgrim passaui püspök"],
        "Astrik (Anastasius) érsek (?–1036 k.) bencés szerzetes, az első esztergomi érsek. Ő hozta el Rómából a pápai koronát István király számára 1000/1001-ben.",
    ),
    _q(
        "Kit neveztek 'a Keresztesek Apostolá'-nak és 'Nándorfehérvár Hősé'-nek? Olasz ferences szerzetes, az 1456-os nándorfehérvári diadal mozgatója.",
        0,
        ["Kapisztrán János", "Astrik érsek", "Szent Gellért", "Ozorai Pipo"],
        "Kapisztrán (Giovanni da Capestrano) Szent János (1386–1456) olasz ferences szerzetes. A nándorfehérvári csatában (1456) a keresztes seregét vezette Hunyadi János oldalán.",
    ),
    _q(
        "Kit neveztek 'a Renegát Pasá'-nak? Szláv származású, keresztény születésű hadvezér, aki oszmán tábornok lett.",
        0,
        ["Palkovics (Palkowitsch) Ibrahim", "Ali pasa (Arnaut)", "Szinán pasa", "Kara Musztafa"],
        "Palkovics Ibrahim pasa szláv származású renegát, aki felvette az iszlámot és oszmán tábornok lett. Keresztény születése ellenére a szultán szolgálatába állt.",
    ),
    _q(
        "Kit neveztek 'a Kegyetlen'-nek? Albán származású oszmán hadvezér, Észak-Magyarország rettegett fosztogatója.",
        0,
        ["Jahja pasa", "Ali pasa (Arnaut)", "Kara Musztafa", "Szinán pasa"],
        "Jahja pasa albán származású oszmán hadvezér. Kegyetlenségéről és Észak-Magyarország fosztogatásáról volt hírhedt.",
    ),
    _q(
        "Kit neveztek 'Európa Csendőré'-nek? Orosz cár, aki 1849-ben sereget küldött a magyar szabadságharc leverésére.",
        0,
        ["I. Miklós cár", "II. Sándor cár", "Paszkevics tábornagy", "Sztálin"],
        "I. Miklós cár (1796–1855) orosz uralkodó. 1849-ben 200 000 fős orosz sereget küldött Magyarországra a szabadságharc leverésére Ferenc József kérésére.",
    ),
    _q(
        "Kit neveztek 'a Varsó Hősé'-nek és 'Magyarország Legyőzőjé'-nek? Orosz tábornagy, az 1849-es orosz intervenció parancsnoka.",
        0,
        ["Paszkevics tábornagy", "I. Miklós cár", "Haynau tábornok", "Zsukov marsall"],
        "Ivan Fjodorovics Paszkevics (1782–1856) orosz tábornagy. Korábban Varsót foglalta vissza (1831), majd 1849-ben a magyarországi orosz intervenció parancsnoka volt.",
    ),
    _q(
        "Kit neveztek 'a Népek Atyja' (propaganda) és 'a Vörös Cár' néven? Grúz származású szovjet diktátor, Rákosi legjobb tanítványa példaképe, a szovjet befolyás forrása.",
        0,
        ["Sztálin", "I. Miklós cár", "Zsukov marsall", "Mikojan"],
        "Joszif Visszarionovics Sztálin (1878–1953) a Szovjetunió diktátora. Rákosi Mátyás 'Sztálin legjobb magyar tanítványa' volt, Magyarország szovjet befolyása Sztálin nevéhez fűződik.",
    ),
    _q(
        "Kit neveztek 'a Győzelem Marsalljá'-nak? Orosz marsall, aki Budapest ostromát irányította 1944–45-ben.",
        0,
        ["Zsukov marsall", "Paszkevics tábornagy", "Sztálin", "Mikojan"],
        "Georgij Konsztantyinovics Zsukov (1896–1974) szovjet marsall, a II. világháború legnagyobb szovjet hadvezére. Budapest ostromát (1944–45) az ő irányítása alatt vívták.",
    ),
    _q(
        "Kit neveztek 'a Túlélő'-nek és 'a Kereskedő'-nek? Örmény származású szovjet politikus, aki 1956-ban Budapestre érkezett a szovjet döntés meghozatalára.",
        0,
        ["Mikojan", "Szuszlov", "Zsukov marsall", "Sztálin"],
        "Anasztasz Mikojan (1895–1978) örmény származású szovjet politikus. 1956 októberében Budapestre érkezett, és részt vett a szovjet beavatkozásról szóló döntésben.",
    ),
    _q(
        "Kit neveztek 'a Szürke Eminenciás'-nak és 'az Ideológus'-nak? Orosz szovjet politikus, az 1956-os beavatkozás fő szorgalmazója.",
        0,
        ["Szuszlov", "Mikojan", "Zsukov marsall", "Sztálin"],
        "Mihail Szuszlov (1902–1982) a Szovjetunió vezető ideológusa. 1956-ban ő volt a magyarországi katonai beavatkozás egyik fő szorgalmazója a Politbüróban.",
    ),
    _q(
        "Kit neveztek 'a Holokauszt Logisztikusá'-nak és 'az Irodai Gyilkos'-nak? Osztrák-német SS-tiszt, a magyar zsidók deportálásának szervezője 1944-ben.",
        0,
        ["Eichmann Adolf", "Sztálin", "Haynau tábornok", "Caraffa Antonio"],
        "Adolf Eichmann (1906–1962) SS-Obersturmbannführer. 1944-ben Budapestre érkezett és megszervezte a magyar zsidók deportálását Auschwitzba. Izraelben elfogták és kivégezték.",
    ),
    _q(
        "Kit neveztek 'a Vaskancellár'-nak? Porosz államférfi, akinek korában alakult ki az Osztrák–Magyar Monarchia politikai kerete.",
        0,
        ["Bismarck", "Metternich herceg", "Moltke idősebb", "I. Ferenc József"],
        "Otto von Bismarck (1815–1898) a Német Birodalom első kancellárja. Az 1866-os königgrätzi csata következtében Ausztria kiszorult Németországból, ami az 1867-es kiegyezéshez vezetett.",
    ),
    _q(
        "Kit neveztek 'a Hallgatag Stratégá'-nak? Porosz tábornok, a königgrätzi csata (1866) győztese, ami az osztrák–magyar kiegyezés előzménye lett.",
        0,
        ["Moltke idősebb", "Bismarck", "Metternich herceg", "Windisch-Grätz herceg"],
        "Helmuth von Moltke idősebb (1800–1891) porosz vezérkari főnök. A königgrätzi csatában (1866) legyőzte Ausztriát, ami kiszorította Németországból és a kiegyezéshez vezetett.",
    ),
    _q(
        "Kit neveztek 'a Kis Káplár'-nak és 'Európa Urá'-nak? Korzikai-francia hadvezér és császár, aki a győri csatát (1809) és a schönbrunni békét is érinti Magyarország szempontjából.",
        0,
        ["Napóleon Bonaparte", "Wellington herceg", "I. Sándor cár", "Metternich herceg"],
        "Napóleon Bonaparte (1769–1821) francia császár. 1809-ben a győri csata és a schönbrunni béke közvetlenül érintette Magyarországot, kiáltványt is intézett a magyarokhoz.",
    ),
    _q(
        "Kit neveztek 'a Raguzai herceg'-nek? Francia marsall, az Illír tartományok kormányzója, akinek szomszédos hatása érintette Magyarországot.",
        0,
        ["Marmont marsall", "Napóleon Bonaparte", "Ney marsall", "Murat"],
        "Auguste de Marmont (1774–1852) francia marsall, Raguza (Dubrovnik) hercege. Az Illír tartományok kormányzójaként Magyarország szomszédságában működött.",
    ),
    _q(
        "Kit neveztek 'II. Rákóczi Ferenc festőjé'-nek? Szász származású portréfestő, aki a fejedelem híres portréját festette.",
        0,
        ["Mányoki Ádám", "Kupeczky János", "Bercsényi Miklós", "Maulbertsch"],
        "Mányoki Ádám (1673–1757) szász származású portréfestő. II. Rákóczi Ferenc ikonikus portréja az ő alkotása, a magyar portréfestészet egyik első jelentős képe.",
    ),
    _q(
        "Kit neveztek 'a Zongorakirály'-nak és 'a Virtuóz'-nak? Magyar-német kettős identitású zeneszerző, a zongorajáték legnagyobb mestere.",
        0,
        ["Franz Liszt (Liszt Ferenc)", "Chopin", "Wagner", "Brahms"],
        "Liszt Ferenc (1811–1886) a romantika legnagyobb zongoravirtuóza. Magyar identitású, de német anyanyelvű zseni, a szimfonikus költemény megteremtője.",
    ),
    _q(
        "Kit neveztek 'a Budapesti Schindler'-nek és 'a Mentő Konzul'-nak? Svájci diplomata, aki tízezer zsidót mentett meg 1944–45-ben Budapesten.",
        0,
        ["Carl Lutz", "Raoul Wallenberg", "Giorgio Perlasca", "Angelo Rotta"],
        "Carl Lutz (1895–1975) svájci alkonzul Budapesten. Schutzpass (védlevél) rendszerével mintegy 62 000 magyar zsidó életét mentette meg a Holokauszt idején.",
    ),
    _q(
        "Kit neveztek 'a Svéd Angyal'-nak és 'a Mártír Diplomata'-nak? Svéd diplomata, aki tízezreket mentett Budapesten, majd eltűnt a szovjeteknél.",
        0,
        ["Raoul Wallenberg", "Carl Lutz", "Giorgio Perlasca", "Oskar Schindler"],
        "Raoul Wallenberg (1912–1947?) svéd diplomata. 1944-ben Budapesten svéd védlevelekkel tízezrek életét mentette meg. A szovjetek letartóztatták, sorsa máig tisztázatlan.",
    ),
    _q(
        "Kit neveztek 'az Olasz Schindler'-nek? Olasz üzletember, aki spanyol konzulnak adta ki magát, és zsidókat mentett Budapesten.",
        0,
        ["Giorgio Perlasca", "Carl Lutz", "Raoul Wallenberg", "Angelo Rotta"],
        "Giorgio Perlasca (1910–1992) olasz üzletember. 1944–45-ben a spanyol követség munkatársaként adta ki magát Budapesten, és mintegy 5200 magyar zsidó életét mentette meg.",
    ),
    _q(
        "Kit neveztek 'a Fekete-erdei Forradalmár'-nak? Német politikus, akinek 1848-as forradalmi tevékenysége az európai forradalmak összefüggésébe illeszkedik.",
        0,
        ["Friedrich Hecker", "Garibaldi", "Mazzini", "Kossuth Lajos"],
        "Friedrich Hecker (1811–1881) német forradalmár. Az 1848-as badeni felkelés vezetője, az európai forradalmak hulláma részeként a magyar szabadságharccal párhuzamosan küzdött.",
    ),
    _q(
        "Kit neveztek 'a Cionizmus Atyjá'-nak? Galíciai zsidó származású újságíró, aki Budapesten született, és a zsidó-magyar identitás határán állt.",
        0,
        ["Theodor Herzl", "Max Nordau", "Chaim Weizmann", "Jabotinszkij"],
        "Theodor Herzl (1860–1904) Budapesten született újságíró és politikus. A modern politikai cionizmus megalapítója, Der Judenstaat című művével indította el a mozgalmat.",
    ),
    _q(
        "Kit neveztek 'a Leghíresebb Hadifotós'-nak? Magyar születésű fotográfus, aki külföldön vált világhírűvé, eredeti neve Friedmann Endre.",
        0,
        ["Robert Capa", "André Kertész", "Cartier-Bresson", "David Seymour"],
        "Robert Capa (Friedmann Endre, 1913–1954) magyar születésű hadifotós. A D-Day partraszállás és a spanyol polgárháború ikonikus fotóinak készítője. Indokínában aknára lépve halt meg.",
    ),
    _q(
        "Kit neveztek 'a Menekülő Kán'-nak és 'a Kunok Fejedelmé'-nek? Kun vezér, akit IV. Béla befogadott a tatárjárás előestéjén.",
        0,
        ["Kötöny (Kotyan) kán", "Batu kán", "Dzsingisz kán", "IV. Béla"],
        "Kötöny kán a kunok fejedelme volt. IV. Béla befogadta a kunokat Magyarországra, de magyar urak meggyilkolták Kötönyt, ami a kunok elvonulásához vezetett a tatárjárás előtt.",
    ),
    _q(
        "Kit neveztek 'a Maros-vidék Urá'-nak? Bolgár-török törzsfő, az utolsó törzsi vezér, akit Szent István legyőzött.",
        0,
        ["Ajtony (Achtum)", "Koppány", "Gyula", "Glad"],
        "Ajtony (Achtum) bolgár-török eredetű törzsfő a Maros vidékén. Szent István Csanád vezérrel győzte le, ő volt az utolsó független törzsi vezér Magyarországon.",
    ),
    _q(
        "Kit neveztek 'a Bánság Urá'-nak? Bolgár törzsfő, aki Anonymus szerint a honfoglalók ellen harcolt.",
        0,
        ["Glad", "Ajtony", "Menumorut", "Zalán"],
        "Glad bolgár törzsfő, aki Anonymus Gesta Hungaroruma szerint a Bánságot uralta és a honfoglaló magyarok ellen harcolt. Történelmi létezése vitatott.",
    ),
    _q(
        "Kit neveztek 'a Háromnyelvű'-nek és 'Bihar Urá'-nak? Anonymus szerint Bihar várának ura volt, akinek származása vitatott.",
        0,
        ["Menumorut", "Glad", "Ajtony", "Zalán"],
        "Menumorut Anonymus szerint Bihar várának és környékének ura, aki a honfoglaló magyaroknak ellenállt. Származása (vlach/kazár/bolgár) és történelmi léte vitatott.",
    ),
    # --- Magyar történelmi személyiségek ---
    _q(
        "Kit neveztek 'a Lovagkirály'-nak és 'a Szent'-nek? Magyar király, a lovagi eszmény megtestesítője, akit 1192-ben avattak szentté.",
        0,
        ["I. (Szent) László király", "Kálmán (Könyves)", "Szent István", "I. Géza"],
        "I. (Szent) László (1077–1095) a lovagi erények megtestesítője. Kunok elleni győzelmeiről és igazságosságáról ismert, 1192-ben avatták szentté.",
    ),
    _q(
        "Kit neveztek 'a Jeruzsálemi'-nek és 'az Aranybullás'-nak? Magyar király, aki keresztes hadjáratot vezetett és 1222-ben kiadta az Aranybullát.",
        0,
        ["II. András", "IV. Béla", "III. Béla", "I. (Szent) László"],
        "II. András (1205–1235) keresztes hadjáratot vezetett a Szentföldre, és 1222-ben kiadta az Aranybullát, az első magyar 'alkotmányos' okiratot.",
    ),
    _q(
        "Kit neveztek 'a Kun'-nak? Magyar király, aki kun anyától született, és akit saját kun katonái gyilkoltak meg.",
        0,
        ["IV. (Kun) László", "III. András", "V. István", "IV. Béla"],
        "IV. (Kun) László (1272–1290) kun anyától, Erzsébet kun hercegnőtől született. Kun szokásokat követett, saját kun testőrei gyilkolták meg.",
    ),
    _q(
        "Kit neveztek 'az Országépítő'-nek és 'a Második Honalapító'-nak? Magyar király, aki a tatárjárás után újjáépítette az országot.",
        0,
        ["IV. Béla", "II. András", "III. András", "I. (Szent) László"],
        "IV. Béla (1235–1270) a tatárjárás (1241–42) pusztítása után újjáépítette Magyarországot. Kővárak építésével és telepítéssel erősítette meg az országot.",
    ),
    _q(
        "Kit neveztek 'az Utolsó Árpád'-nak? Az Árpád-ház utolsó sarja, akinek halálával kihalt a dinasztia.",
        0,
        ["III. András", "IV. (Kun) László", "I. Károly Róbert", "Csák Máté"],
        "III. András (1290–1301) az Árpád-ház utolsó férfi tagja. 1301-ben fiúörökös nélkül halt meg, amivel kihalt az Árpád-dinasztia.",
    ),
    _q(
        "Kit neveztek 'a Luxemburgi'-nak és 'a Zarándok király'-nak? Magyar király, aki sokat utazott Európában és összehívta a konstanzi zsinatot.",
        0,
        ["Zsigmond király", "I. Lajos (Nagy)", "I. Károly Róbert", "Hunyadi Mátyás"],
        "Luxemburgi Zsigmond (1387–1437) magyar király, német-római császár és cseh király. Sokat utazott, Budát tette fővárossá, és összehívta a konstanzi zsinatot.",
    ),
    _q(
        "Kit neveztek 'Igazságos'-nak és 'Corvin'-nak? Magyar király, akinek igazságossága a nép körében legendává vált.",
        0,
        ["Hunyadi Mátyás", "II. Ulászló", "V. László", "Szilágyi Mihály"],
        "Hunyadi (Corvin) Mátyás (1458–1490) a reneszánsz magyar királyság szimbóluma. 'Meghalt Mátyás király, oda az igazság' – tartja a népi mondás.",
    ),
    _q(
        "Kit neveztek 'Dobzse László'-nak? Magyar király, aki a cseh 'dobže' (= jól van) szóról kapta nevét, mert mindent jóváhagyott.",
        0,
        ["II. Ulászló", "Hunyadi Mátyás", "II. Lajos", "Szapolyai János"],
        "II. Ulászló (1490–1516) Jagelló-házi király. A 'dobzse' (= jól van) szavajárásáról kapta gúnynevét, mert gyenge akaratú uralkodó volt.",
    ),
    _q(
        "Kit neveztek 'az Első választott fejedelem'-nek? Erdély első fejedelme, Szapolyai János fia.",
        0,
        ["János Zsigmond", "Báthory István", "Bethlen Gábor", "Bocskai István"],
        "János Zsigmond (1540–1571) Szapolyai János és Izabella királyné fia, Erdély első választott fejedelme. Az erdélyi fejedelemség alapítója.",
    ),
    _q(
        "Kit neveztek 'a Lengyel király'-nak és 'a Győzhetetlen'-nek? Erdélyi fejedelem, aki Lengyelország királya is lett.",
        0,
        ["Báthory István", "Báthory Gábor", "János Zsigmond", "Bethlen Gábor"],
        "Báthory István (1533–1586) erdélyi fejedelem, majd 1576-tól Lengyelország királya. Kiváló hadvezér, soha nem veszített csatát.",
    ),
    _q(
        "Kit neveztek 'az Őrült fejedelem'-nek? Erdélyi fejedelem, aki kegyetlenségéről és kiszámíthatatlanságáról volt hírhedt.",
        0,
        ["Báthory Gábor", "Báthory István", "Bethlen Gábor", "Apafi Mihály"],
        "Báthory Gábor (1589–1613) erdélyi fejedelem. Kegyetlen és kiszámíthatatlan uralkodása miatt saját emberei ölték meg.",
    ),
    _q(
        "Kit neveztek 'az Utolsó Erdélyi fejedelem'-nek? Törökbarát, gyenge fejedelem, akivel lényegében véget ért az erdélyi fejedelemség önállósága.",
        0,
        ["Apafi Mihály", "II. Rákóczi Ferenc", "Thököly Imre", "Báthory Gábor"],
        "I. Apafi Mihály (1632–1690) az utolsó valódi erdélyi fejedelem. Törökbarát, gyenge uralkodó, akinek idején Erdély elveszítette önállóságát.",
    ),
    _q(
        "Kit neveztek 'a Bujdosó Fejedelem'-nek és 'a Szabadságharc vezéré'-nek? Erdélyi fejedelem, aki Rodostóban halt meg számüzetésben.",
        0,
        ["II. Rákóczi Ferenc", "Thököly Imre", "Apafi Mihály", "Bercsényi Miklós"],
        "II. Rákóczi Ferenc (1676–1735) a Rákóczi-szabadságharc (1703–1711) vezére. A szatmári béke után száműzetésbe vonult, Rodostóban halt meg.",
    ),
    _q(
        "Kit neveztek 'a Fehér Lovag'-nak, 'Törökverő'-nek és 'a Kereszténység pajzsá'-nak? Magyar hadvezér, a nándorfehérvári diadal (1456) hőse.",
        0,
        ["Hunyadi János", "Kinizsi Pál", "Mátyás király", "Kapisztrán János"],
        "Hunyadi János (1407–1456) Magyarország kormányzója, a törökök elleni harcok legnagyobb magyar hadvezére. A nándorfehérvári csata (1456) diadala az ő nevéhez fűződik.",
    ),
    _q(
        "Kit neveztek 'a Vasember'-nek és 'a Malomkő-hős'-nek? Magyar hadvezér, akiről az a legenda szól, hogy malomkövet emelt fel.",
        0,
        ["Kinizsi Pál", "Hunyadi János", "Mátyás király", "Dobó István"],
        "Kinizsi Pál (?–1494) Mátyás király legendás hadvezére. A néphagyomány szerint a kenyérszeri csata után két karddal táncolt a holttestek között, és malomkövet emelt fel puszta kézzel.",
    ),
    _q(
        "Kit neveztek 'a Szigetvári Hős'-nek és 'az Önfeláldozó'-nak? Magyar-horvát főúr, aki 1566-ban hősi kirohanást vezetett Szigetvárnál.",
        0,
        ["Zrínyi Miklós (szigetvári)", "Dobó István", "Szondi György", "Zrínyi Miklós (a költő)"],
        "Zrínyi Miklós (1508–1566) a szigetvári hős. 1566-ban I. Szulejmán ostroma alatt hősi kirohanást vezetett, feláldozva életét, hogy feltartóztassa a törököket.",
    ),
    _q(
        "Kit neveztek 'a Hadtudós'-nak és 'Mars és Pallas fiá'-nak? Magyar költő és hadvezér, a Szigeti veszedelem szerzője.",
        0,
        ["Zrínyi Miklós (a költő)", "Zrínyi Miklós (szigetvári)", "Thököly Imre", "Bethlen Gábor"],
        "Zrínyi Miklós (1620–1664) költő, hadvezér és politikus. A Szigeti veszedelem szerzője, hadtudományi művek írója. Vadászbaleset áldozata lett.",
    ),
    _q(
        "Kit neveztek 'Kuruc király'-nak és 'a Kis Törökcsászár'-nak? Felső-Magyarország fejedelme, a kuruc mozgalom vezetője.",
        0,
        ["Thököly Imre", "II. Rákóczi Ferenc", "Apafi Mihály", "Bercsényi Miklós"],
        "Thököly Imre (1657–1705) kuruc fejedelem, Felső-Magyarország ura. A török szövetségben harcolt a Habsburgok ellen, de Bécs felmentése után hatalmát elveszítette.",
    ),
    _q(
        "Kit neveztek 'az Oroszlán'-nak és 'a Szerbek rémé'-nek? Szerb származású honvéd tábornok, az 1848-as szabadságharc hőse, aradi vértanú.",
        0,
        ["Damjanich János", "Görgei Artúr", "Bem József", "Kossuth Lajos"],
        "Damjanich János (1804–1849) szerb származású honvéd tábornok. Az 1849-es tavaszi hadjárat legsikeresebb hadvezére, az aradi vértanúk egyike.",
    ),
    _q(
        "Kit neveztek 'a Lengyel apó'-nak és 'Erdély hősé'-nek? Lengyel tábornok, az erdélyi hadjárat vezetője a szabadságharcban.",
        0,
        ["Bem József", "Damjanich János", "Görgei Artúr", "Kossuth Lajos"],
        "Józef Bem (1794–1850) lengyel tábornok, a magyar szabadságharc honvéd tábornoka. Az erdélyi hadjáratban aratott győzelmeivel 'Bem apó' lett a nép kedvence.",
    ),
    _q(
        "Kit neveztek 'a Szabadságharc árulójá'-nak (vitatott) és 'az Éles eszű'-nek? A magyar honvédsereg fővezére, aki Világosnál letette a fegyvert.",
        0,
        ["Görgei Artúr", "Damjanich János", "Kossuth Lajos", "Bem József"],
        "Görgei Artúr (1818–1916) honvéd tábornok, a szabadságharc fővezére. 1849-ben Világosnál tette le a fegyvert az oroszok előtt – árulónak vagy realistának tartják, máig vitatott.",
    ),
    _q(
        "Kit neveztek 'a Legnagyobb Magyar'-nak? Reformkori politikus és közgazdász, akit Kossuth Lajos nevezett így először.",
        0,
        ["Széchenyi István", "Kossuth Lajos", "Deák Ferenc", "Batthyány Lajos"],
        "Gróf Széchenyi István (1791–1860) a magyar reformkor meghatározó alakja. A Lánchíd, a Magyar Tudományos Akadémia és a lóversenyzés meghonosítása fűződik a nevéhez.",
    ),
    _q(
        "Kit neveztek 'a Nemzet Atyja'-nak és 'a Kormányzó'-nak? Az 1848-as forradalom vezéralakja, Magyarország kormányzó-elnöke.",
        0,
        ["Kossuth Lajos", "Széchenyi István", "Deák Ferenc", "Görgei Artúr"],
        "Kossuth Lajos (1802–1894) az 1848–49-es forradalom és szabadságharc vezéralakja. Magyarország kormányzó-elnöke, a függetlenségi nyilatkozat kihirdetője.",
    ),
    _q(
        "Kit neveztek 'a Haza Bölcsé'-nek és 'a Nemzet Prókátorá'-nak? A kiegyezés atyja, aki tárgyalásaival létrehozta az Osztrák–Magyar Monarchiát.",
        0,
        ["Deák Ferenc", "Kossuth Lajos", "Széchenyi István", "Andrássy Gyula"],
        "Deák Ferenc (1803–1876) a kiegyezés (1867) szellemi atyja. Bölcs tárgyalási stratégiájával hozta létre az Osztrák–Magyar Monarchia kompromisszumát.",
    ),
    _q(
        "Kit neveztek 'a Zsibói Bölény'-nek? Hatalmas termetű, erős magyar főúr, erdélyi politikus.",
        0,
        ["Wesselényi Miklós id.", "Wesselényi Miklós ifj.", "Széchenyi István", "Kazinczy Ferenc"],
        "Id. Wesselényi Miklós (1750–1809) erdélyi báró, hatalmas termetű és erejű főúr. Zsibói birtokáról kapta a 'Zsibói Bölény' ragadványnevet.",
    ),
    _q(
        "Kit neveztek 'az Árvízi Hajós'-nak? Reformkori politikus, aki az 1838-as pesti árvízben csónakkal mentett életeket.",
        0,
        ["Wesselényi Miklós ifj.", "Széchenyi István", "Kossuth Lajos", "Wesselényi Miklós id."],
        "Ifj. Wesselényi Miklós (1796–1850) az 1838-as pesti nagy árvíz hőse. Csónakkal járta az elárasztott utcákat és személyesen mentett több száz embert.",
    ),
    _q(
        "Kit neveztek 'az Első miniszterelnök'-nek és 'a Mártír'-nak? Magyarország első felelős miniszterelnöke, akit 1849. október 6-án végeztek ki.",
        0,
        ["Batthyány Lajos", "Kossuth Lajos", "Deák Ferenc", "Széchenyi István"],
        "Gróf Batthyány Lajos (1807–1849) Magyarország első felelős miniszterelnöke (1848). Az aradi vértanúkkal egy napon, 1849. október 6-án végezték ki Pesten.",
    ),
    _q(
        "Kit neveztek 'a Heves Vérű Tábornok'-nak? Indulatos, de bátor honvéd tábornok az 1848–49-es szabadságharcban.",
        0,
        ["Perczel Mór", "Damjanich János", "Görgei Artúr", "Bem József"],
        "Perczel Mór (1811–1899) honvéd tábornok. Heves temperamentumú, de bátor katona, aki több sikeres csatát vívott a szabadságharcban.",
    ),
    _q(
        "Kit neveztek 'az Első Magyar Humanistá'-nak? Latin nyelvű reneszánsz költő, Mátyás király udvarának dísze.",
        0,
        ["Janus Pannonius", "Vitéz János", "Balassi Bálint", "Galeotto Marzio"],
        "Janus Pannonius (1434–1472) az első jelentős magyar humanista költő. Latin nyelvű versei európai hírnevet szereztek neki Mátyás király korában.",
    ),
    _q(
        "Kit neveztek 'Magyar Petrar'-cának? Az első nagy magyar lírai költő, a reneszánsz szerelmi költészet úttörője.",
        0,
        ["Balassi Bálint", "Janus Pannonius", "Tinódi Lantos Sebestyén", "Zrínyi Miklós (a költő)"],
        "Balassi Bálint (1554–1594) a magyar líra megteremtője. Szerelmi, vitézi és istenes verseivel a magyar irodalom egyik alapítója. A törökök elleni harcban esett el.",
    ),
    _q(
        "Kit neveztek 'Széphalmi Öreg'-nek? A magyar nyelvújítás vezéralakja, aki Széphalmon élt és alkotott.",
        0,
        ["Kazinczy Ferenc", "Berzsenyi Dániel", "Kölcsey Ferenc", "Csokonai Vitéz Mihály"],
        "Kazinczy Ferenc (1759–1831) a magyar nyelvújítás vezére. Széphalmi birtokán élt, és levelezésével irányította az irodalmi életet.",
    ),
    _q(
        "Kit neveztek 'a Niklai Remeté'-nek? Visszavonultan élő költő, akit Kölcsey kritikája mélyen megrendített.",
        0,
        ["Berzsenyi Dániel", "Kazinczy Ferenc", "Kölcsey Ferenc", "Vörösmarty Mihály"],
        "Berzsenyi Dániel (1776–1836) a magyar klasszicizmus költője. Niklai birtokán élt visszavonultan, ódáival és elégiáival a korszak legnagyobb lírikusai közé emelkedett.",
    ),
    _q(
        "Kit neveztek 'Csekei remeté'-nek? A Himnusz szerzője, aki Csekén élt visszavonultan és Csurgón is tanított.",
        0,
        ["Kölcsey Ferenc", "Berzsenyi Dániel", "Kazinczy Ferenc", "Vörösmarty Mihály"],
        "Kölcsey Ferenc (1790–1838) költő, politikus, a Himnusz szerzője (1823). Szatmárcsekén élt visszavonultan, de az országgyűlésben is részt vett.",
    ),
    _q(
        "Kit neveztek 'a Nemzet Költőjé'-nek? Alföldi témákat feldolgozó forradalmi költő, az 1848-as forradalom szimbóluma.",
        0,
        ["Petőfi Sándor", "Arany János", "Vörösmarty Mihály", "Jókai Mór"],
        "Petőfi Sándor (1823–1849) a Nemzet Költője. A Nemzeti dal szerzője, az 1848-as forradalom egyik vezetője. A segesvári csatában tűnt el 1849-ben.",
    ),
    _q(
        "Kit neveztek 'a Nagykőrösi Remeté'-nek, 'az Eposz Mesteré'-nek és 'Toldi szerzőjé'-nek? A Toldi trilógia alkotója, aki Nagykőrösön tanároskodott.",
        0,
        ["Arany János", "Petőfi Sándor", "Jókai Mór", "Madách Imre"],
        "Arany János (1817–1882) a magyar epika legnagyobb mestere. A Toldi trilógia szerzője, Nagykőrösön tanároskodott, később a Magyar Tudományos Akadémia főtitkára lett.",
    ),
    _q(
        "Kit neveztek 'Nagy Mesemondó'-nak és 'a Regénykirály'-nak? Rendkívül termékeny regényíró, a magyar próza egyik legnagyobb alakja.",
        0,
        ["Jókai Mór", "Mikszáth Kálmán", "Arany János", "Madách Imre"],
        "Jókai Mór (1825-1904) a 'nagy mesemondó', a magyar irodalom legtermékenyebb regényírója. Több mint 100 regényt írt, köztük Az arany ember és A kőszívű ember fiai.",
    ),
    _q(
        "Kit neveztek 'a sztregovai remeté'-nek? Az ember tragédiája szerzője.",
        0,
        ["Madách Imre", "Arany János", "Jókai Mór", "Vörösmarty Mihály"],
        "Madách Imre (1823–1864) Az ember tragédiája szerzője. Sztregovai birtokán visszavonultan élt, drámai költeménye a magyar irodalom egyik csúcsa.",
    ),
    _q(
        "Kit neveztek 'Nagy Palóc'-nak? Nógrád megyei palóc vidékről származó író, a magyar anekdotikus próza mestere.",
        0,
        ["Mikszáth Kálmán", "Jókai Mór", "Gárdonyi Géza", "Móricz Zsigmond"],
        "Mikszáth Kálmán (1847-1910) a 'Nagy Palóc', Nógrád megyéből származó író. A Tót atyafiak és A jó palócok szerzője, a magyar anekdotikus elbeszélés mestere.",
    ),
    _q(
        "Kit neveztek 'Lázadó Prófétá'-nak? A forradalmi modernizmus költője, a Nyugat folyóirat emblematikus alakja.",
        0,
        ["Ady Endre", "Babits Mihály", "Móricz Zsigmond", "Kosztolányi Dezső"],
        "Ady Endre (1877–1919) a modern magyar líra megteremtője. Forradalmi verseivel és prózájával az irodalmi megújulás prófétája volt.",
    ),
    _q(
        "Kit neveztek 'Fogarasi tanár'-nak? A Nyugat folyóirat főszerkesztője, aki Fogarason tanároskodott pályája elején.",
        0,
        ["Babits Mihály", "Ady Endre", "Móricz Zsigmond", "Kosztolányi Dezső"],
        "Babits Mihály (1883–1941) költő, író, a Nyugat főszerkesztője. Fogarason kezdte tanári pályáját, Jónás könyve és más művei a magyar irodalom klasszikusai.",
    ),
    _q(
        "Kit neveztek 'Parasztok írójá'-nak? A paraszti világ ábrázolója, a magyar népi realizmus legnagyobb alakja.",
        0,
        ["Móricz Zsigmond", "Ady Endre", "Mikszáth Kálmán", "Gárdonyi Géza"],
        "Móricz Zsigmond (1879–1942) a magyar népi realizmus legjelentősebb írója. A Légy jó mindhalálig és az Erdély-trilógia szerzője, a paraszti világ leghitelesebb ábrázolója.",
    ),
    _q(
        "Kit neveztek 'Tanár úr'-nak? Szatirikus, humoros életművű író, az Így írtok ti szerzője.",
        0,
        ["Karinthy Frigyes", "Móricz Zsigmond", "Babits Mihály", "Kosztolányi Dezső"],
        "Karinthy Frigyes (1887–1938) humorista, író, a magyar szatíra mestere. Az Így írtok ti irodalmi paródiái és az Utazás a koponyám körül önéletrajzi regénye a legismertebbek.",
    ),
    _q(
        "Kit neveztek 'Mártír Költő'-nek? Költő, akit az erőltetett menet során öltek meg 1944-ben.",
        0,
        ["Radnóti Miklós", "József Attila", "Babits Mihály", "Illyés Gyula"],
        "Radnóti Miklós (1909–1944) a Holokauszt mártír költője. Az Erőltetett menet és a Razglednicák szerzője, akit 1944 novemberében agyonlőttek az erőltetett menet során.",
    ),
    _q(
        "Kit neveztek 'az Apostol'-nak és 'a Vértanú'-nak? Velencei származású püspök, akit a Gellérthegyről dobtak le kőbe.",
        0,
        ["Gellért püspök", "Astrik érsek", "Szent Adalbert", "Koppány"],
        "Szent Gellért (980–1046) velencei származású csanádi püspök. 1046-ban a pogánylázadás során a Gellérthegyről dobták le egy kerekes kordéban – vértanúhalált halt.",
    ),
    _q(
        "Kit neveztek 'a Bíboros Fejedelem'-nek? Jezsuita szerzetes és esztergomi érsek, a katolikus megújulás vezéralakja Magyarországon.",
        0,
        ["Pázmány Péter", "Mindszenty József", "Márton Áron", "Gellért püspök"],
        "Pázmány Péter (1570–1637) jezsuita szerzetes, esztergomi érsek, bíboros. Az ellenreformáció legnagyobb magyar alakja, a Nagyszombati Egyetem alapítója.",
    ),
    _q(
        "Kit neveztek 'a Bíboros Herceg'-nek? Magyar bíboros, a kommunizmus elleni ellenállás szimbóluma, aki éveket töltött az amerikai nagykövetségen.",
        0,
        ["Mindszenty József", "Pázmány Péter", "Márton Áron", "Gellért püspök"],
        "Mindszenty József (1892–1975) esztergomi érsek, bíboros. A kommunista diktatúra ellenfele, 1956 után 15 évig az amerikai nagykövetségen élt menedékben.",
    ),
    _q(
        "Kit neveztek 'Erdély Apostolá'-nak és 'a Kősziklá'-nak? Erdélyi katolikus püspök, a kommunista és nacionalista elnyomás elleni bátor ellenálló.",
        0,
        ["Márton Áron", "Mindszenty József", "Pázmány Péter", "Gellért püspök"],
        "Márton Áron (1896–1980) gyulafehérvári püspök, Erdély nagy egyházi vezetője. A náci és a kommunista diktatúra ellen is kiállt, a romániai magyarság szimbóluma.",
    ),
    _q(
        "Kit neveztek 'a Csejtei Vámpír'-nak és 'a Vérgrófnő'-nek? Magyar grófnő, akit állítólag 600-nál több fiatal lány meggyilkolásával vádoltak.",
        0,
        ["Báthory Erzsébet", "Báthory István", "Báthory Gábor", "Erzsébet királyné"],
        "Báthory Erzsébet (1560–1614) a világ egyik leghírhedtebb sorozatgyilkosa. Csejtei kastélyában állítólag fiatal lányok vérében fürdött – bár a vádak vitatottak.",
    ),
    _q(
        "Kit neveztek 'a Magyarok Királynéjá'-nak? Osztrák császárné, aki különösen szerette Magyarországot és a magyar nyelvet.",
        0,
        ["Erzsébet királyné", "Mária Terézia", "Báthory Erzsébet", "Zita királyné"],
        "Wittelsbach Erzsébet (Sisi, 1837–1898) I. Ferenc József felesége. A magyarok rajongva szerették, mert megtanult magyarul és támogatta a kiegyezést.",
    ),
    _q(
        "Kit neveztek 'a Szép Akasztott'-nak és 'a Kiegyezés miniszterelnöké'-nek? Arisztokrata politikus, akit a francia lapok szépnek neveztek.",
        0,
        ["Andrássy Gyula id.", "Deák Ferenc", "Tisza István", "Batthyány Lajos"],
        "Gróf Andrássy Gyula (1823–1890) a kiegyezés utáni első magyar miniszterelnök. 1849-ben in effigie (jelképesen) felakasztották, szép megjelenése miatt 'szép akasztott'-nak nevezték.",
    ),
    _q(
        "Kit neveztek 'a Vas Tiszá'-nak? Erős akaratú magyar miniszterelnök az I. világháború idején.",
        0,
        ["Tisza István", "Andrássy Gyula id.", "Teleki Pál", "Bethlen István"],
        "Gróf Tisza István (1861–1918) kétszeres miniszterelnök. Vas akaratáról és kompromisszumképtelenségéről volt híres. Az őszirózsás forradalom első napján gyilkolták meg.",
    ),
    _q(
        "Kit neveztek 'a Tudós Miniszterelnök'-nek és 'a Geográfus'-nak? Földrajztudós és politikus, aki miniszterelnökként öngyilkos lett.",
        0,
        ["Teleki Pál", "Tisza István", "Horthy Miklós", "Bethlen István"],
        "Gróf Teleki Pál (1879–1941) földrajztudós, kétszeres miniszterelnök. Magyarország háborúba sodródása miatti lelkiismereti válságában 1941-ben öngyilkos lett.",
    ),
    _q(
        "Kit neveztek 'a Fehér Lovag'-nak és 'a Kormányzó'-nak? Magyarország kormányzója 1920 és 1944 között.",
        0,
        ["Horthy Miklós", "Teleki Pál", "Tisza István", "Rákosi Mátyás"],
        "Horthy Miklós (1868–1957) az Osztrák–Magyar Monarchia altengernagya, Magyarország kormányzója 1920–1944 között. Az ellenforradalmi rendszer vezetője.",
    ),
    _q(
        "Kit neveztek 'Sztálin legjobb tanítványá'-nak és 'a Kopasz'-nak? A kommunista diktatúra vezetője Magyarországon, aki saját maga is büszkén viselte e jelzőt.",
        0,
        ["Rákosi Mátyás", "Nagy Imre", "Kádár János", "Rajk László"],
        "Rákosi Mátyás (1892-1971) a kommunista diktatúra legfőbb vezetője (1948-1956). Sztálin legjobb magyar tanítványa - ahogy magát büszkén nevezte.",
    ),
    _q(
        "Kit neveztek 'a Mártír Miniszterelnök'-nek és 'a Reformer'-nek? Az 1956-os forradalom szimbolikus alakja, akit 1958-ban végeztek ki.",
        0,
        ["Nagy Imre", "Rákosi Mátyás", "Kádár János", "Mindszenty József"],
        "Nagy Imre (1896–1958) miniszterelnök 1956-ban. A forradalom idején Magyarország semlegességét hirdette ki, amiért a szovjet beavatkozás után letartóztatták és kivégezték.",
    ),
    _q(
        "Kit neveztek 'a Szász bölcs'-nek és 'Marosvásárhely tudósá'-nak? Matematikus és drámaíró, a nem-euklideszi geometria egyik úttörőjének apja.",
        0,
        ["Bolyai Farkas", "Bolyai János", "Gauss", "Kazinczy Ferenc"],
        "Bolyai Farkas (1775–1856) matematikus, fizikus és drámaíró. Marosvásárhelyen tanított, fia, Bolyai János a nem-euklideszi geometria megalkotója.",
    ),
    _q(
        "Kit neveztek 'az Anyák Megmentőjé'-nek? Orvos, aki felfedezte a gyermekágyi láz okát és a kézmosás fontosságát.",
        0,
        ["Semmelweis Ignác", "Bárány Róbert", "Korányi Frigyes", "Balassa János"],
        "Semmelweis Ignác (1818–1865) a gyermekágyi láz leküzdésének úttörője. Felismerte, hogy a kézmosás drámaian csökkenti az anyák halálozását – ezért 'az anyák megmentője'.",
    ),
    _q(
        "Kit neveztek 'a Dinamó atyjá'-nak és 'a Magyar Edison'-nak? Bencés szerzetes, az elektromotor és a szódavíz feltalálója.",
        0,
        ["Jedlik Ányos", "Bánki Donát", "Puskás Tivadar", "Csonka János"],
        "Jedlik Ányos (1800–1895) bencés szerzetes és fizikus. Az első villamos dinamó és motor megalkotója, a szódavízgyártás úttörője – méltán a 'Magyar Edison'.",
    ),
    _q(
        "Kit neveztek 'a Karburátor atyjá'-nak? Gépészmérnök és feltaláló, a porlasztó egyik megalkotója.",
        0,
        ["Bánki Donát", "Csonka János", "Jedlik Ányos", "Galamb József"],
        "Bánki Donát (1859–1922) gépészmérnök. Csonka Jánossal együtt fejlesztette ki a karburátort (porlasztót), amely forradalmasította a belső égésű motorokat.",
    ),
    _q(
        "Kit neveztek 'a Telefon-Hírmondó atyjá'-nak? Feltaláló és mérnök, aki Edison munkatársa is volt.",
        0,
        ["Puskás Tivadar", "Jedlik Ányos", "Bánki Donát", "Bíró László"],
        "Puskás Tivadar (1844–1893) a telefonközpont és a Telefon-Hírmondó feltalálója. Edison laboratóriumában is dolgozott, a távközlés úttörője.",
    ),
    _q(
        "Kit neveztek 'Öcsi'-nek, 'a Csúcstámadó'-nak és 'a Galaktikus'-nak? Real Madrid legenda, Arany labdás magyar futballista.",
        0,
        ["Puskás Ferenc", "Kocsis Sándor", "Czibor Zoltán", "Bozsik József"],
        "Puskás Ferenc (1927–2006) a magyar és a világfutball egyik legnagyobb alakja. Az Aranycsapat csillaga, a Real Madrid legendája, 84 válogatott góllal a legeredményesebb magyar labdarúgó.",
    ),
    _q(
        "Kit neveztek 'Aranyfejes Kocsis'-nak? Az Aranycsapat csatára, aki a legtöbb fejgólt lőtte a válogatottban.",
        0,
        ["Kocsis Sándor", "Puskás Ferenc", "Czibor Zoltán", "Hidegkuti Nándor"],
        "Kocsis Sándor (1929–1979) az Aranycsapat fejjátékosa. 75 válogatott mérkőzésen 75 gólt szerzett, fejgóljai legendásak. 1956 után a Barcelonában futballozott.",
    ),
    _q(
        "Kit neveztek 'a Szélső Villám'-nak? Villámgyors szélső csatár az Aranycsapatban.",
        0,
        ["Czibor Zoltán", "Puskás Ferenc", "Kocsis Sándor", "Bozsik József"],
        "Czibor Zoltán (1929–1997) az Aranycsapat szélsője. Rendkívüli gyorsasága miatt kapta a 'Szélső Villám' ragadványnevet. 1956 után a Barcelonában játszott.",
    ),
]
