# Teljes földrajzi kérdések a quiz alkalmazáshoz
# PDF alapján minden elérhető táblázat: magyar csúcsok, világ hegyei, fővárosok, pénznemek, Óceánia

_TOPIC = "földrajz"


def _q(question, correct, options, explanation, topic=_TOPIC):
    """Segédfüggvény: kompakt kérdés létrehozása."""
    return {"question": question, "options": options, "correct": correct, "explanation": explanation, "topic": topic}


FOLDRAJZ_QUESTIONS_COMPLETE = [
    _q('Mi a Mátra legmagasabb csúcsa?', 0, ['Kékes', 'Dobogó-kő', 'Csóványos', 'Szilvási-kő'], 'A Kékes 1014 méter magasságával a Mátra legmagasabb csúcsa.'),
    _q('Mi a Bükk hegység legmagasabb csúcsa?', 1, ['Kékes', 'Kettős-bérc déli csúcsa', 'Nagy-Milic', 'Karancs'], 'A Kettős-bérc déli csúcsa 960 méter magasságával a Bükk legmagasabb pontja.'),
    _q('Mi a Zempléni-hegység legmagasabb csúcsa?', 2, ['Kékes', 'Csóványos', 'Nagy-Milic', 'Karancs'], 'A Nagy-Milic 895 méter magasságával a Zempléni-hegység legmagasabb csúcsa.'),
    _q('Mi a Börzsöny hegység legmagasabb csúcsa?', 0, ['Csóványos', 'Nagy-Milic', 'Karancs', 'Nagy-Gerecse'], 'A Csóványos 938 méter magasságával a Börzsöny hegység legmagasabb csúcsa.'),
    _q('Mi a Cserhát legmagasabb csúcsa?', 0, ['Karancs', 'Nagy-Gerecse', 'Pilis', 'Nagy-Kopasz'], 'A Karancs 727 méter magasságával a Cserhát legmagasabb csúcsa.'),
    _q('Mi a Gerecse legmagasabb csúcsa?', 0, ['Nagy-Gerecse', 'Pilis', 'Nagy-Kopasz', 'Dobogó-kő'], 'A Nagy-Gerecse 634 méter magasságával a Gerecse legmagasabb csúcsa.'),
    _q('Mi a Pilis hegység legmagasabb csúcsa?', 0, ['Pilis', 'Nagy-Kopasz', 'Dobogó-kő', 'Nagy-Gerecse'], 'A Pilis 756 méter magasságával a Pilis hegység legmagasabb csúcsa.'),
    _q('Mi a Vértes hegység legmagasabb csúcsa?', 0, ['Nagy-Csákány', 'Kőris-hegy', 'Zengő', 'Írott-kő'], 'A Nagy-Csákány 487 méter magasságával a Vértes hegység legmagasabb csúcsa.'),
    _q('Mi a Bakony legmagasabb csúcsa?', 0, ['Kőris-hegy', 'Zengő', 'Írott-kő', 'Nagy-Csákány'], 'A Kőris-hegy 709 méter magasságával a Bakony legmagasabb csúcsa.'),
    _q('Mi a Kőszegi-hegység legmagasabb csúcsa?', 0, ['Írott-kő', 'Zengő', 'Kőris-hegy', 'Nagy-Csákány'], 'Az Írott-kő 882 méter magasságával a Kőszegi-hegység legmagasabb csúcsa.'),
    _q('Mi a Mecsek legmagasabb csúcsa?', 0, ['Zengő', 'Írott-kő', 'Kőris-hegy', 'Nagy-Csákány'], 'A Zengő 682 méter magasságával a Mecsek legmagasabb csúcsa.'),
    _q('Mi a Villányi-hegység legmagasabb csúcsa?', 0, ['Szársomlyó', 'Zengő', 'Írott-kő', 'Kőris-hegy'], 'A Szársomlyó 442 méter magasságával a Villányi-hegység legmagasabb csúcsa.'),
    _q('Mi a Soproni-hegység magyarországi részének legmagasabb csúcsa?', 0, ['Magas-bérc', 'Írott-kő', 'Zengő', 'Szársomlyó'], 'A Magas-bérc 557 méter magasságával a Soproni-hegység magyarországi részének legmagasabb csúcsa.'),
    _q('Mi a Velencei-hegység legmagasabb csúcsa?', 0, ['Meleg-hegy', 'Magas-bérc', 'Írott-kő', 'Zengő'], 'A Meleg-hegy 352 méter magasságával a Velencei-hegység legmagasabb csúcsa.'),
    _q('Mi a Budai-hegység legmagasabb csúcsa?', 0, ['Nagy-Kopasz', 'Meleg-hegy', 'Magas-bérc', 'Írott-kő'], 'A Nagy-Kopasz 559 méter magasságával a Budai-hegység legmagasabb csúcsa.'),
    _q('Mi a Visegrádi-hegység legmagasabb csúcsa?', 0, ['Dobogó-kő', 'Nagy-Kopasz', 'Meleg-hegy', 'Magas-bérc'], 'A Dobogó-kő 700 méter magasságával a Visegrádi-hegység legmagasabb csúcsa.'),
    _q('Mi az Aggteleki-karszt legmagasabb csúcsa?', 0, ['Fertős-tető', 'Dobogó-kő', 'Nagy-Kopasz', 'Meleg-hegy'], 'A Fertős-tető 604 méter magasságával az Aggteleki-karszt legmagasabb csúcsa.'),
    _q('Mi a Tokaj–Zempléni-hegyvidék legmagasabb csúcsa?', 0, ['Nagy-Milic', 'Fertős-tető', 'Dobogó-kő', 'Nagy-Kopasz'], 'A Nagy-Milic 895 méter magasságával a Tokaj–Zempléni-hegyvidék legmagasabb csúcsa.'),
    _q('Melyik a világ legmagasabb hegycsúcsa?', 1, ['K2', 'Everest', 'Kangchenjunga', 'Lhotse'], 'Az Everest 8848 méter magasságával a világ legmagasabb hegycsúcsa.'),
    _q('Melyik kontinens legmagasabb hegycsúcsa a Kilimandzsáró?', 2, ['Ázsia', 'Dél-Amerika', 'Afrika', 'Ausztrália'], 'A Kilimandzsáró 5895 méter magasságával Afrika legmagasabb hegycsúcsa.'),
    _q('Melyik a világ leghosszabb folyója?', 1, ['Amazonas', 'Nílus', 'Jangce', 'Mississippi'], 'A Nílus 6650 km hosszával a világ leghosszabb folyója.'),
    _q('Melyik az Európa leghosszabb folyója?', 0, ['Volga', 'Duna', 'Rajna', 'Dnyeper'], 'A Volga 3530 km hosszával Európa leghosszabb folyója.'),
    _q('Melyik az Észak-Amerika legmagasabb hegycsúcsa?', 1, ['Mount McKinley', 'Denali', 'Mount Logan', 'Pico de Orizaba'], 'A Denali 6190 méter magasságával Észak-Amerika legmagasabb hegycsúcsa.'),
    _q('Melyik a Dél-Amerika legmagasabb hegycsúcsa?', 0, ['Aconcagua', 'Ojos del Salado', 'Monte Pissis', 'Huascarán'], 'Az Aconcagua 6960 méter magasságával Dél-Amerika legmagasabb hegycsúcsa.'),
    _q('Melyik az Ausztrália legmagasabb hegycsúcsa?', 0, ['Mount Kosciuszko', 'Mount Townsend', 'Mount Twynam', 'Rams Head'], 'A Mount Kosciuszko 2228 méter magasságával Ausztrália legmagasabb hegycsúcsa.'),
    _q('Melyik az Európa legmagasabb hegycsúcsa?', 1, ['Mont Blanc', 'Elbrusz', 'Matterhorn', 'Mount Etna'], 'Az Elbrusz 5642 méter magasságával Európa legmagasabb hegycsúcsa.'),
    _q('Melyik az Antarktisz legmagasabb hegycsúcsa?', 0, ['Vinson-masszívum', 'Mount Erebus', 'Mount Kirkpatrick', 'Mount Terror'], 'A Vinson-masszívum 4892 méter magasságával az Antarktisz legmagasabb hegycsúcsa.'),
    _q('Melyik az Ázsia leghosszabb folyója?', 0, ['Jangce', 'Sárga-folyó', 'Mekong', 'Indus'], 'A Jangce 6300 km hosszával Ázsia leghosszabb folyója.'),
    _q('Melyik az Észak-Amerika leghosszabb folyója?', 0, ['Mississippi', 'Missouri', 'Yukon', 'Rio Grande'], 'A Mississippi 3770 km hosszával Észak-Amerika leghosszabb folyója.'),
    _q('Melyik a Dél-Amerika leghosszabb folyója?', 0, ['Amazonas', 'Paraná', 'Orinoco', 'Madeira'], 'Az Amazonas 6575 km hosszával Dél-Amerika leghosszabb folyója.'),
    _q('Melyik az Ausztrália leghosszabb folyója?', 0, ['Murray-Darling', 'Murray', 'Darling', 'Murrumbidgee'], 'A Murray-Darling 3370 km hosszával Ausztrália leghosszabb folyója.'),
    _q('Mi Üzbegisztán fővárosa?', 0, ['Taskent', 'Biskek', 'Dusanbe', 'Tbiliszi'], 'Üzbegisztán fővárosa Taskent, pénzneme a som.'),
    _q('Mi Kirgizisztán fővárosa?', 1, ['Taskent', 'Biskek', 'Asztana', 'Jereván'], 'Kirgizisztán fővárosa Biskek, pénzneme a som.'),
    _q('Mi Tádzsikisztán fővárosa?', 1, ['Biskek', 'Dusanbe', 'Taskent', 'Baku'], 'Tádzsikisztán fővárosa Dusanbe, pénzneme a somoni.'),
    _q('Mi Grúzia fővárosa?', 2, ['Baku', 'Jereván', 'Tbiliszi', 'Asztana'], 'Grúzia fővárosa Tbiliszi, pénzneme a lari.'),
    _q('Mi Örményország fővárosa?', 1, ['Tbiliszi', 'Jereván', 'Baku', 'Biskek'], 'Örményország fővárosa Jereván, pénzneme a dram.'),
    _q('Mi Kazahsztán fővárosa?', 1, ['Almati', 'Asztana', 'Taskent', 'Biskek'], 'Kazahsztán fővárosa Asztana, pénzneme a tenge.'),
    _q('Mi Bhután fővárosa?', 0, ['Thimphu', 'Katmandu', 'Dhaka', 'Vientiane'], 'Bhután fővárosa Thimphu, pénzneme a ngultrum.'),
    _q('Mi Malajzia fővárosa?', 0, ['Kuala Lumpur', 'Jakarta', 'Bangkok', 'Manila'], 'Malajzia fővárosa Kuala Lumpur, pénzneme a ringgit.'),
    _q('Mi Kambodzsa fővárosa?', 0, ['Phnom Penh', 'Vientiane', 'Bangkok', 'Hanoi'], 'Kambodzsa fővárosa Phnom Penh, pénzneme a riel.'),
    _q('Mi Laosz fővárosa?', 0, ['Vientiane', 'Phnom Penh', 'Bangkok', 'Hanoi'], 'Laosz fővárosa Vientiane, pénzneme a kip.'),
    _q('Mi Brunei fővárosa?', 0, ['Bandar Seri Begawan', 'Kuala Lumpur', 'Jakarta', 'Manila'], 'Brunei fővárosa Bandar Seri Begawan, pénzneme a dollár.'),
    _q('Melyik ország pénzneme a manat?', 2, ['Grúzia', 'Örményország', 'Azerbajdzsán', 'Kazahsztán'], 'Azerbajdzsán pénzneme a manat, fővárosa Baku.'),
    _q('Melyik ország pénzneme a kyat?', 0, ['Mianmar', 'Thaiföld', 'Vietnam', 'Kambodzsa'], 'Mianmar pénzneme a kyat.'),
    _q('Mi Belize fővárosa?', 1, ['Belize City', 'Belmopan', 'San Salvador', 'Guatemala City'], 'Belize fővárosa Belmopan, pénzneme a belize-i dollár.'),
    _q('Mi Costa Rica fővárosa?', 1, ['Guatemala City', 'San José', 'Managua', 'Tegucigalpa'], 'Costa Rica fővárosa San José, pénzneme a colón.'),
    _q('Mi Salvador fővárosa?', 1, ['San José', 'San Salvador', 'Managua', 'Tegucigalpa'], 'Salvador fővárosa San Salvador, pénzneme az amerikai dollár.'),
    _q('Mi Guatemala fővárosa?', 0, ['Guatemala City', 'San José', 'San Salvador', 'Managua'], 'Guatemala fővárosa Guatemala City, pénzneme a quetzal.'),
    _q('Mi Honduras fővárosa?', 2, ['San José', 'Managua', 'Tegucigalpa', 'Panamaváros'], 'Honduras fővárosa Tegucigalpa, pénzneme a lempira.'),
    _q('Mi Nicaragua fővárosa?', 1, ['Tegucigalpa', 'Managua', 'San José', 'Belmopan'], 'Nicaragua fővárosa Managua, pénzneme a córdoba.'),
    _q('Mi Panama fővárosa?', 0, ['Panamaváros', 'San José', 'Managua', 'Tegucigalpa'], 'Panama fővárosa Panamaváros, pénzneme a balboa és az amerikai dollár.'),
    _q('Mi Ausztrália fővárosa?', 2, ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'], 'Ausztrália fővárosa Canberra, nem Sydney vagy Melbourne.'),
    _q('Mi Új-Zéland fővárosa?', 1, ['Auckland', 'Wellington', 'Christchurch', 'Hamilton'], 'Új-Zéland fővárosa Wellington, a legnagyobb város Auckland.'),
    _q('Mi Fidzsi-szigetek fővárosa?', 0, ['Suva', "Nuku'alofa", 'Apia', 'Port Vila'], 'Fidzsi-szigetek fővárosa Suva, pénzneme a fidzsi dollár.'),
    _q('Mi Kiribati fővárosa?', 0, ['Dél-Tarawa', 'Majuro', 'Palikir', 'Yaren'], 'Kiribati fővárosa Dél-Tarawa, pénzneme az ausztrál dollár.'),
    _q('Mi Marshall-szigetek fővárosa?', 0, ['Majuro', 'Palikir', 'Yaren', 'Dél-Tarawa'], 'Marshall-szigetek fővárosa Majuro, pénzneme az amerikai dollár.'),
    _q('Mi Mikronéziai Szövetségi Államok fővárosa?', 0, ['Palikir', 'Majuro', 'Yaren', 'Dél-Tarawa'], 'Mikronéziai Szövetségi Államok fővárosa Palikir, pénzneme az amerikai dollár.'),
    _q('Mi Nauru fővárosa?', 0, ['Yaren', 'Palikir', 'Majuro', 'Dél-Tarawa'], 'Nauru fővárosa Yaren (de facto), pénzneme az ausztrál dollár.'),
    _q('Mi Palau fővárosa?', 0, ['Ngerulmud', 'Yaren', 'Palikir', 'Majuro'], 'Palau fővárosa Ngerulmud, pénzneme az amerikai dollár.'),
    _q('Mi Pápua Új-Guinea fővárosa?', 0, ['Port Moresby', 'Lae', 'Mount Hagen', 'Madang'], 'Pápua Új-Guinea fővárosa Port Moresby, pénzneme a kina.'),
    _q('Mi Salamon-szigetek fővárosa?', 0, ['Honiara', 'Port Moresby', 'Suva', 'Apia'], 'Salamon-szigetek fővárosa Honiara, pénzneme a salamoni dollár.'),
    _q('Mi Samoa fővárosa?', 0, ['Apia', 'Fagamalo', 'Salelologa', 'Asau'], 'Samoa fővárosa Apia, pénzneme a tala.'),
    _q('Mi Tonga fővárosa?', 0, ["Nuku'alofa", 'Neiafu', 'Pangai', 'Hihifo'], "Tonga fővárosa Nuku'alofa, pénzneme a pa'anga."),
    _q('Mi Tuvalu fővárosa?', 0, ['Funafuti', "Nuku'alofa", 'Apia', 'Honiara'], 'Tuvalu fővárosa Funafuti, pénzneme a tuvalui dollár és az ausztrál dollár.'),
    _q('Mi Vanuatu fővárosa?', 0, ['Port Vila', 'Suva', 'Apia', 'Honiara'], 'Vanuatu fővárosa Port Vila, pénzneme a vatu.'),
    _q('Mi a Harmattan?', 0, ['Sivatagi szél', 'Tengeri áramlat', 'Hegycsúcs', 'Folyó'], 'A Harmattan egy száraz, poros szél, amely a Szahara sivatagból fúj.'),
    _q('Hol található a Gotthárd-hágó?', 0, ['Svájc', 'Olaszország', 'Ausztria', 'Németország'], 'A Gotthárd-hágó Svájcban található, fontos átjáró az Alpokban.'),
    _q('Mi az Ellis Island?', 0, ['Sziget New Yorkban', 'Hegycsúcs', 'Folyó', 'Város'], 'Az Ellis Island egy sziget New Yorkban, korábban bevándorlási pont volt.'),
    _q('Mi a Liberty Island?', 0, ['Sziget a Szabadság-szoborral', 'Hegycsúcs', 'Folyó', 'Város'], 'A Liberty Island egy sziget New Yorkban, ahol a Szabadság-szobor található.'),
    _q('Mi az Okawango?', 0, ['Folyó', 'Hegycsúcs', 'Sivatag', 'Tenger'], 'Az Okawango egy folyó Afrikában, amely a Kalahári sivatagba torkollik.'),
    _q('Hol találhatóak a Niagara Falls?', 0, ['USA-Kanada határ', 'Brazília', 'Argentína', 'Chile'], 'A Niagara Falls az USA és Kanada határán található vízesés.'),
    _q('Mi a Wrangel-fok?', 0, ['USA legnyugatibb pontja', 'Hegycsúcs', 'Folyó', 'Sziget'], 'A Wrangel-fok az USA legnyugatibb pontja Alaszka területén.'),
    _q('Mi a Takla-Makán?', 0, ['Sivatag', 'Hegycsúcs', 'Folyó', 'Tenger'], 'A Takla-Makán egy sivatag Kínában, a Selyemút mentén.'),
    _q('Melyik szigetcsoport legészakibb tagja a Stromboli vulkán szigete?', 0, ['Lipari-szigetek', 'Egadi-szigetek', 'Kikládok', 'Dodekanészosz'], 'A Stromboli a Lipari-szigetek (Eolie-szigetek) legészakibb tagja, Szicília északi partjánál.'),
]