# Híres magyarok kérdések a quiz alkalmazáshoz
# Magyar származású vagy magyar hírességek 2-3 mondatos jellemzés alapján

_TOPIC = "híres_magyarok"


def _q(question, correct, options, explanation, topic=_TOPIC):
    """Segédfüggvény: kompakt kérdés létrehozása."""
    return {"question": question, "options": options, "correct": correct, "explanation": explanation, "topic": topic}


HIRES_MAGYAROK_QUESTIONS = [
    _q(
        "Keszthelyen született 1811-ben. A szabadságharc bukása után Amerikába emigrált, ahol az amerikai polgárháborúban uniós tábornok lett. Később Argentína és Uruguay amerikai nagykövete volt.",
        0,
        ["Asbóth Sándor", "Pulitzer József", "Haraszty Ágoston", "Zukor Adolf"],
        "Asbóth Sándor (1811–1868) magyar származású amerikai uniós tábornok és diplomata volt. Keszthelyen született, a szabadságharc után emigrált, és az Arlingtoni Nemzeti Temetőben nyugszik.",
    ),
    _q(
        "Magyar mérnök és repülőmérnök, a helikopter fejlesztésének úttörője. 1928-ban AH-1 helikopterével elsőként a világon szállt fel függőlegesen pilótával, és huzamosabb ideig lebegett nagyobb magasságban.",
        0,
        ["Asboth Oszkár", "Kármán Tódor", "Pavlics Ferenc", "Kandó Kálmán"],
        "Asboth Oszkár (1891–1960) a helikopter fejlesztésének magyar úttörője volt. Kármán Tódor mellett dolgozott a PKZ helikopteren, majd saját AH-sorozatot fejlesztett.",
    ),
    _q(
        "Magyar zeneszerző, zongoraművész és népzenekutató. A 20. század egyik legnagyobb zeneszerzője, aki magyar és kelet-európai népzenei elemeket ötvözött modern kompozíciós technikákkal.",
        0,
        ["Bartók Béla", "Liszt Ferenc", "Goldmark Károly", "Kőrösi Csoma Sándor"],
        "Bartók Béla (1881–1945) a magyar és kelet-európai népzene gyűjtője és feldolgozója volt. Művei – pl. a Mikrokosmosz, a Zene húros hangszerekre és ütőkre – a 20. század klasszikusai.",
    ),
    _q(
        "Magyar fizikus és asztrofizikus. Az első nő, aki fizikából doktorált egy budapesti egyetemen. A kozmikus sugárzás kutatásának úttörője, később az USA-ban a gravitációs lencsézés és a biomágnesség terén dolgozott.",
        0,
        ["Barnóthy Forró Magda", "Telkes Mária", "Karikó Katalin", "Pécsi Eszter"],
        "Barnóthy Forró Magda (1904–1995) az első magyar női fizikus doktor. Férjével, Barnóthy Jenővel együtt Európa egyik első kozmikus sugárzás-teleszkópját építette.",
    ),
    _q(
        "Magyar gépészmérnök és feltaláló. A Csonka–Bánki motor, az első magyar szabadalmas benzinmotor egyik megalkotója. A karburátor feltalálásában is közreműködött.",
        0,
        ["Bánki Donát", "Csonka János", "Jedlik Ányos", "Galamb József"],
        "Bánki Donát (1859–1922) gépészmérnök, aki Csonka Jánossal együtt fejlesztette ki a magyar benzinmotort. A karburátor feltalálása is a nevéhez fűződik.",
    ),
    _q(
        "Magyar újságíró és feltaláló. 1938-ban szabadalmazta a golyóstollat, amely forradalmasította az írás eszközeit. A Bíró László József nevet használta.",
        0,
        ["Bíró László", "Puskás Tivadar", "Rubik Ernő", "Dallos József"],
        "Bíró László (1899–1985) a golyóstoll feltalálója. Argentínában fejlesztette ki a ma is használt elvet, és ott is halt meg.",
    ),
    _q(
        "Magyar gépészmérnök és feltaláló. A Csonka–Bánki motor egyik megalkotója, a magyar gépészet úttörője. Számos szabadalma volt a mezőgazdasági és ipari gépekre.",
        0,
        ["Csonka János", "Bánki Donát", "Jedlik Ányos", "Kandó Kálmán"],
        "Csonka János (1852–1939) gépészmérnök, Bánki Donáttal együtt a magyar benzinmotor feltalálója. Mezőgazdasági és ipari gépeket is tervezett.",
    ),
    _q(
        "Magyar szemorvos és kontaktológus. 1929-ben elsőként fejlesztett ki olyan kontaktlencséket, amelyek a szem alakjához idomultak, így egész nap viselhetővé váltak.",
        0,
        ["Dallos József", "Semmelweis Ignác", "Bárány Róbert", "Békésy György"],
        "Dallos József (1905–1979) a kontaktlencsék tökéletesítője. A British Contact Lens Association halála után az „Josef Dallos Award” pályadíjat alapított.",
    ),
    _q(
        "Magyar úszónő, ötszörös olimpiai bajnok. Az egyetlen női sportoló, aki ugyanabban a számban három egymást követő olimpián nyert aranyérmet (200 m hát).",
        0,
        ["Egerszegi Krisztina", "Szeles Mónika", "Polgár Judit", "Marton Kati"],
        "Egerszegi Krisztina (1974–) magyar úszónő, ötszörös olimpiai bajnok. A 200 méteres hátúszásban 1988, 1992 és 1996-ban is aranyérmet nyert.",
    ),
    _q(
        "Magyar gépészmérnök, a Ford T-modell egyik fő tervezője. A futómű és a gyártási folyamatok fejlesztésében volt kulcsfontosságú szerepe.",
        0,
        ["Galamb József", "Bánki Donát", "Csonka János", "Pavlics Ferenc"],
        "Galamb József (1881–1955) a Ford Motor Company mérnöke volt. A Ford T-modell, a „tin lizzie” tervezésében fontos szerepet játszott.",
    ),
    _q(
        "Amerikai színésznő és énekesnő, magyar származású. Apja budapesti születésű zenész volt. A South Pacific és más musicalek sztárjaként vált híressé.",
        0,
        ["Mitzi Gaynor", "Gábor Zsazsa", "Estée Lauder", "Adrienne Vittadini"],
        "Mitzi Gaynor (1930–2024) apja, Henry de Czanyi von Gerber budapesti születésű zenész volt. A South Pacific (1958) és más filmek sztárjaként ismert.",
    ),
    _q(
        "Magyar származású brit fizikus, a holográfia feltalálója. 1971-ben fizikai Nobel-díjat kapott a holografikus eljárás kidolgozásáért.",
        0,
        ["Gábor Dénes", "Wigner Jenő", "Szilárd Leo", "Teller Ede"],
        "Gábor Dénes (1900–1979) a holográfia feltalálója, 1971-ben fizikai Nobel-díjat kapott. Londonban élt és dolgozott.",
    ),
    _q(
        "Magyar származású hollywoodi színésznő, a „budapesti díva”. Számos filmben játszott, hét férjet vett el, és a sztárélet stílusának egyik ikonja volt.",
        0,
        ["Gábor Zsazsa", "Mitzi Gaynor", "Hargitay Mariska", "Estée Lauder"],
        "Gábor Zsazsa (1917–2016) budapesten született, Hollywoodban lett sztár. A Moulin Rouge, a Lili és más filmekben játszott.",
    ),
    _q(
        "Magyar zeneszerző, a 19. század egyik legnagyobb romantikus zeneszerzője. A zongoraművészet és a szimfonikus költemény úttörője.",
        0,
        ["Goldmark Károly", "Bartók Béla", "Liszt Ferenc", "Puskás Tivadar"],
        "Goldmark Károly (1830–1915) magyar zeneszerző, a Sakuntala és a Sába királynője operák szerzője. A bécsi konzervatórium tanára volt.",
    ),
    _q(
        "Magyar származású amerikai üzletember. A Intel Corporation egyik alapítója és vezérigazgatója volt. A személyi számítógép forradalom egyik kulcsfigurája.",
        0,
        ["Gróf András (Andrew Grove)", "Neumann János", "Simonyi Károly", "Zukor Adolf"],
        "Gróf András (1936–2016), ismertebb nevén Andrew Grove, a Intel vezérigazgatója volt. Budapesten született, 1956 után emigrált az USA-ba.",
    ),
    _q(
        "Magyar nemes és kaliforniai borászat úttörője. „Kalifornia szőlőtermesztésének atyjaként” ismert. A Buena Vista Winery alapítója Sonoma-ban.",
        0,
        ["Haraszty Ágoston", "Asbóth Sándor", "Pulitzer József", "Zukor Adolf"],
        "Haraszty Ágoston (1812–1869) az első magyar, aki állandóan letelepedett az USA-ban. Kaliforniában hozta létre a modern szőlőtermesztést.",
    ),
    _q(
        "Magyar származású amerikai színésznő. A Law & Order: Special Victims Unit főszereplője, ahol Olivia Benson nyomozót alakítja. Apja, Hargitay Miklós bodybuilder és színész volt.",
        0,
        ["Hargitay Mariska", "Gábor Zsazsa", "Rachel Weisz", "Estée Lauder"],
        "Hargitay Mariska (1964–) Hargitay Miklós és Jayne Mansfield lánya. A Law & Order: SVU sztárjaként ismert.",
    ),
    _q(
        "Magyar grófnő, az első magyar nő, aki orvosként diplomázott. Zürichben tanult, hazatérve 18 évig csak bábaként dolgozhatott, mert nem ismerték el a diplomáját.",
        0,
        ["Hugonnay Vilma", "Brunszvik Teréz", "Pécsi Eszter", "Slachta Margit"],
        "Hugonnay Vilma (1847–1922) az első magyar női orvos. 1897-ben ismerték el végül a diplomáját, és magánpraxist nyitott főleg nőknek és szegényeknek.",
    ),
    _q(
        "Magyar grófnő és neveléspedagógus. 1828-ban megnyitotta az első magyar óvodát Budapesten, Pestalozzi tanításai alapján.",
        0,
        ["Brunszvik Teréz", "Hugonnay Vilma", "Slachta Margit", "Barnóthy Forró Magda"],
        "Brunszvik Teréz (1775–1861) az első magyar óvoda alapítója. „A korai nevelés a legfontosabb!” – hangzott el híres mondása.",
    ),
    _q(
        "Magyar kémikus és feltaláló. A biztonságos gyufa feltalálója 1836-ban. A fehér foszfor helyett a vörös foszfort használta, ami kevésbé mérgező és kevésbé könnyen gyúlékony.",
        0,
        ["Irinyi János", "Bánki Donát", "Jedlik Ányos", "Bíró László"],
        "Irinyi János (1817–1895) a biztonságos gyufa feltalálója. A „cikketlen gyufa” forradalmasította a mindennapi életet.",
    ),
    _q(
        "Magyar bencés szerzetes, fizikus és feltaláló. Az első villamos dinamó és az első villamos motor megalkotója. Az elektromos járművek úttörője.",
        0,
        ["Jedlik Ányos", "Kandó Kálmán", "Csonka János", "Puskás Tivadar"],
        "Jedlik Ányos (1800–1895) bencés szerzetes és fizikus. Az első elektromos generátort és motort készítette, és a szódavíz készítésének egyik úttörője is volt.",
    ),
    _q(
        "Magyar mérnök, a villamos vasút egyik úttörője. A háromfázisú váltakozó áramú vontatás kidolgozója, a Ganz gyár mérnöke.",
        0,
        ["Kandó Kálmán", "Jedlik Ányos", "Puskás Tivadar", "Kármán Tódor"],
        "Kandó Kálmán (1869–1931) a villamos vasút úttörője. A milánói villamosvonal és más nagyberuházások tervezője volt.",
    ),
    _q(
        "Magyar származású amerikai aerodinamikus. Az aerodinamika és a repülőgépmérnöki tudomány egyik megalapítója. A NASA Jet Propulsion Laboratory szellemi atyja.",
        0,
        ["Kármán Tódor", "Szilárd Leo", "Neumann János", "Teller Ede"],
        "Kármán Tódor (1881–1963) az aerodinamika úttörője. A repülőgépek és rakéták tervezésének elméleti alapjait fektette le.",
    ),
    _q(
        "Magyar származású amerikai informatikus. A BASIC programozási nyelv egyik megalkotója a Dartmouth Egyetemen. A személyi számítógépek elterjedésének úttörője.",
        0,
        ["Kemény János", "Neumann János", "Simonyi Károly", "Rubik Ernő"],
        "Kemény János (1926–1992) a BASIC programozási nyelv egyik megalkotója. A Dartmouth Egyetem elnöke volt, és a számítógépes oktatás úttörője.",
    ),
    _q(
        "Magyar orientalista és tibetológus. Indiában és Tibeten utazott, összeállította az első tibeti–angol szótárt, és a buddhizmus európai tanulmányozásának úttörője volt.",
        0,
        ["Kőrösi Csoma Sándor", "Irinyi János", "Jedlik Ányos", "Kandó Kálmán"],
        "Kőrösi Csoma Sándor (1784–1842) a tibetológia megalapítója. Kőrösen (Romániában) született, Indiában és Tibeten kutatta a tibeti nyelvet és kultúrát.",
    ),
    _q(
        "Kossuth Lajos lánya, magyar írónő és publicista. Apja emigrációja alatt és után is aktívan támogatta a magyar ügyet, és írásaival népszerűsítette a szabadságharcot.",
        0,
        ["Kossuth Zsuzsanna", "Brunszvik Teréz", "Slachta Margit", "Hugonnay Vilma"],
        "Kossuth Zsuzsanna (1817–1854) Kossuth Lajos lánya. Írónőként és publicistaként dolgozott apja mellett.",
    ),
    _q(
        "Magyar orvos, a szervezett mentés és a budapesti önkéntes mentőszolgálat (BÖME) megalapítója 1887-ben. Az anyatej-ellátás és a korcsolyázás népszerűsítője is volt.",
        0,
        ["Kresz Géza", "Semmelweis Ignác", "Bárány Róbert", "Békésy György"],
        "Kresz Géza (1845–1901) orvos, aki 1887-ben megalapította a budapesti önkéntes mentőszolgálatot. Az első szervezett mentés egyik úttörője.",
    ),
    _q(
        "Magyar származású amerikai üzletasszony, aki az Estée Lauder kozmetikai birodalom alapítója lett. A világ egyik legsikeresebb kozmetikai márkáját hozta létre.",
        0,
        ["Estée Lauder", "Adrienne Vittadini", "Gábor Zsazsa", "Anna M. Rosenberg"],
        "Estée Lauder (1906–2004) magyar zsidó családban született New Yorkban. Az Estée Lauder Companies alapítója, a kozmetikai ipar egyik legnagyobb alakja.",
    ),
    _q(
        "Magyar zeneszerző és zongoraművész, a 19. század egyik legnagyobb zeneszerzője. A szimfonikus költemény megteremtője, a zongoraművészet forradalmára.",
        0,
        ["Liszt Ferenc", "Bartók Béla", "Goldmark Károly", "Puskás Tivadar"],
        "Liszt Ferenc (1811–1886) a romantika egyik legnagyobb zeneszerzője és zongoraművésze. A szimfonikus költemények, a zongoraversenyek és a Magyar rapszódiák szerzője.",
    ),
    _q(
        "Magyar operaénekesnő (szoprán), a Metropolitan Opera sztárja. A világ vezető operaházainak vendégművésze, számos Grammy-díjas felvétel készült vele.",
        0,
        ["Marton Kati", "Egerszegi Krisztina", "Polgár Judit", "Pécsi Eszter"],
        "Marton Kati (1943–) magyar operaénekesnő. A Metropolitan Opera és más világvezető operaházak sztárjaként ismert.",
    ),
    _q(
        "Magyar bíboros és esztergomi érsek. A kommunista rezsim egyik legkiemelkedőbb ellenállója, éveket töltött börtönben és az amerikai nagykövetségen menedékben.",
        0,
        ["Mindszenty József", "Slachta Margit", "Kossuth Zsuzsanna", "Brunszvik Teréz"],
        "Mindszenty József (1892–1975) bíboros, esztergomi érsek. A kommunista diktatúra ellenállója, 1956 után 15 évig az amerikai nagykövetségen élt menedékben.",
    ),
    _q(
        "Magyar származású amerikai matematikus és fizikus. A modern számítógép-architektúra és a játékelmélet egyik megalapítója. A „Neumann-architektúra” a nevéhez fűződik.",
        0,
        ["Neumann János", "Kemény János", "Wigner Jenő", "Szilárd Leo"],
        "Neumann János (1903–1957) a számítógép-architektúra és a kvantummechanika úttörője. A Manhattan-projektben is részt vett.",
    ),
    _q(
        "Magyar származású amerikai mérnök, a NASA holdjáró (Lunar Rover Vehicle) főkonstruktőre. Az Apollo 15, 16 és 17 küldetések holdjáróját tervezte.",
        0,
        ["Pavlics Ferenc", "Kandó Kálmán", "Galamb József", "Asboth Oszkár"],
        "Pavlics Ferenc (1928–2024) a holdjáró vezető mérnöke volt. 1956 után emigrált, a General Motorsnál dolgozott, majd a NASA holdjáró-projektjét vezette.",
    ),
    _q(
        "Magyar építészmérnök és statikus. Az első magyar nő, aki mérnöki diplomát szerzett. A Margitszigeti fedett uszoda és más jelentős épületek statikus tervezője volt.",
        0,
        ["Pécsi Eszter", "Barnóthy Forró Magda", "Telkes Mária", "Adrienne Vittadini"],
        "Pécsi Eszter (1899–1975) az első magyar női mérnök. A modern építészet és statika terén dolgozott Budapesten és később New Yorkban.",
    ),
    _q(
        "Magyar sakknagymester, a sakktörténelem legerősebb női játékosa. A legfiatalabb sakknagymester címet szerezte meg (korábban), és háromszor nyert világbajnokságot.",
        0,
        ["Polgár Judit", "Egerszegi Krisztina", "Szeles Mónika", "Marton Kati"],
        "Polgár Judit (1976–) a sakktörténelem legerősebb női játékosa. A „Polgár nővérek” (Zsófia, Zsuzsa, Judit) mind sakknagymesterek lettek.",
    ),
    _q(
        "Magyar újságíró és kiadó. A Pulitzer-díj alapítója, aki végrendeletében létrehozta a híres Pulitzer-díjat az amerikai újságírás, irodalom és zene terén.",
        0,
        ["Pulitzer József", "Zukor Adolf", "Haraszty Ágoston", "Asbóth Sándor"],
        "Pulitzer József (1847–1911) magyar származású amerikai újságíró és kiadó. A Pulitzer-díj alapítója, a New York World tulajdonosa volt.",
    ),
    _q(
        "Magyar mérnök és feltaláló. A telefonközpont és a színházi telefon feltalálója. Edisonnal is dolgozott együtt, és a „távíró” szót is ő alkotta.",
        0,
        ["Puskás Tivadar", "Bíró László", "Kandó Kálmán", "Jedlik Ányos"],
        "Puskás Tivadar (1844–1893) a telefonközpont feltalálója. Edison laboratóriumában dolgozott, és a színházi telefont is feltalálta.",
    ),
    _q(
        "Magyar származású amerikai színésznő. A The Mummy és a The Constant Gardener filmekben játszott, utóbbival Oscar-díjat nyert. Brit állampolgár, magyar felmenőkkel.",
        0,
        ["Rachel Weisz", "Gábor Zsazsa", "Hargitay Mariska", "Estée Lauder"],
        "Rachel Weisz (1970–) brit színésznő magyar zsidó felmenőkkel. Oscar-díjat nyert A Constant Gardener – A tégla meleg napja című filmben nyújtott alakításáért.",
    ),
    _q(
        "Magyar származású amerikai kormánytisztviselő. Truman elnök alatt a Védelmi Minisztérium emberi erőforrásokért felelős helyettes államtitkára volt – a legmagasabb rangú nő a hadseregben.",
        0,
        ["Anna M. Rosenberg", "Estée Lauder", "Adrienne Vittadini", "Slachta Margit"],
        "Anna M. Rosenberg (1899/1902–1983) Budapesten született, az USA-ba emigrált. A koreai háború idején a hadsereg deszegregációjában és a nők bevonásában kulcsfontosságú szerepet játszott.",
    ),
    _q(
        "Magyar építész és feltaláló. A Rubik-kocka megalkotója, amely a világ egyik legnagyobb példányszámban eladott játéka lett.",
        0,
        ["Rubik Ernő", "Bíró László", "Neumann János", "Gábor Dénes"],
        "Rubik Ernő (1944–) a Rubik-kocka feltalálója. Építész és formatervező, a Budapesti Műszaki Egyetem professzora.",
    ),
    _q(
        "Magyar orvos, a gyermekágyi láz megelőzésének úttörője. Az aszeptikus módszerek és a kézmosás bevezetésével drámai csökkenést ért el az anyák halálozásában.",
        0,
        ["Semmelweis Ignác", "Bárány Róbert", "Békésy György", "Kresz Géza"],
        "Semmelweis Ignác (1818–1865) a gyermekágyi láz okának felfedezője. A kézmosás és az aszepszis bevezetésével megmentette több ezer anya életét.",
    ),
    _q(
        "Magyar apáca, politikus és humanitárius aktivista. Az első nő, aki bekerült a magyar országgyűlésbe (1920). A Holokauszt alatt több ezer zsidót mentett, és Világraszólóként ismerik.",
        0,
        ["Slachta Margit", "Brunszvik Teréz", "Hugonnay Vilma", "Anna M. Rosenberg"],
        "Slachta Margit (1884–1974) az első magyar női országgyűlési képviselő. A Szociális Testvérek Kongregációjának alapítója, a Holokauszt alatt több ezer zsidót mentett.",
    ),
    _q(
        "Magyar származású amerikai fizikus. Az első láncreakció elméleti megalapozója, a Manhattan-projekt egyik kezdeményezője. A Szilárd-lemma és más fontos elméletek a nevéhez fűződnek.",
        0,
        ["Szilárd Leo", "Teller Ede", "Wigner Jenő", "Neumann János"],
        "Szilárd Leo (1898–1964) a nukleáris láncreakció elméleti megalapozója. Einsteinnel együtt írta a Roosevelt elnöknek küldött levelet az atombomba fejlesztéséről.",
    ),
    _q(
        "Magyar származású amerikai tudós és feltaláló. A napenergia hasznosításának úttörője, a napenergiával működő ház és a szoláris sós vízdesztilláció kidolgozója.",
        0,
        ["Telkes Mária", "Barnóthy Forró Magda", "Karikó Katalin", "Pécsi Eszter"],
        "Telkes Mária (1900–1995) a napenergia kutatásának úttörője. A passzív napenergia-hasznosítás és a szoláris desztilláció terén dolgozott.",
    ),
    _q(
        "Magyar származású amerikai fizikus, „a hidrogénbomba atyja”. A Manhattan-projektben és a hidrogénbomba fejlesztésében kulcsfontosságú szerepet játszott.",
        0,
        ["Teller Ede", "Szilárd Leo", "Wigner Jenő", "Neumann János"],
        "Teller Ede (1908–2003) a hidrogénbomba egyik fő fejlesztője. A Strategic Defense Initiative (SDI, „Csillagháború”) egyik szellemi atyja is volt.",
    ),
    _q(
        "Magyar származású divattervező. Budapesten született, 1956 után emigrált. Az Adrienne Vittadini divatmárka alapítója, elegancia és sportos stílus keverékével.",
        0,
        ["Adrienne Vittadini", "Estée Lauder", "Gábor Zsazsa", "Anna M. Rosenberg"],
        "Adrienne Vittadini (1945–) Budapesten született, 1956 után emigrált. Az Adrienne Vittadini divatmárka alapítója, sportruházat és kiegészítők tervezője.",
    ),
    _q(
        "Magyar származású úszó és színész. Ötszörös olimpiai bajnok, „Tarzan” szerepében vált világhírűvé a klasszikus filmekben.",
        0,
        ["Weissmüller János", "Egerszegi Krisztina", "Pavlics Ferenc", "Kőrösi Csoma Sándor"],
        "Weissmüller János (1904–1984) magyar származású amerikai úszó és színész. Ötszörös olimpiai bajnok, a Tarzan-filmek sztárja.",
    ),
    _q(
        "Magyar származású amerikai fizikus. Az atommag és az elemi részecskék elméletéhez adott alapvető hozzájárulásaiért kapott Nobel-díjat. A szimmetriaelvek a kutatásának középpontjában álltak.",
        0,
        ["Wigner Jenő", "Szilárd Leo", "Teller Ede", "Gábor Dénes"],
        "Wigner Jenő (1902–1995) fizikai Nobel-díjas. Az atommagfizika és a kvantummechanika egyik megalapítója, a Wigner-függvény a nevéhez fűződik.",
    ),
    _q(
        "Magyar származású amerikai filmproducer. A Paramount Pictures egyik alapítója, a moziipar úttörője. A „A mozi királya” melléknevet kapta.",
        0,
        ["Zukor Adolf", "Pulitzer József", "Gróf András", "Haraszty Ágoston"],
        "Zukor Adolf (1873–1976) a Paramount Pictures alapítója. A hosszú játékfilmek és a moziipar egyik úttörője volt.",
    ),
    _q(
        "Magyar fizikus, a katódsugarak vizsgálatáért kapott Nobel-díjat. A fotoelektromos jelenség és a röntgensugárzás kutatásában is fontos eredményeket ért el.",
        0,
        ["Lénárd Fülöp", "Bárány Róbert", "Zsigmondy Richard Adolf", "Gábor Dénes"],
        "Lénárd Fülöp (1862–1947) fizikai Nobel-díjas. A katódsugarak vizsgálatáért kapta a díjat, bár később a nácizmussal szimpatizált.",
    ),
    _q(
        "Magyar orvos, a belső fül és az egyensúlyérzék kutatásáért kapott Nobel-díjat. Az egyensúlyozó szervek működésének feltérképezője.",
        0,
        ["Bárány Róbert", "Békésy György", "Semmelweis Ignác", "Karikó Katalin"],
        "Bárány Róbert (1876–1936) orvostudományi Nobel-díjas. A belső fül és az egyensúlyérzék kutatásáért kapta a díjat.",
    ),
    _q(
        "Magyar származású német kémikus. A kolloidok vizsgálatáért és az ultramikroszkóp fejlesztéséért kapott Nobel-díjat.",
        0,
        ["Zsigmondy Richard Adolf", "Hevesy György", "Oláh György", "Herskó Ferenc"],
        "Zsigmondy Richard Adolf (1865–1929) kémiai Nobel-díjas. Az ultramikroszkóp feltalálója, a kolloidkémia úttörője.",
    ),
    _q(
        "Magyar biokémikus, a C-vitamin azonosításáért és a biológiai oxidáció vizsgálatáért kapott Nobel-díjat. A magyar tudomány egyik legnagyobb alakja.",
        0,
        ["Szent-Györgyi Albert", "Hevesy György", "Békésy György", "Karikó Katalin"],
        "Szent-Györgyi Albert (1893–1986) orvostudományi Nobel-díjas. A C-vitamin felfedezője, a biológiai oxidáció és az izomkutatás úttörője.",
    ),
    _q(
        "Magyar származású kémikus. Az izotópos nyomjelzés módszeréért kapott Nobel-díjat. A hafnium elem egyik felfedezője.",
        0,
        ["Hevesy György", "Zsigmondy Richard Adolf", "Oláh György", "Polányi János"],
        "Hevesy György (1885–1966) kémiai Nobel-díjas. Az izotópos nyomjelzés módszerének kidolgozója, a hafnium felfedezője.",
    ),
    _q(
        "Magyar származású amerikai biofizikus. A hallás mechanizmusának és a csiga működésének vizsgálatáért kapott Nobel-díjat.",
        0,
        ["Békésy György", "Bárány Róbert", "Semmelweis Ignác", "Karikó Katalin"],
        "Békésy György (1899–1972) orvostudományi Nobel-díjas. A hallás fiziológiájának kutatásáért kapta a díjat.",
    ),
    _q(
        "Magyar származású amerikai író és aktivista. A Holokauszt túlélője, a Békélnobel-díjjal kitüntetett író. Az Éj (La Nuit) és más művek szerzője.",
        0,
        ["Elie Wiesel", "Kertész Imre", "Slachta Margit", "Anna M. Rosenberg"],
        "Elie Wiesel (1928–2016) magyar származású (Érsekújváron született) amerikai író. 1986-ban Békélnobel-díjat kapott, a Holokauszt egyik legfontosabb tanúja.",
    ),
    _q(
        "Magyar származású kanadai kémikus. A kémiai elemi reakciók dinamikájának kutatásáért kapott Nobel-díjat.",
        0,
        ["Polányi János", "Oláh György", "Herskó Ferenc", "Hevesy György"],
        "Polányi János (1929–) kémiai Nobel-díjas. A kémiai reakciók dinamikájának kutatásáért kapta a díjat.",
    ),
    _q(
        "Magyar származású amerikai kémikus. A karbokationok és szupererős savak kutatásáért kapott Nobel-díjat.",
        0,
        ["Oláh György", "Polányi János", "Herskó Ferenc", "Zsigmondy Richard Adolf"],
        "Oláh György (1927–2017) kémiai Nobel-díjas. A karbokationok kémiájának kutatásáért kapta a díjat.",
    ),
    _q(
        "Magyar származású amerikai közgazdász. A hiányos információjú játékelmélet kidolgozásáért kapott Nobel-díjat.",
        0,
        ["Harsányi János", "Neumann János", "Kemény János", "Gróf András"],
        "Harsányi János (1920–2000) közgazdasági Nobel-díjas. A játékelmélet és a közgazdaságtan terén végzett munkájáért kapta a díjat.",
    ),
    _q(
        "Magyar író, a Sorstalanság című regényéért kapott irodalmi Nobel-díjat. A Holokauszt irodalmi feldolgozásának egyik legnagyobb alakja.",
        0,
        ["Kertész Imre", "Elie Wiesel", "Polgár Judit", "Kossuth Zsuzsanna"],
        "Kertész Imre (1929–2016) irodalmi Nobel-díjas. A Sorstalanság a Holokauszt egyik legfontosabb irodalmi emlékműve.",
    ),
    _q(
        "Magyar származású izraeli biokémikus. Az ubikvitin-mediált fehérjelebontás felfedezéséért kapott Nobel-díjat.",
        0,
        ["Herskó Ferenc", "Karikó Katalin", "Szent-Györgyi Albert", "Oláh György"],
        "Herskó Ferenc (1937–) kémiai Nobel-díjas. Az ubikvitin-mediált fehérjelebontás felfedezéséért kapta a díjat.",
    ),
    _q(
        "Magyar biokémikus, a nukleozid-módosított mRNS technológiáért kapott Nobel-díjat. A COVID-19 mRNA vakcinák alapját fektette le.",
        0,
        ["Karikó Katalin", "Telkes Mária", "Barnóthy Forró Magda", "Szent-Györgyi Albert"],
        "Karikó Katalin (1955–) orvostudományi Nobel-díjas. A mRNA technológia úttörője, a COVID-19 vakcinák alapját fektette le.",
    ),
    _q(
        "Magyar fizikus, az attoszekundumos fényimpulzusok előállításáért és méréséért kapott Nobel-díjat.",
        0,
        ["Krausz Ferenc", "Gábor Dénes", "Wigner Jenő", "Lénárd Fülöp"],
        "Krausz Ferenc (1962–) fizikai Nobel-díjas. Az attoszekundumos lézertechnika úttörője, a legrövidebb fényimpulzusok előállítója.",
    ),
    _q(
        "Magyar származású amerikai informatikus. A Microsoft Word és Excel egyik fő fejlesztője. Az első magánűrhajósok egyike, aki a Nemzetközi Űrállomásra repült.",
        0,
        ["Simonyi Károly", "Neumann János", "Kemény János", "Gróf András"],
        "Simonyi Károly (1948–) a Microsoft Word és Excel egyik fő fejlesztője. Kétszer repült az űrbe magánűrhajósként.",
    ),
    _q(
        "Magyar származású teniszezőnő. Kilenc Grand Slam győzelmet aratott, a világranglista első helyén állt. 2007-ben magyar állampolgárságot kapott.",
        0,
        ["Szeles Mónika", "Egerszegi Krisztina", "Polgár Judit", "Marton Kati"],
        "Szeles Mónika (Monica Seles, 1973–) etnikailag magyar teniszezőnő, Jugoszláviában született. Kilenc Grand Slam-et nyert, 2007-ben magyar állampolgár lett.",
    ),
    _q(
        "Magyar és az Osztrák-Magyar Monarchia első női pilótája. 1912-ben Bécsújhelyen letette a pilótavizsgát, 21 évesen. A budapesti repülőverseny ihlette el a repülés iránti szenvedélyét.",
        0,
        ["Steinschneider Lilly", "Barnóthy Forró Magda", "Pécsi Eszter", "Telkes Mária"],
        "Steinschneider Lilly (1891–1975) az első magyar női pilóta. Budapesten született, 1912-ben kapta meg a Magyar Aero Szövetség 4. számú pilótaigazolványát.",
    ),
    _q(
        "Magyar származású osztrák író, születési neve Salzmann Zsigmond. A Bambi című regény szerzője, amely a Walt Disney rajzfilm alapjául szolgált. Pesten született, háromhetes korában Bécsbe költözött.",
        0,
        ["Salzmann Zsigmond", "Pulitzer József", "Zukor Adolf", "Kertész Imre"],
        "Salzmann Zsigmond (1869–1945), ismertebb nevén Felix Salten, a Bambi szerzője. Magyar származású író, Pesten született, Bécsben és később Zürichben élt.",
    ),
    _q(
        "Magyar sakknagymester, Polgár Judit és Polgár Zsuzsa testvére. 1989-ben Rómában világszenzációt keltett 14 évesen páratlan teljesítménnyel. Kétszeres sakkolimpiai bajnok.",
        0,
        ["Polgár Zsófia", "Polgár Judit", "Egerszegi Krisztina", "Szeles Mónika"],
        "Polgár Zsófia (1974–) a „Polgár nővérek” egyike, női nemzetközi nagymester. 1989-ben Rómában 2900 körüli performance ratinggel játszott, máig páratlan eredmény.",
    ),
    _q(
        "Magyar hegedűművész és zeneszerző, születési nevén Hoffmann Ede. Az 1848/49-es szabadságharc után emigrált, Görgey Artúr tábornok kedvenc hegedűse volt. Liszt Ferenc barátja és munkatársa.",
        0,
        ["Reményi Ede", "Liszt Ferenc", "Bartók Béla", "Goldmark Károly"],
        "Reményi Ede (1828–1898) hegedűművész és zeneszerző. Miskolcon született, az 1848/49-es forradalom után Amerikába emigrált, később hazatért és Európában koncertezett.",
    ),
    _q(
        "Magyar származású amerikai fizikus, a plazmafizika és a fúziós energia kutatásának nemzetközileg elismert szakértője. A MIT Plasma Science and Fusion Center igazgatója volt, a James Clerk Maxwell-díj és a Hannes Alfvén-díj kitüntetettje.",
        0,
        ["Porkoláb Miklós", "Kármán Tódor", "Szilárd Leo", "Teller Ede"],
        "Porkoláb Miklós (1937–) magyar származású fizikus, Budapesten született. A MIT professzora, a fúziós energia kutatásának világszínvonalú szakértője, 2016-ban a Magyar Tudományos Akadémia külső tagjává választották.",
    ),
]
