# Idióta szavak kérdések többválasztós opciókkal

_TOPIC = 'idiota_szavak'


def _q(question, correct, options, explanation, topic=_TOPIC):
    """Segédfüggvény: kompakt kérdés létrehozása."""
    return {"question": question, "options": options, "correct": correct, "explanation": explanation, "topic": topic}


IDIOTA_SZAVAK_QUESTIONS = [
    _q('Hogy hívják a **dán életfelfogást, kellemes, otthonos hangulatot**?', 0, ['Hygge', 'Lagom', 'Sisu', 'Friluftsliv'], 'A dán életfelfogást, kellemes, otthonos hangulatot hygge-nek hívják. Ez a dán kultúra egyik alapvető fogalma, amely a kellemes, otthonos pillanatokat jelenti.'),
    _q('Hogy hívják a **japán életcél fogalmat, az élet értelmét**?', 0, ['Ikigai', 'Wabi-sabi', 'Zen', 'Kintsugi'], 'A japán életcél fogalmat, az élet értelmét ikigai-nak hívják. Ez a japán filozófia egyik alapvető fogalma, amely az élet értelmét és célját jelenti.'),
    _q('Hogy hívják a **japán termálfürdőt**?', 0, ['Onsen', 'Sento', 'Ramen', 'Sake'], 'A japán termálfürdőt onsennak hívják. Ezek a természetes forróvizes forrásokból táplálkozó fürdők, amelyek a japán kultúra fontos részei.'),
    _q('Mit jelent az alábbi idióta szó: **appaloosa**?', 0, ['Amerikai indián lovasfajta, pettyes szőrrel', 'Spanyol tánc', 'Afrikai törzsi maszk', 'Ókori görög fegyver'], "A(z) 'appaloosa' jelentése: Amerikai indián lovasfajta, pettyes szőrrel"),
    _q('Mit jelent az alábbi idióta szó: **apszis**?', 0, ['apszis', 'axis', 'alkóv', 'apcisz'], "Az apszis építészeti elem: a templomokban a szentély vagy főoltár mögötti félkör (vagy sokszögű) fülke. A görög 'ápsis' (ἁψίς) szóból ered, a klasszikus római építészetből származik. A keresztény templomokban gyakran itt található a főoltár."),
    _q('Hogy hívják a **sefárd zsidók nyelvét**?', 0, ['Ladino', 'Jiddis', 'Hebrea', 'Aramita'], 'A sefárd zsidók nyelvét ladinonak hívják. Ez egy spanyol nyelvjárás, amelyet a 1492-es kiűzetés után a sefárd zsidók őriztek meg és használtak.'),
    _q('Mit jelent az alábbi idióta szó: **sinobi-kunoicsi**?', 0, ['Nindzsa harcosok', 'Szamurájok', 'Kamikaze pilóták', 'Ronin harcosok'], "A(z) 'sinobi-kunoicsi' jelentése: Nindzsa harcosok"),
    _q('Mit jelent az alábbi idióta szó: **talkum**?', 0, ['Por, amit a bőrre szórnak', 'Fűszer', 'Gyógyszer', 'Festék'], "A(z) 'talkum' jelentése: Por, amit a bőrre szórnak"),
    _q('Hogy hívják a **dominikai táncot és zenei stílust**?', 0, ['Merengue', 'Salsa', 'Bachata', 'Reggaeton'], 'A dominikai táncot és zenei stílust merengue-nek hívják. Ez a Dominikai Köztársaság nemzeti tánca, amely gyors tempójú és ritmikus.'),
    _q('Hogy hívják a fiktív bárt a **From Dusk Till Dawn** filmből?', 0, ['Titty Twister', 'The Vampire Bar', 'El Diablo', "Satan's Hideout"], 'A From Dusk Till Dawn filmben a fiktív bár neve Titty Twister. Ez egy vampírok által lakott bár, ahol a film főbb cselekménye játszódik.'),
    _q('Mit jelent az alábbi idióta szó: **homo florensis**?', 0, ["Kihalt emberfaj, 'hobbit' ember", 'Neandervölgyi ember', 'Homo erectus', 'Australopithecus'], "A(z) 'homo florensis' jelentése: Kihalt emberfaj, 'hobbit' ember"),
    _q('Mit jelent az alábbi idióta szó: **endoplazmatikus retikulum**?', 0, ['Sejtszervecske, fehérje szintézis', 'Mitokondrium', 'Golgi-készülék', 'Lizoszóma'], "A(z) 'endoplazmatikus retikulum' jelentése: Sejtszervecske, fehérje szintézis"),
    _q('Mit jelent az alábbi idióta szó: **marengo csirke**?', 0, ['Olasz étel, csirke szósszal', 'Francia pác', 'Spanyol tapas', 'Görög saláta'], "A(z) 'marengo csirke' jelentése: Olasz étel, csirke szósszal"),
    _q('Mit jelent az alábbi idióta szó: **kallisztenix**?', 0, ['Ókori görög pankráció bajnok', 'Római gladiátor', 'Görög filozófus', 'Olimpiai bíró'], 'A kallisztenix egy ókori görög pankráció bajnok volt. A pankráció egy kevert harcművészet volt, amely bokszot és birkózást ötvözött. Kallisztenix a Kr.e. 2. században élt és többszörös olimpiai bajnok volt.'),
    _q('Hogy hívják a **pápai hivatalnokot**?', 0, ['Kamerlengo', 'Kardinális', 'Nuncius', 'Prefektus'], 'A pápai hivatalnokot kamerlengonek hívják. Ez a Vatikán egyik legmagasabb rangú hivatalnoka, aki a pápai kamara vezetője.'),
    _q('Mit jelent az alábbi idióta szó: **guanakó**?', 0, ['Dél-amerikai lámafaj', 'Alpaka', 'Vikunya', 'Andoki kondor'], "A(z) 'guanakó' jelentése: Dél-amerikai lámafaj"),
    _q('Mi az az eszköz, ami nyomás és magas hőmérséklet mellett fertőtlenítésre használunk?', 0, ['Autókláv', 'Sztúra', 'Inkubátor', 'Centrifuga'], 'Az autókláv egy nyomás és magas hőmérséklet mellett működő fertőtlenítő készülék. Laboratóriumokban, kórházakban és ipari környezetben használják a sterilizálásra. A magas hőmérséklet és nyomás kombinációja biztosítja a mikroorganizmusok teljes elpusztítását.'),
    _q('Milyen pénznem **K** betűvel?', 0, ['Kwanza', 'Kina', 'Forint', 'Korona'], 'A K betűvel kezdődő pénznem a Kwanza, amely Angola hivatalos pénzneme. A kwanza 1977-ben váltotta fel az angolai escudót.'),
    _q('Hogy hívják a **video szerkesztő alkalmazást**?', 0, ['CapCut', 'iMovie', 'DaVinci Resolve', 'Adobe Premiere'], 'A video szerkesztő alkalmazást CapCut-nak hívják. Ez a ByteDance által fejlesztett ingyenes video szerkesztő alkalmazás, amely TikTok videók készítésére is használható.'),
    _q('Hogy hívják a **brit média céget**?', 0, ['Unilad', 'Ladbible', 'BuzzFeed', 'Vice'], 'A brit média céget Unilad-nak hívják. Ez egy digitális média cég, amely fiatal férfiaknak szóló tartalmakat készít.'),
    _q('Hogy hívják a **lengyel játékfejlesztő céget**?', 0, ['CD Projekt RED', 'Ubisoft', 'Electronic Arts', 'Paradox Interactive'], 'A lengyel játékfejlesztő céget CD Projekt RED-nek hívják. Ez a cég a Witcher sorozat és a Cyberpunk 2077 fejlesztője.'),
    _q('Hogy hívják az **égbolt legalsó pontját**?', 0, ['Nadír', 'Zenit', 'Horizont', 'Meridián'], 'Az égbolt legalsó pontját nadírnak hívják. Ez a zenit ellentéte - míg a zenit a fejünk feletti pont, addig a nadír a lábunk alatti pont az égbolton.'),
    _q('Hogy hívják a **fekete lyuk határát**?', 0, ['Eseményhorizont', 'Singularitás', 'Akkréciós korong', 'Foton gömb'], 'A fekete lyuk határát eseményhorizontnak hívják. Ez az a pont, ahonnan már semmi, még a fény sem tud kiszabadulni a fekete lyuk gravitációs teréből.'),
    _q('Hogy hívják a **keresztes lovagot Tasso művéből**?', 0, ['Tankréd lovag', 'Rinaldo', 'Goffredo', 'Baudolino'], "A keresztes lovagot Tasso művéből Tankréd lovagnak hívják. Ez Torquato Tasso 'A megszabadított Jeruzsálem' című eposzából származó karakter, aki a keresztes lovagok egyik vezetője."),
    _q('Jamaikai vallás **R** betűvel', 0, ['Rasztafári', 'Voodoo', 'Szufizmus', 'Santeria'], 'A Jamaikai vallás R betűvel a Rasztafári vallás. Ez egy monoteista vallási mozgalom, amely Etiópia volt császárát, Hailé Szelassziét tekinti Isten megtestesülésének.'),
    _q('Melyik történetíróhoz fűződik a **Párhuzamos életrajzok**?', 0, ['Plutharkosz', 'Hérodotosz', 'Thuküdidész', 'Xenophón'], "A 'Párhuzamos életrajzok' Plutharkosz (kb. 46-120) ókori görög történetíró, filozófus és biográfus műve. Ebben a műben görög és római híres személyek életét hasonlította össze."),
    _q('Mit jelent az alábbi idióta szó: **Takla-Makán**?', 0, ['Kína sivataga', 'Gobi sivatag', 'Szahara', 'Karakum'], "A(z) 'Takla-Makán' jelentése: Kína sivataga"),
    _q('Mit jelent az alábbi idióta szó: **Dahomey**?', 0, ['Afrikai királyság Benin területén 16-19. században', 'Kongó királyság', 'Mali birodalom', 'Szonghai birodalom'], "A(z) 'Dahomey' jelentése: Afrikai királyság Benin területén 16-19. században"),
    _q('Amerikai rajzfilmsorozat 1999-től **F** betűvel', 0, ['Futurama', 'Simpson család', 'Family Guy', 'South Park'], 'Az Amerikai rajzfilmsorozat 1999-től F betűvel a Futurama. Ez egy sci-fi animációs sorozat, amelyet Matt Groening készített, és egy pizzafutár, Fry kalandjait követi a 31. században.'),
    _q('Ki írta le a Lagrange mechanikát?\n\n**Lagrange pontok:** Egymás körül keringő tömeg (pl. Föld és Nap) gravitációs terében, ahol egy harmadik, sokkal kisebb test (pl. űrszonda) viszonylagos mozdulatlanságban maradhat. Ezen pontok segítségével azonosíthatók az asztrodinamikai szempontból stabil vagy instabil pályák, különösen a Hold, a Föld és a Nap rendszerében, valamint más bolygórendszerekben.', 0, ['Joseph-Louis Lagrange', 'Isaac Newton', 'Leonhard Euler', 'Pierre-Simon Laplace'], 'A Lagrange mechanikát Joseph-Louis Lagrange (1736-1813) olasz-francia matematikus és fizikus írta le. A Lagrange pontok az űrhajózásban fontos szerepet játszanak, mivel ezeken a pontokon az űreszközök minimális energia felhasználással stabil pályán maradhatnak.'),
    _q('Mit neveztek **cserépszavazás**nak az ókori Athénban?', 0, ['Osztrakiszmosz', 'Peti', 'Ekkleszia', 'Bule'], "A cserépszavazást ókori görögül 'osztrákiszmosz'-nak nevezték. Az ókori Athénban használt eljárás, ahol a polgárok cseréptöredékekre (osztrákákra) írták fel a számukra kellemetlen személyek nevét, és aki a legtöbb szavazatot kapta, azt száműzték a városból 10 évre."),
    _q('Mit jelent az alábbi idióta szó: **Auxológia**?', 0, ['Növekedéskutatás', 'Gerinctan', 'Bőrgyógyászat', 'Gyermekgyógyászat'], "Az 'Auxológia' jelentése: Növekedéskutatás. A gyermekek és fiatalok fizikai fejlődésének, növekedésének tudományos vizsgálata. A szó a görög 'auxein' (növekedni) és 'logos' (tudomány) szavakból származik."),
    _q('Hogy hívják a **május 6-i roma ünnepet a Balkánon**? Ez a roma kultúra egyik legfontosabb ünnepe, amely a tavasz érkezését és a természet újjászületését ünnepli. Az ünnep során a roma közösségek összegyűlnek, énekelnek, táncolnak és hagyományos ételeket készítenek.', 0, ['Éderlezi / Ederlezi', 'Vasárnap', 'Khamoro', 'Roma nap'], 'A május 6-i roma ünnepet a Balkánon Éderlezi-nek hívják. Ez a roma kultúra egyik legfontosabb ünnepe, amely a tavasz érkezését és a természet újjászületését ünnepli. Az ünnep során a roma közösségek összegyűlnek, énekelnek, táncolnak és hagyományos ételeket készítenek.'),
    _q('A hegy, ahonnan Mózes megpillantotta a Kánaánt és ahol is Mózes meghalt.', 0, ['Nébó hegy', 'Sínai hegy', 'Olajfák hegye', 'Karmel hegy'], 'A Nébó hegy (hebraiul: הַר נְבוֹ, Har Nevo) a Jordán folyótól keletre, a mai Jordánia területén található hegy. A Biblia szerint itt halt meg Mózes, miután megpillantotta a Kánaán földjét, ahová az Izraeliták be akartak vonulni. A hegy a Mózes 5. könyvében szerepel, ahol Mózes a hegy tetejéről láthatja a Kánaán földjét, de nem lépheti át a Jordán folyót.'),
    _q('Melyik az a hagyományos, keményítőtartalmú étel Nyugat- és Közép-Afrikából, amelyet keményítőtartalmú hozzávalók, például manióka, jamszgyökér vagy főzőbanán főzésével, pürésítésével és sima, rugalmas tésztalabdává formálással készítenek? (F)', 0, ['Fufu', 'Injera', 'Jollof', 'Suya'], 'A fufu egy hagyományos afrikai étel, amelyet Nyugat- és Közép-Afrikában készítenek. Keményítőtartalmú hozzávalókból (manióka, jamszgyökér, főzőbanán, taro vagy kukorica) készül. A hozzávalókat megfőzik, pürésítik, majd sima, rugalmas tésztalabdává formálják. A fufu általában szósszal vagy levesekkel együtt fogyasztják, és kézzel eszik. Ez az egyik legfontosabb alapétel sok afrikai országban.'),
    _q('Melyik az a rendkívül egészséges, temérdek pozitív egészségügyi hatással rendelkező, a barna algák fajához tartozó alga fajta, melyet a világ számos országában fogyasztanak. Legnagyobb felhasználói a japánok, akik több mint másfél évezrede használják, és úgy tekintenek rá, mint az egészség és a hosszú élettartam zálogára.', 0, ['Kombu', 'Nori', 'Wakame', 'Spirulina'], 'A kombu egy barna alga fajta (Laminaria japonica), amelyet a világ számos országában fogyasztanak, de leginkább Japánban. A japánok több mint 1500 éve használják, és az egészség és hosszú élettartam szimbólumának tekintik. A kombu rendkívül gazdag jódban, vitaminokban és ásványi anyagokban. Gyakran használják dashi (japán alaplé) készítésére, és számos pozitív egészségügyi hatással rendelkezik, köztük a pajzsmirigy működés javításával és az immunrendszer erősítésével.'),
    _q('Egy horvát technológiai vállalat, amely egy azonos nevű népszerű sportstatisztikai és élő eredményalkalmazást fejleszt és tart karban. A 2010-ben indított alkalmazás körülbelül 20 sportág adatait szolgáltatja több ezer ligában világszerte. (S)', 0, ['Sofascore', 'Flashscore', 'FotMob', 'OneFootball'], 'A Sofascore egy horvát technológiai vállalat és azonos nevű alkalmazás, amely élő eredményeket és sportstatisztikákat kínál közel 20 sportághoz, több ezer ligában világszerte. 2010-ben indult, és széles körben használják a sportkedvelők.'),
    _q('Theodore John „Ted” Kaczynski amerikai anarchista, terrorista, aki levélbombáiról híresült el. Több egyetemnek és légitársaságnak küldött levélbombát a kései 1970-es évektől az 1990-es évek elejéig. Robbanószerkezetei három embert megöltek, 23-at megsebesítettek. (U)', 0, ['Unabomber', 'Zodiac', 'BTK', 'Son of Sam'], 'Ted Kaczynski, ismertebb nevén Unabomber.\n\n![Ted Kaczynski](https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Ted_Kaczynski.jpg/220px-Ted_Kaczynski.jpg)'),
    _q('Milyen becenéven vált ismertté az ausztrál breaktáncos, aki részt vett a 2024-es párizsi olimpián?\n\nElőadását szokatlan padlómozgás és „rúgásos” stílus jellemezte, ami egyszerre váltott ki gúnyt és csodálatot a nézőkből. (R)', 0, ['Raygun', 'B-Boy', 'Breakmaster', 'Footwork'], 'Az ausztrál breaktáncos, aki a 2024-es párizsi olimpián vett részt, Raygun becenéven vált ismertté. Szokatlan padlómozgása és „rúgásos” stílusa egyszerre váltott ki gúnyt és csodálatot a nézőkből.'),
    _q('Középkori vallási mozgalom tagjai, akik bűneik vezekléséül testüket naponta ostorozták – hogy hívják őket?', 0, ['Flagellánsok', 'Aszkéták', 'Koldulórendek', 'Pénitensek'], "A flagellánsok középkori mozgalom tagjai voltak, akik önkéntes testi önfenyítéssel (ostorozással) kívánták bűneiket vezekelni. A szó a latin 'flagello' (ostoroz) szóból ered. A mozgalom a 14. századi pestisjárvány idején érte el legnagyobb felfutását."),
]