# irodalom kvíz kérdések

_TOPIC = "irodalom"


def _q(question, correct, options, explanation, topic=_TOPIC):
    """Segédfüggvény: kompakt kérdés létrehozása."""
    return {"question": question, "options": options, "correct": correct, "explanation": explanation, "topic": topic}


IRODALOM_QUESTIONS = [
    _q('Feltételezhetően 1944. november 9-én hunyt el Radnóti Miklós költő, a modern magyar líra kiemelkedő képviselője. Ki volt az a francia költő, aki 1918-ban szintén november 9-én hunyt el és akinek Radnóti sok versét magyarra fordította?', 2, ['Charles Baudelaire', 'Paul Éluard', 'Guillaume Apollinaire', 'Jean Cocteau'], 'Helyes válasz: Guillaume Apollinaire'),
    _q('1791. november 11-én született Katona József drámaíró, a magyar drámairodalom kiemelkedő alakja. Legismertebb műve a Bánk bán, amelyből 1861-ben Erkel Ferenc írt háromfelvonásos operát Egressy Béni szövegkönyvére. Mikor játszódik a Bánk bán története?', 1, ['1113-ban', '1213-ban', '1313-ban', '1413-ban'], 'Helyes válasz: 1213-ban'),
    _q('November 17-e Budapest napja annak emlékére, hogy 1873-ban ezen a napon ülésezett először a Pest, Buda és Óbuda egyesülésével létrejött székesfőváros közgyűlése. Ki nevezte először Buda-Pestnek a korábban Pest-Budaként emlegetett városokat?', 2, ['Arany János', 'Petőfi Sándor', 'Széchenyi István', 'Kossuth Lajos'], 'Helyes válasz: Széchenyi István'),
    _q('1773. november 17-én született Csokonai Vitéz Mihály, a magyar felvilágosodáskori irodalom egyik legjelentősebb költője. Mi volt múzsájának, nagy szerelmének neve?', 1, ['Anna', 'Lilla', 'Léda', 'Berta'], 'Helyes válasz: Lilla'),
    _q('1939. november 18-án született Margaret Atwood kanadai író, költő, irodalomkritikus és feminista aktivista. Leghíresebb műve A szolgálólány meséje, amelyből sorozat is készült. Melyik mai ország területén fekszik Gileád, ahol a termékeny nőknek szolgálólányként kell dolgozniuk és egyetlen feladatuk minél több gyermeket szülni a ház urának?', 1, ['Franciaország', 'Amerikai Egyesült Államok', 'Kanada', 'Oroszország'], 'Helyes válasz: Amerikai Egyesült Államok'),
    _q('1855. november 19-én hunyt el Vörösmarty Mihály magyar költő, író, ügyvéd, táblabíró, a Magyar Tudományos Akadémia és a Kisfaludy Társaság rendes tagja, a magyar romantika egyik legnagyobb alakja. Melyik művét szokták hattyúdalának nevezni, mivel nem sokkal halála előtt írta?', 2, ['Szózat', 'Gondolatok a könyvtárban', 'A vén cigány', 'Csongor és Tünde'], 'Helyes válasz: A vén cigány'),
    _q('1858. november 20-án született Selma Lagerlöf svéd írónő, akinek Nils Holgerson kalandjait köszönhetjük. Ő volt az első nő, aki irodalmi Nobel-díjat kapott. Milyen céllal írta meg a törpévé változtatott kisfiú történetét?', 2, ['azért, hogy a gyerekek jobban megismerjék a háziállatok életét', 'azért, hogy a gyerekek az élvezetes történetek segítségével megszeressék az olvasást', 'azért, hogy a gyerekek jobban megismerjék Svédország földrajzát', 'azért, hogy erőszakmentes meséket tudjon olvasni a gyermekeinek'], 'Helyes válasz: azért, hogy a gyerekek jobban megismerjék Svédország földrajzát'),
    _q('1877. november 22-én született Ady Endre, a huszadik század egyik legjelentősebb magyar költője. Hogy nevezte verseiben feleségét, Boncza Bertát?', 3, ['Léda', 'Bertuska', 'Bella', 'Csinszka'], 'Helyes válasz: Csinszka'),
    _q('1963. november 22-én hunyt el John Fitzgerald Kennedy, az Amerikai Egyesült Államok 35. elnöke, 1961 és 1963 között. Melyik államban követte el ellene a merényletet Lee Harvey Oswald, amelynek következtében életét vesztette?', 0, ['Texas', 'Maine', 'Kalifornia', 'Iowa'], 'Helyes válasz: Texas'),
    _q('1802. november 25-én alapította Gróf Széchényi Ferenc az Országos Széchényi Könyvtárat. Melyik állítás NEM igaz?', 2, ['Kossuth Lajos és Madách Imre könyvtárai a gyűjtemény értékes részévé váltak', 'A könyvtár üzemelteti a Magyar Elektronikus Könyvtárat, ami jelenleg kb. 21500 letölthető dokumentumot tartalmaz', 'A könyvtár minden nyomtatott kiadványból 2 kötelespéldányt kap, de nem nyomtatott kiadványokat nem gyűjt', 'A könyvtár őrzi a legrégebbi magyar összefüggő szöveget, a Halotti beszédet'], 'Helyes válasz: A könyvtár minden nyomtatott kiadványból 2 kötelespéldányt kap, de nem nyomtatott kiadványokat nem gyűjt'),
    _q('1912-ben ezen a napon vált függetlenné Albánia az Oszmán Birodalomtól. Mi a legvalószínűbb jelentése az ország nevének saját nyelvükön?', 1, ['aranyló búzamezők földje', 'sasok földje', 'déli vidék', 'bátor vitézek földje'], 'Helyes válasz: sasok földje'),
    _q('1800. december 1-jén született Vörösmarty Mihály magyar költő, író, ügyvéd, táblabíró, a Magyar Tudományos Akadémia és a Kisfaludy Társaság rendes tagja, a magyar romantika egyik legnagyobb alakja. Melyik művét szokták hattyúdalának nevezni, mivel nem sokkal halála előtt írta?', 2, ['Gondolatok a könyvtárban', 'Csongor és Tünde', 'A vén cigány', 'Szózat'], 'Helyes válasz: A vén cigány'),
    _q('1547. december 2-án hunyt el Hernán Cortés de Monroy y Pizarro spanyol konkvisztádor, aki 1521-ben megdöntötte az Azték Birodalmat, létrehozta a mai Mexikó elődjének számító Új-Spanyolország gyarmatot és annak első kormányzója volt. Mikor vált függetlenné Mexikó Spanyolországtól?', 1, ['1786', '1821', '1856', '1898'], 'Helyes válasz: 1821'),
    _q('1937. december 3-án hunyt el József Attila. Melyik verse miatt tanácsolta el a tanári pályától Horger Antal szegedi professzor?', 2, ['Nem én kiáltok', 'Levegőt!', 'Tiszta szívvel', 'Születésnapomra'], 'Helyes válasz: Tiszta szívvel'),
    _q('1892. december 18-án mutatták be először A diótörő című művet Szentpéterváron, amely Csajkovszkij utolsó balettje és egyben utolsó színpadi műve volt. Kinek a műve A diótörő és az egérkirály, amely alapján a balett született?', 3, ['Hans Christian Andersen', 'Alekszandr Szergejevics Puskin', 'Grimm fivérek', 'E. T. A. Hoffmann'], 'Helyes válasz: E. T. A. Hoffmann'),
    _q('1865. december 26-án született Róth Miksa magyar üvegfestő és mozaikművész. Művei révén az üvegfestészet iparművészetből újra képzőművészetté vált a századforduló környékén. 1898-ban elsőként neki ítélték az Iparművészeti Állami Aranyérmet, majd több világkiállításon díjazták műveit, először 1900-ban. Hol volt ebben az évben a világkiállítás?', 2, ['Torinó', 'Berlin', 'Párizs', 'St. Louis'], 'Helyes válasz: Párizs'),
    _q('1828. december 29-én született Szendrey Júlia, akinek első férje Petőfi Sándor volt. Melyik állítás NEM igaz?', 3, ['második férje Horvát Árpád történész volt, akitől azután költözött el, hogy pornóújságokat talált nála', '1848. március 15-én ő varrta és tűzte Petőfi mellére a később ismertté vált kokárda első példányát', 'Hans Christian Andersen meséi először az ő fordításában jelentek meg nyomtatásban Magyarországon', 'Petőfivel egy év ismeretség után házasodott össze, kevesebb mint két évig tartott a házasságuk, gyermekük nem született'], 'Helyes válasz: Petőfivel egy év ismeretség után házasodott össze, kevesebb mint két évig tartott a házasságuk, gyermekük nem született'),
    _q('1909. december 30-án nyílt meg a Nyolcak, a legjelentősebb magyar avantgárd művészcsoport első kiállítása Új Képek címmel. A cím utalás az 1906-ban megjelent Új versek című kötetre: a festők ezzel azt sugallták, hogy ők is a korszerű párizsi szellemet jelenítik meg. Kinek a verseskötetére utaltak?', 0, ['Ady Endre', 'Juhász Gyula', 'Babits Mihály', 'Áprily Lajos'], 'Helyes válasz: Ady Endre'),
    _q('Melyik költőnk született január 1-jén?', 1, ['Csokonai Vitéz Mihály', 'Petőfi Sándor', 'Arany János', 'Babits Mihály'], 'Helyes válasz: Petőfi Sándor'),
    _q('1943. január 1-jén hunyt el az a magyar író, aki többek között P. Howard álnéven adta ki műveit. Ki ő?', 3, ['Karinthy Frigyes', 'Örkény István', 'Márai Sándor', 'Rejtő Jenő'], 'Helyes válasz: Rejtő Jenő'),
    _q('1878. január 12-én született Molnár Ferenc, akinek legismertebb műve A Pál utcai fiúk. 1939-ben, a nemzetiszocializmus elől elmenekült Magyarországról. Melyik országban élt élete végéig?', 2, ['Írország', 'Kanada', 'Egyesült Államok', 'Argentína'], 'Helyes válasz: Egyesült Államok'),
    _q('1945. január 13-án a németek felrobbantották a budapesti Horthy Miklós hidat. Melyik mai híd volt a Horthy híd?', 0, ['Petőfi híd', 'Megyeri híd', 'Lánchíd', 'Szabadság híd'], 'Helyes válasz: Petőfi híd'),
    _q('1971-ben ezen a napon volt a Macskajáték című dráma ősbemutatója Szolnokon, a Szigligeti Színházban. Ki a mű szerzője?', 0, ['Örkény István', 'Bródy Sándor', 'Karinthy Ferenc', 'Márai Sándor'], 'Helyes válasz: Örkény István'),
    _q('1946. január 15-én nyitották meg Budapesten a gyalogos forgalom számára a világháború után megépített első állandó dunai átkelőt. Kiről kapta a nevét a híd?', 3, ['Petőfi Sándor', 'Széchenyi István', 'II. Rákóczi Ferenc', 'Kossuth Lajos'], 'Helyes válasz: Kossuth Lajos'),
    _q('1622. január 15-én született Molière, francia drámaíró, színész. Milyen tulajdonságú emberről írta egyik leghíresebb művét?', 0, ['fösvény', 'hazug', 'iszákos', 'tolvaj'], 'Helyes válasz: fösvény'),
    _q('1945-ben a németek ezen a napon robbantották fel a budapesti Ferenc József hidat. Mi a híd mai neve?', 0, ['Szabadság híd', 'Erzsébet híd', 'Petőfi híd', 'Árpád híd'], 'Helyes válasz: Szabadság híd'),
    _q('1847-ben ezen a napon született Mikszáth Kálmán író, újságíró, országgyűlési képviselő. Melyik NEM az ő műve?', 1, ['A jó palócok', 'Rokonok', 'Két választás Magyarországon', 'A Noszty fiú esete Tóth Marival'], 'Helyes válasz: Rokonok'),
    _q('1882. január 18-án született Alan Alexander Milne, a Micimackó és a Micimackó kuckója szerzője. Kinek a műfordításában ismerjük ezeket a műveket?', 2, ['Kosztolányi Dezső', 'Örkény István', 'Karinthy Frigyes', 'Móricz Zsigmond'], 'Helyes válasz: Karinthy Frigyes'),
    _q('1823. január 23-án született Madách Imre, akinek legismertebb műve Az ember tragédiája. Mikor volt betiltva ez a mű?', 2, ['1867–72 között, a kiegyezés után', '1920–26 között, a trinanoni békeszerződés aláírását követően', '1947–55 között, az épülő kommunizmus idején', '1956–62 között, az 56-os forradalom következményeként'], 'Helyes válasz: 1947–55 között, az épülő kommunizmus idején'),
    _q('1950-ben ezen a napon hunyt el George Orwell, az 1984 és az Állatfarm írója. Milyen műfajba sorolható az 1984?', 0, ['disztópia', 'emlékirat', 'sci-fi', 'dráma'], 'Helyes válasz: disztópia'),
    _q('Január 22-e a magyar kultúra napja, mert ezen a napon született meg egy igen jelentős magyar irodalmi mű. Melyik?', 1, ['Madách Imre: Az ember tragédiája', 'Kölcsey Ferenc: Himnusz', 'Vörösmarty Mihály: Szózat', 'Katona József: Bánk bán'], 'Helyes válasz: Kölcsey Ferenc: Himnusz'),
    _q('1945. január 23-án indult útnak az aranyvonat, amely a Magyar Nemzeti Bank arany- és devizakészletét és más értékeket szállított nyugat felé az előretörő szovjet hadsereg elől. Mikor kapta vissza Magyarország az aranykészletét?', 0, ['1946-ban', '1956-ban', '1972-ben', '1989-ben'], 'Helyes válasz: 1946-ban'),
    _q('1965-ben ezen a napon hunyt el Winston Churchill. Melyik állítás NEM igaz vele kapcsolatban?', 0, ['soha nem fogyasztott alkoholt', 'kétszer volt az Egyesült Királyság miniszterelnöke, néhány év kihagyással', 'termékeny festő volt, több mint 750 képet alkotott', 'irodalmi Nobel-díjat kapott'], 'Helyes válasz: soha nem fogyasztott alkoholt'),
    _q('1919. január 27-én hunyt el Ady Endre. Mi volt az oka a halálának?', 0, ['spanyolnátha', 'vérmérgezés', 'baleset', 'öngyilkosság'], 'Helyes válasz: spanyolnátha'),
    _q('1805. január 28-án hunyt el Csokonai Vitéz Mihály, a magyar felvilágosodáskori irodalom egyik legjelentősebb költője. Mi volt múzsájának, nagy szerelmének neve?', 1, ['Berta', 'Lilla', 'Léda', 'Anna'], 'Helyes válasz: Lilla'),
    _q('1837. január 29-én hunyt el Alekszandr Szergejevics Puskin orosz költő, író, drámaíró. Melyik állítás NEM igaz vele kapcsolatban?', 1, ['21 éves korában a cár száműzte lázító hangú költeményei miatt', 'soha nem házasodott meg', 'afrikai vér is csörgedezett ereiben', 'párbaj következtében hunyt el'], 'Helyes válasz: soha nem házasodott meg'),
    _q('1556. január 16-án ért véget Tinódi Lantos Sebestyén élete. Melyik állítás NEM igaz vele kapcsolatban?', 3, ['30 éves kora előtt megsebesült, további hadi szolgálatra nem volt alkalmas', 'Énekeihez dallamokat is szerzett lantkísérettel, és amikor tehette, elő is adta őket', 'Eger diadalmas megvédése után rögtön a várba ment, hogy megismerje a harc részleteit', 'Híre eljutott Ferdinánd király udvarába is aki 1553. augusztus 23-án börtönbe záratta, itt is halt meg 1555-ben'], 'Helyes válasz: Híre eljutott Ferdinánd király udvarába is aki 1553. augusztus 23-án börtönbe záratta, itt is halt meg 1555-ben'),
    _q('2012. február 4-én hunyt el Csurka István kétszeres József Attila-díjas magyar író, dramaturg, politikus. Mi volt a neve az általa alapított pártnak, amelynek haláláig elnöke volt?', 1, ['Három a Magyar Igazság', 'Magyar Igazság és Élet Pártja', 'Harmadik Út', 'Magyar Demokrata Fórum'], 'Helyes válasz: Magyar Igazság és Élet Pártja'),
    _q('1828. február 8-án született Jules Verne francia író, akinek segítségével megszületett a tudományos-fantasztikus (sci-fi) irodalom. Több műve is kapcsolódik Magyarországhoz. Az alábbiak közül melyik?', 3, ['Kétévi vakáció', 'Utazás a Föld középpontja felé', 'Sztrogof Mihály', 'Mathias Sandorf (Sándor Mátyás)'], 'Helyes válasz: Mathias Sandorf (Sándor Mátyás)'),
    _q('1881. február 9-én hunyt el Fjodor Mihajlovics Dosztojevszkij orosz író, az orosz irodalom és az egész világirodalom mindmáig legnevesebb képviselőinek egyike, a 19. századi orosz irodalom felemelkedésének kulcsfigurája. Melyik NEM az ő műve?', 2, ['Bűn és bűnhődés', 'A félkegyelmű', 'Háború és béke', 'A Karamazov testvérek'], 'Helyes válasz: Háború és béke'),
    _q('1942. február 11-én adták át az első aranylemezt, mégpedig Glenn Millernek, a Chattanooga Choo Choo című dalért. Hány eladott példányért járt aranylemez abban az időben?', 3, ['100.000', '300.000', '500.000', '1.000.000'], 'Helyes válasz: 1.000.000'),
    _q('1945. február 16-án hunyt el Ditrói Mór magyar színigazgató, rendező, az Országos Színészegyesület örökös díszelnöke. Melyik budapesti színháznak volt alapító igazgatója?', 0, ['Vígszínház', 'Erkel Színház', 'Nemzeti Színház', 'Madách Színház'], 'Helyes válasz: Vígszínház'),
    _q('Február 18-a a Magyar Széppróza Napja – 2018 óta egy meghatározó jelentőségű magyar író születésnapján ünnepeljük. Ki az író?', 1, ['Gárdonyi Géza', 'Jókai Mór', 'Móricz Zsigmond', 'Mikszáth Kálmán'], 'Helyes válasz: Jókai Mór'),
]