# Magyar királyok kérdések a quiz alkalmazáshoz
# Magyar történelmi királyok – informatív, magyaros kérdések

_TOPIC = 'magyar_királyok'


def _q(question, correct, options, explanation, topic=_TOPIC):
    """Segédfüggvény: kompakt kérdés létrehozása."""
    return {"question": question, "options": options, "correct": correct, "explanation": explanation, "topic": topic}


KIRALYOK_QUESTIONS = [
    _q('Melyik király alapította meg a keresztény magyar államot, amikor III. Silvester pápától koronát kapott 1000-ben?', 0, ['Szent István', 'Szent László', 'Kálmán', 'II. András'], 'Szent István (1000–1038) volt Magyarország első királya. Törvénykezéssel, egyházszervezéssel és a keresztény hitre térítéssel alapozta meg az európai szintű magyar államot.'),
    _q('Melyik királyt űzték el kétszer a trónról, mert a német császár katonai támogatásával került hatalomra, idegennek tartották?', 0, ['I. Péter', 'Sámuel Aba', 'Szent László', 'Kálmán'], 'I. Péter (1038–1041, majd 1044–1046) Orseolo Péter volt, István sógora. A magyar nemesség nem fogadta el, mert túl szoros kapcsolatot tartott a német udvarral.'),
    _q('Melyik király volt a Vata-féle pogány lázadás egyik vezetője, aki a német uralom ellen lépett fel, de Ménfőnél vereséget szenvedett?', 0, ['Sámuel Aba', 'I. Péter', 'Szent László', 'Kálmán'], 'Sámuel Aba (1041–1044) a magyar nemesség támogatásával került trónra. A Ménfői csatában III. Henrik német császár legyőzte, és I. Péter visszakerült a trónra.'),
    _q('Melyik király került trónra a Vata-féle pogány lázadás leverése után, és bizánci segítséggel próbálta megerősíteni hatalmát?', 0, ['I. András', 'I. Péter', 'Szent László', 'Kálmán'], 'I. András (1046–1060) a lázadás után került trónra. A bizánci császárral kötött szövetséget, és fiát, Salamont jelölte örökösnek.'),
    _q('Melyik király uralkodott mindössze három évig, és a bizánci udvarban nevelkedett, mielőtt trónra lépett?', 0, ['I. Béla', 'I. András', 'Szent László', 'Kálmán'], 'I. Béla (1060–1063) András testvére volt, aki Konstantinápolyban nevelkedett. Rövid uralkodása alatt megpróbálta megerősíteni a királyi hatalmat.'),
    _q('Melyik király vívta a Mogyoródi csatát nagybátyjával, I. Gézával, és a német császár segítségével került trónra?', 0, ['I. Salamon', 'I. Béla', 'Szent László', 'Kálmán'], 'I. Salamon (1063–1074) András fia volt. A Mogyoródi csatában legyőzte Géza és László seregeit, de később a nemesség elűzte.'),
    _q('Melyik király uralkodott mindössze három évig a Mogyoródi csata után, és testvére, László követte a trónon?', 0, ['I. Géza', 'I. Salamon', 'Szent László', 'Kálmán'], 'I. Géza (1074–1077) Béla fia volt. A Mogyoródi győzelem után lett király, de rövid uralkodás után meghalt, és Szent László követte.'),
    _q('Melyik királyt avatták szentté, aki törvényei alapján a boszorkányságot halálbüntetéssel sújtotta, és a kunok ellen vívott hadjáratokat?', 1, ['Szent István', 'Szent László', 'Kálmán', 'II. Béla'], 'Szent László (1077–1095) törvénykezéséről és hadvezéri képességeiről híres. A kunok elleni győzelmei védték meg a Kárpát-medencét. 1192-ben avatták szentté.'),
    _q('Melyik királyt nevezték „Könyves”-nek, aki meghódította Horvátországot és Dalmáciát, és törvényeiben tiltotta a boszorkánypereket?', 1, ['Szent László', 'Kálmán', 'II. István', 'II. Géza'], 'Kálmán Könyves (1095–1116) tanult, művelt király volt. „A boszorkányok nem léteznek” – írta törvényeiben. Horvátországot diplomáciai úton szerezte meg.'),
    _q('Melyik király uralkodott 1116-tól 1131-ig, és Kálmán fia volt, aki békés időszakot biztosított az országnak?', 0, ['II. István', 'Kálmán', 'II. Géza', 'II. Béla'], 'II. István (1116–1131) Kálmán fia volt. Uralkodása alatt megerősödött a királyi hatalom, és békés kapcsolatot tartottak a szomszédos országokkal.'),
    _q('Melyik királyt nevezték „Vak” Bélának, mert a bizánci fogságban kivakították, de később mégis trónra került?', 2, ['II. István', 'II. Géza', 'II. Béla', 'III. István'], 'II. Béla Vak (1131–1141) a bizánci császár fogságában veszítette el a látását. Ennek ellenére uralkodni tudott, és békés politikát folytatott.'),
    _q('Melyik király uralkodott 21 évig a 12. század közepén, és Kálmán unokája volt, aki békés kapcsolatot tartott Bizánccal?', 0, ['II. Géza', 'III. István', 'II. László', 'III. Béla'], 'II. Géza (1141–1162) II. István fia volt. Hosszú, viszonylag békés uralkodása alatt megerősödött a királyság.'),
    _q('Melyik király uralkodott mindössze hat hónapig 1162-ben, és a bizánci császár nyomására került trónra?', 0, ['II. László', 'II. Géza', 'III. István', 'III. Béla'], 'II. László (1162–1163) II. Géza testvére volt. A bizánci császár támogatásával lett király, de mindössze fél évig uralkodott.'),
    _q('Melyik király uralkodott 1162-től 1172-ig, és II. Géza fia volt, aki hosszú trónviszályok közepette uralkodott?', 0, ['III. István', 'II. László', 'III. Béla', 'II. Imre'], 'III. István (1162–1172) II. Géza fia volt. Uralkodása alatt folytatódtak a trónviszályok a bizánci befolyás miatt.'),
    _q('Melyik királyt avatták szentté a 13. században, aki a bizánci császár lányát vette feleségül, és építkezéseiről ismert?', 1, ['II. László', 'III. Béla', 'II. Imre', 'III. László'], 'III. Béla (1172–1196) uralkodása alatt virágzott a magyar kultúra. A bizánci Anna Komnénét vette feleségül. 1213-ban avatták szentté.'),
    _q('Melyik király vezetett keresztes hadjáratot, és „Jeruzsálemi” melléknevet kapott, bár nem érte el a Szent Várost?', 0, ['II. Imre', 'III. László', 'II. András', 'IV. Béla'], 'II. Imre (1196–1204) keresztes hadjáratot vezetett a Szentföldre. Jeruzsálemi királyként koronázták, de hamarosan hazatért.'),
    _q('Melyik király uralkodott mindössze négy hónapig 1204–1205-ben, és II. Imre kiskorú fia volt?', 0, ['III. László', 'II. András', 'IV. Béla', 'III. István'], 'III. László (1204–1205) II. Imre fia volt. Gyermekként került trónra, és négy hónap után meghalt.'),
    _q('Melyik király adta ki 1222-ben az Aranybullát, amely korlátozta a királyi hatalmat és a nemesség jogait védte?', 0, ['II. András', 'IV. Béla', 'III. István', 'V. István'], 'II. András (1205–1235) 1222-ben kiadta az Aranybullát – ez volt az első európai alkotmányszerű okirat, amely a nemesség jogait védte a király önkénye ellen.'),
    _q('Melyik király uralkodott a tatárjárás (1241–1242) után, és kővárak építésével, kun szövetséggel védte meg az országot?', 0, ['IV. Béla', 'III. István', 'V. István', 'IV. László'], 'IV. Béla (1235–1270) a tatárjárás pusztítása után építette újjá az országot. Kővárakat építtetett, kun segédcsapatokat telepített, hogy védje a határokat.'),
    _q('Melyik királyt nevezték Kun Lászlónak, aki IV. Béla fia volt, és a kunokkal szövetségben harcolt a csehekkel?', 1, ['III. István', 'V. István', 'IV. László', 'III. András'], 'V. István (1270–1272) IV. Béla fia volt. Kun László néven ismert, mert anyja kun hercegnő volt. Cseh Ottokár ellen harcolt.'),
    _q('Melyik királyt gyilkolták meg 1290-ben, aki szintén kun származású volt, és a Kőszegi család ellen indított hadjáratban vesztette életét?', 0, ['IV. László', 'III. András', 'V. László', 'I. Károly'], 'IV. László (1272–1290) Kun László néven ismert. A Kőszegiek elleni hadjárat során saját kun katonái gyilkolták meg a táborában.'),
    _q('Melyik király volt az Árpád-ház utolsó tagja, aki Velenceből származott, és 1301-ben fiúörökös nélkül halt meg?', 0, ['III. András', 'V. László', 'I. Károly', 'I. Lajos'], 'III. András (1290–1301) az Árpád-ház utolsó férfi tagja volt. Velencei származású anyja miatt „Veneciai”-nek nevezték. Halálával kihalt az Árpád-ház.'),
    _q('Melyik király volt az első Anjou-házi magyar király, aki Róbert Károly néven 41 évig uralkodott, és megtörte a oligarchák hatalmát?', 0, ['I. Károly', 'I. Lajos', 'Mária', 'II. Károly'], 'I. Károly Róbert (1301–1342) az Anjou-házból került a magyar trónra. Hosszú harcok után megerősítette a királyi hatalmat a hatalmasurak ellen.'),
    _q('Melyik királyt nevezték Nagy Lajosnak, aki Nápolyt és Dalmáciát is meghódította, és a lengyel trónra is igényt tartott?', 0, ['I. Lajos', 'Mária', 'II. Károly', 'Zsigmond'], 'I. Lajos Nagy (1342–1382) uralma alatt ért el Magyarország a legnagyobb területi kiterjedésére. Nápolyi és dalmát hadjáratai híresek.'),
    _q('Melyik magyar királynő volt Nagy Lajos lánya, aki Luxemburgi Zsigmonddal kötött házasságot, és a női örökösödés képviselője?', 0, ['Mária', 'II. Károly', 'Zsigmond', 'I. Albert'], 'Mária (1382–1395) Nagy Lajos lánya volt. Apja halála után trónra lépett, és Zsigmondot vette férjül – ez alapozta meg a Luxemburgi uralmat Magyarországon.'),
    _q('Melyik királyt nevezték Kis Károlynak, aki Nápolyból jött, rövid ideig uralkodott, majd Visegrádon meggyilkolták?', 0, ['II. Károly', 'Zsigmond', 'I. Albert', 'I. Ulászló'], 'II. Károly (1385–1386) a nápolyi Anjou-házból származott. „Kis” Károly néven ismert, mert alacsony termetű volt. Mária királynő ellenfelei gyilkolták meg.'),
    _q('Melyik király volt egyszerre magyar király, német-római császár és cseh király, aki 50 évig uralkodott, és Budát tette fővárossá?', 0, ['Zsigmond', 'I. Albert', 'I. Ulászló', 'II. Ulászló'], 'Zsigmond (1387–1437) a Luxemburgi-házból származott. Magyar királyként, német-római császáraként és cseh királyként is uralkodott. Buda az ő idejében lett a főváros.'),
    _q('Melyik király uralkodott mindössze két évig, aki Habsburg Albert néven Ausztriából került a magyar trónra Zsigmond halála után?', 0, ['I. Albert', 'I. Ulászló', 'II. Ulászló', 'I. Mátyás'], 'I. Albert (1437–1439) Zsigmond veje volt. Habsburg hercegként került a magyar trónra, de rövid uralkodása alatt a török elleni háborúban halt meg.'),
    _q('Melyik lengyel királyt választották magyar királyként is, aki 1444-ben a várnai csatában esett el a törökök ellen?', 0, ['I. Ulászló', 'II. Ulászló', 'I. Mátyás', 'II. Lajos'], 'I. Ulászló (1440–1444) lengyel királyként III. Ulászló néven uralkodott. A várnai csatában (1444) a törökök elleni keresztes hadjárat során esett el – „nem futunk tovább!”.'),
    _q('Melyik királyt nevezték Corvin Mátyásnak, aki reneszánsz udvart tartott, és a Corvina könyvtár alapítója volt?', 0, ['I. Mátyás', 'II. Lajos', 'II. Ulászló', 'I. Ferdinánd'], 'I. Mátyás (1458–1490) Hunyadi János fia volt. A reneszánsz magyar királya, a Corvina könyvtár és a Budai vár újjáépítése az ő nevéhez fűződik.'),
    _q('Melyik királyt nevezték „Dobzse” Ulászlónak, mert állítólag minden döntésnél „dobsem” (tehát) szót használta?', 0, ['II. Ulászló', 'II. Lajos', 'I. Ferdinánd', 'I. János'], 'II. Ulászló (1490–1516) Jagelló-házi lengyel király volt. „Dobzse” melléknevét a gyakori „dobsem” (tehát) szóhasználata miatt kapta – gyenge uralkodónak tartották.'),
    _q('Melyik király esett el 1526-ban a mohácsi csatában, amely a magyar történelem egyik legnagyobb katasztrófája volt?', 0, ['II. Lajos', 'I. Ferdinánd', 'I. János', 'I. Miksa'], 'II. Lajos (1516–1526) a mohácsi csatában (1526. augusztus 29.) veszítette életét. A vereség után Magyarország három részre szakadt: királyi Magyarország, török és Erdély.'),
    _q('Melyik Habsburg király lett magyar király a mohácsi csata után, és 38 évig uralkodott, megosztva a hatalmat I. János Szapolyai erdélyi királlyal?', 0, ['I. Ferdinánd', 'I. János', 'I. Miksa', 'II. Rudolf'], 'I. Ferdinánd (1526–1564) a mohácsi csata után lett magyar király. A Habsburg uralom Magyarországon az ő nevéhez fűződik. Duális királyság alakult ki I. Jánossal.'),
    _q('Melyik király volt egyszerre magyar király és erdélyi fejedelem, aki a török szultán vazallusaként uralkodott a Habsburgokkal szemben?', 0, ['I. János', 'I. Miksa', 'II. Rudolf', 'I. Mátyás'], 'I. János (1526–1540, majd 1540–1570 erdélyi fejedelemként) Szapolyai János volt. A török szultán támogatásával uralkodott a keleti országrészen.'),
    _q('Melyik király költözött Prágába, ahol a reneszánsz udvarában csillagászok és alkimisták dolgoztak?', 0, ['II. Rudolf', 'I. Mátyás', 'II. Ferdinánd', 'III. Ferdinánd'], 'II. Rudolf (1576–1612) Prágában élt, ahol a „csodálatos” udvart tartott. Tycho Brahe és Kepler csillagászok dolgoztak nála. Keveset foglalkozott magyar ügyekkel.'),
    _q('Melyik király uralkodott a harmincéves háború (1618–1648) nagy részében, és keményen fellépett a protestánsok ellen?', 0, ['II. Ferdinánd', 'III. Ferdinánd', 'I. Lipót', 'I. József'], 'II. Ferdinánd (1619–1637) a harmincéves háború egyik fő szereplője volt. Katolikus restaurációt hajtott végre, és a protestáns felkelőkkel szemben keményen fellépett.'),
    _q('Melyik király uralkodott a Bécs 1683-as török ostroma és felszabadítása idején, amikor Sobieski lengyel király megmentette a várost?', 0, ['I. Lipót', 'I. József', 'I. Károly', 'Mária Terézia'], 'I. Lipót (1657–1705) uralkodása alatt zajlott a török háborúk felszámolása. 1683-ban a törökök ostromolták Bécset, amit Sobieski János lengyel király mentett meg.'),
    _q('Melyik király hirdette ki 1713-ban a Pragmatikus szankciót, amely lehetővé tette, hogy lánya, Mária Terézia örökölje a trónt?', 0, ['I. Károly', 'Mária Terézia', 'II. József', 'I. Ferenc'], 'I. Károly (1711–1740) a Pragmatikus szankcióval biztosította, hogy lányai is örökölhessék a Habsburg birodalmat. Ez alapozta meg Mária Terézia uralmát.'),
    _q('Melyik királynő uralkodott 40 évig, aki Pozsonyban koronázták meg, és a magyar rendek hűségét megnyerte a háborúk idején?', 0, ['Mária Terézia', 'II. József', 'I. Ferenc', 'II. Lipót'], 'Mária Terézia (1740–1780) a magyar rendek segítségével védte meg trónját. „Vitam et sanguinem” – életet és vért ígért a magyar nemeseknek. Reformjai modernizálták az országot.'),
    _q('Melyik királyt nevezték „kalapos” királynak, aki felvilágosult abszolutizmust vezetett be, és a németet tette hivatalos nyelvvé?', 0, ['II. József', 'I. Ferenc', 'II. Lipót', 'I. Ferenc József'], 'II. József (1780–1790) radikális reformokat vezetett be. A jobbágyfelszabadítás, a német nyelv kényszerítése és a kalapviselés előírása az ő nevéhez fűződik.'),
    _q('Melyik király uralkodott a napóleoni háborúk alatt, amikor Napóleon többször legyőzte a Habsburg seregeket?', 0, ['I. Ferenc', 'I. Ferenc József', 'II. Lipót', 'I. Károly'], 'I. Ferenc (1792–1835) uralkodása alatt zajlottak a napóleoni háborúk. Lánya, Mária Luiza feleségül ment Napóleonhoz. Német-római császárként II. Ferenc, osztrák császárként I. Ferenc néven uralkodott.'),
    _q('Melyik király uralkodott a reformkorban (1835–1848), aki „jólelkű” Ferdinánd néven ismert, és 1848-ban lemondott a forradalom miatt?', 0, ['I. Ferdinánd', 'I. Ferenc József', 'II. Lipót', 'I. Károly'], 'I. Ferdinánd (1835–1848) a reformkor uralkodója volt. „Jólelkű” Ferdinánd néven ismerték, mert gyenge akaratú volt. 1848-ban a forradalom nyomására lemondott unokaöccse, Ferenc József javára.'),
    _q('Melyik király uralkodott 68 évig, aki 1848-ban lépett trónra, majd a kiegyezés (1867) után magyar királlyá koronázták Pozsonyban?', 0, ['I. Ferenc József', 'II. Ferenc József', 'I. Károly', 'IV. Károly'], 'I. Ferenc József (1848–1916) a leghosszabb uralkodó magyar király. 1867-ben a kiegyezés után koronázták meg magyar királlyá. Az Osztrák–Magyar Monarchia szimbóluma.'),
    _q('Ki volt az utolsó magyar király, aki 1916-ban lépett trónra, és 1918-ban kényszerült lemondani, majd kétszer próbálta visszaszerezni a magyar trónt?', 0, ['IV. Károly', 'II. Ferenc József', 'I. Károly', 'II. Károly'], 'IV. Károly (1916–1918) volt az utolsó magyar király. 1918 novemberében kényszerült lemondani. 1921-ben kétszer próbált visszatérni („királypuccs”), de sikertelenül.'),
]