# Auto-generated questions file
# Generated on: 2026-02-01 21:53:26

_DEFAULT_QUESTION = "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:"
_TOPIC = "komolyzene"


def _q(audio_file, correct, options, explanation, question=_DEFAULT_QUESTION, **extra):
    """Segédfüggvény: kompakt kérdés létrehozása."""
    return {
        "question": question,
        "options": options,
        "correct": correct,
        "explanation": explanation,
        "audio_file": audio_file,
        "topic": _TOPIC,
        **extra,
    }


QUESTIONS = [
    _q("1. Dvorak - New World Symphony.mp3", 0, ["Dvorak", "Beethoven", "Mozart", "Bach"], "Dvorak: IX. Új világ szimfónia"),
    _q("2. Dvorak - Humoresque.mp3", 0, ["Dvorak", "Beethoven", "Mozart", "Bach"], "Dvorak: Humoresque"),
    _q("3. Dvorak - Symphony 8.mp3", 0, ["Dvorak", "Beethoven", "Mozart", "Bach"], "Dvorak: 8. G-dúr szimfónia"),
    _q("4. Beethoven - Symphony 5.mp3", 0, ["Beethoven", "Mozart", "Csajkovszkij", "Bach"], "Beethoven: V. Szimfónia - A sors szimfónia"),
    _q("5. Beethoven - Moonlight Sonata.mp3", 0, ["Beethoven", "Mozart", "Csajkovszkij", "Bach"], "Beethoven: Holdvilág szonáta - Mondscheinsonate"),
    _q("6. Beethoven - Ode to Joy.mp3", 0, ["Beethoven", "Mozart", "Csajkovszkij", "Bach"], "Beethoven: Ode to Joy - 9. szimfónia"),
    _q("7. Tchaikovsky - Nutcracker.mp3", 2, ["Beethoven", "Mozart", "Csajkovszkij", "Bach"], "Csajkovszkij: Diótörő - Tánc a cukorkák hercegnőjéről"),
    _q("8. Tchaikovsky - Swan Lake.mp3", 2, ["Beethoven", "Mozart", "Csajkovszkij", "Bach"], "Csajkovszkij: Hattyúk tava - Swan Lake"),
    _q("9. Tchaikovsky - Piano Concerto 1.mp3", 2, ["Beethoven", "Mozart", "Csajkovszkij", "Bach"], "Csajkovszkij: 1. Zongoraverseny"),
    _q("10. Handel - Rinaldo.mp3", 0, ["Handel", "Bach", "Mozart", "Beethoven"], "Handel: Rinaldo"),
    _q("11. Handel - Minuet B flat.mp3", 0, ["Handel", "Bach", "Mozart", "Beethoven"], "Handel: IV. B-dúr menüett"),
    _q("12. Handel - Keyboard Suite D minor.mp3", 0, ["Handel", "Bach", "Mozart", "Beethoven"], "Handel: Keyboard Suite in D minor"),
    _q("13. Wagner - Ride of Valkyries.mp3", 0, ["Wagner", "Beethoven", "Mozart", "Bach"], "Wagner: A Valkűrök bevonulása"),
    _q("14. Wagner - Lohengrin Wedding March.mp3", 0, ["Wagner", "Beethoven", "Mozart", "Bach"], "Wagner: Lohengrin - Here comes the Bride"),
    _q("15. Schubert - Ave Maria.mp3", 0, ["Schubert", "Wagner", "Mozart", "Bach"], "Schubert: Ave Maria"),
    _q("16. Beethoven - Ode to Joy 2.mp3", 0, ["Beethoven", "Wagner", "Mozart", "Bach"], "Beethoven: Ode to Joy - 9. szimfónia"),
    _q("17. Kodaly - Hary Janos.mp3", 0, ["Kodály", "Bartók", "Liszt", "Dvorak"], "Kodály Zoltán: Háry János"),
    _q("18. Kodaly - Kallai Kettos.mp3", 0, ["Kodály", "Bartók", "Liszt", "Dvorak"], "Kodály Zoltán: Kállai kettős"),
    _q("19. Kodaly - Adagio.mp3", 0, ["Kodály", "Bartók", "Liszt", "Dvorak"], "Kodály Zoltán: Adagio"),
    _q("20. Bartok - Bluebeard Castle.mp3", 0, ["Bartók", "Kodály", "Liszt", "Dvorak"], "Bartók: Kékszakállú herceg vára"),
    _q("21. Bartok - Miraculous Mandarin.mp3", 0, ["Bartók", "Kodály", "Liszt", "Dvorak"], "Bartók: Csodálatos mandarin"),
    _q("22. Khachaturian - Sabre Dance.mp3", 0, ["Hacsaturján", "Bartók", "Csajkovszkij", "Bach"], "Hacsaturján: Kartánc"),
    _q("23. Khachaturian - Spartacus.mp3", 0, ["Hacsaturján", "Bartók", "Csajkovszkij", "Bach"], "Hacsaturján: Spartacus / Onedin"),
    _q("24. Weiner - Fox Dance.mp3", 0, ["Weiner Leó", "Kodály", "Bartók", "Liszt"], "Weiner Leó: Rókatánc"),
    _q("25. Rimsky Korsakov - Flight of Bumblebee.mp3", 0, ["Rimsky-Korsakov", "Csajkovszkij", "Mussorgsky", "Bach"], "Rimsky-Korsakov: Bumblebee"),
    _q("26. Mussorgsky - Night on Bald Mountain.mp3", 0, ["Mussorgsky", "Rimsky-Korsakov", "Csajkovszkij", "Bach"], "Mussorgsky: Éjszaka a hegyen"),
    _q("27. Schubert - Trout Quintet.mp3", 0, ["Schubert", "Mozart", "Beethoven", "Bach"], "Schubert: Pisztráng ötös"),
    _q("28. Prokofiev - Peter and Wolf.mp3", 0, ["Prokofjev", "Shostakovich", "Csajkovszkij", "Bach"], "Prokofjev: Péter és a farkas"),
    _q("29. Carl Orff - Carmina Burana.mp3", 0, ["Carl Orff", "Bach", "Beethoven", "Mozart"], "Carl Orff: Carmina Burana"),
    _q("30. Ravel - Bolero.mp3", 0, ["Ravel", "Debussy", "Beethoven", "Mozart"], "Ravel: Bolero"),
    _q("31. Bach - Brandenburg Concerto 3.mp3", 3, ["Beethoven", "Mozart", "Csajkovszkij", "Bach"], "Bach: Brandenburgi versenyek - 3. verseny"),
    _q("32. Bach - Toccata Fugue D minor.mp3", 3, ["Beethoven", "Mozart", "Csajkovszkij", "Bach"], "Bach: Toccata és fúga d-moll"),
    _q("33. Bach - Air on G String.mp3", 3, ["Beethoven", "Mozart", "Csajkovszkij", "Bach"], "Bach: Air on G-string"),
    _q("34. Bach - Italian Concerto.mp3", 3, ["Beethoven", "Mozart", "Csajkovszkij", "Bach"], "Bach: Italian Concerto"),
    _q("35. Bach - Jesu Joy.mp3", 3, ["Beethoven", "Mozart", "Csajkovszkij", "Bach"], "Bach: Jesu, Joy of Man"),
    _q("36. Bach - Brandenburg Concerto 5.mp3", 3, ["Beethoven", "Mozart", "Csajkovszkij", "Bach"], "Bach: Brandenburg Concerto No. 5"),
    _q("37. Bach - Concerto Two Violins.mp3", 3, ["Beethoven", "Mozart", "Csajkovszkij", "Bach"], "Bach: Vivace"),
    _q("38. Bach - Minuet G major.mp3", 3, ["Beethoven", "Mozart", "Csajkovszkij", "Bach"], "Bach: G-dúr menüett"),
    _q("39. Charpentier - Te Deum Prelude.mp3", 0, ["Charpentier", "Handel", "Bach", "Vivaldi"], "Charpentier: Te Deum Prelude"),
    _q("40. Delibes - Lakme Flower Duet.mp3", 0, ["Delibes", "Bizet", "Gounod", "Offenbach"], "Delibes: Lakmé - Flower Duet"),
    _q("41. Offenbach - Offenbach.mp3", 0, ["Offenbach", "Bizet", "Gounod", "Delibes"], "Offenbach: YouTube klasszikus"),
    _q("42. Vivaldi - Four Seasons.mp3", 0, ["Vivaldi", "Bach", "Handel", "Corelli"], "Vivaldi: Négy évszak (YouTube)"),
    _q("43. Mozart - Mozart.mp3", 0, ["Mozart", "Haydn", "Beethoven", "Schubert"], "Mozart: YouTube klasszikus"),
    _q("44. Rossini - Rossini.mp3", 0, ["Rossini", "Verdi", "Donizetti", "Bellini"], "Rossini: YouTube klasszikus"),
    _q("45. Delibes - Sylvia - Pizzicato.mp3", 0, ["Delibes", "Bizet", "Gounod", "Offenbach"], "Delibes: YouTube klasszikus"),
    _q("46. Mozart - Rondo Turca.mp3", 0, ["Mozart", "Beethoven", "Bach", "Chopin"], "Mozart: Rondo Alla Turca"),
    _q("47. Erkel Ferenc - Hunyadi Laszlo Palotas.mp3", 0, ["Erkel Ferenc", "Bartók Béla", "Mozart", "Johann Strauss"], "Erkel Ferenc: Hunyadi László - Palotás"),
    _q("48. Edvard Grieg - Mountain King.mp3", 0, ["Edvard Grieg", "Jean Sibelius", "Carl Nielsen", "Dmitri Shostakovich"], "Edvard Grieg: In the Hall of the Mountain King"),
    _q("49. Brahms - Hungarian Dances No 5.mp3", 0, ["Johannes Brahms", "Franz Schubert", "Robert Schumann", "Felix Mendelssohn"], "Johannes Brahms: Hungarian Dances No. 5"),
    _q("50. Gershwin - Rhapsody in Blue.mp3", 0, ["George Gershwin", "Aaron Copland", "Leonard Bernstein", "Igor Stravinsky"], "George Gershwin: Rhapsody in Blue"),
    _q("51. Csardas - Kennedy Orchestra.mp3", 0, ["Johann Strauss II", "Franz Liszt", "Béla Bartók", "Zoltán Kodály"], "Csárdás - Kennedy Orchestra"),
    _q("52. Debussy - Clair de lune.mp3", 0, ["Claude Debussy", "Maurice Ravel", "Gabriel Fauré", "Erik Satie"], "Claude Debussy: Clair de lune"),
    _q("53. Lola Astanova - Fantaisie Impromptu.mp3", 0, ["Frédéric Chopin", "Franz Liszt", "Robert Schumann", "Johannes Brahms"], "Lola Astanova: Fantaisie Impromptu (Chopin)"),
    _q("54. Claude Debussy - Clair de lune.mp3", 0, ["Claude Debussy", "Maurice Ravel", "Gabriel Fauré", "Erik Satie"], "Claude Debussy: Clair de lune (Menahem Pressler előadás)"),
    _q("55. Zoltán Kodály - Háry János - Toborzó.mp3", 0, ["Zoltán Kodály", "Béla Bartók", "Weiner Leó", "Dohnány Ernő"], "Kodály Zoltán: Háry János – Toborzó"),
    _q("56. Johann Strauss II - Die Fleder.mp3", 0, ["Johann Strauss II", "Johann Strauss I", "Franz Lehár", "Haydn"], "Johann Strauss II: Die Fledermaus (részlet)"),
    _q("57. Mozart - Requiem Lacrimosa SO.mp3", 0, ["Mozart", "Beethoven", "Bach", "Haydn"], "Ismeretlen: Unknown Artist Mozart Requiem Lacrimosa SO "),
    _q("58. Mozart - The Magic Flute.mp3", 0, ["Mozart", "Beethoven", "Bach", "Haydn"], "Ismeretlen: Unknown Artist The Magic Flute Queen of the ", question="Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét!"),
    _q("59. Mozart -  Mozart Sonata in C major.mp3", 0, ["Mozart", "Beethoven", "Bach", "Haydn"], "Ismeretlen: Unknown Artist Lang Lang Mozart Sonata in C ", question="Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét!"),
    _q("60. Mozart - Canzonetta sullaria.mp3", 0, ["Mozart", "Beethoven", "Bach", "Haydn"], "Ismeretlen: Unknown Artist The Shawshank redemption Canzo", question="Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét!"),
    _q("61. Mozart - Die Meistersinger von Nürnberg.mp3", 2, ["Mozart", "Beethoven", "Wagner", "Haydn"], "Ismeretlen: 7-OndaxNqzM", question="Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét!"),
    _q("62. Mozart - Symphony 9 From The New World II.mp3", 2, ["Mozart", "Beethoven", "Dvorak", "Haydn"], "Ismeretlen: Dvorak Dvořák Symphony 9 From The New World II ", question="Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét: "),
    _q("63. Mozart - Dvorak Symphony No 9 From the New World Mvmt 4.mp3", 0, ["Dvorak", "Beethoven", "Wagner", "Mozart"], "Ismeretlen: Dvorak Symphony No 9 From the New World Mvmt 4", question="Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét: "),
    _q("64. Mozart - Requiem Dies irae.mp3", 0, ["Mozart", "Beethoven", "Verdi", "Wagner"], "Ismeretlen: Verdi Verdis Requiem Dies irae", question="Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét: "),
    _q("65. Wagner - Tristan und Isolde Prelude.mp3", 0, ["Wagner", "Dvorak", "Mozart", "Beethoven"], "Wagner: Tristan und Isolde (Prelude)"),
    _q("66. Wagner - Lohengrin Prelude.mp3", 0, ["Wagner", "Dvorak", "Mozart", "Beethoven"], "Wagner: Lohengrin (Prelude)"),
    _q("67. Vivaldi - Vivaldi Wednesday playing Winter cello scene.mp3", 0, ["Vivaldi", "Bach", "Mozart", "Handel"], "Vivaldi - Komolyzene", question="Ki a zeneszerző?"),
    _q("68. Vivaldi - Sinfonia in C Major I Allegro mo.mp3", 0, ["Vivaldi", "Handel", "Mozart", "Bach"], "Vivaldi - Komolyzene", question="Ki a zeneszerző?", song_title="Sinfonia in C Major I Allegro mo"),
    _q("Verdi_La_Traviata_Libiamo_ne_lieti_calici.mp3", 0, ["Verdi", "Donizetti", "Rossini", "Puccini"], "Verdi - Komolyzene", question="Ki a zeneszerző?", song_title='La Traviata: "Libiamo, ne\' lieti calici"'),
    _q("Verdi_Triumphal_March_from_Aida.mp3", 0, ["Verdi", "Puccini", "Donizetti", "Rossini"], "Verdi - Komolyzene", question="Ki a zeneszerző?", song_title="Triumphal March from Aida"),
    _q("69. Rossini - Cat Duet.mp3", 0, ["Rossini", "Donizetti", "Puccini", "Verdi"], "Rossini: Macskaduett (Duetto buffo di due gatti)", question="Ki a zeneszerző?", song_title="Macskaduett"),
    _q("70. Handel - Water Music.mp3", 0, ["Handel", "Bach", "Vivaldi", "Telemann"], "Handel: Vízizene (Water Music Suite)", question="Ki a zeneszerző?", song_title="Vízizene"),
    _q("71. Liszt - Hungarian Rhapsody No 2.mp3", 0, ["Liszt", "Brahms", "Chopin", "Bartók"], "Liszt: 2. Magyar Rapszódia", question="Ki a zenszerző?", song_title="Magyar Rapszódia"),
    _q("72. Schubert - Szerenád.mp3", 0, ["Schubert", "Schumann", "Brahms", "Mendelssohn"], "Schubert: Szerenád (Serenade, D. 957)", question="Ki a zenszerző?", song_title="Szerenád"),
    _q("73. Pachelbel - Canon in D.mp3", 0, ["Pachelbel", "Vivaldi", "Handel", "Telemann"], "Pachelbel: Canon in D-dúr", question="Ki a zenszerző?", song_title="Canon in D"),
    _q("74. Shostakovich - 2nd Waltz.mp3", 0, ["Sosztakovics", "Prokofjev", "Sztravinszkij", "Rahmaninov"], "Sosztakovics: 2. Keringő (Suite for Variety Orchestra)", question="Ki a zenszerző?", song_title="2nd Waltz"),
    _q("75. Elgar - Pomp and Circumstance.mp3", 0, ["Elgar", "Holst", "Vaughan Williams", "Britten"], "Elgar: Pomp and Circumstance – 1. induló (Land of Hope and Glory)", question="Ki a zenszerző?", song_title="Pomp and Circumstance"),
]

# Export alias for compatibility
KOMOLYZENE_QUESTIONS = QUESTIONS
