# Auto-generated questions file
# Generated on: 2026-01-27 13:52:28

QUESTIONS = [
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Dvorak",
            "Beethoven",
            "Mozart",
            "Bach",
        ],
        "correct": 0,
        "explanation": "Dvorak: IX. Új világ szimfónia",
        "audio_file": "1. Dvorak - New World Symphony.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Dvorak",
            "Beethoven",
            "Mozart",
            "Bach",
        ],
        "correct": 0,
        "explanation": "Dvorak: Humoresque",
        "audio_file": "2. Dvorak - Humoresque.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Dvorak",
            "Beethoven",
            "Mozart",
            "Bach",
        ],
        "correct": 0,
        "explanation": "Dvorak: 8. G-dúr szimfónia",
        "audio_file": "3. Dvorak - Symphony 8.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Beethoven",
            "Mozart",
            "Csajkovszkij",
            "Bach",
        ],
        "correct": 0,
        "explanation": "Beethoven: V. Szimfónia - A sors szimfónia",
        "audio_file": "4. Beethoven - Symphony 5.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Beethoven",
            "Mozart",
            "Csajkovszkij",
            "Bach",
        ],
        "correct": 0,
        "explanation": "Beethoven: Holdvilág szonáta - Mondscheinsonate",
        "audio_file": "5. Beethoven - Moonlight Sonata.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Beethoven",
            "Mozart",
            "Csajkovszkij",
            "Bach",
        ],
        "correct": 0,
        "explanation": "Beethoven: Ode to Joy - 9. szimfónia",
        "audio_file": "6. Beethoven - Ode to Joy.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Beethoven",
            "Mozart",
            "Csajkovszkij",
            "Bach",
        ],
        "correct": 2,
        "explanation": "Csajkovszkij: Diótörő - Tánc a cukorkák hercegnőjéről",
        "audio_file": "7. Tchaikovsky - Nutcracker.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Beethoven",
            "Mozart",
            "Csajkovszkij",
            "Bach",
        ],
        "correct": 2,
        "explanation": "Csajkovszkij: Hattyúk tava - Swan Lake",
        "audio_file": "8. Tchaikovsky - Swan Lake.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Beethoven",
            "Mozart",
            "Csajkovszkij",
            "Bach",
        ],
        "correct": 2,
        "explanation": "Csajkovszkij: 1. Zongoraverseny",
        "audio_file": "9. Tchaikovsky - Piano Concerto 1.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Handel",
            "Bach",
            "Mozart",
            "Beethoven",
        ],
        "correct": 0,
        "explanation": "Handel: Rinaldo",
        "audio_file": "10. Handel - Rinaldo.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Handel",
            "Bach",
            "Mozart",
            "Beethoven",
        ],
        "correct": 0,
        "explanation": "Handel: IV. B-dúr menüett",
        "audio_file": "11. Handel - Minuet B flat.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Handel",
            "Bach",
            "Mozart",
            "Beethoven",
        ],
        "correct": 0,
        "explanation": "Handel: Keyboard Suite in D minor",
        "audio_file": "12. Handel - Keyboard Suite D minor.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Wagner",
            "Beethoven",
            "Mozart",
            "Bach",
        ],
        "correct": 0,
        "explanation": "Wagner: A Valkűrök bevonulása",
        "audio_file": "13. Wagner - Ride of Valkyries.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Wagner",
            "Beethoven",
            "Mozart",
            "Bach",
        ],
        "correct": 0,
        "explanation": "Wagner: Lohengrin - Here comes the Bride",
        "audio_file": "14. Wagner - Lohengrin Wedding March.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Schubert",
            "Wagner",
            "Mozart",
            "Bach",
        ],
        "correct": 0,
        "explanation": "Schubert: Ave Maria",
        "audio_file": "15. Schubert - Ave Maria.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Beethoven",
            "Wagner",
            "Mozart",
            "Bach",
        ],
        "correct": 0,
        "explanation": "Beethoven: Ode to Joy - 9. szimfónia",
        "audio_file": "16. Beethoven - Ode to Joy 2.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Kodály",
            "Bartók",
            "Liszt",
            "Dvorak",
        ],
        "correct": 0,
        "explanation": "Kodály Zoltán: Háry János",
        "audio_file": "17. Kodaly - Hary Janos.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Kodály",
            "Bartók",
            "Liszt",
            "Dvorak",
        ],
        "correct": 0,
        "explanation": "Kodály Zoltán: Kállai kettős",
        "audio_file": "18. Kodaly - Kallai Kettos.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Kodály",
            "Bartók",
            "Liszt",
            "Dvorak",
        ],
        "correct": 0,
        "explanation": "Kodály Zoltán: Adagio",
        "audio_file": "19. Kodaly - Adagio.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Bartók",
            "Kodály",
            "Liszt",
            "Dvorak",
        ],
        "correct": 0,
        "explanation": "Bartók: Kékszakállú herceg vára",
        "audio_file": "20. Bartok - Bluebeard Castle.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Bartók",
            "Kodály",
            "Liszt",
            "Dvorak",
        ],
        "correct": 0,
        "explanation": "Bartók: Csodálatos mandarin",
        "audio_file": "21. Bartok - Miraculous Mandarin.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Hacsaturján",
            "Bartók",
            "Csajkovszkij",
            "Bach",
        ],
        "correct": 0,
        "explanation": "Hacsaturján: Kartánc",
        "audio_file": "22. Khachaturian - Sabre Dance.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Hacsaturján",
            "Bartók",
            "Csajkovszkij",
            "Bach",
        ],
        "correct": 0,
        "explanation": "Hacsaturján: Spartacus / Onedin",
        "audio_file": "23. Khachaturian - Spartacus.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Weiner Leó",
            "Kodály",
            "Bartók",
            "Liszt",
        ],
        "correct": 0,
        "explanation": "Weiner Leó: Rókatánc",
        "audio_file": "24. Weiner - Fox Dance.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Rimsky-Korsakov",
            "Csajkovszkij",
            "Mussorgsky",
            "Bach",
        ],
        "correct": 0,
        "explanation": "Rimsky-Korsakov: Bumblebee",
        "audio_file": "25. Rimsky Korsakov - Flight of Bumblebee.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Mussorgsky",
            "Rimsky-Korsakov",
            "Csajkovszkij",
            "Bach",
        ],
        "correct": 0,
        "explanation": "Mussorgsky: Éjszaka a hegyen",
        "audio_file": "26. Mussorgsky - Night on Bald Mountain.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Schubert",
            "Mozart",
            "Beethoven",
            "Bach",
        ],
        "correct": 0,
        "explanation": "Schubert: Pisztráng ötös",
        "audio_file": "27. Schubert - Trout Quintet.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Prokofjev",
            "Shostakovich",
            "Csajkovszkij",
            "Bach",
        ],
        "correct": 0,
        "explanation": "Prokofjev: Péter és a farkas",
        "audio_file": "28. Prokofiev - Peter and Wolf.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Carl Orff",
            "Bach",
            "Beethoven",
            "Mozart",
        ],
        "correct": 0,
        "explanation": "Carl Orff: Carmina Burana",
        "audio_file": "29. Carl Orff - Carmina Burana.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Ravel",
            "Debussy",
            "Beethoven",
            "Mozart",
        ],
        "correct": 0,
        "explanation": "Ravel: Bolero",
        "audio_file": "30. Ravel - Bolero.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Beethoven",
            "Mozart",
            "Csajkovszkij",
            "Bach",
        ],
        "correct": 3,
        "explanation": "Bach: Brandenburgi versenyek - 3. verseny",
        "audio_file": "31. Bach - Brandenburg Concerto 3.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Beethoven",
            "Mozart",
            "Csajkovszkij",
            "Bach",
        ],
        "correct": 3,
        "explanation": "Bach: Toccata és fúga d-moll",
        "audio_file": "32. Bach - Toccata Fugue D minor.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Beethoven",
            "Mozart",
            "Csajkovszkij",
            "Bach",
        ],
        "correct": 3,
        "explanation": "Bach: Air on G-string",
        "audio_file": "33. Bach - Air on G String.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Beethoven",
            "Mozart",
            "Csajkovszkij",
            "Bach",
        ],
        "correct": 3,
        "explanation": "Bach: Italian Concerto",
        "audio_file": "34. Bach - Italian Concerto.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Beethoven",
            "Mozart",
            "Csajkovszkij",
            "Bach",
        ],
        "correct": 3,
        "explanation": "Bach: Jesu, Joy of Man",
        "audio_file": "35. Bach - Jesu Joy.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Beethoven",
            "Mozart",
            "Csajkovszkij",
            "Bach",
        ],
        "correct": 3,
        "explanation": "Bach: Brandenburg Concerto No. 5",
        "audio_file": "36. Bach - Brandenburg Concerto 5.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Beethoven",
            "Mozart",
            "Csajkovszkij",
            "Bach",
        ],
        "correct": 3,
        "explanation": "Bach: Vivace",
        "audio_file": "37. Bach - Concerto Two Violins.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Beethoven",
            "Mozart",
            "Csajkovszkij",
            "Bach",
        ],
        "correct": 3,
        "explanation": "Bach: G-dúr menüett",
        "audio_file": "38. Bach - Minuet G major.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Charpentier",
            "Handel",
            "Bach",
            "Vivaldi",
        ],
        "correct": 0,
        "explanation": "Charpentier: Te Deum Prelude",
        "audio_file": "39. Charpentier - Te Deum Prelude.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Delibes",
            "Bizet",
            "Gounod",
            "Offenbach",
        ],
        "correct": 0,
        "explanation": "Delibes: Lakmé - Flower Duet",
        "audio_file": "40. Delibes - Lakme Flower Duet.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Offenbach",
            "Bizet",
            "Gounod",
            "Delibes",
        ],
        "correct": 0,
        "explanation": "Offenbach: YouTube klasszikus",
        "audio_file": "41. Offenbach - Offenbach.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Vivaldi",
            "Bach",
            "Handel",
            "Corelli",
        ],
        "correct": 0,
        "explanation": "Vivaldi: Négy évszak (YouTube)",
        "audio_file": "42. Vivaldi - Four Seasons.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Mozart",
            "Haydn",
            "Beethoven",
            "Schubert",
        ],
        "correct": 0,
        "explanation": "Mozart: YouTube klasszikus",
        "audio_file": "43. Mozart - Mozart.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Rossini",
            "Verdi",
            "Donizetti",
            "Bellini",
        ],
        "correct": 0,
        "explanation": "Rossini: YouTube klasszikus",
        "audio_file": "44. Rossini - Rossini.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Delibes",
            "Bizet",
            "Gounod",
            "Offenbach",
        ],
        "correct": 0,
        "explanation": "Delibes: YouTube klasszikus",
        "audio_file": "45. Delibes - Sylvia - Pizzicato.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Erkel Ferenc",
            "Bartók Béla",
            "Mozart",
            "Johann Strauss",
        ],
        "correct": 0,
        "explanation": "Erkel Ferenc: Hunyadi László - Palotás",
        "audio_file": "47. Erkel Ferenc - Hunyadi Laszlo Palotas.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Mozart",
            "Beethoven",
            "Bach",
            "Chopin",
        ],
        "correct": 0,
        "explanation": "Mozart: Rondo Alla Turca",
        "audio_file": "46. Mozart - Rondo Turca.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Edvard Grieg",
            "Jean Sibelius",
            "Carl Nielsen",
            "Dmitri Shostakovich",
        ],
        "correct": 0,
        "explanation": "Edvard Grieg: In the Hall of the Mountain King",
        "audio_file": "48. Edvard Grieg - Mountain King.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Johannes Brahms",
            "Franz Schubert",
            "Robert Schumann",
            "Felix Mendelssohn",
        ],
        "correct": 0,
        "explanation": "Johannes Brahms: Hungarian Dances No. 5",
        "audio_file": "49. Brahms - Hungarian Dances No 5.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "George Gershwin",
            "Aaron Copland",
            "Leonard Bernstein",
            "Igor Stravinsky",
        ],
        "correct": 0,
        "explanation": "George Gershwin: Rhapsody in Blue",
        "audio_file": "50. Gershwin - Rhapsody in Blue.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Johann Strauss II",
            "Franz Liszt",
            "Béla Bartók",
            "Zoltán Kodály",
        ],
        "correct": 0,
        "explanation": "Csárdás - Kennedy Orchestra",
        "audio_file": "51. Csardas - Kennedy Orchestra.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Claude Debussy",
            "Maurice Ravel",
            "Gabriel Fauré",
            "Erik Satie",
        ],
        "correct": 0,
        "explanation": "Claude Debussy: Clair de lune",
        "audio_file": "52. Debussy - Clair de lune.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Frédéric Chopin",
            "Franz Liszt",
            "Robert Schumann",
            "Johannes Brahms",
        ],
        "correct": 0,
        "explanation": "Lola Astanova: Fantaisie Impromptu (Chopin)",
        "audio_file": "53. Lola Astanova - Fantaisie Impromptu.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Claude Debussy",
            "Maurice Ravel",
            "Gabriel Fauré",
            "Erik Satie",
        ],
        "correct": 0,
        "explanation": "Claude Debussy: Clair de lune (Menahem Pressler előadás)",
        "audio_file": "54. Claude Debussy - Clair de lune.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Zoltán Kodály",
            "Béla Bartók",
            "Weiner Leó",
            "Dohnány Ernő",
        ],
        "correct": 0,
        "explanation": "Kodály Zoltán: Háry János – Toborzó",
        "audio_file": "55. Zoltán Kodály - Háry János - Toborzó.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét:",
        "options": [
            "Johann Strauss II",
            "Johann Strauss I",
            "Franz Lehár",
            "Haydn",
        ],
        "correct": 0,
        "explanation": "Johann Strauss II: Die Fledermaus (részlet)",
        "audio_file": "56. Johann Strauss II - Die Fleder.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét: ",
        "options": [
            "Mozart",
            "Beethoven",
            "Bach",
            "Haydn",
        ],
        "correct": 0,
        "explanation": "Ismeretlen: Unknown Artist Mozart Requiem Lacrimosa SO ",
        "audio_file": "57. Mozart - Requiem Lacrimosa SO.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét!",
        "options": [
            "Mozart",
            "Beethoven",
            "Bach",
            "Haydn",
        ],
        "correct": 0,
        "explanation": "Ismeretlen: Unknown Artist The Magic Flute Queen of the ",
        "audio_file": "58. Mozart - The Magic Flute.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét!",
        "options": [
            "Mozart",
            "Beethoven",
            "Bach",
            "Haydn",
        ],
        "correct": 0,
        "explanation": "Ismeretlen: Unknown Artist Lang Lang Mozart Sonata in C ",
        "audio_file": "59. Mozart -  Mozart Sonata in C major.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét!",
        "options": [
            "Mozart",
            "Beethoven",
            "Bach",
            "Haydn",
        ],
        "correct": 0,
        "explanation": "Ismeretlen: Unknown Artist The Shawshank redemption Canzo",
        "audio_file": "60. Mozart - Canzonetta sullaria.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét!",
        "options": [
            "Mozart",
            "Beethoven",
            "Wagner",
            "Haydn",
        ],
        "correct": 2,
        "explanation": "Ismeretlen: 7-OndaxNqzM",
        "audio_file": "61. Mozart - Die Meistersinger von Nürnberg.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét: ",
        "options": [
            "Wagner",
            "Beethoven",
            "Bach",
            "Haydn",
        ],
        "correct": 0,
        "explanation": "Ismeretlen: Unknown Artist Tannhäuser Music fragment D",
        "audio_file": "Unknown_Artist_Tannhäuser_Music_fragment_D.mp3",
        "song_title": "Tannhäuser Music fragment ",
        "topic": "komolyzene",
    },
    {
        "question": "Hallgasd meg ezt a zeneművet és válaszd ki a zeneszerzőjét: \"Dvorak Dvořák Symphony 9 From The New World II \"",
        "options": [
            "Mozart",
            "Beethoven",
            "Bach",
            "Haydn",
        ],
        "correct": 0,
        "explanation": "Ismeretlen: Dvorak Dvořák Symphony 9 From The New World II ",
        "audio_file": "Dvorak_Dvořák_Symphony_9_From_The_New_World_II_.mp3",
        "topic": "komolyzene",
    },
]
