# Auto-generated questions file
# Generated on: 2026-01-27 15:03:29

KOMPOLYZENE_QUESTIONS = [
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Beethoven",
            "Mozart",
            "Bach",
            "Haydn",
        ],
        "correct": 0,
        "explanation": "Beethoven - Komolyzene",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Mozart",
            "Beethoven",
            "Bach",
            "Chopin",
        ],
        "correct": 0,
        "explanation": "Mozart - Komolyzene",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Bach",
            "Beethoven",
            "Mozart",
            "Handel",
        ],
        "correct": 0,
        "explanation": "Bach - Komolyzene",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Mozart",
            "Rossini",
            "Brahms",
            "Beethoven",
        ],
        "correct": 0,
        "explanation": "Mozart - Komolyzene",
        "audio_file": "Unknown_Artist_Rondo_Alla_Turca_Mozart.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Grieg",
            "Dvorak",
            "Prokofjev",
            "Mussorgsky",
        ],
        "correct": 0,
        "explanation": "Grieg - Komolyzene",
        "audio_file": "Unknown_Artist_Edvard_Grieg_In_the_Hall_of_th.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Gershwin",
            "Prokofjev",
            "Kodály",
            "Khachaturian",
        ],
        "correct": 0,
        "explanation": "Gershwin - Komolyzene",
        "audio_file": "Unknown_Artist_Rhapsody_in_Claret_Blue_Arr_K.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Brahms",
            "Mozart",
            "Rossini",
            "Puccini",
        ],
        "correct": 0,
        "explanation": "Brahms - Komolyzene",
        "audio_file": "Unknown_Artist_21_Hungarian_Dances_WoO_1_No_5.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Nigel Kennedy",
            "Vanessa Mae",
            "Itzhak Perlman",
            "Joshua Bell",
        ],
        "correct": 0,
        "explanation": "Nigel Kennedy - Komolyzene",
        "audio_file": "Unknown_Artist_Csárdás_Orch_Kennedy.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Chopin",
            "Liszt",
            "Dvorak",
            "Wagner",
        ],
        "correct": 0,
        "explanation": "Chopin - Komolyzene",
        "audio_file": "Unknown_Artist_Lola_Astanova_Fantaisie_Impr.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Debussy",
            "Liszt",
            "Chopin",
            "Mozart",
        ],
        "correct": 0,
        "explanation": "Debussy - Komolyzene",
        "audio_file": "Unknown_Artist_Debussy_Clair_de_lune_Menahem.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Debussy",
            "Mozart",
            "Haydn",
            "Liszt",
        ],
        "correct": 0,
        "explanation": "Debussy - Komolyzene",
        "audio_file": "Unknown_Artist_Debussy_Clair_de_lune_Menahem.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Kodály Zoltán",
            "Bartók Béla",
            "Weiner Leó",
            "Dohnány Ernő",
        ],
        "correct": 0,
        "explanation": "Kodály Zoltán - Komolyzene",
        "audio_file": "Unknown_Artist_Háry_János_Toborzó.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Johann Strauss II.",
            "Offenbach",
            "Handel",
            "Liszt",
        ],
        "correct": 0,
        "explanation": "Johann Strauss II. - Komolyzene",
        "audio_file": "Unknown_Artist_Johann_Strauss_II_Die_Fleder.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Mozart",
            "Bach",
            "Beethoven",
            "Handel",
        ],
        "correct": 0,
        "explanation": "Mozart - Komolyzene",
        "audio_file": "Unknown_Artist_Mozart_Requiem_Lacrimosa_SO_.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Mozart",
            "Handel",
            "Puccini",
            "Beethoven",
        ],
        "correct": 0,
        "explanation": "Mozart - Komolyzene",
        "audio_file": "Unknown_Artist_The_Magic_Flute_Queen_of_the_.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Mozart",
            "Bach",
            "Handel",
            "Schubert",
        ],
        "correct": 0,
        "explanation": "Mozart - Komolyzene",
        "audio_file": "Unknown_Artist_Lang_Lang_Mozart_Sonata_in_C_.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Mozart",
            "Puccini",
            "Donizetti",
            "Johann Strauss II",
        ],
        "correct": 0,
        "explanation": "Mozart - Canzonetta sull'aria",
        "audio_file": "Unknown_Artist_The_Shawshank_redemption_Canzo.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Wagner",
            "Beethoven",
            "Mozart",
            "Handel",
        ],
        "correct": 0,
        "explanation": "Wagner - Die Meistersinger von Nürnberg",
        "audio_file": "7-OndaxNqzM.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Wagner",
            "Beethoven",
            "Mozart",
            "Haydn",
        ],
        "correct": 0,
        "explanation": "Wagner - Tannhäuser",
        "audio_file": "Wagner_Tannhäuser_Music_fragment_Dutch_National.mp3",
        "song_title": "Tannhäuser: Music fragment  - Dutch National Opera",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Dvorak",
            "Beethoven",
            "Wagner",
            "Liszt",
        ],
        "correct": 0,
        "explanation": "Dvorak - Komolyzene",
        "audio_file": "Dvorak_Dvořák_Symphony_9_From_The_New_World_II_.mp3",
        "song_title": "Dvořák: Symphony №9, \"From The New World\" - II - Largo",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Dvorak",
            "Beethoven",
            "Wagner",
            "Liszt",
        ],
        "correct": 0,
        "explanation": "Dvorak ",
        "audio_file": "Dvorak_Symphony_No_9_From_the_New_World_Mvmt_4.mp3",
        "song_title": "Symphony No. 9 (From the New World) Mvmt 4",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Verdi",
            "Wagner",
            "Beethoven",
            "Mozart",
        ],
        "correct": 0,
        "explanation": "Verdi ",
        "audio_file": "Verdi_Verdis_Requiem_Dies_irae.mp3",
        "song_title": "Verdi’s Requiem: “Dies irae”",
        "topic": "komolyzene",
    },
]
