# Auto-generated questions file
# Generated on: 2025-09-22 13:27:56

KOMPOLYZENE_QUESTIONS = [
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Beethoven",
            "Mozart",
            "Bach",
            "Haydn",
        ],
        "correct": 0,
        "explanation": "Beethoven - Komolyzene",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Mozart",
            "Beethoven",
            "Bach",
            "Chopin",
        ],
        "correct": 0,
        "explanation": "Mozart - Komolyzene",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Bach",
            "Beethoven",
            "Mozart",
            "Handel",
        ],
        "correct": 0,
        "explanation": "Bach - Komolyzene",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Mozart",
            "Rossini",
            "Brahms",
            "Beethoven",
        ],
        "correct": 0,
        "explanation": "Mozart - Komolyzene",
        "audio_file": "Unknown_Artist_Rondo_Alla_Turca_Mozart.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Grieg",
            "Dvorak",
            "Prokofjev",
            "Mussorgsky",
        ],
        "correct": 0,
        "explanation": "Grieg - Komolyzene",
        "audio_file": "Unknown_Artist_Edvard_Grieg_In_the_Hall_of_th.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Gershwin",
            "Prokofjev",
            "Kodály",
            "Khachaturian",
        ],
        "correct": 0,
        "explanation": "Gershwin - Komolyzene",
        "audio_file": "Unknown_Artist_Rhapsody_in_Claret_Blue_Arr_K.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Brahms",
            "Mozart",
            "Rossini",
            "Puccini",
        ],
        "correct": 0,
        "explanation": "Brahms - Komolyzene",
        "audio_file": "Unknown_Artist_21_Hungarian_Dances_WoO_1_No_5.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Nigel Kennedy",
            "Vanessa Mae",
            "Itzhak Perlman",
            "Joshua Bell",
        ],
        "correct": 0,
        "explanation": "Nigel Kennedy - Komolyzene",
        "audio_file": "Unknown_Artist_Csárdás_Orch_Kennedy.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Chopin",
            "Liszt",
            "Dvorak",
            "Wagner",
        ],
        "correct": 0,
        "explanation": "Chopin - Komolyzene",
        "audio_file": "Unknown_Artist_Lola_Astanova_Fantaisie_Impr.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Debussy",
            "Liszt",
            "Chopin",
            "Mozart",
        ],
        "correct": 0,
        "explanation": "Debussy - Komolyzene",
        "audio_file": "Unknown_Artist_Debussy_Clair_de_lune_Menahem.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Debussy",
            "Mozart",
            "Haydn",
            "Liszt",
        ],
        "correct": 0,
        "explanation": "Debussy - Komolyzene",
        "audio_file": "Unknown_Artist_Debussy_Clair_de_lune_Menahem.mp3",
        "topic": "komolyzene",
    },
    {
        "question": "Ki a zeneszerző?",
        "options": [
            "Kodály Zoltán",
            "Bartók Béla",
            "Weiner Leó",
            "Dohnány Ernő",
        ],
        "correct": 0,
        "explanation": "Kodály Zoltán - Komolyzene",
        "audio_file": "Unknown_Artist_Háry_János_Toborzó.mp3",
        "topic": "komolyzene",
    },
]
