# Auto-generated questions file
# Generated on: 2025-09-19 20:59:05

_DEFAULT_QUESTION = "Ki az előadó?"
_TOPIC = "magyar_zenekarok_uj"


def _q(audio_file, correct, options, explanation="", question=_DEFAULT_QUESTION, **extra):
    """Segédfüggvény: kompakt kérdés létrehozása."""
    return {
        "question": question,
        "options": options,
        "correct": correct,
        "explanation": explanation,
        "audio_file": audio_file,
        "topic": _TOPIC,
        **extra,
    }


QUESTIONS = [
    _q('41_Alvin_és_a_Mókusok.mp3', 0, ['Alvin és a Mókusok', 'Hétköznapi Csalódások', 'Tudósok', 'Tankcsapda'], 'Alvin és a Mókusok magyar punk zenekar'),
    _q('55_Hétköznapi_Csalódások.mp3', 0, ['Hétköznapi Csalódások', 'Alvin és a Mókusok', 'Tudósok', 'Tankcsapda'], 'Hétköznapi Csalódások magyar punk zenekar'),
    _q('', 0, ['Tudósok', 'Alvin és a Mókusok', 'Hétköznapi Csalódások', 'Tankcsapda'], ''),
    _q('54_Tankcsapda.mp3', 0, ['Tankcsapda', 'Pokolgép', 'Ossian', 'Dalriada'], 'Tankcsapda magyar metal zenekar'),
    _q('37_Pokolgép.mp3', 0, ['Pokolgép', 'Tankcsapda', 'Ossian', 'Dalriada'], 'Pokolgép magyar metal zenekar'),
    _q('', 0, ['Ossian', 'Tankcsapda', 'Pokolgép', 'Dalriada'], ''),
    _q('', 0, ['Magashegyi Underground', 'Blahalouisiana', 'Biorobot', 'PBox'], ''),
    _q('', 0, ['Biorobot', 'Hiperkarma', 'Supernem', 'Carson Coma'], ''),
    _q('57_Blahalouisiana.mp3', 0, ['Blahalouisiana', 'Honeybeast', 'Odett', 'Magashegyi Underground'], 'Blahalouisiana magyar metal zenekar'),
    _q('49_PBox.mp3', 0, ['PBox', 'Dalriada', 'Thy Catafalque', 'Sear Bliss'], 'PBox magyar metal zenekar'),
    _q('44_Republic.mp3', 0, ['Republic', 'Bon-Bon', 'Neoton Família', 'Omega'], 'Republic magyar mainstream zenekar'),
    _q('53_Bon-Bon.mp3', 0, ['Bon-Bon', 'Republic', 'Neoton Família', 'Omega'], 'Bon-Bon magyar mainstream zenekar'),
    _q('36_Neoton_Família.mp3', 0, ['Neoton Família', 'Republic', 'Bon-Bon', 'Omega'], 'Neoton Família magyar mainstream zenekar'),
    _q('34_Omega.mp3', 0, ['Omega', 'Republic', 'Bon-Bon', 'Neoton Família'], 'Omega magyar mainstream zenekar'),
    _q('32_Illés.mp3', 0, ['Illés', 'LGT', 'Piramis', 'Korai Öröm'], 'Illés magyar mainstream zenekar'),
    _q('59_LGT.mp3', 0, ['LGT', 'Illés', 'Piramis', 'Korai Öröm'], 'LGT magyar mainstream zenekar'),
    _q('45_Piramis.mp3', 0, ['Piramis', 'Illés', 'LGT', 'Korai Öröm'], 'Piramis magyar mainstream zenekar'),
    _q('39_Korai_Öröm.mp3', 0, ['Korai Öröm', 'Illés', 'LGT', 'Piramis'], 'Korai Öröm magyar mainstream zenekar'),
    _q('47_P_Mobil.mp3', 0, ['P. Mobil', 'P.Box', 'Republic', 'Omega'], 'P. Mobil magyar mainstream zenekar'),
    _q('24_Bonanza_Banzai.mp3', 0, ['Bonanza Banzaiii', 'P. Mobil', 'Republic', 'Omega'], 'Bonanza Banzai magyar mainstream zenekar'),
    _q('48_Caramel.mp3', 0, ['Caramel', 'Bon-Bon', 'Republic', 'Omega'], 'Caramel magyar trash-mainstream zenekar'),
    _q('28_A_Maci.mp3', 0, ['A Maci', 'Moriones', 'Manuel', 'Desh'], 'A Maci magyar hip-hop előadó'),
    _q('23. Moriones - Ez az ára.mp3', 0, ['Moriones', 'A Maci', 'Manuel', 'Desh'], 'Moriones magyar hip-hop előadó'),
    _q('27_Manuel.mp3', 0, ['Manuel', 'A Maci', 'Moriones', 'Desh'], 'Manuel magyar hip-hop előadó'),
    _q('33_Desh.mp3', 0, ['Desh', 'Betonhofi', 'T.Danny', 'K.Kevin'], 'Desh magyar hip-hop előadó'),
    _q('25_Betonhofi.mp3', 0, ['Betonhofi', 'Desh', 'T.Danny', 'K.Kevin'], 'Betonhofi magyar hip-hop előadó'),
    _q('42_T_Danny.mp3', 0, ['T.Danny', 'Desh', 'Betonhofi', 'K.Kevin'], 'T.Danny magyar hip-hop előadó'),
    _q('26_K_Kevin.mp3', 0, ['K.Kevin', 'Desh', 'Betonhofi', 'T.Danny'], 'K.Kevin magyar hip-hop előadó'),
    _q('30_Dzsúdló.mp3', 0, ['Dzsúdló', 'Azariah', 'Alee', 'Krúbi'], 'Dzsúdló magyar hip-hop előadó'),
    _q('35_Azariah.mp3', 0, ['Azariah', 'Dzsúdló', 'Alee', 'Krúbi'], 'Azariah magyar hip-hop előadó'),
    _q('40_Alee.mp3', 0, ['Alee', 'Dzsúdló', 'Azariah', 'Krúbi'], 'Alee magyar hip-hop előadó'),
    _q('52_Krúbi.mp3', 0, ['Krúbi', 'Dzsúdló', 'Azariah', 'Alee'], 'Krúbi magyar hip-hop előadó'),
    _q('23_Carson_Coma.mp3', 0, ['Carson Coma', 'A Maci', 'Ómen', 'Sing Sing'], 'Carson Coma magyar hip-hop előadó'),
    _q('62_Ómen.mp3', 0, ['Ómen', 'Sing Sing', 'Leander Kills', 'Ossian'], 'Ómen magyar zenekar'),
    _q('50_Sing_Sing.mp3', 0, ['Sing Sing', 'Ómen', 'Leander Kills', 'Ossian'], 'Sing Sing magyar zenekar'),
    _q('51_Leander_Kills.mp3', 0, ['Leander Kills', 'Ómen', 'Sing Sing', 'Ossian'], 'Leander Kills magyar zenekar'),
    _q('46_Ossián.mp3', 0, ['Ossian', 'Ómen', 'Sing Sing', 'Leander Kills'], 'Ossian magyar zenekar'),
    _q('22_Zana_Zoltán.mp3', 0, ['Zana Zoltán', 'Széki Attila', 'Wolf Kati', 'Republic'], 'Zana Zoltán magyar előadó'),
    _q('38_Széki_Attila.mp3', 0, ['Széki Attila', 'Zana Zoltán', 'Wolf Kati', 'Republic'], 'Széki Attila magyar előadó'),
    _q('29_Wolf_Kati.mp3', 0, ['Wolf Kati', 'Zana Zoltán', 'Széki Attila', 'Republic'], 'Wolf Kati magyar előadó'),
    _q('63_Intim_Torna_Illegal.mp3', 0, ['Intim Torna Illegál', 'Magashegyi Underground', 'Blahalouisiana', 'Biorobot'], 'Intim Torna Illegál magyar alternatív zenekar'),
    _q('64_Kistehen.mp3', 0, ['Kistehén', 'Intim Torna Illegál', 'Tudósok', 'dr BRS'], 'Kistehén magyar alternatív zenekar'),
    _q('65_Kollar_Klemencz_Laszlo.mp3', 2, ['Kistehén', 'Intim Torna Illegál', 'Kollár Klemencz László', 'Kardos Horváth János'], 'Kollár Klemencz László magyar előadó'),
    _q('66_Honeybeast.mp3', 0, ['Honeybeast', 'Blahalouisiana', 'Margaret Island', 'Paulina'], 'Honeybeast magyar zenekar'),
    _q('67_Kaukazus.mp3', 0, ['Kaukázus', 'Honeybeast', 'Kollár Klemencz László', 'Kistehén'], 'Kaukázus magyar zenekar'),
    _q('46. 30Y - 30Y.mp3', 0, ['30Y', 'Kaukázus', 'Honeybeast', 'Kollár Klemencz László'], '30Y magyar zenekar'),
    _q('69_Mate_Peter.mp3', 0, ['Máté Péter', '30Y', 'Kaukázus', 'Honeybeast'], 'Máté Péter magyar énekes'),
    _q('70_Aradszky_Laszlo.mp3', 0, ['Aradszky László', 'Máté Péter', '30Y', 'Kaukázus'], 'Aradszky László magyar énekes'),
    _q('00_Follow_the_flow.mp3', 0, ['Follow the flow', '4Street', 'Bagossy Brothers', 'Lóci játszik'], 'Follow the flow magyar zenekar'),
    _q('01_4Street.mp3', 0, ['4Street', 'Follow the flow', 'Bagossy Brothers', 'Csaknekedkislány'], '4Street magyar zenekar'),
    _q('02_Bagossy_Brothers.mp3', 0, ['Bagossy Brothers', '4Street', 'Follow the flow', 'Csaknekedkislány'], 'Bagossy Brothers magyar zenekar'),
    _q('03_Csaknekedkislány.mp3', 0, ['Csaknekedkislány', 'Bagossy Brothers', '4Street', 'Follow the flow'], 'Csaknekedkislány magyar zenekar'),
    _q('04_Lóci_játszik.mp3', 0, ['Lóci játszik', 'Csaknekedkislány', 'Bagossy Brothers', '4Street'], 'Lóci játszik magyar zenekar'),
    _q('05_Galaxisok.mp3', 0, ['Galaxisok', 'Lóci játszik', 'Csaknekedkislány', 'Bagossy Brothers'], 'Galaxisok magyar zenekar'),
    _q('06_Parno_Graszt.mp3', 0, ['Parno Graszt', 'Galaxisok', 'Lóci játszik', 'Csaknekedkislány'], 'Parno Graszt magyar zenekar'),
    _q('07_Palya_Bea.mp3', 0, ['Palya Bea', 'Parno Graszt', 'Galaxisok', 'Lóci játszik'], 'Palya Bea magyar énekesnő'),
    _q('08_Bohemian_Betyars.mp3', 0, ['Bohemian Betyars', 'Palya Bea', 'Parno Graszt', 'Galaxisok'], 'Bohemian Betyars magyar zenekar'),
    _q('09_Aurevoir.mp3', 0, ['Aurevoir', 'Bohemian Betyars', 'Palya Bea', 'Parno Graszt'], 'Aurevoir magyar zenekar'),
    _q('10_Dánielffy.mp3', 0, ['Dánielffy', 'Aurevoir', 'Bohemian Betyars', 'Palya Bea'], 'Dánielffy magyar zenekar'),
    _q('11_Ham_Ko_Ham.mp3', 0, ['Ham Ko Ham', 'Dánielffy', 'Aurevoir', 'Bohemian Betyars'], 'Ham Ko Ham magyar zenekar'),
    _q('12_Carbonfools.mp3', 0, ['Carbonfools', 'Ham Ko Ham', 'Dánielffy', 'Aurevoir'], 'Carbonfools magyar zenekar'),
    _q('13_Zagar.mp3', 0, ['Zagar', 'Carbonfools', 'Ham Ko Ham', 'Dánielffy'], 'Zagar magyar zenekar'),
    _q('14_Neo.mp3', 0, ['Neo', 'Zagar', 'Carbonfools', 'Ham Ko Ham'], 'Neo magyar zenekar'),
    _q('15_Soulwave.mp3', 0, ['Soulwave', 'Neo', 'Zagar', 'Carbonfools'], 'Soulwave magyar zenekar'),
    _q('16_Quimby.mp3', 0, ['Quimby', 'Soulwave', 'Neo', 'Zagar'], 'Quimby magyar zenekar'),
    _q('18_P._Mobil.mp3', 0, ['P. Mobil', 'Quimby', 'Soulwave', 'Neo'], 'P. Mobil magyar zenekar'),
    _q('19_Republic.mp3', 0, ['Republic', 'P. Mobil', 'Quimby', 'Soulwave'], 'Republic magyar zenekar'),
    _q('21_Korai_Öröm.mp3', 0, ['Korai Öröm', 'Republic', 'P. Mobil', 'Quimby'], 'Korai Öröm magyar zenekar'),
    _q('71_Bagossy_Brothers_Company.mp3', 0, ['Bagossy Brothers Company', 'Bagossy Brothers', 'Republic', 'Korai Öröm'], 'Bagossy Brothers Company magyar zenekar'),
    _q('72_Neoton_Família.mp3', 0, ['Neoton Família', 'Bagossy Brothers Company', 'Bagossy Brothers', 'Republic'], 'Neoton Família magyar zenekar'),
    _q('73_Follow_the_flow.mp3', 0, ['Follow the Flow', 'Neoton Família', 'Bagossy Brothers Company', 'Bagossy Brothers'], 'Follow the Flow magyar zenekar'),
    _q('74_4Street.mp3', 0, ['4Street', 'Follow the Flow', 'Neoton Família', 'Bagossy Brothers Company'], '4Street magyar zenekar'),
    _q('75_Bagossy_Brothers.mp3', 0, ['Bagossy Brothers', '4Street', 'Follow the Flow', 'Neoton Família'], 'Bagossy Brothers magyar zenekar'),
    _q('76_Csaknekedkislány.mp3', 0, ['Csaknekedkislány', 'Bagossy Brothers', '4Street', 'Follow the Flow'], 'Csaknekedkislány magyar zenekar'),
    _q('77_Lóci_játszik.mp3', 0, ['Lóci játszik', 'Csaknekedkislány', 'Bagossy Brothers', '4Street'], 'Lóci játszik magyar zenekar'),
    _q('78_Galaxisok.mp3', 0, ['Galaxisok', 'Lóci játszik', 'Csaknekedkislány', 'Bagossy Brothers'], 'Galaxisok magyar zenekar'),
    _q('79_Parno_Graszt.mp3', 0, ['Parno Graszt', 'Galaxisok', 'Lóci játszik', 'Csaknekedkislány'], 'Parno Graszt magyar zenekar'),
    _q('80_Palya_Bea.mp3', 0, ['Palya Bea', 'Parno Graszt', 'Galaxisok', 'Lóci játszik'], 'Palya Bea magyar zenekar'),
    _q('81_Bohemian_Betyars.mp3', 0, ['Bohemian Betyars', 'Palya Bea', 'Parno Graszt', 'Galaxisok'], 'Bohemian Betyars magyar zenekar'),
    _q('82_Aurevoir.mp3', 0, ['Aurevoir', 'Bohemian Betyars', 'Palya Bea', 'Parno Graszt'], 'Aurevoir magyar zenekar'),
    _q('83_Dánielffy.mp3', 0, ['Dánielffy', 'Aurevoir', 'Bohemian Betyars', 'Palya Bea'], 'Dánielffy magyar zenekar'),
    _q('84_Ham_Ko_Ham.mp3', 0, ['Ham Ko Ham', 'Dánielffy', 'Aurevoir', 'Bohemian Betyars'], 'Ham Ko Ham magyar zenekar'),
    _q('85_Carbonfools.mp3', 0, ['Carbonfools', 'Ham Ko Ham', 'Dánielffy', 'Aurevoir'], 'Carbonfools magyar zenekar'),
    _q('86_Zagar.mp3', 0, ['Zagar', 'Carbonfools', 'Ham Ko Ham', 'Dánielffy'], 'Zagar magyar zenekar'),
    _q('87_Neo.mp3', 0, ['Neo', 'Zagar', 'Carbonfools', 'Ham Ko Ham'], 'Neo magyar zenekar'),
    _q('88_Soulwave.mp3', 0, ['Soulwave', 'Neo', 'Zagar', 'Carbonfools'], 'Soulwave magyar zenekar'),
    _q('89_Quimby.mp3', 0, ['Quimby', 'Soulwave', 'Neo', 'Zagar'], 'Quimby magyar zenekar'),
    _q('90_Tankcsapda.mp3', 0, ['Tankcsapda', 'Quimby', 'Soulwave', 'Neo'], 'Tankcsapda magyar zenekar'),
    _q('91_P._Mobil.mp3', 0, ['P. Mobil', 'Tankcsapda', 'Quimby', 'Soulwave'], 'P. Mobil magyar zenekar'),
    _q('92_Republic.mp3', 0, ['Republic', 'P. Mobil', 'Tankcsapda', 'Quimby'], 'Republic magyar zenekar'),
    _q('93_Bonanza_Banzai.mp3', 0, ['Bonanza Banzai', 'Republic', 'P. Mobil', 'Tankcsapda'], 'Bonanza Banzai magyar zenekar'),
    _q('94_Korai_Öröm.mp3', 0, ['Korai Öröm', 'Bonanza Banzai', 'Republic', 'P. Mobil'], 'Korai Öröm magyar zenekar'),
    _q('93. 4F Club - Balatoni Láz.mp3', 0, ['4F Club', 'Betty Blue', 'Emergency House', 'Kozmix'], '4F Club - Magyar Zenekarok'),
    _q('94. A Kutya Vacsorája - Ez a mese.mp3', 0, ['A Kutya Vacsorája', 'Pál utcai fiúk', 'Kiscsillag', 'Lovasi András'], 'A Kutya Vacsorája - Magyar Zenekarok'),
    _q('95. Kaukázus - Honvéd.mp3', 0, ['Kaukázus', '30Y', 'Kiscsillag', 'Kistehén'], 'Kaukázus - Magyar Zenekarok'),
    _q('96. P Box - Zöld csillag.mp3', 0, ['Radics Béla', 'P. Mobile', 'Beatrice', 'Vikidál Gyula'], 'P. Box - Magyar Zenekarok'),
    _q('97. PBox - A zöld a bibor és a fekete.mp3', 0, ['P.Box', 'P.Mobile', 'Vikidál Gyula', 'Deák Bill Gyula'], 'P.Box - Magyar Zenekarok'),
    _q('audio_files/magyar_zenekarok/4F-Club - Balatoni Láz.mp3', 0, ['4F Club', 'Ámokfutók', 'Shyguys', 'Soho Party'], '30Y - Magyar Zenekarok', song_title='Balatoni Láz'),
    _q('99. cserihanna - Akinek én sok vagyok.mp3', 0, ['cserihanna', 'Odett', 'Parno Graszt', 'Palya Bea'], 'cserihanna - Magyar Zenekarok'),
    _q('Sisi_Yalla_Official_Music_Vi.mp3', 0, ['Sisi', 'Odet', 'cserihanna', 'Detto'], 'Sisi - Magyar Zenekarok'),
    _q('102. Irie Maffia -  VOLT EGY ÁLMOM.mp3', 0, ['Irie Maffia', 'Hiperkarma', 'Magna Cum Laude', 'Punnany Massif'], 'Irie Maffia - Magyar Zenekarok'),
]