# magyar_tortenelm kvíz kérdések

_TOPIC = "magyar_tortenelm"


def _q(question, correct, options, explanation, topic=_TOPIC):
    """Segédfüggvény: kompakt kérdés létrehozása."""
    return {"question": question, "options": options, "correct": correct, "explanation": explanation, "topic": topic}


MAGYAR_TORTENELM_QUESTIONS = [
    _q('1962-ben ezen a napon avatták fel a Kab-hegyi televízióadót. A Kab-hegy a Déli-Bakony legmagasabb hegye, Úrkút és Nagyvázsony között helyezkedik el, tengerszint feletti magassága 599 méter. 2013-ban kilátó épült a hegyre, amelyet egy magyar hősről neveztek el. Kiről?', 2, ['Hunyadi János', 'Zrínyi Miklós', 'Kinizsi Pál', 'Dobó István'], 'Helyes válasz: Kinizsi Pál'),
    _q('November 4-e nemzeti gyásznap Magyarországon az 1956-os forradalom leverésének emlékére. Ennek a napnak a hajnalán szovjet csapatok hadüzenet nélküli háborút indítottak Magyarország ellen. Kinek a beszéde hangzott el kora reggel a Kossuth Rádióban, amely így hangzott: „... Ma hajnalban a szovjet csapatok támadást indítottak fővárosunk ellen azzal a nyilvánvaló szándékkal, hogy megdöntsék a törvényes magyar demokratikus kormányt. Csapataink harcban állnak! A kormány a helyén van. Ezt közlöm az ország népével és a világ közvéleményével!”', 0, ['Nagy Imre', 'Kádár János', 'Bibó István', 'Tildy Zoltán'], 'Helyes válasz: Nagy Imre'),
    _q('Kőszeg 1648. november 6-án lett szabad királyi város, erre emlékeznek minden évben a Királyi Nap ünnepség keretében a városban. Kőszeg történelmének legnevesebb eseménye az 1532-ben lezajlott török ostrom, amikor a kis számú várvédő visszaverte a Bécs ellen vonuló, többszörös túlerőben lévő török sereget. Ki volt a várkapitány?', 3, ['Losonczy István', 'Zrínyi Miklós', 'Szondi György', 'Jurisics Miklós'], 'Helyes válasz: Jurisics Miklós'),
    _q('1921. november 6-án mondta ki a Nemzetgyűlés a Habsburg-ház trónfosztását, és IV. Károlyt Madeira szigetére száműzték. A történelem során hányszor került sor egy-egy Habsburg uralkodó eltávolítására a magyar trónról?', 3, ['egyszer', 'kétszer', 'háromszor', 'négyszer'], 'Helyes válasz: négyszer'),
    _q('1457. november 14-én született Aragóniai Beatrix nápolyi királyi hercegnő, aki először Mátyás király második feleségeként volt magyar királyné. Melyik királyunk felesége lett Mátyás halálát követően?', 1, ['I. Ulászló', 'II. Ulászló', 'II. Lajos', 'I. János'], 'Helyes válasz: II. Ulászló'),
    _q('1629. november 15-én hunyt el Bethlen Gábor erdélyi fejedelem (1613–1629), I. Gábor néven megválasztott magyar király (1620–1621), a 17. századi magyar történelem egyik legjelentősebb személyisége. Melyik bankjegyünkön látható az arcképe?', 1, ['1000 forint', '2000 forint', '5000 forint', '10000 forint'], 'Helyes válasz: 2000 forint'),
    _q('1912. november 20-án született Habsburg Ottó, az utolsó Habsburg-trónörökös, politikus, közíró, az Európai Parlament volt tagja. Apját, aki IV. Károly néven volt magyar király, 1921-ben fosztották meg trónjától. Mikor mondott le Habsburg Ottó véglegesen az osztrák trónról, hogy lehetősége legyen újra Ausztria területére lépni?', 3, ['1924', '1939', '1945', '1961'], 'Helyes válasz: 1961'),
    _q('1916. november 21-én hunyt el I. Ferenc József osztrák császár, magyar és cseh király, az Osztrák–Magyar Monarchia első uralkodója. Ő volt a Habsburg monarchia leghosszabb ideig regnáló uralkodója. Hány évig ült a trónon?', 2, ['48', '58', '68', '78'], 'Helyes válasz: 68'),
    _q('1948. november 26-án fogadta el az Országgyűlés „a nőkre nézve a közszolgálat körében és más életpályákon fennálló hátrányos helyzet megszüntetéséről" szóló törvényt, amely immár minden téren a férfiakkal egyenlő jogokat biztosított a nők számára. Mióta van a nőknek szavazati joga országunkban?', 2, ['1848', '1896', '1918', '1946'], 'Helyes válasz: 1918'),
    _q('1780. november 29-én hunyt el Mária Terézia magyar királynő, aki 40 éven keresztül uralkodott országunkban. Melyik állítás NEM igaz vele kapcsolatban?', 3, ['ő volt a Habsburg Birodalom egyetlen női uralkodója', 'apja halálakor több európai uralkodó háborút indított a Habsburgok ellen, mert nem ismerték el a nőági öröklést', 'Magyarország, Csehország és Ausztria uralkodója volt, illetve a Német-római Birodalom császárnéja', 'házastársa I. Ferenc német-római császár volt, gyermekük nem született'], 'Helyes válasz: házastársa I. Ferenc német-római császár volt, gyermekük nem született'),
    _q('1351. december 11-én hirdette ki a király az ősiség törvényét, amely az 1848 előtti magyar jogban a nemesi birtok öröklési és elidegenítési szabályrendszere volt. Egyenesági fiúörökös hiányában a rokonság, a nemzetség örökösödését biztosította a koronára való visszaháramlással szemben, és érvénytelennek tekintette az öröklött birtok eladását, eladományozását vagy örökül hagyását. Ki volt ekkor a király?', 0, ['I. Lajos', 'III. András', 'I. Károly', 'IV. Béla'], 'Helyes válasz: I. Lajos'),
    _q('1921. december 14–16. között Sopron és környékének lakossága népszavazáson döntötte el, hogy 257 km²-nyi terület Magyarországhoz vagy Ausztriához tartozzon-e. Ez volt a trianoni békeszerződés egyetlen komolyabb területi revíziója, amit a nagyhatalmak tartósan elfogadtak. A szavazók 65%-a Magyarország mellett döntött. Milyen megnevezéssel illetjük Sopront a szavazás óta?', 0, ['A leghűségesebb város / A hűség városa', 'A leghősiesebb város', 'A legbátrabb város', 'A legmagyarabb város'], 'Helyes válasz: A leghűségesebb város / A hűség városa'),
    _q('1978-ban a Szent Korona ezen a napon tért vissza Magyarországra, miután a 2. világháború után elvitték. Melyik országtól kaptuk vissza?', 0, ['Amerikai Egyesült Államok', 'Németország', 'Franciaország', 'Szovjetunió'], 'Helyes válasz: Amerikai Egyesült Államok'),
    _q('1973-ban hozták létre Magyarország első nemzeti parkját. Melyik volt az?', 0, ['Hortobágyi Nemzeti Park', 'Fertő-Hanság Nemzeti Park', 'Duna-Dráva Nemzeti Park', 'Kiskunsági Nemzeti Park'], 'Helyes válasz: Hortobágyi Nemzeti Park'),
    _q('2015. január 10-én megdőlt az országos hőmérsékleti rekord – a Soprontól nem messze fekvő Fertőrákoson mértek szokatlanul meleget. Hány fokot?', 3, ['9,6 °C', '13,4 °C', '16,1 °C', '19,7 °C'], 'Helyes válasz: 19,7 °C'),
    _q('Január 12-e a 2. magyar hadsereg emléknapja. Hány fős volt a hadsereg, amelyet 1943. január 12-én szovjet támadás ért?', 3, ['kb. 100.000', 'kb. 150.000', 'kb. 200.000', 'kb. 250.000'], 'Helyes válasz: kb. 250.000'),
    _q('1519-ben ezen a napon hunyt el I. Miksa német-római császár, aki Mátyás király halála után, a vele kötött szerződés értelmében jogosult lett volna a magyar trónra. Kit választottak helyette királynak a magyar rendek, vagyis ki uralkodott Mátyás után?', 2, ['I. Ulászló', 'I. János', 'II. Ulászló', 'II. Lajos'], 'Helyes válasz: II. Ulászló'),
    _q('1301-ben ezen a napon hunyt el az utolsó Árpád-házi királyunk. Ki volt ő?', 3, ['I. Károly', 'III. István', 'I. Géza', 'III. András'], 'Helyes válasz: III. András'),
    _q('1688. január 15-én az osztrák császári haderő elfoglalta a munkácsi várat. Ki volt a vár védője?', 1, ['Jurisics Miklós', 'Zrínyi Ilona', 'Zrínyi Miklós', 'Dobó István'], 'Helyes válasz: Zrínyi Ilona'),
    _q('Január 18-a Árpád-házi Szent Margit ünnepe. Melyik királyunk lánya volt?', 1, ['I. Károly', 'IV. Béla', 'V. István', 'III. László'], 'Helyes válasz: IV. Béla'),
    _q('1898. január 23-án született Széchenyi Zsigmond magyar vadász, utazó, író, a magyar vadászati kultúra kimagasló alakja. Melyik városban található a róla elnevezett vadászati múzeum?', 2, ['Szekszárd', 'Sopron', 'Hatvan', 'Békéscsaba'], 'Helyes válasz: Hatvan'),
    _q('Ezen a napon válaszották magyar királlyá Hunyadi Mátyást, I. Mátyás néven. Melyik évben?', 1, ['1358', '1458', '1558', '1658'], 'Helyes válasz: 1458'),
    _q('1830. január 28-án jelent meg a Hitel, a magyar gazdasági szakirodalom egyik első képviselője. Ki a szerzője?', 0, ['Széchenyi István', 'Deák Ferenc', 'Kossuth Lajos', 'Batthyány Lajos'], 'Helyes válasz: Széchenyi István'),
    _q('1919-ben bátor önkéntesek visszaverték a megszálló cseh helyőrséget, ezzel a város kiérdemelte a Civitas Fortissima (Legbátrabb Város) kitüntető elnevezést. Melyik városról van szó?', 0, ['Balassagyarmat', 'Vác', 'Esztergom', 'Komárom'], 'Helyes válasz: Balassagyarmat'),
    _q('1892. január 29-én született Matuska Szilveszter. Melyik évben követte el a biatorbágyi vonatrobbantásos merényletet?', 2, ['1911', '1921', '1931', '1941'], 'Helyes válasz: 1931'),
    _q('1990. január 31-én nyílt meg az első McDonald’s étterem Moszkvában. És Budapesten, a Régiposta utcában melyik évben volt a megnyitó?', 1, ['1985', '1988', '1991', '1994'], 'Helyes válasz: 1988'),
    _q('997. február 1-jén hunyt el Géza fejedelem. Melyik magyar várost alapította 972-ben?', 1, ['Szeged', 'Székesfehérvár', 'Sopron', 'Pécs'], 'Helyes válasz: Székesfehérvár'),
    _q('2012. február 3-án a Malév bejelentette, hogy gépei többé nem szállnak fel, megkezdődött a nemzeti légtársaság felszámolása. Melyik évben alakult meg a Malév jogelődje?', 0, ['1946', '1956', '1966', '1976'], 'Helyes válasz: 1946'),
    _q('1849-ben ezen a napon volt a piski csata, melyben Bem tábornok a piski hídnál megtámadta Puchner császári csapatait és döntő vereséget mért rájuk. Merrefelé van Ópiski település, ahol a csata zajlott?', 1, ['Pécs környékén', 'Erdélyben', 'Az Alföldön', 'Győrtől nem messze'], 'Helyes válasz: Erdélyben'),
    _q('1853-ban ezen a napon kezdték el építeni a Budai Váralagutat Clark Ádám tervei szerint. Ötletadója Széchenyi István volt. Milyen hosszú az alagút?', 1, ['150 méter', '350 méter', '550 méter', '750 méter'], 'Helyes válasz: 350 méter'),
    _q('1945. február 13-án ért véget Budapest ostroma, a várost a német megszállás alól felszabadító szovjet csapatok szállták meg. Melyik állítás NEM igaz?', 2, ['Február 11-én német–magyar kitörési kísérlet kezdődött, amelynek során a védelem parancsnokainak nagy része is fogságba esett', 'Az ostrom alatt és után a szovjet katonák több tízezer civil lakost hurcoltak el „málenkij robot”-ra, vagyis kényszermunkára', 'A harcokat különösen kegyetlenné tette, hogy a védőknek bőven volt fegyverük és lőszerük', 'Az ostrom során a németek felrobbantották a Duna-hidakat, hogy a szovjetek előrejutását akadályozzák'], 'Helyes válasz: A harcokat különösen kegyetlenné tette, hogy a védőknek bőven volt fegyverük és lőszerük'),
    _q('1837. február 16-án született Sobri Jóska, dunántúli betyár. Bandájával általában gazdag számadó juhászokat, kereskedőket fosztogatott. Hogyan ért véget az élete?', 3, ['egy betörés során elfogták és rövid per után felakasztották', 'társaival összekülönböztek egy gazdag zsákmányon, lövöldözés kezdődött, amiben találat is érte', 'lova megcsúszott egy jeges úton és lovasával együtt szakadékba zuhant', 'katonák kerítették be társaival együtt, véres küzdelmet követően, reménytelen helyzetét látva szíven lőtte magát'], 'Helyes válasz: katonák kerítették be társaival együtt, véres küzdelmet követően, reménytelen helyzetét látva szíven lőtte magát'),
    _q('1867-ben ezen a napon született meg az osztrák–magyar kiegyezés a Habsburg-uralkodóház, pontosabban annak feje, I. Ferenc József és a Deák Ferenc és Andrássy Gyula gróf vezette magyar tárgyalódelegáció között. Meddig állt fenn az ekkor létrejött Osztrák–Magyar Monarchia?', 1, ['1896', '1918', '1920', '1945'], 'Helyes válasz: 1918'),
    _q('1703. február 18-án hunyt el Zrínyi Ilona, Thököly Imre felesége, II. Rákóczi Ferenc fejedelem édesanyja. Melyik várnak volt védője a 1685–1688 közötti években?', 3, ['Eger', 'Regéc', 'Sárospatak', 'Munkács'], 'Helyes válasz: Munkács'),
]