# Magyar festmények kérdések - valódi képekkel
# Generated on: 2025-09-20 19:15:00

MAGYAR_FESTMENYEK_UJ_QUESTIONS = [
    {
        "question": "Nézd meg ezt a festményt: 'Szerelmesek találkozása' és válaszd ki a festő nevét:",
        "options": [
            "Csontváry Kosztka Tivadar",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Csontváry Kosztka Tivadar: Szerelmesek találkozása, 1902 körül",
        "image_file": "2. Csontváry - Szerelmesek találkozása.jpg",
        "topic": "magyar_festmenyek_uj",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Traui látkép naplemente idején' és válaszd ki a festő nevét:",
        "options": [
            "Csontváry Kosztka Tivadar",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Gulácsy Lajos",
        ],
        "correct": 0,
        "explanation": "Csontváry Kosztka Tivadar: Traui látkép naplemente idején, 1899",
        "image_file": "3. Csontváry_-_Traui_látkép_naplemente_idején.jpg",
        "topic": "magyar_festmenyek_uj",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Hídon átvonuló társaság' és válaszd ki a festő nevét:",
        "options": [
            "Csontváry Kosztka Tivadar",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Gulácsy Lajos",
        ],
        "correct": 0,
        "explanation": "Csontváry Kosztka Tivadar: Hídon átvonuló társaság, 1903-1905",
        "image_file": "Csontváry - Hídon átvonuló társaság.jpg",
        "topic": "magyar_festmenyek_uj",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Olasz halász' és válaszd ki a festő nevét:",
        "options": [
            "Csontváry Kosztka Tivadar",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Csontváry Kosztka Tivadar: Olasz halász, 1901 körül",
        "image_file": "Csontváry - Olasz halász.jpg",
        "topic": "magyar_festmenyek_uj",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Önarckép' és válaszd ki a festő nevét:",
        "options": [
            "Csontváry Kosztka Tivadar",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Aba-Novák Vilmos",
        ],
        "correct": 0,
        "explanation": "Csontváry Kosztka Tivadar: Önarckép, 1896-1902",
        "image_file": "Csontváry - Önarckép.jpg",
        "topic": "magyar_festmenyek_uj",
    },
    {
        "question": "Nézd meg ezt a festményt: 'A baba látogatói' és válaszd ki a festő nevét:",
        "options": [
            "Munkácsy Mihály",
            "Csontváry Kosztka Tivadar",
            "Tihanyi Lajos",
            "Gulácsy Lajos",
        ],
        "correct": 0,
        "explanation": "Munkácsy Mihály: A baba látogatói, 1879 - 160 millió forint",
        "image_file": "Munkácsy - A baba látogatói.jpg",
        "topic": "magyar_festmenyek_uj",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Alvó nagyapó' és válaszd ki a festő nevét:",
        "options": [
            "Munkácsy Mihály",
            "Csontváry Kosztka Tivadar",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Munkácsy Mihály: Alvó nagyapó, 1887 - 180 millió forint",
        "image_file": "Munkácsy - Alvó nagyapó.jpg",
        "topic": "magyar_festmenyek_uj",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Poros út' és válaszd ki a festő nevét:",
        "options": [
            "Munkácsy Mihály",
            "Csontváry Kosztka Tivadar",
            "Tihanyi Lajos",
            "Aba-Novák Vilmos",
        ],
        "correct": 0,
        "explanation": "Munkácsy Mihály: Poros út I., 1874 - 220 millió forint",
        "image_file": "Munkácsy- Poros út.jpg",
        "topic": "magyar_festmenyek_uj",
    },
    {
        "question": "Nézd meg ezt a festményt: 'A Pont Saint-Michel Párizsban' és válaszd ki a festő nevét:",
        "options": [
            "Tihanyi Lajos",
            "Munkácsy Mihály",
            "Csontváry Kosztka Tivadar",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Tihanyi Lajos: A Pont Saint-Michel Párizsban, 1908 - 220 millió forint",
        "image_file": "Tihanyi Lajos - A_Pont Saint-Michel Párizsban_(1908).jpg",
        "topic": "magyar_festmenyek_uj",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Lámpagyújtó' és válaszd ki a festő nevét:",
        "options": [
            "Bortnyik Sándor",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Aba-Novák Vilmos",
        ],
        "correct": 0,
        "explanation": "Bortnyik Sándor: Lámpagyújtó, 1921 - 170 millió forint",
        "image_file": "Bortnyik Sándor - Lámpagyújtó.jpg",
        "topic": "magyar_festmenyek_uj",
    },
    {
        "question": "Nézd meg ezt a festményt: 'A púpos vénkisasszony régi emlékeit meséli Herbertnek' és válaszd ki a festő nevét:",
        "options": [
            "Gulácsy Lajos",
            "Munkácsy Mihály",
            "Csontváry Kosztka Tivadar",
            "Aba-Novák Vilmos",
        ],
        "correct": 0,
        "explanation": "Gulácsy Lajos: A púpos vénkisasszony régi emlékeit meséli Herbertnek, 1911-1912",
        "image_file": "Gulácsy Lajos - A púpos vénkisasszony régi emlékeit meséli herbertnek.jpg",
        "topic": "magyar_festmenyek_uj",
    },
    {
        "question": "Nézd meg ezt a festményt: 'A varázsló kertje' és válaszd ki a festő nevét:",
        "options": [
            "Gulácsy Lajos",
            "Munkácsy Mihály",
            "Csontváry Kosztka Tivadar",
            "Tihanyi Lajos",
        ],
        "correct": 0,
        "explanation": "Gulácsy Lajos: A varázsló kertje, 1906",
        "image_file": "Gulácsy Lajos - A varázsló kertje.jpg",
        "topic": "magyar_festmenyek_uj",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Az ópiumszippó álma' és válaszd ki a festő nevét:",
        "options": [
            "Gulácsy Lajos",
            "Munkácsy Mihály",
            "Csontváry Kosztka Tivadar",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Gulácsy Lajos: Az ópiumszippó álma",
        "image_file": "Gulácsy Lajos - Az ópiumszívó álma.jpg",
        "topic": "magyar_festmenyek_uj",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Dal a rózsáról' és válaszd ki a festő nevét:",
        "options": [
            "Gulácsy Lajos",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Aba-Novák Vilmos",
        ],
        "correct": 0,
        "explanation": "Gulácsy Lajos: Dal a rózsáról, 1904",
        "image_file": "Gulácsy Lajos - Dal a rózsáról.jpg",
        "topic": "magyar_festmenyek_uj",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Karosszékben ülő lány' és válaszd ki a festő nevét:",
        "options": [
            "Gulácsy Lajos",
            "Munkácsy Mihály",
            "Csontváry Kosztka Tivadar",
            "Tihanyi Lajos",
        ],
        "correct": 0,
        "explanation": "Gulácsy Lajos: Karosszékben ülő lány",
        "image_file": "Gulácsy Lajos - Karosszékben ülő lány.jpg",
        "topic": "magyar_festmenyek_uj",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Olasz kikötő' és válaszd ki a festő nevét:",
        "options": [
            "Aba-Novák Vilmos",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Aba-Novák Vilmos: Olasz kikötő",
        "image_file": "Aba-Novák Vilmos - Olasz kikötő.jpg",
        "topic": "magyar_festmenyek_uj",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Önarckép' és válaszd ki a festő nevét:",
        "options": [
            "Aba-Novák Vilmos",
            "Munkácsy Mihály",
            "Csontváry Kosztka Tivadar",
            "Gulácsy Lajos",
        ],
        "correct": 0,
        "explanation": "Aba-Novák Vilmos: Önarckép",
        "image_file": "Aba-Novák Vilmos - Önarckép.jpg",
        "topic": "magyar_festmenyek_uj",
    },
]

# Export alias for compatibility
QUESTIONS = MAGYAR_FESTMENYEK_UJ_QUESTIONS
