# Magyar festmények kérdések - 58 valódi képpel
# Generated on: 2025-09-20 20:00:00

MAGYAR_FESTMENYEK_QUESTIONS = [
    {
        "question": "Nézd meg ezt a festményt: 'Szerelmesek találkozása' és válaszd ki a festő nevét:",
        "options": [
            "Csontváry Kosztka Tivadar",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Csontváry Kosztka Tivadar: Szerelmesek találkozása, 1902 körül",
        "image_file": "2. Csontváry - Szerelmesek találkozása.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Traui látkép naplemente idején' és válaszd ki a festő nevét:",
        "options": [
            "Csontváry Kosztka Tivadar",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Gulácsy Lajos",
        ],
        "correct": 0,
        "explanation": "Csontváry Kosztka Tivadar: Traui látkép naplemente idején, 1899",
        "image_file": "3. Csontváry_-_Traui_látkép_naplemente_idején.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Hídon átvonuló társaság' és válaszd ki a festő nevét:",
        "options": [
            "Csontváry Kosztka Tivadar",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Gulácsy Lajos",
        ],
        "correct": 0,
        "explanation": "Csontváry Kosztka Tivadar: Hídon átvonuló társaság, 1903-1905",
        "image_file": "Csontváry - Hídon átvonuló társaság.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Olasz halász' és válaszd ki a festő nevét:",
        "options": [
            "Csontváry Kosztka Tivadar",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Csontváry Kosztka Tivadar: Olasz halász, 1901 körül",
        "image_file": "Csontváry - Olasz halász.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Önarckép' és válaszd ki a festő nevét:",
        "options": [
            "Csontváry Kosztka Tivadar",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Aba-Novák Vilmos",
        ],
        "correct": 0,
        "explanation": "Csontváry Kosztka Tivadar: Önarckép, 1896-1902",
        "image_file": "Csontváry - Önarckép.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'A baba látogatói' és válaszd ki a festő nevét:",
        "options": [
            "Munkácsy Mihály",
            "Csontváry Kosztka Tivadar",
            "Tihanyi Lajos",
            "Gulácsy Lajos",
        ],
        "correct": 0,
        "explanation": "Munkácsy Mihály: A baba látogatói, 1879 - 160 millió forint",
        "image_file": "Munkácsy - A baba látogatói.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Alvó nagyapó' és válaszd ki a festő nevét:",
        "options": [
            "Munkácsy Mihály",
            "Csontváry Kosztka Tivadar",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Munkácsy Mihály: Alvó nagyapó, 1887 - 180 millió forint",
        "image_file": "Munkácsy - Alvó nagyapó.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Poros út' és válaszd ki a festő nevét:",
        "options": [
            "Munkácsy Mihály",
            "Csontváry Kosztka Tivadar",
            "Tihanyi Lajos",
            "Aba-Novák Vilmos",
        ],
        "correct": 0,
        "explanation": "Munkácsy Mihály: Poros út I., 1874 - 220 millió forint",
        "image_file": "Munkácsy- Poros út.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'A Pont Saint-Michel Párizsban' és válaszd ki a festő nevét:",
        "options": [
            "Tihanyi Lajos",
            "Munkácsy Mihály",
            "Csontváry Kosztka Tivadar",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Tihanyi Lajos: A Pont Saint-Michel Párizsban, 1908 - 220 millió forint",
        "image_file": "Tihanyi Lajos - A_Pont Saint-Michel Párizsban_(1908).jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Önarckép' és válaszd ki a festő nevét:",
        "options": [
            "Tihanyi Lajos",
            "Munkácsy Mihály",
            "Csontváry Kosztka Tivadar",
            "Aba-Novák Vilmos",
        ],
        "correct": 0,
        "explanation": "Tihanyi Lajos: Önarckép",
        "image_file": "Tihanyi Lajos - Önarckép.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Lámpagyújtó' és válaszd ki a festő nevét:",
        "options": [
            "Bortnyik Sándor",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Aba-Novák Vilmos",
        ],
        "correct": 0,
        "explanation": "Bortnyik Sándor: Lámpagyújtó, 1921 - 170 millió forint",
        "image_file": "Bortnyik Sándor - Lámpagyújtó.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Géplovag' és válaszd ki a festő nevét:",
        "options": [
            "Bortnyik Sándor",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Aba-Novák Vilmos",
        ],
        "correct": 0,
        "explanation": "Bortnyik Sándor: Géplovag",
        "image_file": "Bortnyik Sándor - Géplovag.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Zöld szamár' és válaszd ki a festő nevét:",
        "options": [
            "Bortnyik Sándor",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Aba-Novák Vilmos",
        ],
        "correct": 0,
        "explanation": "Bortnyik Sándor: Zöld szamár",
        "image_file": "Bortnyik Sándor - Zöld szamár.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'A púpos vénkisasszony régi emlékeit meséli Herbertnek' és válaszd ki a festő nevét:",
        "options": [
            "Gulácsy Lajos",
            "Munkácsy Mihály",
            "Csontváry Kosztka Tivadar",
            "Aba-Novák Vilmos",
        ],
        "correct": 0,
        "explanation": "Gulácsy Lajos: A púpos vénkisasszony régi emlékeit meséli Herbertnek, 1911-1912",
        "image_file": "Gulácsy Lajos - A púpos vénkisasszony régi emlékeit meséli herbertnek.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'A varázsló kertje' és válaszd ki a festő nevét:",
        "options": [
            "Gulácsy Lajos",
            "Munkácsy Mihály",
            "Csontváry Kosztka Tivadar",
            "Tihanyi Lajos",
        ],
        "correct": 0,
        "explanation": "Gulácsy Lajos: A varázsló kertje, 1906",
        "image_file": "Gulácsy Lajos - A varázsló kertje.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Az ópiumszívó álma' és válaszd ki a festő nevét:",
        "options": [
            "Gulácsy Lajos",
            "Munkácsy Mihály",
            "Csontváry Kosztka Tivadar",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Gulácsy Lajos: Az ópiumszívó álma",
        "image_file": "Gulácsy Lajos - Az ópiumszívó álma.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Dal a rózsáról' és válaszd ki a festő nevét:",
        "options": [
            "Gulácsy Lajos",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Aba-Novák Vilmos",
        ],
        "correct": 0,
        "explanation": "Gulácsy Lajos: Dal a rózsáról, 1904",
        "image_file": "Gulácsy Lajos - Dal a rózsáról.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Karosszékben ülő lány' és válaszd ki a festő nevét:",
        "options": [
            "Gulácsy Lajos",
            "Munkácsy Mihály",
            "Csontváry Kosztka Tivadar",
            "Tihanyi Lajos",
        ],
        "correct": 0,
        "explanation": "Gulácsy Lajos: Karosszékben ülő lány",
        "image_file": "Gulácsy Lajos - Karosszékben ülő lány.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Olasz kikötő' és válaszd ki a festő nevét:",
        "options": [
            "Aba-Novák Vilmos",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Aba-Novák Vilmos: Olasz kikötő",
        "image_file": "Aba-Novák Vilmos - Olasz kikötő.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Önarckép' és válaszd ki a festő nevét:",
        "options": [
            "Aba-Novák Vilmos",
            "Munkácsy Mihály",
            "Csontváry Kosztka Tivadar",
            "Gulácsy Lajos",
        ],
        "correct": 0,
        "explanation": "Aba-Novák Vilmos: Önarckép",
        "image_file": "Aba-Novák Vilmos - Önarckép.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Nagy vursli' és válaszd ki a festő nevét:",
        "options": [
            "Aba-Novák Vilmos",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Aba-Novák Vilmos: Nagy vursli",
        "image_file": "Aba-Novák Vilmos - Nagy vursli.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Állvány ablak előtt' és válaszd ki a festő nevét:",
        "options": [
            "Barcsay Jenő",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Barcsay Jenő: Állvány ablak előtt",
        "image_file": "Barcsay Jenő - Állvány ablak előtt.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Éjjeli mulató' és válaszd ki a festő nevét:",
        "options": [
            "Batthyány Gyula",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Batthyány Gyula: Éjjeli mulató",
        "image_file": "Batthyány Gyula - Éjjeli mulató.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Lóverseny' és válaszd ki a festő nevét:",
        "options": [
            "Batthyány Gyula",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Batthyány Gyula: Lóverseny",
        "image_file": "Batthyány Gyula - Lóverseny.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Angyalföld' és válaszd ki a festő nevét:",
        "options": [
            "Csernus Tibor",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Csernus Tibor: Angyalföld",
        "image_file": "Csernus Tibor - Angyalföld.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Saint Tropez' és válaszd ki a festő nevét:",
        "options": [
            "Csernus Tibor",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Csernus Tibor: Saint Tropez",
        "image_file": "Csernus Tibor - Saint Tropez.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Szénagyűjtők' és válaszd ki a festő nevét:",
        "options": [
            "Csók István",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Csók István: Szénagyűjtők",
        "image_file": "Csók István - Szénagyűjtők.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'A bergeni lelkész' és válaszd ki a festő nevét:",
        "options": [
            "Czóbel Béla",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Czóbel Béla: A bergeni lelkész",
        "image_file": "Czóbel Béla - A bergeni lelkész.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Halálus' és válaszd ki a festő nevét:",
        "options": [
            "Derkovits Gyula",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Derkovits Gyula: Halálus",
        "image_file": "Derkovits Gyula - Halálus.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Hálóvető' és válaszd ki a festő nevét:",
        "options": [
            "Egry József",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Egry József: Hálóvető",
        "image_file": "Egry József - Hálóvető.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Plakátumok előtt' és válaszd ki a festő nevét:",
        "options": [
            "Ferenczy Károly",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Ferenczy Károly: Plakátumok előtt",
        "image_file": "Ferenczy Károly - Plakátumok előtt.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Amszterdam' és válaszd ki a festő nevét:",
        "options": [
            "Galimberti Sándor",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Galimberti Sándor: Amszterdam",
        "image_file": "Galimberti Sándor - Amszterdam.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Nagybányai táj II.' és válaszd ki a festő nevét:",
        "options": [
            "Iványi Grünwald Béla",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Iványi Grünwald Béla: Nagybányai táj II.",
        "image_file": "Iványi Grünwald Béla - Nagybányai táj II..jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Udvarlás' és válaszd ki a festő nevét:",
        "options": [
            "Kádár Béla",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Kádár Béla: Udvarlás",
        "image_file": "Kádár Béla - Udvarlás.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Színes leányfej' és válaszd ki a festő nevét:",
        "options": [
            "Kernstok Károly",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Kernstok Károly: Színes leányfej",
        "image_file": "Kernstok Károly - Színes leányfej.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Pléh Krisztus' és válaszd ki a festő nevét:",
        "options": [
            "Kondor Béla",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Kondor Béla: Pléh Krisztus",
        "image_file": "Kondor Béla - Pléh Krisztus.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Mezei Vénusz' és válaszd ki a festő nevét:",
        "options": [
            "Korniss Dezső",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Korniss Dezső: Mezei Vénusz",
        "image_file": "Korniss Dezső - Mezei Vénusz.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Tücsköklakodalom' és válaszd ki a festő nevét:",
        "options": [
            "Korniss Dezső",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Korniss Dezső: Tücsköklakodalom",
        "image_file": "Korniss Dezső - Tücsköklakodalom.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Fürdő után' és válaszd ki a festő nevét:",
        "options": [
            "Lotz Károly",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Lotz Károly: Fürdő után",
        "image_file": "Lotz Károly - Fürdő után.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Fekvő akt' és válaszd ki a festő nevét:",
        "options": [
            "Márffy Ödön",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Márffy Ödön: Fekvő akt",
        "image_file": "Márffy Ödön - Fekvő akt.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Ágyút húzó katonák a hegyek között' és válaszd ki a festő nevét:",
        "options": [
            "Mednyánszky László",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Mednyánszky László: Ágyút húzó katonák a hegyek között",
        "image_file": "Mednyánszky László - Ágyút húzó katonák a hegyek között.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Olvadás' és válaszd ki a festő nevét:",
        "options": [
            "Mednyánszky László",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Mednyánszky László: Olvadás",
        "image_file": "Mednyánszky László - Olvadás.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Lidó' és válaszd ki a festő nevét:",
        "options": [
            "Mészőly Géza",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Mészőly Géza: Lidó",
        "image_file": "Mészőly Géza - Lidó.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Cipők' és válaszd ki a festő nevét:",
        "options": [
            "Ország Lili",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Ország Lili: Cipők",
        "image_file": "Ország Lili - Cipők.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Élet' és válaszd ki a festő nevét:",
        "options": [
            "Paizs Goebel Jenő",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Paizs Goebel Jenő: Élet",
        "image_file": "Paizs Goebel Jenő - Élet.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Verőfényes udvar Nagybányán' és válaszd ki a festő nevét:",
        "options": [
            "Perlrott-Csaba Vilmos",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Perlrott-Csaba Vilmos: Verőfényes udvar Nagybányán",
        "image_file": "Perlrott-Csaba Vilmos - Verőfényes udvar Nagybányán.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Lajos és Ödön' és válaszd ki a festő nevét:",
        "options": [
            "Rippl-Rónai József",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Rippl-Rónai József: Lajos és Ödön",
        "image_file": "Rippl-Rónai József - Lajos és Ödön.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Párizsi enteriőr' és válaszd ki a festő nevét:",
        "options": [
            "Rippl-Rónai József",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Rippl-Rónai József: Párizsi enteriőr",
        "image_file": "Rippl-Rónai József - Párizsi enteriőr.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Négy részes cirkusz' és válaszd ki a festő nevét:",
        "options": [
            "Scheiber Hugó",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Scheiber Hugó: Négy részes cirkusz",
        "image_file": "Scheiber Hugó - Négy részes cirkusz.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Villamoson' és válaszd ki a festő nevét:",
        "options": [
            "Scheiber Hugó",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Scheiber Hugó: Villamoson",
        "image_file": "Scheiber Hugó - Villamoson.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Ketten' és válaszd ki a festő nevét:",
        "options": [
            "Schönberger Armanf",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Schönberger Armanf: Ketten",
        "image_file": "Schönberger Armanf - Ketten.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Japán nő' és válaszd ki a festő nevét:",
        "options": [
            "Székely Bertalan",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Székely Bertalan: Japán nő",
        "image_file": "Székely Bertalan - Japán nő.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Léghajó' és válaszd ki a festő nevét:",
        "options": [
            "Szinyei Merse Pál",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Szinyei Merse Pál: Léghajó",
        "image_file": "Szinyei Merse Pál - Léghajó.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Majális' és válaszd ki a festő nevét:",
        "options": [
            "Szinyei-Merse Pál",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Szinyei-Merse Pál: Majális",
        "image_file": "Szinyei-Merse Pál - Majális.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Férfi portré' és válaszd ki a festő nevét:",
        "options": [
            "Szobotka Imre",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Szobotka Imre: Férfi portré",
        "image_file": "Szobotka Imre - Férfi portré.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Harc' és válaszd ki a festő nevét:",
        "options": [
            "Uitz Béla",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Uitz Béla: Harc",
        "image_file": "Uitz Béla - Harc.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Felmutató Ikonos Önarckép' és válaszd ki a festő nevét:",
        "options": [
            "Vajda Lajos",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Vajda Lajos: Felmutató Ikonos Önarckép",
        "image_file": "Vajda Lajos - Felmutató Ikonos Önarckép.jpg",
        "topic": "magyar_festmenyek",
    },
    {
        "question": "Nézd meg ezt a festményt: 'Morfinista' és válaszd ki a festő nevét:",
        "options": [
            "Vaszary János",
            "Munkácsy Mihály",
            "Tihanyi Lajos",
            "Bortnyik Sándor",
        ],
        "correct": 0,
        "explanation": "Vaszary János: Morfinista",
        "image_file": "Vaszary János - Morfinista.jpg",
        "topic": "magyar_festmenyek",
    },
]

# Export alias for compatibility
QUESTIONS = MAGYAR_FESTMENYEK_QUESTIONS