# Auto-generated questions file
# Generated on: 2025-08-25 16:39:59

MAGYAR_ZENEKAROK_QUESTIONS_UJ = [
    {
        "question": "Ki az előadó?",
        "options": [
            "Alvin és a Mókusok",
            "Hétköznapi Csalódások",
            "Tudósok",
            "Tankcsapda",
        ],
        "correct": 0,
        "explanation": "Alvin és a Mókusok magyar punk zenekar",
        "audio_file": "41_Alvin_és_a_Mókusok.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Hétköznapi Csalódások",
            "Alvin és a Mókusok",
            "Tudósok",
            "Tankcsapda",
        ],
        "correct": 0,
        "explanation": "Hétköznapi Csalódások magyar punk zenekar",
        "audio_file": "55_Hétköznapi_Csalódások.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Tudósok",
            "Alvin és a Mókusok",
            "Hétköznapi Csalódások",
            "Tankcsapda",
        ],
        "correct": 0,
        "explanation": "Tudósok magyar punk zenekar",
        "audio_file": "31_Tudósok.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Tankcsapda",
            "Pokolgép",
            "Ossian",
            "Dalriada",
        ],
        "correct": 0,
        "explanation": "Tankcsapda magyar metal zenekar",
        "audio_file": "54_Tankcsapda.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Pokolgép",
            "Tankcsapda",
            "Ossian",
            "Dalriada",
        ],
        "correct": 0,
        "explanation": "Pokolgép magyar metal zenekar",
        "audio_file": "37_Pokolgép.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Ossian",
            "Tankcsapda",
            "Pokolgép",
            "Dalriada",
        ],
        "correct": 0,
        "explanation": "Ossian magyar metal zenekar",
        "audio_file": "60_Ossian.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Magashegyi Underground",
            "Blahalouisiana",
            "Biorobot",
            "PBox",
        ],
        "correct": 0,
        "explanation": "Magashegyi Underground magyar alternatív zenekar",
        "audio_file": "61_Magashegyi_Underground.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Biorobot",
            "Hiperkarma",
            "Supernem",
            "Carson Coma",
        ],
        "correct": 0,
        "explanation": "Biorobot magyar metal zenekar",
        "audio_file": "58_Biorobot.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Blahalouisiana",
            "Honeybeast",
            "Odett",
            "Magashegyi Underground",
        ],
        "correct": 0,
        "explanation": "Blahalouisiana magyar metal zenekar",
        "audio_file": "57_Blahalouisiana.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "PBox",
            "Dalriada",
            "Thy Catafalque",
            "Sear Bliss",
        ],
        "correct": 0,
        "explanation": "PBox magyar metal zenekar",
        "audio_file": "49_PBox.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Republic",
            "Bon-Bon",
            "Neoton Família",
            "Omega",
        ],
        "correct": 0,
        "explanation": "Republic magyar mainstream zenekar",
        "audio_file": "44_Republic.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Bon-Bon",
            "Republic",
            "Neoton Família",
            "Omega",
        ],
        "correct": 0,
        "explanation": "Bon-Bon magyar mainstream zenekar",
        "audio_file": "53_Bon-Bon.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Neoton Família",
            "Republic",
            "Bon-Bon",
            "Omega",
        ],
        "correct": 0,
        "explanation": "Neoton Família magyar mainstream zenekar",
        "audio_file": "36_Neoton_Família.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Omega",
            "Republic",
            "Bon-Bon",
            "Neoton Família",
        ],
        "correct": 0,
        "explanation": "Omega magyar mainstream zenekar",
        "audio_file": "34_Omega.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Illés",
            "LGT",
            "Piramis",
            "Korai Öröm",
        ],
        "correct": 0,
        "explanation": "Illés magyar mainstream zenekar",
        "audio_file": "32_Illés.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "LGT",
            "Illés",
            "Piramis",
            "Korai Öröm",
        ],
        "correct": 0,
        "explanation": "LGT magyar mainstream zenekar",
        "audio_file": "59_LGT.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Piramis",
            "Illés",
            "LGT",
            "Korai Öröm",
        ],
        "correct": 0,
        "explanation": "Piramis magyar mainstream zenekar",
        "audio_file": "45_Piramis.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Korai Öröm",
            "Illés",
            "LGT",
            "Piramis",
        ],
        "correct": 0,
        "explanation": "Korai Öröm magyar mainstream zenekar",
        "audio_file": "39_Korai_Öröm.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "P. Mobil",
            "Bonanza Banzai",
            "Republic",
            "Omega",
        ],
        "correct": 0,
        "explanation": "P. Mobil magyar mainstream zenekar",
        "audio_file": "47_P_Mobil.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Bonanza Banzai",
            "P. Mobil",
            "Republic",
            "Omega",
        ],
        "correct": 0,
        "explanation": "Bonanza Banzai magyar mainstream zenekar",
        "audio_file": "24_Bonanza_Banzai.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Caramel",
            "Bon-Bon",
            "Republic",
            "Omega",
        ],
        "correct": 0,
        "explanation": "Caramel magyar trash-mainstream zenekar",
        "audio_file": "48_Caramel.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "A Maci",
            "Moriones",
            "Manuel",
            "Desh",
        ],
        "correct": 0,
        "explanation": "A Maci magyar hip-hop előadó",
        "audio_file": "28_A_Maci.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Moriones",
            "A Maci",
            "Manuel",
            "Desh",
        ],
        "correct": 0,
        "explanation": "Moriones magyar hip-hop előadó",
        "audio_file": "43_Moriones.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Manuel",
            "A Maci",
            "Moriones",
            "Desh",
        ],
        "correct": 0,
        "explanation": "Manuel magyar hip-hop előadó",
        "audio_file": "27_Manuel.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Desh",
            "Betonhofi",
            "T.Danny",
            "K.Kevin",
        ],
        "correct": 0,
        "explanation": "Desh magyar hip-hop előadó",
        "audio_file": "33_Desh.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Betonhofi",
            "Desh",
            "T.Danny",
            "K.Kevin",
        ],
        "correct": 0,
        "explanation": "Betonhofi magyar hip-hop előadó",
        "audio_file": "25_Betonhofi.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "T.Danny",
            "Desh",
            "Betonhofi",
            "K.Kevin",
        ],
        "correct": 0,
        "explanation": "T.Danny magyar hip-hop előadó",
        "audio_file": "42_T_Danny.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "K.Kevin",
            "Desh",
            "Betonhofi",
            "T.Danny",
        ],
        "correct": 0,
        "explanation": "K.Kevin magyar hip-hop előadó",
        "audio_file": "26_K_Kevin.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Dzsúdló",
            "Azariah",
            "Alee",
            "Krúbi",
        ],
        "correct": 0,
        "explanation": "Dzsúdló magyar hip-hop előadó",
        "audio_file": "30_Dzsúdló.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Azariah",
            "Dzsúdló",
            "Alee",
            "Krúbi",
        ],
        "correct": 0,
        "explanation": "Azariah magyar hip-hop előadó",
        "audio_file": "35_Azariah.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Alee",
            "Dzsúdló",
            "Azariah",
            "Krúbi",
        ],
        "correct": 0,
        "explanation": "Alee magyar hip-hop előadó",
        "audio_file": "40_Alee.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Krúbi",
            "Dzsúdló",
            "Azariah",
            "Alee",
        ],
        "correct": 0,
        "explanation": "Krúbi magyar hip-hop előadó",
        "audio_file": "52_Krúbi.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Carson Coma",
            "A Maci",
            "Ómen",
            "Sing Sing",
        ],
        "correct": 0,
        "explanation": "Carson Coma magyar hip-hop előadó",
        "audio_file": "23_Carson_Coma.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Ómen",
            "Sing Sing",
            "Leander Kills",
            "Ossian",
        ],
        "correct": 0,
        "explanation": "Ómen magyar zenekar",
        "audio_file": "62_Ómen.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Sing Sing",
            "Ómen",
            "Leander Kills",
            "Ossian",
        ],
        "correct": 0,
        "explanation": "Sing Sing magyar zenekar",
        "audio_file": "50_Sing_Sing.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Leander Kills",
            "Ómen",
            "Sing Sing",
            "Ossian",
        ],
        "correct": 0,
        "explanation": "Leander Kills magyar zenekar",
        "audio_file": "51_Leander_Kills.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Ossian",
            "Ómen",
            "Sing Sing",
            "Leander Kills",
        ],
        "correct": 0,
        "explanation": "Ossian magyar zenekar",
        "audio_file": "46_Ossián.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Zana Zoltán",
            "Széki Attila",
            "Wolf Kati",
            "Republic",
        ],
        "correct": 0,
        "explanation": "Zana Zoltán magyar előadó",
        "audio_file": "22_Zana_Zoltán.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Széki Attila",
            "Zana Zoltán",
            "Wolf Kati",
            "Republic",
        ],
        "correct": 0,
        "explanation": "Széki Attila magyar előadó",
        "audio_file": "38_Széki_Attila.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Wolf Kati",
            "Zana Zoltán",
            "Széki Attila",
            "Republic",
        ],
        "correct": 0,
        "explanation": "Wolf Kati magyar előadó",
        "audio_file": "29_Wolf_Kati.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Intim Torna Illegál",
            "Magashegyi Underground",
            "Blahalouisiana",
            "Biorobot",
        ],
        "correct": 0,
        "explanation": "Intim Torna Illegál magyar alternatív zenekar",
        "audio_file": "63_Intim_Torna_Illegal.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Kistehén",
            "Intim Torna Illegál",
            "Tudósok",
            "dr BRS",
        ],
        "correct": 0,
        "explanation": "Kistehén magyar alternatív zenekar",
        "audio_file": "64_Kistehen.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Kistehén",
            "Intim Torna Illegál",
            "Kollár Klemencz László",
            "Kardos Horváth János",
        ],
        "correct": 2,
        "explanation": "Kollár Klemencz László magyar előadó",
        "audio_file": "65_Kollar_Klemencz_Laszlo.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Honeybeast",
            "Blahalouisiana",
            "Margaret Island",
            "Paulina",
        ],
        "correct": 0,
        "explanation": "Honeybeast magyar zenekar",
        "audio_file": "66_Honeybeast.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Kaukázus",
            "Honeybeast",
            "Kollár Klemencz László",
            "Kistehén",
        ],
        "correct": 0,
        "explanation": "Kaukázus magyar zenekar",
        "audio_file": "67_Kaukazus.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "30Y",
            "Kaukázus",
            "Honeybeast",
            "Kollár Klemencz László",
        ],
        "correct": 0,
        "explanation": "30Y magyar zenekar",
        "audio_file": "68_30Y.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Máté Péter",
            "30Y",
            "Kaukázus",
            "Honeybeast",
        ],
        "correct": 0,
        "explanation": "Máté Péter magyar énekes",
        "audio_file": "69_Mate_Peter.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Aradszky László",
            "Máté Péter",
            "30Y",
            "Kaukázus",
        ],
        "correct": 0,
        "explanation": "Aradszky László magyar énekes",
        "audio_file": "70_Aradszky_Laszlo.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Follow the flow",
            "4Street",
            "Bagossy Brothers",
            "Lóci játszik",
        ],
        "correct": 0,
        "explanation": "Follow the flow magyar zenekar",
        "audio_file": "00_Follow_the_flow.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "4Street",
            "Follow the flow",
            "Bagossy Brothers",
            "Csaknekedkislány",
        ],
        "correct": 0,
        "explanation": "4Street magyar zenekar",
        "audio_file": "01_4Street.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Bagossy Brothers",
            "4Street",
            "Follow the flow",
            "Csaknekedkislány",
        ],
        "correct": 0,
        "explanation": "Bagossy Brothers magyar zenekar",
        "audio_file": "02_Bagossy_Brothers.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Csaknekedkislány",
            "Bagossy Brothers",
            "4Street",
            "Follow the flow",
        ],
        "correct": 0,
        "explanation": "Csaknekedkislány magyar zenekar",
        "audio_file": "03_Csaknekedkislány.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Lóci játszik",
            "Csaknekedkislány",
            "Bagossy Brothers",
            "4Street",
        ],
        "correct": 0,
        "explanation": "Lóci játszik magyar zenekar",
        "audio_file": "04_Lóci_játszik.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Galaxisok",
            "Lóci játszik",
            "Csaknekedkislány",
            "Bagossy Brothers",
        ],
        "correct": 0,
        "explanation": "Galaxisok magyar zenekar",
        "audio_file": "05_Galaxisok.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Parno Graszt",
            "Galaxisok",
            "Lóci játszik",
            "Csaknekedkislány",
        ],
        "correct": 0,
        "explanation": "Parno Graszt magyar zenekar",
        "audio_file": "06_Parno_Graszt.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Palya Bea",
            "Parno Graszt",
            "Galaxisok",
            "Lóci játszik",
        ],
        "correct": 0,
        "explanation": "Palya Bea magyar énekesnő",
        "audio_file": "07_Palya_Bea.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Bohemian Betyars",
            "Palya Bea",
            "Parno Graszt",
            "Galaxisok",
        ],
        "correct": 0,
        "explanation": "Bohemian Betyars magyar zenekar",
        "audio_file": "08_Bohemian_Betyars.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Aurevoir",
            "Bohemian Betyars",
            "Palya Bea",
            "Parno Graszt",
        ],
        "correct": 0,
        "explanation": "Aurevoir magyar zenekar",
        "audio_file": "09_Aurevoir.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Dánielffy",
            "Aurevoir",
            "Bohemian Betyars",
            "Palya Bea",
        ],
        "correct": 0,
        "explanation": "Dánielffy magyar zenekar",
        "audio_file": "10_Dánielffy.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Ham Ko Ham",
            "Dánielffy",
            "Aurevoir",
            "Bohemian Betyars",
        ],
        "correct": 0,
        "explanation": "Ham Ko Ham magyar zenekar",
        "audio_file": "11_Ham_Ko_Ham.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Carbonfools",
            "Ham Ko Ham",
            "Dánielffy",
            "Aurevoir",
        ],
        "correct": 0,
        "explanation": "Carbonfools magyar zenekar",
        "audio_file": "12_Carbonfools.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Zagar",
            "Carbonfools",
            "Ham Ko Ham",
            "Dánielffy",
        ],
        "correct": 0,
        "explanation": "Zagar magyar zenekar",
        "audio_file": "13_Zagar.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Neo",
            "Zagar",
            "Carbonfools",
            "Ham Ko Ham",
        ],
        "correct": 0,
        "explanation": "Neo magyar zenekar",
        "audio_file": "14_Neo.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Soulwave",
            "Neo",
            "Zagar",
            "Carbonfools",
        ],
        "correct": 0,
        "explanation": "Soulwave magyar zenekar",
        "audio_file": "15_Soulwave.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Quimby",
            "Soulwave",
            "Neo",
            "Zagar",
        ],
        "correct": 0,
        "explanation": "Quimby magyar zenekar",
        "audio_file": "16_Quimby.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "P. Mobil",
            "Quimby",
            "Soulwave",
            "Neo",
        ],
        "correct": 0,
        "explanation": "P. Mobil magyar zenekar",
        "audio_file": "18_P._Mobil.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Republic",
            "P. Mobil",
            "Quimby",
            "Soulwave",
        ],
        "correct": 0,
        "explanation": "Republic magyar zenekar",
        "audio_file": "19_Republic.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Korai Öröm",
            "Republic",
            "P. Mobil",
            "Quimby",
        ],
        "correct": 0,
        "explanation": "Korai Öröm magyar zenekar",
        "audio_file": "21_Korai_Öröm.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Bagossy Brothers Company",
            "Bagossy Brothers",
            "Republic",
            "Korai Öröm",
        ],
        "correct": 0,
        "explanation": "Bagossy Brothers Company magyar zenekar",
        "audio_file": "71_Bagossy_Brothers_Company.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Neoton Família",
            "Bagossy Brothers Company",
            "Bagossy Brothers",
            "Republic",
        ],
        "correct": 0,
        "explanation": "Neoton Família magyar zenekar",
        "audio_file": "72_Neoton_Família.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Follow the Flow",
            "Neoton Família",
            "Bagossy Brothers Company",
            "Bagossy Brothers",
        ],
        "correct": 0,
        "explanation": "Follow the Flow magyar zenekar",
        "audio_file": "73_Follow_the_flow.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "4Street",
            "Follow the Flow",
            "Neoton Família",
            "Bagossy Brothers Company",
        ],
        "correct": 0,
        "explanation": "4Street magyar zenekar",
        "audio_file": "74_4Street.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Bagossy Brothers",
            "4Street",
            "Follow the Flow",
            "Neoton Família",
        ],
        "correct": 0,
        "explanation": "Bagossy Brothers magyar zenekar",
        "audio_file": "75_Bagossy_Brothers.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Csaknekedkislány",
            "Bagossy Brothers",
            "4Street",
            "Follow the Flow",
        ],
        "correct": 0,
        "explanation": "Csaknekedkislány magyar zenekar",
        "audio_file": "76_Csaknekedkislány.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Lóci játszik",
            "Csaknekedkislány",
            "Bagossy Brothers",
            "4Street",
        ],
        "correct": 0,
        "explanation": "Lóci játszik magyar zenekar",
        "audio_file": "77_Lóci_játszik.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Galaxisok",
            "Lóci játszik",
            "Csaknekedkislány",
            "Bagossy Brothers",
        ],
        "correct": 0,
        "explanation": "Galaxisok magyar zenekar",
        "audio_file": "78_Galaxisok.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Parno Graszt",
            "Galaxisok",
            "Lóci játszik",
            "Csaknekedkislány",
        ],
        "correct": 0,
        "explanation": "Parno Graszt magyar zenekar",
        "audio_file": "79_Parno_Graszt.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Palya Bea",
            "Parno Graszt",
            "Galaxisok",
            "Lóci játszik",
        ],
        "correct": 0,
        "explanation": "Palya Bea magyar zenekar",
        "audio_file": "80_Palya_Bea.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Bohemian Betyars",
            "Palya Bea",
            "Parno Graszt",
            "Galaxisok",
        ],
        "correct": 0,
        "explanation": "Bohemian Betyars magyar zenekar",
        "audio_file": "81_Bohemian_Betyars.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Aurevoir",
            "Bohemian Betyars",
            "Palya Bea",
            "Parno Graszt",
        ],
        "correct": 0,
        "explanation": "Aurevoir magyar zenekar",
        "audio_file": "82_Aurevoir.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Dánielffy",
            "Aurevoir",
            "Bohemian Betyars",
            "Palya Bea",
        ],
        "correct": 0,
        "explanation": "Dánielffy magyar zenekar",
        "audio_file": "83_Dánielffy.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Ham Ko Ham",
            "Dánielffy",
            "Aurevoir",
            "Bohemian Betyars",
        ],
        "correct": 0,
        "explanation": "Ham Ko Ham magyar zenekar",
        "audio_file": "84_Ham_Ko_Ham.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Carbonfools",
            "Ham Ko Ham",
            "Dánielffy",
            "Aurevoir",
        ],
        "correct": 0,
        "explanation": "Carbonfools magyar zenekar",
        "audio_file": "85_Carbonfools.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Zagar",
            "Carbonfools",
            "Ham Ko Ham",
            "Dánielffy",
        ],
        "correct": 0,
        "explanation": "Zagar magyar zenekar",
        "audio_file": "86_Zagar.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Neo",
            "Zagar",
            "Carbonfools",
            "Ham Ko Ham",
        ],
        "correct": 0,
        "explanation": "Neo magyar zenekar",
        "audio_file": "87_Neo.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Soulwave",
            "Neo",
            "Zagar",
            "Carbonfools",
        ],
        "correct": 0,
        "explanation": "Soulwave magyar zenekar",
        "audio_file": "88_Soulwave.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Quimby",
            "Soulwave",
            "Neo",
            "Zagar",
        ],
        "correct": 0,
        "explanation": "Quimby magyar zenekar",
        "audio_file": "89_Quimby.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Tankcsapda",
            "Quimby",
            "Soulwave",
            "Neo",
        ],
        "correct": 0,
        "explanation": "Tankcsapda magyar zenekar",
        "audio_file": "90_Tankcsapda.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "P. Mobil",
            "Tankcsapda",
            "Quimby",
            "Soulwave",
        ],
        "correct": 0,
        "explanation": "P. Mobil magyar zenekar",
        "audio_file": "91_P._Mobil.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Republic",
            "P. Mobil",
            "Tankcsapda",
            "Quimby",
        ],
        "correct": 0,
        "explanation": "Republic magyar zenekar",
        "audio_file": "92_Republic.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Bonanza Banzai",
            "Republic",
            "P. Mobil",
            "Tankcsapda",
        ],
        "correct": 0,
        "explanation": "Bonanza Banzai magyar zenekar",
        "audio_file": "93_Bonanza_Banzai.mp3",
        "topic": "magyar_zenekarok_uj",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Korai Öröm",
            "Bonanza Banzai",
            "Republic",
            "P. Mobil",
        ],
        "correct": 0,
        "explanation": "Korai Öröm magyar zenekar",
        "audio_file": "94_Korai_Öröm.mp3",
        "topic": "magyar_zenekarok_uj",
    },

]
