# Auto-generated questions file
# Generated on: 2025-09-19 20:48:12

_DEFAULT_QUESTION = "Ki az előadó?"
_TOPIC = "nemzetkozi_zenekarok"


def _q(audio_file, correct, options, explanation, question=_DEFAULT_QUESTION, **extra):
    """Segédfüggvény: kompakt kérdés létrehozása."""
    return {
        "question": question,
        "options": options,
        "correct": correct,
        "explanation": explanation,
        "audio_file": audio_file,
        "topic": _TOPIC,
        **extra,
    }


QUESTIONS = [
    _q('1_Ariana_Grande.mp3', 3, ['Dua Lipa', 'Taylor Swift', 'Katy Perry', 'Ariana Grande'], 'Ariana Grande - Nemzetközi előadó'),
    _q('2_Sabrina_Carpenter.mp3', 3, ['Dua Lipa', 'Taylor Swift', 'Ariana Grande', 'Sabrina Carpenter'], 'Sabrina Carpenter - Nemzetközi előadó'),
    _q('3_Olivia_Rodrigo.mp3', 0, ['Olivia Rodrigo', 'Mabel', 'Sia', 'Taylor Swift'], 'Ellie Goulding - Nemzetközi előadó'),
    _q('4_Rihanna.mp3', 1, ['Dua Lipa', 'Rihanna', 'Billie Eilish', 'Lady Gaga'], 'Rihanna - Nemzetközi előadó'),
    _q('5_Dua_Lipa.mp3', 0, ['Dua Lipa', 'Taylor Swift', 'Beyonce', 'Anne-Marie'], 'Dua Lipa - Nemzetközi előadó'),
    _q('6_Camilla_Cabello.mp3', 2, ['Lady Gaga', 'Selena Gomez', 'Camilla Cabello', 'Sia'], 'Lilly Allen - Nemzetközi előadó'),
    _q('7_Miley_Cyrus.mp3', 0, ['Miley Cyrus', 'Kylie Minogue', 'Ellie Goulding', 'Sia'], 'Miley Cyrus - Nemzetközi előadó'),
    _q('8_Lady_Gaga.mp3', 1, ['Ariana Grande', 'Lady Gaga', 'Pink', 'Ellie Goulding'], 'Lady Gaga - Nemzetközi előadó'),
    _q('9_Billie_Eilish.mp3', 2, ['Dua Lipa', 'Taylor Swift', 'Billie Eilish', 'Kylie Minogue'], 'Billie Eilish - Nemzetközi előadó'),
    _q('10_Adele.mp3', 0, ['Adele', 'Taylor Swift', 'Camilla Cabello', 'Miley Cyrus'], 'Adele - Nemzetközi előadó'),
    _q('11_Zaz.mp3', 2, ['Mabel', 'Kesha', 'Zaz', 'Selena Gomez'], 'Zaz - Nemzetközi előadó'),
    _q('12_Ellie_Goulding.mp3', 0, ['Ellie Goulding', 'Anne-Marie', 'Kesha', 'Kylie Minogue'], 'Beyonce - Nemzetközi előadó'),
    _q('13_Emelie_Sande.mp3', 3, ['Dua Lipa', 'Miley Cyrus', 'Kylie Minogue', 'Emelie Sande'], 'Emelie Sande - Nemzetközi előadó'),
    _q('14_Katy_Perry.mp3', 0, ['Katy Perry', 'Adele', 'Sia', 'Lana del Rey'], 'Katy Perry - Nemzetközi előadó'),
    _q('15_Lilly_Allen.mp3', 2, ['Dua Lipa', 'Taylor Swift', 'Lilly Allen', 'Anne-Marie'], 'Lilly Allen - Nemzetközi előadó'),
    _q('16_Jessie_J..mp3', 0, ['Jessie J.', 'Zaz', 'Kesha', 'Bebe Rexha'], 'Jessie J. - Nemzetközi előadó'),
    _q('17_Pink.mp3', 3, ['Dua Lipa', 'Kylie Minogue', 'Lady Gaga', 'Pink'], 'Pink - Nemzetközi előadó'),
    _q('18_Sia.mp3', 0, ['Sia', 'Bebe Rexha', 'Taylor Swift', 'Katy Perry'], 'Selena Gomez - Nemzetközi előadó'),
    _q('19_Zara_Larsson.mp3', 3, ['Emelie Sande', 'Billie Eilish', 'Taylor Swift', 'Zara Larsson'], 'Zara Larsson - Nemzetközi előadó'),
    _q('20_Beyonce.mp3', 0, ['Beyonce', 'Billie Eilish', 'Rihanna', 'Zaz'], 'Beyonce - Nemzetközi előadó'),
    _q('21_Norah_Jones.mp3', 2, ['Dua Lipa', 'Miley Cyrus', 'Norah Jones', 'Taylor Swift'], 'Norah Jones - Nemzetközi előadó'),
    _q('22_Janis_Joplin.mp3', 2, ['Christina Aguilera', 'Anne-Marie', 'Janis Joplin', 'Alanis Morissette'], 'Janis Joplin - Nemzetközi előadó'),
    _q('23_Anne-Marie.mp3', 2, ['Dua Lipa', 'Taylor Swift', 'Anne-Marie', 'Billie Eilish'], 'Anne-Marie - Nemzetközi előadó'),
    _q('24_Bebe_Rexha.mp3', 1, ['Dua Lipa', 'Bebe Rexha', 'Kesha', 'Taylor Swift'], 'Bebe Rexha - Nemzetközi előadó'),
    _q('25_Taylor_Swift.mp3', 2, ['Katy Perry', 'Meghan Trainor', 'Taylor Swift', 'Lana del Rey'], 'Taylor Swift - Nemzetközi előadó'),
    _q('26_Selena_Gomez.mp3', 1, ['Kylie Minogue', 'Selena Gomez', 'Ariana Grande', 'Taylor Swift'], 'Nelly Furtado - Nemzetközi előadó'),
    _q('27_Meghan_Trainor.mp3', 2, ['Lady Gaga', 'Taylor Swift', 'Meghan Trainor', 'Dua Lipa'], 'Meghan Trainor - Nemzetközi előadó'),
    _q('28_Lana_del_Rey.mp3', 3, ['Zara Larsson', 'Adele', 'Sia', 'Lana del Rey'], 'Lana del Rey - Nemzetközi előadó'),
    _q('29_Mabel.mp3', 3, ['Dua Lipa', 'Olivia Rodrigo', 'Sabrina Carpenter', 'Mabel'], 'Mabel - Nemzetközi előadó'),
    _q('30_Kesha.mp3', 0, ['Kesha', 'Dua Lipa', 'Taylor Swift', 'Billie Eilish'], 'Kesha - Nemzetközi előadó'),
    _q('31_Christina_Aguilera.mp3', 2, ['Dua Lipa', 'Kesha', 'Christina Aguilera', 'Kylie Minogue'], 'Christina Aguilera - Nemzetközi előadó'),
    _q('31_Ed_Sheeran.mp3', 3, ['John Legend', 'Bruno Mars', 'Emelie Sande', 'Ed Sheeran'], 'Sean Paul - Nemzetközi előadó'),
    _q('32_Shawn_Mendes.mp3', 0, ['Shawn Mendes', 'Bruno Mars', 'Charlie Puth', 'Ed Sheeran'], 'Shawn Mendes - Nemzetközi előadó'),
    _q('34_Alanis_Morissette.mp3', 3, ['Ellie Goulding', 'Adele', 'Sia', 'Alanis Morissette'], 'Alanis Morissette - Nemzetközi előadó'),
    _q('35_Adam_Levine.mp3', 0, ['Adam Levine', 'Bruno Mars', 'Charlie Puth', 'Ed Sheeran'], 'Adam Levine - Nemzetközi előadó'),
    _q('36_Charlie_Puth.mp3', 0, ['Charlie Puth', 'Bruno Mars', 'Ed Sheeran', 'Shawn Mendes'], 'Charlie Puth - Nemzetközi előadó'),
    _q('37_Sean_Paul.mp3', 2, ['Bruno Mars', 'Ed Sheeran', 'Sean Paul', 'Michael Buble'], 'Sean Paul - Nemzetközi előadó'),
    _q('38_Ed_Sheeran.mp3', 3, ['Bruno Mars', 'Charlie Puth', 'Shawn Mendes', 'Ed Sheeran'], 'Ed Sheeran - Nemzetközi előadó'),
    _q('39_James_Arthur.mp3', 0, ['James Arthur', 'Lukas Graham', 'Sam Smith', 'Charlie Puth'], 'James Arthur - Nemzetközi előadó'),
    _q('40_Sam_Smith.mp3', 0, ['Sam Smith', 'Ed Sheeran', 'FloRida', 'Bruno Mars'], 'Sam Smith - Nemzetközi előadó'),
    _q('41_Michael_Buble.mp3', 2, ['Bruno Mars', 'Shawn Mendes', 'Michael Buble', 'My Chemical Romance'], 'Michael Buble - Nemzetközi előadó'),
    _q('42_George_Ezra.mp3', 1, ['Adam Levine', 'George Ezra', 'Ed Sheeran', 'Michael Buble'], 'George Ezra - Nemzetközi előadó'),
    _q('43_Keane.mp3', 1, ['Will.i.am', 'Keane', 'Charlie Puth', 'Maroon 5'], 'Keane - Nemzetközi előadó'),
    _q('44_Justin_Bieber.mp3', 2, ['Bruno Mars', 'Ed Sheeran', 'Justin Bieber', 'Charlie Puth'], 'Justin Bieber - Nemzetközi előadó'),
    _q('45_Lukas_Graham.mp3', 2, ['Bruno Mars', 'Sam Smith', 'Lukas Graham', 'Charlie Puth'], 'Lukas Graham - Nemzetközi előadó'),
    _q('46_James_Bay.mp3', 3, ['Bruno Mars', 'Charlie Puth', 'Maroon 5', 'James Bay'], 'James Bay - Nemzetközi előadó'),
    _q('47_Pharrel_Williams.mp3', 3, ['Ed Sheeran', 'Maroon 5', 'Bruno Mars', 'Pharrel Williams'], 'Pharrel Williams - Nemzetközi előadó'),
    _q('48_FloRida.mp3', 0, ['FloRida', 'Bruno Mars', 'Sean Paul', 'Ed Sheeran'], 'FloRida - Nemzetközi előadó'),
    _q('49_Will.i.am.mp3', 3, ['Train', 'Bruno Mars', 'Justin Bieber', 'Will.i.am'], 'Will.i.am - Nemzetközi előadó'),
    _q('50_Pharrel_Williams.mp3', 1, ['Bruno Mars', 'Pharell Williams', 'John Legend', 'Ed Sheeran'], 'Pharrel Williams - Nemzetközi előadó'),
    _q('51_Jason_Mraz.mp3', 3, ['Ed Sheeran', 'Justin Bieber', 'Bruno Mars', 'Jason Mraz'], 'Jason Mraz - Nemzetközi előadó'),
    _q('52_Harry_Styles.mp3', 2, ['Jason Mraz', 'Robbie Williams', 'Harry Styles', 'Ed Sheeran'], 'Harry Styles - Nemzetközi előadó'),
    _q('53_Enrique_Iglesias.mp3', 0, ['Enrique Iglesias', 'Sean Paul', 'Sam Smith', 'John Legend'], 'Enrique Iglesias - Nemzetközi előadó'),
    _q('54_John_Legend.mp3', 3, ['Shawn Mendes', 'Anne-Marie', 'Taylor Swift', 'John Legend'], 'Robbie Williams - Nemzetközi előadó'),
    _q('55_James_Blunt.mp3', 3, ['Ed Sheeran', 'John Legend', 'Bruno Mars', 'James Blunt'], 'James Blunt - Nemzetközi előadó'),
    _q('56_The_Weeknd.mp3', 2, ['Bruno Mars', 'Ed Sheeran', 'The Weeknd', 'Harry Styles'], 'The Weeknd - Nemzetközi előadó'),
    _q('57_Bruno_Mars.mp3', 2, ['Charlie Puth', 'Ed Sheeran', 'Bruno Mars', 'James Bay'], 'Bruno Mars - Nemzetközi előadó'),
    _q('58_Robbie_Williams.mp3', 0, ['Robbie Williams', 'Bruno Mars', 'Enrique Iglesias', 'Ed Sheeran'], 'Robbie Williams - Nemzetközi előadó'),
    _q('59_One_Direction.mp3', 0, ['One Direction', 'Maroon 5', 'The Weeknd', 'Imagine Dragons'], 'One Direction - Nemzetközi előadó'),
    _q('60_Maroon_5.mp3', 3, ['Lukas Graham', 'Emelie Sande', 'Lilly Allen', 'Maroon 5'], 'My Chemical Romance - Nemzetközi előadó'),
    _q('61_Imagine_Dragons.mp3', 3, ['Maneskin', 'Bruno Mars', 'Miley Cyrus', 'Imagine Dragons'], 'One Republic - Nemzetközi előadó'),
    _q('62_My_Chemical_Romance.mp3', 1, ['The Weeknd', 'My Chemical Romance', 'Justin Bieber', 'Maroon 5'], 'One Republic - Nemzetközi előadó'),
    _q('63_The_Chainsmokers.mp3', 2, ['FloRida', 'Maroon 5', 'The Chainsmokers', 'Imagine Dragons'], 'The Chainsmokers - Nemzetközi előadó'),
    _q('64_Taylor_Swift.mp3', 0, ['Taylor Swift', 'Lilly Allen', 'Lady Gaga', 'Beyonce'], 'Taylor Swift - Nemzetközi előadó'),
    _q('65_Nelly_Furtado.mp3', 0, ['Nelly Furtado', 'Lady Gaga', 'Shakira', 'Zaz'], 'Nelly Furtado - Nemzetközi előadó'),
    _q('71. Stakka Bo - Here We Go.mp3', 0, ['Stakka Bo', 'Boomfunk MC', 'Stereo MCs', 'The KLF'], "'Here We Go' egy nemzetközi dal az előadótól: Stakka Bo"),
    _q('Audioslave - Like a Stone.mp3', 0, ['Audioslave', 'Soundgarden', 'Pearl Jam', 'Nirvana'], "'Like a Stone' egy nemzetközi dal az előadótól: Audioslave"),
    _q('68. Queen - 39.mp3', 0, ['Queen', 'Bastille', 'Imagine Dragons', 'Beatles'], 'Queen - Nemzetkozi Zenekarok'),
    _q('69. The Beatles - For No One.mp3', 0, ['The Beatles', 'Rolling Stones', 'Beach Boys', 'Ringo Starr'], 'The Beatles - Nemzetkozi Zenekarok'),
    _q('70. The Rolling Stones - Paint It Black Official Lyric Video.mp3', 0, ['The Rolling Stones', 'The Beatles', 'T-Rex', 'Ramones'], 'The Rolling Stones - Nemzetkozi Zenekarok'),
    _q('72. Depeche Mode - Policy Of Truth.mp3', 0, ['Depeche Mode', 'Tears for Fears', 'Spandau Ballet', 'New Order'], 'Depeche Mode - Nemzetkozi Zenekarok'),
    _q('73. Yazoo - Dont Go.mp3', 0, ['Yazoo', 'Nouvelle Vague', 'Pink Martini', 'Bananarama'], 'Yazoo - Nemzetkozi Zenekarok'),
    _q('74. Cypress Hill - Dr Greenthumb.mp3', 0, ['Cypress Hill', 'Naughty By Nature', 'Public Enemy', 'Wu-Tang Clan'], 'Cypress Hill - Nemzetkozi Zenekarok'),
    _q('Naughty_by_Nature_Hip_Hop_Ho.mp3', 0, ['Naughty By Nature', 'Public Enemy', 'Cypress Hill', 'KRS-One'], 'Naughty By Nature - Nemzetkozi Zenekarok'),
    _q('76. Reel 2 Reel - I like to move it.mp3', 0, ['Reel 2 Reel', 'Sir Mix a Lot', 'Strictly Rhythm', 'Technotronic'], 'Reel 2 Reel - Nemzetkozi Zenekarok'),
    _q('77. Christina Aguilera - Pero Me A.mp3', 0, ['Christina Aguilera', 'Shakira', 'Jennifer Lopez', 'Nelly Furtado'], 'Christina Aguilera - Nemzetkozi Zenekarok', song_title='Pero Me A'),
]