# Auto-generated questions file
# Generated on: 2025-09-19 20:48:12

QUESTIONS = [
    {
        "question": "Ki az előadó?",
        "options": [
            "Dua Lipa",
            "Taylor Swift",
            "Katy Perry",
            "Ariana Grande",
        ],
        "correct": 3,
        "explanation": "Ariana Grande - Nemzetközi előadó",
        "audio_file": "1_Ariana_Grande.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Dua Lipa",
            "Taylor Swift",
            "Ariana Grande",
            "Sabrina Carpenter",
        ],
        "correct": 3,
        "explanation": "Sabrina Carpenter - Nemzetközi előadó",
        "audio_file": "2_Sabrina_Carpenter.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Olivia Rodrigo",
            "Mabel",
            "Sia",
            "Taylor Swift",
        ],
        "correct": 0,
        "explanation": "Ellie Goulding - Nemzetközi előadó",
        "audio_file": "3_Olivia_Rodrigo.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Dua Lipa",
            "Rihanna",
            "Billie Eilish",
            "Lady Gaga",
        ],
        "correct": 1,
        "explanation": "Rihanna - Nemzetközi előadó",
        "audio_file": "4_Rihanna.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Dua Lipa",
            "Taylor Swift",
            "Beyonce",
            "Anne-Marie",
        ],
        "correct": 0,
        "explanation": "Dua Lipa - Nemzetközi előadó",
        "audio_file": "5_Dua_Lipa.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Lady Gaga",
            "Selena Gomez",
            "Camilla Cabello",
            "Sia",
        ],
        "correct": 2,
        "explanation": "Lilly Allen - Nemzetközi előadó",
        "audio_file": "6_Camilla_Cabello.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Miley Cyrus",
            "Kylie Minogue",
            "Ellie Goulding",
            "Sia",
        ],
        "correct": 0,
        "explanation": "Miley Cyrus - Nemzetközi előadó",
        "audio_file": "7_Miley_Cyrus.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Ariana Grande",
            "Lady Gaga",
            "Pink",
            "Ellie Goulding",
        ],
        "correct": 1,
        "explanation": "Lady Gaga - Nemzetközi előadó",
        "audio_file": "8_Lady_Gaga.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Dua Lipa",
            "Taylor Swift",
            "Billie Eilish",
            "Kylie Minogue",
        ],
        "correct": 2,
        "explanation": "Billie Eilish - Nemzetközi előadó",
        "audio_file": "9_Billie_Eilish.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Adele",
            "Taylor Swift",
            "Camilla Cabello",
            "Miley Cyrus",
        ],
        "correct": 0,
        "explanation": "Adele - Nemzetközi előadó",
        "audio_file": "10_Adele.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Mabel",
            "Kesha",
            "Zaz",
            "Selena Gomez",
        ],
        "correct": 2,
        "explanation": "Zaz - Nemzetközi előadó",
        "audio_file": "11_Zaz.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Ellie Goulding",
            "Anne-Marie",
            "Kesha",
            "Kylie Minogue",
        ],
        "correct": 0,
        "explanation": "Beyonce - Nemzetközi előadó",
        "audio_file": "12_Ellie_Goulding.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Dua Lipa",
            "Miley Cyrus",
            "Kylie Minogue",
            "Emelie Sande",
        ],
        "correct": 3,
        "explanation": "Emelie Sande - Nemzetközi előadó",
        "audio_file": "13_Emelie_Sande.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Katy Perry",
            "Adele",
            "Sia",
            "Lana del Rey",
        ],
        "correct": 0,
        "explanation": "Katy Perry - Nemzetközi előadó",
        "audio_file": "14_Katy_Perry.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Dua Lipa",
            "Taylor Swift",
            "Lilly Allen",
            "Anne-Marie",
        ],
        "correct": 2,
        "explanation": "Lilly Allen - Nemzetközi előadó",
        "audio_file": "15_Lilly_Allen.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Jessie J.",
            "Zaz",
            "Kesha",
            "Bebe Rexha",
        ],
        "correct": 0,
        "explanation": "Jessie J. - Nemzetközi előadó",
        "audio_file": "16_Jessie_J..mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Dua Lipa",
            "Kylie Minogue",
            "Lady Gaga",
            "Pink",
        ],
        "correct": 3,
        "explanation": "Pink - Nemzetközi előadó",
        "audio_file": "17_Pink.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Sia",
            "Bebe Rexha",
            "Taylor Swift",
            "Katy Perry",
        ],
        "correct": 0,
        "explanation": "Selena Gomez - Nemzetközi előadó",
        "audio_file": "18_Sia.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Emelie Sande",
            "Billie Eilish",
            "Taylor Swift",
            "Zara Larsson",
        ],
        "correct": 3,
        "explanation": "Zara Larsson - Nemzetközi előadó",
        "audio_file": "19_Zara_Larsson.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Beyonce",
            "Billie Eilish",
            "Rihanna",
            "Zaz",
        ],
        "correct": 0,
        "explanation": "Beyonce - Nemzetközi előadó",
        "audio_file": "20_Beyonce.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Dua Lipa",
            "Miley Cyrus",
            "Norah Jones",
            "Taylor Swift",
        ],
        "correct": 2,
        "explanation": "Norah Jones - Nemzetközi előadó",
        "audio_file": "21_Norah_Jones.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Christina Aguilera",
            "Anne-Marie",
            "Janis Joplin",
            "Alanis Morissette",
        ],
        "correct": 2,
        "explanation": "Janis Joplin - Nemzetközi előadó",
        "audio_file": "22_Janis_Joplin.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Dua Lipa",
            "Taylor Swift",
            "Anne-Marie",
            "Billie Eilish",
        ],
        "correct": 2,
        "explanation": "Anne-Marie - Nemzetközi előadó",
        "audio_file": "23_Anne-Marie.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Dua Lipa",
            "Bebe Rexha",
            "Kesha",
            "Taylor Swift",
        ],
        "correct": 1,
        "explanation": "Bebe Rexha - Nemzetközi előadó",
        "audio_file": "24_Bebe_Rexha.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Katy Perry",
            "Meghan Trainor",
            "Taylor Swift",
            "Lana del Rey",
        ],
        "correct": 2,
        "explanation": "Taylor Swift - Nemzetközi előadó",
        "audio_file": "25_Taylor_Swift.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Kylie Minogue",
            "Selena Gomez",
            "Ariana Grande",
            "Taylor Swift",
        ],
        "correct": 1,
        "explanation": "Nelly Furtado - Nemzetközi előadó",
        "audio_file": "26_Selena_Gomez.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Lady Gaga",
            "Taylor Swift",
            "Meghan Trainor",
            "Dua Lipa",
        ],
        "correct": 2,
        "explanation": "Meghan Trainor - Nemzetközi előadó",
        "audio_file": "27_Meghan_Trainor.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Zara Larsson",
            "Adele",
            "Sia",
            "Lana del Rey",
        ],
        "correct": 3,
        "explanation": "Lana del Rey - Nemzetközi előadó",
        "audio_file": "28_Lana_del_Rey.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Dua Lipa",
            "Olivia Rodrigo",
            "Sabrina Carpenter",
            "Mabel",
        ],
        "correct": 3,
        "explanation": "Mabel - Nemzetközi előadó",
        "audio_file": "29_Mabel.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Kesha",
            "Dua Lipa",
            "Taylor Swift",
            "Billie Eilish",
        ],
        "correct": 0,
        "explanation": "Kesha - Nemzetközi előadó",
        "audio_file": "30_Kesha.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Dua Lipa",
            "Kesha",
            "Christina Aguilera",
            "Kylie Minogue",
        ],
        "correct": 2,
        "explanation": "Christina Aguilera - Nemzetközi előadó",
        "audio_file": "31_Christina_Aguilera.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "John Legend",
            "Bruno Mars",
            "Emelie Sande",
            "Ed Sheeran",
        ],
        "correct": 3,
        "explanation": "Sean Paul - Nemzetközi előadó",
        "audio_file": "31_Ed_Sheeran.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Shawn Mendes",
            "Bruno Mars",
            "Charlie Puth",
            "Ed Sheeran",
        ],
        "correct": 0,
        "explanation": "Shawn Mendes - Nemzetközi előadó",
        "audio_file": "32_Shawn_Mendes.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Ellie Goulding",
            "Adele",
            "Sia",
            "Alanis Morissette",
        ],
        "correct": 3,
        "explanation": "Alanis Morissette - Nemzetközi előadó",
        "audio_file": "34_Alanis_Morissette.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Adam Levine",
            "Bruno Mars",
            "Charlie Puth",
            "Ed Sheeran",
        ],
        "correct": 0,
        "explanation": "Adam Levine - Nemzetközi előadó",
        "audio_file": "35_Adam_Levine.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Charlie Puth",
            "Bruno Mars",
            "Ed Sheeran",
            "Shawn Mendes",
        ],
        "correct": 0,
        "explanation": "Charlie Puth - Nemzetközi előadó",
        "audio_file": "36_Charlie_Puth.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Bruno Mars",
            "Ed Sheeran",
            "Sean Paul",
            "Michael Buble",
        ],
        "correct": 2,
        "explanation": "Sean Paul - Nemzetközi előadó",
        "audio_file": "37_Sean_Paul.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Bruno Mars",
            "Charlie Puth",
            "Shawn Mendes",
            "Ed Sheeran",
        ],
        "correct": 3,
        "explanation": "Ed Sheeran - Nemzetközi előadó",
        "audio_file": "38_Ed_Sheeran.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "James Arthur",
            "Lukas Graham",
            "Sam Smith",
            "Charlie Puth",
        ],
        "correct": 0,
        "explanation": "James Arthur - Nemzetközi előadó",
        "audio_file": "39_James_Arthur.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Sam Smith",
            "Ed Sheeran",
            "FloRida",
            "Bruno Mars",
        ],
        "correct": 0,
        "explanation": "Sam Smith - Nemzetközi előadó",
        "audio_file": "40_Sam_Smith.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Bruno Mars",
            "Shawn Mendes",
            "Michael Buble",
            "My Chemical Romance",
        ],
        "correct": 2,
        "explanation": "Michael Buble - Nemzetközi előadó",
        "audio_file": "41_Michael_Buble.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Adam Levine",
            "George Ezra",
            "Ed Sheeran",
            "Michael Buble",
        ],
        "correct": 1,
        "explanation": "George Ezra - Nemzetközi előadó",
        "audio_file": "42_George_Ezra.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Will.i.am",
            "Keane",
            "Charlie Puth",
            "Maroon 5",
        ],
        "correct": 1,
        "explanation": "Keane - Nemzetközi előadó",
        "audio_file": "43_Keane.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Bruno Mars",
            "Ed Sheeran",
            "Justin Bieber",
            "Charlie Puth",
        ],
        "correct": 2,
        "explanation": "Justin Bieber - Nemzetközi előadó",
        "audio_file": "44_Justin_Bieber.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Bruno Mars",
            "Sam Smith",
            "Lukas Graham",
            "Charlie Puth",
        ],
        "correct": 2,
        "explanation": "Lukas Graham - Nemzetközi előadó",
        "audio_file": "45_Lukas_Graham.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Bruno Mars",
            "Charlie Puth",
            "Maroon 5",
            "James Bay",
        ],
        "correct": 3,
        "explanation": "James Bay - Nemzetközi előadó",
        "audio_file": "46_James_Bay.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Ed Sheeran",
            "Maroon 5",
            "Bruno Mars",
            "Pharrel Williams",
        ],
        "correct": 3,
        "explanation": "Pharrel Williams - Nemzetközi előadó",
        "audio_file": "47_Pharrel_Williams.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "FloRida",
            "Bruno Mars",
            "Sean Paul",
            "Ed Sheeran",
        ],
        "correct": 0,
        "explanation": "FloRida - Nemzetközi előadó",
        "audio_file": "48_FloRida.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Train",
            "Bruno Mars",
            "Justin Bieber",
            "Will.i.am",
        ],
        "correct": 3,
        "explanation": "Will.i.am - Nemzetközi előadó",
        "audio_file": "49_Will.i.am.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Bruno Mars",
            "Pharell Williams",
            "John Legend",
            "Ed Sheeran",
        ],
        "correct": 1,
        "explanation": "Pharrel Williams - Nemzetközi előadó",
        "audio_file": "50_Pharrel_Williams.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Ed Sheeran",
            "Justin Bieber",
            "Bruno Mars",
            "Jason Mraz",
        ],
        "correct": 3,
        "explanation": "Jason Mraz - Nemzetközi előadó",
        "audio_file": "51_Jason_Mraz.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Jason Mraz",
            "Robbie Williams",
            "Harry Styles",
            "Ed Sheeran",
        ],
        "correct": 2,
        "explanation": "Harry Styles - Nemzetközi előadó",
        "audio_file": "52_Harry_Styles.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Enrique Iglesias",
            "Sean Paul",
            "Sam Smith",
            "John Legend",
        ],
        "correct": 0,
        "explanation": "Enrique Iglesias - Nemzetközi előadó",
        "audio_file": "53_Enrique_Iglesias.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Shawn Mendes",
            "Anne-Marie",
            "Taylor Swift",
            "John Legend",
        ],
        "correct": 3,
        "explanation": "Robbie Williams - Nemzetközi előadó",
        "audio_file": "54_John_Legend.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Ed Sheeran",
            "John Legend",
            "Bruno Mars",
            "James Blunt",
        ],
        "correct": 3,
        "explanation": "James Blunt - Nemzetközi előadó",
        "audio_file": "55_James_Blunt.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Bruno Mars",
            "Ed Sheeran",
            "The Weeknd",
            "Harry Styles",
        ],
        "correct": 2,
        "explanation": "The Weeknd - Nemzetközi előadó",
        "audio_file": "56_The_Weeknd.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Charlie Puth",
            "Ed Sheeran",
            "Bruno Mars",
            "James Bay",
        ],
        "correct": 2,
        "explanation": "Bruno Mars - Nemzetközi előadó",
        "audio_file": "57_Bruno_Mars.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Robbie Williams",
            "Bruno Mars",
            "Enrique Iglesias",
            "Ed Sheeran",
        ],
        "correct": 0,
        "explanation": "Robbie Williams - Nemzetközi előadó",
        "audio_file": "58_Robbie_Williams.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "One Direction",
            "Maroon 5",
            "The Weeknd",
            "Imagine Dragons",
        ],
        "correct": 0,
        "explanation": "One Direction - Nemzetközi előadó",
        "audio_file": "59_One_Direction.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Lukas Graham",
            "Emelie Sande",
            "Lilly Allen",
            "Maroon 5",
        ],
        "correct": 3,
        "explanation": "My Chemical Romance - Nemzetközi előadó",
        "audio_file": "60_Maroon_5.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Maneskin",
            "Bruno Mars",
            "Miley Cyrus",
            "Imagine Dragons",
        ],
        "correct": 3,
        "explanation": "One Republic - Nemzetközi előadó",
        "audio_file": "61_Imagine_Dragons.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "The Weeknd",
            "My Chemical Romance",
            "Justin Bieber",
            "Maroon 5",
        ],
        "correct": 1,
        "explanation": "One Republic - Nemzetközi előadó",
        "audio_file": "62_My_Chemical_Romance.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "FloRida",
            "Maroon 5",
            "The Chainsmokers",
            "Imagine Dragons",
        ],
        "correct": 2,
        "explanation": "The Chainsmokers - Nemzetközi előadó",
        "audio_file": "63_The_Chainsmokers.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Taylor Swift",
            "Lilly Allen",
            "Lady Gaga",
            "Beyonce",
        ],
        "correct": 0,
        "explanation": "Taylor Swift - Nemzetközi előadó",
        "audio_file": "64_Taylor_Swift.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Nelly Furtado",
            "Lady Gaga",
            "Shakira",
            "Zaz",
        ],
        "correct": 0,
        "explanation": "Nelly Furtado - Nemzetközi előadó",
        "audio_file": "65_Nelly_Furtado.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó a 'Here We Go' című dalban?",
        "options": [
            "Stakka Bo",
            "Boomfunk MC",
            "Stereo MCs",
            "The KLF",
        ],
        "correct": 0,
        "explanation": "'Here We Go' egy nemzetközi dal az előadótól: Stakka Bo",
        "audio_file": "71. Stakka Bo - Here We Go.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó a 'Like a Stone' című dalban?",
        "options": [
            "Audioslave",
            "Soundgarden",
            "Pearl Jam",
            "Nirvana",
        ],
        "correct": 0,
        "explanation": "'Like a Stone' egy nemzetközi dal az előadótól: Audioslave",
        "audio_file": "Audioslave - Like a Stone.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Queen",
            "Bastille",
            "Imagine Dragons",
            "Beatles",
        ],
        "correct": 0,
        "explanation": "Queen - Nemzetkozi Zenekarok",
        "audio_file": "68. Queen - 39.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "The Beatles",
            "Rolling Stones",
            "Beach Boys",
            "Ringo Starr",
        ],
        "correct": 0,
        "explanation": "The Beatles - Nemzetkozi Zenekarok",
        "audio_file": "69. The Beatles - For No One.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "The Rolling Stones",
            "The Beatles",
            "T-Rex",
            "Ramones",
        ],
        "correct": 0,
        "explanation": "The Rolling Stones - Nemzetkozi Zenekarok",
        "audio_file": "70. The Rolling Stones - Paint It Black Official Lyric Video.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó a 'Here We Go' című dalban?",
        "options": [
            "Stakka Bo",
            "Ultravox",
            "New Order",
            "Yello",
        ],
        "correct": 0,
        "explanation": "'Here We Go' egy nemzetközi dal az előadótól: Stakka Bo",
        "audio_file": "71. Stakka Bo - Here We Go.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Depeche Mode",
            "Tears for Fears",
            "Spandau Ballet",
            "New Order",
        ],
        "correct": 0,
        "explanation": "Depeche Mode - Nemzetkozi Zenekarok",
        "audio_file": "72. Depeche Mode - Policy Of Truth.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az eredeti előadó?",
        "options": [
            "Yazoo",
            "Nouvelle Vague",
            "Pink Martini",
            "Bananarama",
        ],
        "correct": 0,
        "explanation": "Yazoo - Nemzetkozi Zenekarok",
        "audio_file": "73. Yazoo - Dont Go.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Cypress Hill",
            "Naughty By Nature",
            "Public Enemy",
            "Wu-Tang Clan",
        ],
        "correct": 0,
        "explanation": "Cypress Hill - Nemzetkozi Zenekarok",
        "audio_file": "74. Cypress Hill - Dr Greenthumb.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Naughty By Nature",
            "Public Enemy",
            "Cypress Hill",
            "KRS-One",
        ],
        "correct": 0,
        "explanation": "Naughty By Nature - Nemzetkozi Zenekarok",
        "audio_file": "Naughty_by_Nature_Hip_Hop_Ho.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Reel 2 Reel",
            "Sir Mix a Lot",
            "Strictly Rhythm",
            "Technotronic",
        ],
        "correct": 0,
        "explanation": "Reel 2 Reel - Nemzetkozi Zenekarok",
        "audio_file": "76. Reel 2 Reel - I like to move it.mp3",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "options": [
            "Christina Aguilera",
            "Shakira",
            "Jennifer Lopez",
            "Nelly Furtado",
        ],
        "correct": 0,
        "explanation": "Christina Aguilera - Nemzetkozi Zenekarok",
        "audio_file": "77. Christina Aguilera - Pero Me A.mp3",
        "song_title": "Pero Me A",
        "topic": "nemzetkozi_zenekarok",
    },
]
