# -*- coding: utf-8 -*-
"""
Nemzetközi zenekarok kérdések - javított audio fájlokkal, válaszopciókkal és helyes válaszokkal
"""

NEMZETKOZI_ZENEKAROK_QUESTIONS = [
    {
        "question": "Ki az előadó?",
        "audio_file": "1_Ariana_Grande.mp3",
        "original_index": 1,
        "options": ['My Chemical Romance', 'John Legend', 'George Ezra', 'Ariana Grande'],
        "correct": 3,
        "explanation": "Adele - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "audio_file": "2_Sabrina_Carpenter.mp3",
        "original_index": 2,
        "options": ['Shawn Mendes', 'Ed Sheeran', 'Ariana Grande', 'Sabrina Carpenter'],
        "correct": 3,
        "explanation": "Zaz - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 3,
        "options": ['Olivia Rodrigo', 'Mabel', 'Sia', 'Taylor Swift'],
        "correct": 0,
        "explanation": "Ellie Goulding - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "3_Olivia_Rodrigo.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 4,
        "options": ['Robbie Williams', 'Rihanna', 'Billie Eilish', 'Lady Gaga'],
        "correct": 1,
        "explanation": "Emelie Sande - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "4_Rihanna.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 5,
        "options": ['Dua Lipa', 'Pharrel Williams', 'Beyonce', 'Anne-Marie'],
        "correct": 0,
        "explanation": "Katy Perry - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "5_Dua_Lipa.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 6,
        "options": ['Lady Gaga', 'Selena Gomez', 'Camilla Cabello', 'Sia'],
        "correct": 2,
        "explanation": "Lilly Allen - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "6_Camilla_Cabello.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 7,
        "options": ['Miley Cyrus', 'John Legend', 'Sean Paul', 'Sia'],
        "correct": 0,
        "explanation": "Jessie J. - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "7_Miley_Cyrus.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 8,
        "options": ['Ariana Grande', 'Lady Gaga', 'Will.i.am', 'Ellie Goulding'],
        "correct": 1,
        "explanation": "Pink - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "8_Lady_Gaga.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 9,
        "options": ['Shawn Mendes', 'The Weeknd', 'Billie Eilish', 'Kylie Minogue'],
        "correct": 2,
        "explanation": "Sia - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "9_Billie_Eilish.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 10,
        "options": ['Adele', 'The Chainsmokers', 'Camilla Cabello', 'Miley Cyrus'],
        "correct": 0,
        "explanation": "Zara Larsson - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "10_Adele.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 11,
        "options": ['Mabel', 'James Arthur', 'Zaz', 'Selena Gomez'],
        "correct": 2,
        "explanation": "Ariana Grande - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "11_Zaz.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 12,
        "options": ['Ellie Goulding', 'Anne-Marie', 'Kesha', 'Kylie Minogue'],
        "correct": 0,
        "explanation": "Beyonce - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "12_Ellie_Goulding.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 13,
        "options": ['James Bay', 'Miley Cyrus', 'Kylie Minogue', 'Emelie Sande'],
        "correct": 3,
        "explanation": "Norah Jones - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "13_Emelie_Sande.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 14,
        "options": ['Katy Perry', 'Adele', 'Sia', 'Lana del Rey'],
        "correct": 0,
        "explanation": "Katy Perry - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "14_Katy_Perry.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 15,
        "options": ['One Direction', 'Dua Lipa', 'Lilly Allen', 'Imagine Dragons'],
        "correct": 2,
        "explanation": "Anne-Marie - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "15_Lilly_Allen.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 16,
        "options": ['Jessie J.', 'Zaz', 'Kesha', 'Enrique Iglesias'],
        "correct": 0,
        "explanation": "Bebe Rexha - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "16_Jessie_J..mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 17,
        "options": ['Robbie Williams', 'Kylie Minogue', 'John Legend', 'Pink'],
        "correct": 3,
        "explanation": "Taylor Swift - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "17_Pink.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 18,
        "options": ['Sia', 'Bebe Rexha', 'Taylor Swift', 'Katy Perry'],
        "correct": 0,
        "explanation": "Selena Gomez - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "18_Sia.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 19,
        "options": ['Emelie Sande', 'Billie Eilish', 'Shawn Mendes', 'Zara Larsson'],
        "correct": 3,
        "explanation": "21 Pilots - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "19_Zara_Larsson.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 20,
        "options": ['Beyonce', 'Billie Eilish', 'Maroon 5', 'Zaz'],
        "correct": 0,
        "explanation": "Lana del Rey - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "20_Beyonce.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 21,
        "options": ['Sam Smith', 'Miley Cyrus', 'Norah Jones', 'Ed Sheeran'],
        "correct": 2,
        "explanation": "Mabel - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "21_Norah_Jones.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 22,
        "options": ['Christina Aguilera', 'Anne-Marie', 'Janis Joplin', 'John Legend'],
        "correct": 2,
        "explanation": "Sabrina Carpenter - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "22_Janis_Joplin.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 23,
        "options": ['The Weeknd', 'Will.i.am', 'Anne-Marie', 'Billie Eilish'],
        "correct": 2,
        "explanation": "Kesha - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "23_Anne-Marie.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 24,
        "options": ['Will.i.am', 'Bebe Rexha', 'Maroon 5', 'Taylor Swift'],
        "correct": 1,
        "explanation": "Christina Aguilera - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "24_Bebe_Rexha.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 25,
        "options": ['Katy Perry', 'Meghan Trainor', 'Taylor Swift', 'Lana del Rey'],
        "correct": 2,
        "explanation": "Taylor Swift - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "25_Taylor_Swift.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 26,
        "options": ['Kylie Minogue', 'Selena Gomez', 'Ariana Grande', 'Taylor Swift'],
        "correct": 1,
        "explanation": "Nelly Furtado - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "26_Selena_Gomez.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 27,
        "options": ['Lady Gaga', 'Ed Sheeran', 'Meghan Trainor', 'Pharell Williams'],
        "correct": 2,
        "explanation": "Shawn Mendes - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "27_Meghan_Trainor.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 28,
        "options": ['Zara Larsson', 'Adele', 'Sia', 'Lana del Rey'],
        "correct": 3,
        "explanation": "Lana del Rey - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "28_Lana_del_Rey.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 29,
        "options": ['Dua Lipa', 'Olivia Rodrigo', 'Sabrina Carpenter', 'Mabel'],
        "correct": 3,
        "explanation": "Mabel - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "29_Mabel.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 30,
        "options": ['Kesha', 'One Direction', 'Maneskin', 'Will.i.am'],
        "correct": 0,
        "explanation": "Adam Levine - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "30_Kesha.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 31,
        "options": ['Lukas Graham', 'Kesha', 'Christina Aguilera', 'Kylie Minogue'],
        "correct": 2,
        "explanation": "Charlie Puth - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "31_Christina_Aguilera.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 32,
        "options": ['John Legend', 'Bruno Mars', 'Emelie Sande', 'Ed Sheeran'],
        "correct": 3,
        "explanation": "Sean Paul - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "31_Ed_Sheeran.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 33,
        "options": ['Shawn Mendes', 'Taylor Swift', 'My Chemical Romance', 'Ed Sheeran'],
        "correct": 0,
        "explanation": "Ed Sheeran - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "32_Shawn_Mendes.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 34,
        "options": ['Ellie Goulding', 'Adele', 'Sia', 'Alanis Morissette'],
        "correct": 3,
        "explanation": "Alanis Morissette - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "34_Alanis_Morissette.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 35,
        "options": ['Adam Levine', 'Will.i.am', 'Train', 'The Chainsmokers'],
        "correct": 0,
        "explanation": "Olivia Rodrigo - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "35_Adam_Levine.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 36,
        "options": ['Beyonce', 'Adele', 'Sia', 'Lana del Rey'],
        "correct": 0,
        "explanation": "Beyonce - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "36_Charlie_Puth.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 37,
        "options": ['Bruno Mars', 'Meghan Trainor', 'Sean Paul', 'Michael Buble'],
        "correct": 2,
        "explanation": "Michael Buble - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "37_Sean_Paul.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 38,
        "options": ['Zara Larsson', 'Sabrina Carpenter', 'Bruno Mars', 'Ed Sheeran'],
        "correct": 3,
        "explanation": "George Ezra - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "38_Ed_Sheeran.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 39,
        "options": ['James Arthur', 'Lukas Graham', 'Sam Smith', 'Emelie Sande'],
        "correct": 0,
        "explanation": "Keane - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "39_James_Arthur.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 40,
        "options": ['Sam Smith', 'Olivia Rodrigo', 'FloRida', 'Jessie J.'],
        "correct": 0,
        "explanation": "Justin Bieber - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "40_Sam_Smith.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 41,
        "options": ['Kesha', 'Shawn Mendes', 'Michael Buble', 'My Chemical Romance'],
        "correct": 2,
        "explanation": "Lukas Graham - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "41_Michael_Buble.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 42,
        "options": ['Adam Levine', 'George Ezra', 'Taylor Swift', 'Michael Buble'],
        "correct": 1,
        "explanation": "James Bay - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "42_George_Ezra.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 43,
        "options": ['Will.i.am', 'Keane', 'Charlie Puth', 'Taylor Swift'],
        "correct": 1,
        "explanation": "Pharrel Williams - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "43_Keane.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 44,
        "options": ['Ellie Goulding', 'Emelie Sande', 'Justin Bieber', 'Kesha'],
        "correct": 2,
        "explanation": "FloRida - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "44_Justin_Bieber.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 45,
        "options": ['Camilla Cabello', 'Sam Smith', 'Lukas Graham', 'Charlie Puth'],
        "correct": 2,
        "explanation": "Will.i.am - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "45_Lukas_Graham.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 46,
        "options": ['Katy Perry', 'Charlie Puth', 'Maroon 5', 'James Bay'],
        "correct": 3,
        "explanation": "Rihanna - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "46_James_Bay.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 47,
        "options": ['Taylor Swift', 'Maroon 5', 'Anne-Marie', 'Pharrel Williams'],
        "correct": 3,
        "explanation": "Jason Mraz - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "47_Pharrel_Williams.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 48,
        "options": ['Adele', 'Sia', 'Lana del Rey', 'Katy Perry'],
        "correct": 0,
        "explanation": "Adele - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "48_FloRida.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 49,
        "options": ['Train', 'Billie Eilish', 'Justin Bieber', 'Will.i.am'],
        "correct": 3,
        "explanation": "Enrique Iglesias - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "49_Will.i.am.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 50,
        "options": ['Camilla Cabello', 'Pharell Williams', 'Lady Gaga', 'Dua Lipa'],
        "correct": 1,
        "explanation": "John Legend - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "50_Pharell_Williams.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 51,
        "options": ['Olivia Rodrigo', 'Justin Bieber', 'Bebe Rexha', 'Jason Mraz'],
        "correct": 3,
        "explanation": "James Blunt - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "51_Jason_Mraz.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 52,
        "options": ['Jason Mraz', 'Robbie Williams', 'Harry Styles', 'Jessie J.'],
        "correct": 2,
        "explanation": "The Weeknd - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "52_Harry_Styles.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 53,
        "options": ['Enrique Iglesias', 'Sean Paul', 'Sam Smith', 'John Legend'],
        "correct": 0,
        "explanation": "Enrique Iglesias - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "53_Enrique_Iglesias.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 54,
        "options": ['Shawn Mendes', 'Anne-Marie', 'Taylor Swift', 'John Legend'],
        "correct": 3,
        "explanation": "Robbie Williams - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "54_John_Legend.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 55,
        "options": ['Kylie Minogue', 'John Legend', 'Jessie J.', 'James Blunt'],
        "correct": 3,
        "explanation": "One Direction - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "55_James_Blunt.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 56,
        "options": ['Rihanna', 'Adele', 'The Weeknd', 'Lilly Allen'],
        "correct": 2,
        "explanation": "Dua Lipa - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "56_The_Weeknd.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 57,
        "options": ['Ariana Grande', 'Ed Sheeran', 'Bruno Mars', 'James Bay'],
        "correct": 2,
        "explanation": "Maroon 5 - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "57_Bruno_Mars.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 58,
        "options": ['Robbie Williams', 'Emelie Sande', 'Enrique Iglesias', 'Sabrina Carpenter'],
        "correct": 0,
        "explanation": "Imagine Dragons - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "58_Robbie_Williams.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 59,
        "options": ['One Direction', 'Christina Aguilera', 'The Weeknd', 'John Legend'],
        "correct": 0,
        "explanation": "Maneskin - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "59_One_Direction.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 60,
        "options": ['Lukas Graham', 'Emelie Sande', 'Lilly Allen', 'Maroon 5'],
        "correct": 3,
        "explanation": "My Chemical Romance - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "60_Maroon_5.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 61,
        "options": ['Maneskin', 'Bruno Mars', 'Miley Cyrus', 'Imagine Dragons'],
        "correct": 3,
        "explanation": "One Republic - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "61_Imagine_Dragons.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 62,
        "options": ['The Weeknd', 'My Chemical Romance', 'Justin Bieber', 'Maroon 5'],
        "correct": 1,
        "explanation": "One Republic - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "62_My_Chemical_Romance.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 63,
        "options": ['FloRida', 'Dua Lipa', 'The Chainsmokers', 'Billie Eilish'],
        "correct": 2,
        "explanation": "The Chainsmokers - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "63_The_Chainsmokers.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 64,
        "options": ['Taylor Swift', 'Lilly Allen', 'Lady Gaga', 'Beyonce'],
        "correct": 0,
        "explanation": "Taylor Swift - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "64_Taylor_Swift.mp3",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 65,
        "options": ['Nelly Furtado', 'Lady Gaga', 'Pharell Williams', 'Zaz'],
        "correct": 0,
        "explanation": "Train - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
        "audio_file": "65_Nelly_Furtado.mp3",
    },
]
