#!/usr/bin/env python3
"""
Nemzetközi zenekarok kérdések - javított válaszokkal és original_index mezőkkel
"""

NEMZETKOZI_ZENEKAROK_QUESTIONS = [
    {
        "question": "Ki az előadó?",
        "audio_file": "1_Adele.mp3",
        "original_index": 0,
        "options": ['Adele', 'Ed Sheeran', 'Ariana Grande', 'Taylor Swift'],
        "correct": "0",
        "explanation": "Adele - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "audio_file": "10_Adele.mp3",
        "original_index": 1,
        "options": ['Zaz', 'Taylor Swift', 'Ed Sheeran', 'Ariana Grande'],
        "correct": "0",
        "explanation": "Zaz - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 2,
        "options": ['Ellie Goulding', 'Taylor Swift', 'Ariana Grande', 'Ed Sheeran'],
        "correct": "0",
        "explanation": "Ellie Goulding - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 3,
        "options": ['Emelie Sande', 'Ariana Grande', 'Ed Sheeran', 'Taylor Swift'],
        "correct": "0",
        "explanation": "Emelie Sande - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 4,
        "options": ['Katy Perry', 'Ariana Grande', 'Taylor Swift', 'Ed Sheeran'],
        "correct": "0",
        "explanation": "Katy Perry - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 5,
        "options": ['Lilly Allen', 'Ariana Grande', 'Taylor Swift', 'Ed Sheeran'],
        "correct": "0",
        "explanation": "Lilly Allen - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 6,
        "options": ['Jessie J.', 'Ed Sheeran', 'Ariana Grande', 'Taylor Swift'],
        "correct": "0",
        "explanation": "Jessie J. - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 7,
        "options": ['Pink', 'Ed Sheeran', 'Ariana Grande', 'Taylor Swift'],
        "correct": "0",
        "explanation": "Pink - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 8,
        "options": ['Sia', 'Ed Sheeran', 'Ariana Grande', 'Taylor Swift'],
        "correct": "0",
        "explanation": "Sia - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 9,
        "options": ['Zara Larsson', 'Taylor Swift', 'Ed Sheeran', 'Ariana Grande'],
        "correct": "0",
        "explanation": "Zara Larsson - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 10,
        "options": ['Ariana Grande', 'Ed Sheeran', 'Taylor Swift', 'Bruno Mars'],
        "correct": "0",
        "explanation": "Ariana Grande - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 11,
        "options": ['Beyonce', 'Taylor Swift', 'Ariana Grande', 'Ed Sheeran'],
        "correct": "0",
        "explanation": "Beyonce - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 12,
        "options": ['Norah Jones', 'Ariana Grande', 'Ed Sheeran', 'Taylor Swift'],
        "correct": "0",
        "explanation": "Norah Jones - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 13,
        "options": ['Janis Joplin', 'Taylor Swift', 'Ed Sheeran', 'Ariana Grande'],
        "correct": "0",
        "explanation": "Janis Joplin - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 14,
        "options": ['Anne-Marie', 'Taylor Swift', 'Ed Sheeran', 'Ariana Grande'],
        "correct": "0",
        "explanation": "Anne-Marie - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 15,
        "options": ['Bebe Rexha', 'Taylor Swift', 'Ed Sheeran', 'Ariana Grande'],
        "correct": "0",
        "explanation": "Bebe Rexha - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 16,
        "options": ['Taylor Swift', 'Bruno Mars', 'Ed Sheeran', 'Ariana Grande'],
        "correct": "0",
        "explanation": "Taylor Swift - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 17,
        "options": ['Selena Gomez', 'Ariana Grande', 'Taylor Swift', 'Ed Sheeran'],
        "correct": "0",
        "explanation": "Selena Gomez - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 18,
        "options": ['21 Pilots', 'Taylor Swift', 'Ed Sheeran', 'Ariana Grande'],
        "correct": "0",
        "explanation": "21 Pilots - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 19,
        "options": ['Lana del Rey', 'Ed Sheeran', 'Taylor Swift', 'Ariana Grande'],
        "correct": "0",
        "explanation": "Lana del Rey - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 20,
        "options": ['Mabel', 'Ed Sheeran', 'Taylor Swift', 'Ariana Grande'],
        "correct": "0",
        "explanation": "Mabel - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 21,
        "options": ['Sabrina Carpenter', 'Taylor Swift', 'Ariana Grande', 'Ed Sheeran'],
        "correct": "0",
        "explanation": "Sabrina Carpenter - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 22,
        "options": ['Kesha', 'Ariana Grande', 'Taylor Swift', 'Ed Sheeran'],
        "correct": "0",
        "explanation": "Kesha - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 23,
        "options": ['Christina Aguilera', 'Ariana Grande', 'Taylor Swift', 'Ed Sheeran'],
        "correct": "0",
        "explanation": "Christina Aguilera - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 24,
        "options": ['Ed Sheeran', 'Bruno Mars', 'Ariana Grande', 'Taylor Swift'],
        "correct": "0",
        "explanation": "Ed Sheeran - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 25,
        "options": ['Nelly Furtado', 'Ed Sheeran', 'Taylor Swift', 'Ariana Grande'],
        "correct": "0",
        "explanation": "Nelly Furtado - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 26,
        "options": ['Shawn Mendes', 'Taylor Swift', 'Ed Sheeran', 'Ariana Grande'],
        "correct": "0",
        "explanation": "Shawn Mendes - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 27,
        "options": ['Kylie Minogue', 'Ariana Grande', 'Ed Sheeran', 'Taylor Swift'],
        "correct": "0",
        "explanation": "Kylie Minogue - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 28,
        "options": ['Alanis Morissette', 'Taylor Swift', 'Ariana Grande', 'Ed Sheeran'],
        "correct": "0",
        "explanation": "Alanis Morissette - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 29,
        "options": ['Adam Levine', 'Taylor Swift', 'Ariana Grande', 'Ed Sheeran'],
        "correct": "0",
        "explanation": "Adam Levine - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 30,
        "options": ['Charlie Puth', 'Taylor Swift', 'Ed Sheeran', 'Ariana Grande'],
        "correct": "0",
        "explanation": "Charlie Puth - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 31,
        "options": ['Sean Paul', 'Taylor Swift', 'Ariana Grande', 'Ed Sheeran'],
        "correct": "0",
        "explanation": "Sean Paul - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 32,
        "options": ['Ed Sheeran', 'Ariana Grande', 'Taylor Swift', 'Bruno Mars'],
        "correct": "0",
        "explanation": "Ed Sheeran - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 33,
        "options": ['James Arthur', 'Ed Sheeran', 'Ariana Grande', 'Taylor Swift'],
        "correct": "0",
        "explanation": "James Arthur - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 34,
        "options": ['Olivia Rodrigo', 'Taylor Swift', 'Ed Sheeran', 'Ariana Grande'],
        "correct": "0",
        "explanation": "Olivia Rodrigo - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 35,
        "options": ['Sam Smith', 'Taylor Swift', 'Ed Sheeran', 'Ariana Grande'],
        "correct": "0",
        "explanation": "Sam Smith - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 36,
        "options": ['Michael Buble', 'Ed Sheeran', 'Taylor Swift', 'Ariana Grande'],
        "correct": "0",
        "explanation": "Michael Buble - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 37,
        "options": ['George Ezra', 'Ariana Grande', 'Ed Sheeran', 'Taylor Swift'],
        "correct": "0",
        "explanation": "George Ezra - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 38,
        "options": ['Keane', 'Ed Sheeran', 'Taylor Swift', 'Ariana Grande'],
        "correct": "0",
        "explanation": "Keane - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 39,
        "options": ['Justin Bieber', 'Taylor Swift', 'Ariana Grande', 'Ed Sheeran'],
        "correct": "0",
        "explanation": "Justin Bieber - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 40,
        "options": ['Lukas Graham', 'Ariana Grande', 'Ed Sheeran', 'Taylor Swift'],
        "correct": "0",
        "explanation": "Lukas Graham - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 41,
        "options": ['James Bay', 'Ed Sheeran', 'Ariana Grande', 'Taylor Swift'],
        "correct": "0",
        "explanation": "James Bay - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 42,
        "options": ['Pharrel Williams', 'Ariana Grande', 'Taylor Swift', 'Ed Sheeran'],
        "correct": "0",
        "explanation": "Pharrel Williams - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 43,
        "options": ['FloRida', 'Taylor Swift', 'Ed Sheeran', 'Ariana Grande'],
        "correct": "0",
        "explanation": "FloRida - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 44,
        "options": ['Will.i.am', 'Taylor Swift', 'Ariana Grande', 'Ed Sheeran'],
        "correct": "0",
        "explanation": "Will.i.am - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 45,
        "options": ['Rihanna', 'Taylor Swift', 'Ariana Grande', 'Ed Sheeran'],
        "correct": "0",
        "explanation": "Rihanna - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 46,
        "options": ['Jason Mraz', 'Ed Sheeran', 'Taylor Swift', 'Ariana Grande'],
        "correct": "0",
        "explanation": "Jason Mraz - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 47,
        "options": ['Harry Styles', 'Taylor Swift', 'Ariana Grande', 'Ed Sheeran'],
        "correct": "0",
        "explanation": "Harry Styles - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 48,
        "options": ['Enrique Iglesias', 'Ariana Grande', 'Taylor Swift', 'Ed Sheeran'],
        "correct": "0",
        "explanation": "Enrique Iglesias - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 49,
        "options": ['John Legend', 'Taylor Swift', 'Ed Sheeran', 'Ariana Grande'],
        "correct": "0",
        "explanation": "John Legend - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 50,
        "options": ['James Blunt', 'Taylor Swift', 'Ariana Grande', 'Ed Sheeran'],
        "correct": "0",
        "explanation": "James Blunt - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 51,
        "options": ['The Weeknd', 'Ed Sheeran', 'Taylor Swift', 'Ariana Grande'],
        "correct": "0",
        "explanation": "The Weeknd - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 52,
        "options": ['Bruno Mars', 'Taylor Swift', 'Ed Sheeran', 'Ariana Grande'],
        "correct": "0",
        "explanation": "Bruno Mars - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 53,
        "options": ['Robbie Williams', 'Ed Sheeran', 'Ariana Grande', 'Taylor Swift'],
        "correct": "0",
        "explanation": "Robbie Williams - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 54,
        "options": ['One Direction', 'Ariana Grande', 'Taylor Swift', 'Ed Sheeran'],
        "correct": "0",
        "explanation": "One Direction - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 55,
        "options": ['Dua Lipa', 'Taylor Swift', 'Ed Sheeran', 'Ariana Grande'],
        "correct": "0",
        "explanation": "Dua Lipa - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 56,
        "options": ['Maroon 5', 'Ariana Grande', 'Taylor Swift', 'Ed Sheeran'],
        "correct": "0",
        "explanation": "Maroon 5 - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 57,
        "options": ['Imagine Dragons', 'Ed Sheeran', 'Ariana Grande', 'Taylor Swift'],
        "correct": "0",
        "explanation": "Imagine Dragons - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 58,
        "options": ['Maneskin', 'Ariana Grande', 'Ed Sheeran', 'Taylor Swift'],
        "correct": "0",
        "explanation": "Maneskin - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 59,
        "options": ['My Chemical Romance', 'Ed Sheeran', 'Taylor Swift', 'Ariana Grande'],
        "correct": "0",
        "explanation": "My Chemical Romance - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 60,
        "options": ['One Republic', 'Taylor Swift', 'Ed Sheeran', 'Ariana Grande'],
        "correct": "0",
        "explanation": "One Republic - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 61,
        "options": ['One Republic', 'Ed Sheeran', 'Taylor Swift', 'Ariana Grande'],
        "correct": "0",
        "explanation": "One Republic - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 62,
        "options": ['The Chainsmokers', 'Taylor Swift', 'Ariana Grande', 'Ed Sheeran'],
        "correct": "0",
        "explanation": "The Chainsmokers - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 63,
        "options": ['Taylor Swift', 'Ariana Grande', 'Bruno Mars', 'Ed Sheeran'],
        "correct": "0",
        "explanation": "Taylor Swift - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    },
    {
        "question": "Ki az előadó?",
        "spotify_embed": "https://open.spotify.com/embed/track/0V3wPSX9ygBnCm8psDIegu",
        "original_index": 64,
        "options": ['Train', 'Taylor Swift', 'Ariana Grande', 'Ed Sheeran'],
        "correct": "0",
        "explanation": "Train - Nemzetközi előadó",
        "topic": "nemzetkozi_zenekarok",
    }
]
