# Auto-generated questions file
# Generated on: 2025-09-19 21:46:41

_TOPIC = "one_hit_wonders"


def _q(question, correct, options, explanation, topic=_TOPIC):
    """Segédfüggvény: kompakt kérdés létrehozása."""
    return {
        "question": question,
        "options": options,
        "correct": correct,
        "explanation": explanation,
        "topic": topic,
    }


ONE_HIT_WONDERS_QUESTIONS = [
    _q("Ki az előadó a 'Teenage Dirtbag' című dalban?", 1, ['Lady Gaga', 'Wheatus', 'Drake', 'Bruno Mars'], "'Teenage Dirtbag' egy One Hit Wonder dal az előadótól: Wheatus"),
    _q("Ki az előadó a 'Somebody That I Used To Know' című dalban?", 1, ['Katy Perry', 'Gotye', 'Justin Bieber', 'Lady Gaga'], "'Somebody That I Used To Know' egy One Hit Wonder dal az előadótól: Gotye"),
    _q("Ki az előadó a 'Tainted Love' című dalban?", 2, ['Ariana Grande', 'Post Malone', 'Soft Cell', 'Billie Eilish'], "'Tainted Love' egy One Hit Wonder dal az előadótól: Soft Cell"),
    _q("Ki az előadó a 'Return of the Mack' című dalban?", 1, ['Drake', 'Mark Morrison', 'The Weeknd', 'One Direction'], "'Return of the Mack' egy One Hit Wonder dal az előadótól: Mark Morrison"),
    _q("Ki az előadó a 'Bad Day' című dalban?", 2, ['Drake', 'Ariana Grande', 'Daniel Powter', 'Rihanna'], "'Bad Day' egy One Hit Wonder dal az előadótól: Daniel Powter"),
    _q("Ki az előadó a 'Bitch' című dalban?", 1, ['Taylor Swift', 'Meredith Brooks', 'Maroon 5', 'Dua Lipa'], "'Bitch' egy One Hit Wonder dal az előadótól: Meredith Brooks"),
    _q("Ki az előadó a 'Ice Ice Baby' című dalban?", 3, ['Ed Sheeran', 'Rihanna', 'Taylor Swift', 'Vanilla Ice'], "'Ice Ice Baby' egy One Hit Wonder dal az előadótól: Vanilla Ice"),
    _q("Ki az előadó a 'Video Killed The Radio Star' című dalban?", 0, ['The Buggles', 'Depeche Mode', 'New Order', 'The Cure'], "'Video Killed The Radio Star' egy One Hit Wonder dal az előadótól: The Buggles"),
    _q("Ki az előadó a 'Walking in Memphis' című dalban?", 0, ['Marc Cohn', 'Bruce Springsteen', 'Bob Dylan', 'Tom Petty'], "'Walking in Memphis' egy One Hit Wonder dal az előadótól: Marc Cohn"),
    _q("Ki az előadó a 'Saturday Night' című dalban?", 0, ['Whigfield', 'Ace of Base', 'Real McCoy', 'La Bouche'], "'Saturday Night' egy One Hit Wonder dal az előadótól: Whigfield"),
    _q("Ki az előadó a 'Who Let The Dogs Out' című dalban?", 0, ['Baha Men', 'Village People', 'Boney M', 'ABBA'], "'Who Let The Dogs Out' egy One Hit Wonder dal az előadótól: Baha Men"),
    _q("Ki az előadó a 'Shake It' című dalban?", 0, ['Metro Station', 'Panic! At The Disco', 'Fall Out Boy', 'My Chemical Romance'], "'Shake It' egy One Hit Wonder dal az előadótól: Metro Station"),
    _q("Ki az előadó az 'Informer' című dalban?", 0, ['Snow', 'Shaggy', 'Maxi Priest', 'Mark Morrison'], "'Informer' egy One Hit Wonder dal az előadótól: Snow"),
    _q("Ki az előadó a 'Jerk It Out' című dalban?", 0, ['Caesars', 'The Strokes', 'The Hives', 'The Vines'], "'Jerk It Out' egy One Hit Wonder dal az előadótól: Caesars"),
    _q("Ki az előadó a 'Heartbeats' című dalban?", 0, ['José González', 'Iron & Wine', 'Bon Iver', 'Fleet Foxes'], "'Heartbeats' egy One Hit Wonder dal az előadótól: José González"),
    _q("Ki az előadó a 'Rude' című dalban?", 0, ['MAGIC!', 'Maroon 5', 'OneRepublic', 'Imagine Dragons'], "'Rude' egy One Hit Wonder dal az előadótól: MAGIC!"),
    _q("Ki az előadó a 'Turn Me On' című dalban?", 0, ['Kevin Lyttle', 'Sean Paul', 'Shaggy', 'Beenie Man'], "'Turn Me On' egy One Hit Wonder dal az előadótól: Kevin Lyttle"),
    _q("Ki az előadó a 'Ring My Bell' című dalban?", 0, ['Anita Ward', 'Donna Summer', 'Gloria Gaynor', 'Diana Ross'], "'Ring My Bell' egy One Hit Wonder dal az előadótól: Anita Ward"),
    _q("Ki az előadó az 'It Just Won't Do' című dalban?", 0, ['Tim Deluxe', 'Basement Jaxx', 'Daft Punk', 'The Chemical Brothers'], "'It Just Won't Do' egy One Hit Wonder dal az előadótól: Tim Deluxe"),
    _q("Ki az előadó a 'Safety Dance' című dalban?", 0, ['Men Without Hats', 'Depeche Mode', 'New Order', 'The Cure'], "'Safety Dance' egy One Hit Wonder dal az előadótól: Men Without Hats"),
    _q("Ki az előadó az 'I Love It' című dalban?", 0, ['Icona Pop', 'Robyn', 'Tove Lo', 'Zara Larsson'], "'I Love It' egy One Hit Wonder dal az előadótól: Icona Pop"),
    _q("Ki az előadó a 'Hold You - Hold Yuh' című dalban?", 0, ['Gyptian', 'Sean Paul', 'Shaggy', 'Beenie Man'], "'Hold You - Hold Yuh' egy One Hit Wonder dal az előadótól: Gyptian"),
    _q("Ki az előadó a 'Macarena' című dalban?", 0, ['Los del Río', 'Ricky Martin', 'Enrique Iglesias', 'Shakira'], "'Macarena' egy One Hit Wonder dal az előadótól: Los del Río"),
    _q("Ki az előadó a 'Gangnam Style' című dalban?", 0, ['PSY', 'Big Bang', '2NE1', 'Wonder Girls'], "'Gangnam Style' egy One Hit Wonder dal az előadótól: PSY"),
    _q("Ki az előadó a 'Harlem Shake' című dalban?", 0, ['Baauer', 'Skrillex', 'Deadmau5', 'Daft Punk'], "'Harlem Shake' egy One Hit Wonder dal az előadótól: Baauer"),
    _q("Ki az előadó a 'Call Me Maybe' című dalban?", 3, ['Drake', 'Coldplay', 'Katy Perry', 'Carly Rae Jepsen'], "'Call Me Maybe' egy One Hit Wonder dal az előadótól: Carly Rae Jepsen"),
    _q("Ki az előadó a 'Royals' című dalban?", 0, ['Lorde', 'Lana Del Rey', 'Florence + The Machine', 'Halsey'], "'Royals' egy One Hit Wonder dal az előadótól: Lorde"),
    _q("Ki az előadó a 'Pumped Up Kicks' című dalban?", 0, ['Foster the People', 'MGMT', 'Passion Pit', 'Vampire Weekend'], "'Pumped Up Kicks' egy One Hit Wonder dal az előadótól: Foster the People"),
    _q("Ki az előadó a 'Some Nights' című dalban?", 0, ['fun.', 'Panic! At The Disco', 'Fall Out Boy', 'My Chemical Romance'], "'Some Nights' egy One Hit Wonder dal az előadótól: fun."),
    _q("Ki az előadó a 'We Are Young' című dalban?", 0, ['fun.', 'Panic! At The Disco', 'Fall Out Boy', 'My Chemical Romance'], "'We Are Young' egy One Hit Wonder dal az előadótól: fun."),
    _q("Ki az előadó a 'Radioactive' című dalban?", 0, ['Imagine Dragons', 'Mumford & Sons', 'The Lumineers', 'Of Monsters and Men'], "'Radioactive' egy One Hit Wonder dal az előadótól: Imagine Dragons"),
    _q("Ki az előadó a 'Sail' című dalban?", 0, ['AWOLNATION', 'Imagine Dragons', 'Mumford & Sons', 'The Lumineers'], "'Sail' egy One Hit Wonder dal az előadótól: AWOLNATION"),
    _q("Ki az előadó a 'Thrift Shop' című dalban?", 2, ['Beyoncé', 'Bruno Mars', 'Macklemore & Ryan Lewis', 'Rihanna'], "'Thrift Shop' egy One Hit Wonder dal az előadótól: Macklemore & Ryan Lewis"),
    _q("Ki az előadó a 'Hold Us' című dalban?", 0, ['Macklemore & Ryan Lewis', 'Billie Eilish', 'Drake', 'Post Malone'], "Macklemore & Ryan Lewis – Can't Hold Us"),
    _q("Ki az előadó a 'Blurred Lines' című dalban?", 0, ['Robin Thicke', 'Pharrell Williams', 'Bruno Mars', 'Justin Timberlake'], "'Blurred Lines' egy One Hit Wonder dal az előadótól: Robin Thicke"),
    _q("Ki az előadó az 'Uptown Funk' című dalban?", 0, ['Mark Ronson ft. Bruno Mars', 'Bruno Mars', 'Pharrell Williams', 'Justin Timberlake'], "'Uptown Funk' egy One Hit Wonder dal az előadótól: Mark Ronson ft. Bruno Mars"),
    _q("Ki az előadó a 'Blank Space' című dalban?", 0, ['Taylor Swift', 'Katy Perry', 'Lady Gaga', 'Rihanna'], "'Blank Space' egy One Hit Wonder dal az előadótól: Taylor Swift"),
    _q("Ki az előadó a 'Shut Up and Dance' című dalban?", 0, ['WALK THE MOON', 'Panic! At The Disco', 'Fall Out Boy', 'My Chemical Romance'], "'Shut Up and Dance' egy One Hit Wonder dal az előadótól: WALK THE MOON"),
    _q("Ki az előadó a 'Cheerleader' című dalban?", 0, ['OMI', 'Sean Paul', 'Shaggy', 'Beenie Man'], "'Cheerleader' egy One Hit Wonder dal az előadótól: OMI"),
    _q("Ki az előadó a 'See You Again' című dalban?", 0, ['Wiz Khalifa ft. Charlie Puth', 'Charlie Puth', 'Wiz Khalifa', 'Post Malone'], "'See You Again' egy One Hit Wonder dal az előadótól: Wiz Khalifa ft. Charlie Puth"),
    _q("Ki az előadó a 'Fancy' című dalban?", 0, ['Iggy Azalea ft. Charli XCX', 'Iggy Azalea', 'Charli XCX', 'Rita Ora'], "'Fancy' egy One Hit Wonder dal az előadótól: Iggy Azalea ft. Charli XCX"),
    _q("Ki az előadó az 'All About That Bass' című dalban?", 0, ['Meghan Trainor', 'Ariana Grande', 'Demi Lovato', 'Selena Gomez'], "'All About That Bass' egy One Hit Wonder dal az előadótól: Meghan Trainor"),
    _q("Ki az előadó a 'Despacito' című dalban?", 0, ['Luis Fonsi ft. Daddy Yankee', 'Enrique Iglesias', 'Ricky Martin', 'Shakira'], "'Despacito' egy One Hit Wonder dal az előadótól: Luis Fonsi ft. Daddy Yankee"),
    _q("Ki az előadó a 'Shape of You' című dalban?", 0, ['Ed Sheeran', 'James Blunt', 'Robbie Williams', 'Gary Barlow'], "'Shape of You' egy One Hit Wonder dal az előadótól: Ed Sheeran"),
    _q("Ki az előadó a 'Havana' című dalban?", 0, ['Camila Cabello', 'Fifth Harmony', 'Little Mix', 'Ariana Grande'], "'Havana' egy One Hit Wonder dal az előadótól: Camila Cabello"),
    _q("Ki az előadó a 'Bad Guy' című dalban?", 0, ['Billie Eilish', 'Lorde', 'Lana Del Rey', 'Halsey'], "'Bad Guy' egy One Hit Wonder dal az előadótól: Billie Eilish"),
    _q("Ki az előadó az 'Old Town Road' című dalban?", 0, ['Lil Nas X', 'Post Malone', 'Travis Scott', 'Migos'], "'Old Town Road' egy One Hit Wonder dal az előadótól: Lil Nas X"),
    _q("Ki az előadó a 'Dance Monkey' című dalban?", 0, ['Tones and I', 'Billie Eilish', 'Lorde', 'Halsey'], "'Dance Monkey' egy One Hit Wonder dal az előadótól: Tones and I"),
    _q("Ki az előadó a 'Blinding Lights' című dalban?", 0, ['The Weeknd', 'Post Malone', 'Drake', 'Travis Scott'], "'Blinding Lights' egy One Hit Wonder dal az előadótól: The Weeknd"),
    _q("Ki az előadó a 'Stay' című dalban?", 0, ['The Kid LAROI & Justin Bieber', 'Justin Bieber', 'The Kid LAROI', 'Post Malone'], "'Stay' egy One Hit Wonder dal az előadótól: The Kid LAROI & Justin Bieber"),
    _q("Ki az előadó a 'Flowers' című dalban?", 0, ['Miley Cyrus', 'Selena Gomez', 'Demi Lovato', 'Ariana Grande'], "'Flowers' egy One Hit Wonder dal az előadótól: Miley Cyrus"),
    _q("Ki az előadó a 'Cruel Summer' című dalban?", 0, ['Taylor Swift', 'Katy Perry', 'Lady Gaga', 'Rihanna'], "'Cruel Summer' egy One Hit Wonder dal az előadótól: Taylor Swift"),
    _q("Ki az előadó a 'Last Night' című dalban?", 0, ['Morgan Wallen', 'Luke Combs', 'Florida Georgia Line', 'Blake Shelton'], "'Last Night' egy One Hit Wonder dal az előadótól: Morgan Wallen"),
    _q("Ki az előadó a 'Smooth Criminal' című dalban?", 1, ['Michael Jackson', 'Alien Ant Farm', 'The Weeknd', 'Bruno Mars'], "'Smooth Criminal' egy One Hit Wonder dal az előadótól: Alien Ant Farm"),
    _q("Ki az előadó a 'Lemon Tree' című dalban?", 0, ['Fools Garden', 'The Cranberries', 'The Cardigans', 'The Corrs'], "'Lemon Tree' egy One Hit Wonder dal az előadótól: Fools Garden"),
    _q("Ki az előadó a 'Stolen Dance' című dalban?", 0, ['Milky Chance', 'Of Monsters and Men', 'Vance Joy', 'Passenger'], "'Stolen Dance' egy One Hit Wonder dal az előadótól: Milky Chance"),
    _q("Ki az előadó a 'Mr. Toot' című dalban?", 0, ['Ylvis', 'Bastille', 'Imagine Dragons', 'Bambee'], "'Mr. Toot' egy One Hit Wonder dal az előadótól: Ylvis"),
    _q("Ki az előadó a 'Bitter Sweet Symphony' című dalban?", 0, ['The Verve', 'Bastille', 'Imagine Dragons', 'The Pulp'], "'Bitter Sweet Symphony' egy One Hit Wonder dal az előadótól: The Verve"),
    _q("Ki az előadó az 'One Night in Bangkok' című dalban?", 0, ['Murray Head', 'Bananarama', 'Fleetwood Mac', 'Bee Gees'], "'One Night in Bangkok' egy One Hit Wonder dal az előadótól: Murray Head"),
    _q("Ki az előadó a 'Goodnight Moon' című dalban?", 0, ['Shivaree', 'Urge Overkill', 'Dusty Springfield', 'Tanita Tikaram'], "'Goodnight Moon' egy One Hit Wonder dal az előadótól: Shivaree"),
    _q("Ki az előadó a 'Black Betty' című dalban?", 0, ['RamJam', 'Jerry Lee Lewis', 'Elvis Presley', 'Little Richard'], 'RamJam - Black Betty'),
    _q("Ki az előadó a 'The Entertainer' című dalban?", 0, ['Scott Joplin', 'Janis Joplin', 'George Gershwin', 'Oscar Petterson'], 'Scott Joplin - The Entertainer'),
    _q("Ki az előadó a 'Come On Eileen' című dalban?", 0, ['Dexys Midnight Runners', 'The Clash', 'The Jam', 'Madness'], "'Come On Eileen' – Dexys Midnight Runners (1982)"),
    _q("Ki az előadó az 'Im Too Sexy' című dalban?", 0, ['Right Said Fred', 'Frankie Goes to Hollywood', 'Spandau Ballet', 'Kajagoogoo'], "Right Said Fred – I'm Too Sexy (1992)"),
    _q("Ki az előadó a 'Take On Me' című dalban?", 0, ['a-ha', 'Duran Duran', 'The Human League', 'Talk Talk'], "'Take On Me' – a-ha (1985)"),
    _q("Ki az előadó a 'You Light Up My Life' című dalban?", 0, ['Debby Boone', 'Olivia Newton-John', 'Kim Carnes', 'Carly Simon'], "'You Light Up My Life' – Debby Boone (1977)"),
    _q("Ki az előadó a 'Baby Got Back' című dalban?", 0, ['Sir Mix-A-Lot', 'MC Hammer', 'Vanilla Ice', 'Biz Markie'], "'Baby Got Back' – Sir Mix-A-Lot (1992)"),
    _q("Ki az előadó a 'The Hustle' című dalban?", 0, ['Van McCoy', 'Barry White', 'KC and the Sunshine Band', 'Chic'], "'The Hustle' – Van McCoy (1975)"),
    _q("Ki az előadó a 'Groove Is in the Heart' című dalban?", 0, ['Deee-Lite', 'Snap!', 'C+C Music Factory', '2 Unlimited'], "'Groove Is in the Heart' – Deee-Lite (1990)"),
    _q("Ki az előadó a 'Rapper's Delight' című dalban?", 0, ['The Sugarhill Gang', 'Grandmaster Flash', 'Kurtis Blow', 'Afrika Bambaataa'], "'Rapper's Delight' – The Sugarhill Gang (1979)"),
    _q("Ki az előadó a 'Were Not Gonna Take It' című dalban?", 0, ['Twisted Sister', 'Quiet Riot', 'Poison', 'W.A.S.P.'], "Twisted Sister – We're Not Gonna Take It (1984)"),
    _q("Ki az előadó a 'Nothing Compares 2 U' című dalban?", 0, ['Sinéad O\'Connor', 'Annie Lennox', 'k.d. lang', 'Tracy Chapman'], "'Nothing Compares 2 U' – Sinéad O'Connor (1990)"),
    _q("Ki az előadó a 'Play That Funky Music' című dalban?", 0, ['Wild Cherry', 'Average White Band', 'War', 'Tower of Power'], "'Play That Funky Music' – Wild Cherry (1976)"),
    _q("Ki az előadó az 'All My Life' című dalban?", 0, ['K-Ci & JoJo', 'Boyz II Men', 'Brian McKnight', '112'], "'All My Life' – K-Ci & JoJo (1998)"),
    _q("Ki az előadó a 'Too Shy' című dalban?", 0, ['Kajagoogoo', 'A Flock of Seagulls', 'Spandau Ballet', 'Culture Club'], "'Too Shy' – Kajagoogoo (1983)"),
    _q("Ki az előadó a 'Stumblin' In' című dalban?", 0, ['Suzi Quatro', 'Joan Jett', 'Pat Benatar', 'Blondie'], "'Stumblin' In' – Suzi Quatro (1978)"),
    _q("Ki az előadó a 'Seasons in the Sun' című dalban?", 0, ['Terry Jacks', 'Glen Campbell', 'John Denver', 'Harry Nilsson'], "'Seasons in the Sun' – Terry Jacks (1974)"),
    _q("Ki az előadó az 'Unbelievable' című dalban?", 0, ['EMF', 'Jesus Jones', 'Carter USM', 'Ned\'s Atomic Dustbin'], "'Unbelievable' – EMF (1990)"),
    _q("Ki az előadó a 'Got to Be Real' című dalban?", 0, ['Cheryl Lynn', 'Chaka Khan', 'Gloria Gaynor', 'Donna Summer'], "'Got to Be Real' – Cheryl Lynn (1978)"),
    _q("Ki az előadó a 'Me and Mrs. Jones' című dalban?", 0, ['Billy Paul', 'Marvin Gaye', 'Al Green', 'Teddy Pendergrass'], "'Me and Mrs. Jones' – Billy Paul (1972)"),
    _q("Ki az előadó a 'Relax' című dalban?", 0, ['Frankie Goes to Hollywood', 'Pet Shop Boys', 'Bronski Beat', 'Yazoo'], "'Relax' – Frankie Goes to Hollywood (1984)"),
    _q("Ki az előadó a 'Rock Me Amadeus' című dalban?", 0, ['Falco', 'Klaus Nomi', 'Nena', 'Peter Schilling'], "'Rock Me Amadeus' – Falco (1985)"),
    _q("Ki az előadó a 'Lovefool' című dalban?", 0, ['The Cardigans', 'Roxette', 'Ace of Base', 'Robyn'], "'Lovefool' – The Cardigans (1996)"),
    _q("Ki az előadó a 'Don't Worry, Be Happy' című dalban?", 0, ['Bobby McFerrin', 'Jimmy Cliff', 'Bob Marley', 'UB40'], "'Don't Worry, Be Happy' – Bobby McFerrin (1988)"),
    _q("Ki az előadó a 'True' című dalban?", 0, ['Spandau Ballet', 'Duran Duran', 'Wham!', 'Culture Club'], "'True' – Spandau Ballet (1983)"),
    _q("Ki az előadó a '500 Miles' című dalban?", 0, ['The Proclaimers', 'Deacon Blue', 'The Waterboys', 'Aztec Camera'], "The Proclaimers – I'm Gonna Be (500 Miles) (1988)"),
    _q("Ki az előadó az 'Its Raining Men' című dalban?", 0, ['The Weather Girls', 'Gloria Gaynor', 'Sister Sledge', 'Pointer Sisters'], "The Weather Girls – It's Raining Men (1982)"),
    _q("Ki az előadó a 'What Is Love' című dalban?", 0, ['Haddaway', 'Snap!', 'Real McCoy', '2 Unlimited'], "'What Is Love' – Haddaway (1993)"),
    _q("Ki az előadó a 'The Future's So Bright, I Gotta Wear Shades' című dalban?", 0, ['Timbuk 3', 'They Might Be Giants', 'R.E.M.', 'The B-52s'], "'The Future's So Bright' – Timbuk 3 (1986)"),
    _q("Ki az előadó a 'Jump Around' című dalban?", 0, ['House of Pain', 'Cypress Hill', 'Naughty By Nature', 'Tag Team'], "'Jump Around' – House of Pain (1992)"),
    _q("Ki az előadó a 'You Get What You Give' című dalban?", 0, ['New Radicals', 'Third Eye Blind', 'Semisonic', 'Fastball'], "'You Get What You Give' – New Radicals (1998)"),
    _q("Ki az előadó a 'Mambo No. 5' című dalban?", 0, ['Lou Bega', 'Ricky Martin', 'Marc Anthony', 'Enrique Iglesias'], "'Mambo No. 5' – Lou Bega (1999)"),
    _q("Ki az előadó az 'Epic' című dalban?", 0, ['Faith No More', 'Primus', 'Mr. Bungle', 'Red Hot Chili Peppers'], "'Epic' – Faith No More (1989)"),
    _q("Ki az előadó az 'A Girl Like You' című dalban?", 0, ['Edwyn Collins', 'The Proclaimers', 'Lloyd Cole', 'Prefab Sprout'], "'A Girl Like You' – Edwyn Collins (1994)"),
    _q("Ki az előadó a 'How Bizarre' című dalban?", 0, ['OMC', 'Crowded House', 'Split Enz', 'Shihad'], "'How Bizarre' – OMC (1995)"),
    _q("Ki az előadó a 'Maniac' című dalban?", 0, ['Michael Sembello', 'Giorgio Moroder', 'Harold Faltermeyer', 'Kenny Loggins'], "'Maniac' – Michael Sembello (1983, Flashdance)"),
    _q("Ki az előadó az 'Mmm Mmm Mmm Mmm' című dalban?", 0, ['Crash Test Dummies', 'Barenaked Ladies', 'The Tragically Hip', 'Great Big Sea'], "'Mmm Mmm Mmm Mmm' – Crash Test Dummies (1993)"),
    _q("Ki az előadó a 'Puttin' on the Ritz' című dalban?", 0, ['Taco', 'Fred Astaire', 'Mel Brooks', 'Jive Bunny'], "'Puttin' on the Ritz' – Taco (1982)"),
    _q("Ki az előadó a 'You Gotta Be' című dalban?", 0, ["Des'ree", 'Tracy Chapman', 'Sade', 'Lisa Stansfield'], "'You Gotta Be' – Des'ree (1994)"),
    _q("Ki az előadó az 'Achy Breaky Heart' című dalban?", 0, ['Billy Ray Cyrus', 'Garth Brooks', 'Alan Jackson', 'Brooks & Dunn'], "'Achy Breaky Heart' – Billy Ray Cyrus (1992)"),
    _q("Ki az előadó az 'Electric Avenue' című dalban?", 0, ['Eddy Grant', 'Jimmy Cliff', 'Steel Pulse', 'UB40'], "'Electric Avenue' – Eddy Grant (1982)"),
    _q("Ki az előadó a 'China in Your Hand' című dalban?", 0, ["T'Pau", 'Kim Wilde', 'Transvision Vamp', 'Shakespears Sister'], "'China in Your Hand' – T'Pau (1987)"),
    _q("Ki az előadó a 'Whats Up' című dalban?", 0, ['4 Non Blondes', 'Alanis Morissette', 'Sheryl Crow', 'Melissa Etheridge'], "4 Non Blondes – What's Up (1992)"),
    _q("Ki az előadó az 'I Want Candy' című dalban?", 0, ['Bow Wow Wow', 'Blondie', 'The B-52s', 'The Bangles'], "'I Want Candy' – Bow Wow Wow (1982)"),
    _q("Ki az előadó a 'Kung Fu Fighting' című dalban?", 0, ['Carl Douglas', 'David Bowie', 'T. Rex', 'Slade'], "'Kung Fu Fighting' – Carl Douglas (1974)"),
    _q("Ki az előadó az 'Everytime We Touch' című dalban?", 0, ['Cascada', 'Basshunter', 'Scooter', 'ATB'], "'Everytime We Touch' – Cascada (2005)"),
    _q("Ki az előadó a 'Living Next Door to Alice' című dalban?", 0, ['Smokie', 'Sweet', 'Mud', 'Bay City Rollers'], "'Living Next Door to Alice' – Smokie (1976)"),
    _q("Ki az előadó az 'I Wanna Be with U' című dalban?", 0, ['Fun Factory', 'Corona', '2 Unlimited', 'Haddaway'], "'I Wanna Be with U' – Fun Factory (1994)"),
    _q("Ki az előadó az 'Ive Been Thinking About You' című dalban?", 0, ['London Beat', 'Swing Out Sister', 'Lisa Stansfield', 'Soul II Soul'], "'I've Been Thinking About You' – London Beat (1990)"),
    _q("Ki az előadó a 'Boom Boom Boom Boom' című dalban?", 0, ['Vengaboys', '2 Unlimited', 'Haddaway', 'Corona'], "'Boom, Boom, Boom, Boom!!' – Vengaboys (1998)"),
    _q("Ki az előadó a 'Somewhere in My Heart' című dalban?", 0, ['Aztec Camera', 'The Blue Nile', 'Prefab Sprout', 'Lloyd Cole'], "'Somewhere in My Heart' – Aztec Camera (1988)"),
    _q("Ki az előadó a 'Wicked Game' című dalban?", 0, ['Chris Isaak', 'Lenny Kravitz', 'Bryan Adams', 'Chris Rea'], "'Wicked Game' – Chris Isaak (1990)"),
    _q("Ki az előadó a 'Tubthumping' című dalban?", 0, ['Chumbawamba', 'Carter USM', 'Pop Will Eat Itself', 'The Levellers'], "'Tubthumping' – Chumbawamba (1997)"),
    _q("Ki az előadó a 'Baby I Love Your Way' című dalban?", 0, ['Big Mountain', 'UB40', 'Maxi Priest', 'Bitty McLean'], "'Baby, I Love Your Way' – Big Mountain (1994)"),
    _q("Ki az előadó a 'Sleeping Satellite' című dalban?", 0, ['Tasmin Archer', 'Tanita Tikaram', 'Lisa Stansfield', 'Alison Moyet'], "'Sleeping Satellite' – Tasmin Archer (1992)"),
    _q("Ki az előadó a 'Save Tonight' című dalban?", 0, ['Eagle-Eye Cherry', 'Semisonic', 'Fastball', 'Wheatus'], "'Save Tonight' – Eagle-Eye Cherry (1997)"),
    _q("Ki az előadó a 'Breakfast at Tiffanys' című dalban?", 0, ['Deep Blue Something', 'Toad the Wet Sprocket', 'Dishwalla', 'Gin Blossoms'], "'Breakfast at Tiffany's' – Deep Blue Something (1995)"),
    _q("Ki az előadó a 'Steal My Sunshine' című dalban?", 0, ['Len', 'Smash Mouth', 'Fountains of Wayne', 'Sugar Ray'], "'Steal My Sunshine' – Len (1999)"),
    _q("Ki az előadó a 'Your Woman' című dalban?", 0, ['White Town', 'Saint Etienne', 'Pulp', 'Menswe@r'], "'Your Woman' – White Town (1997)"),
    _q("Ki az előadó a 'Connected' című dalban?", 0, ['Stereo MCs', 'Massive Attack', 'Portishead', 'Tricky'], "'Connected' – Stereo MCs (1992)"),
    _q("Ki az előadó a 'Life Is a Highway' című dalban?", 0, ['Tom Cochrane', 'Bryan Adams', 'John Mellencamp', 'Bob Seger'], "'Life Is a Highway' – Tom Cochrane (1991)"),
    _q("Ki az előadó a 'One of Us' című dalban?", 0, ['Joan Osborne', 'Alanis Morissette', 'Sheryl Crow', 'Tracy Chapman'], "'One of Us' – Joan Osborne (1995)"),
    _q("Ki az előadó a 'Bad Boys' című dalban?", 0, ['Inner Circle', 'UB40', 'Shaggy', 'Ini Kamoze'], "'Bad Boys' – Inner Circle (1994)"),
    _q("Ki az előadó a 'Pump Up the Jam' című dalban?", 0, ['Technotronic', 'Black Box', 'C+C Music Factory', '2 Unlimited'], "'Pump Up the Jam' – Technotronic (1989)"),
    _q("Ki az előadó az 'I Try' című dalban?", 0, ['Macy Gray', 'Erykah Badu', 'Jill Scott', 'India.Arie'], "'I Try' – Macy Gray (1999)"),
    _q("Ki az előadó a 'Here Comes the Hotstepper' című dalban?", 0, ['Ini Kamoze', 'Inner Circle', 'Shaggy', 'Chaka Demus'], "'Here Comes the Hotstepper' – Ini Kamoze (1994)"),
    _q("Ki az előadó a 'Rhythm of the Night' című dalban?", 0, ['Corona', 'Haddaway', '2 Unlimited', 'Robin S.'], "'The Rhythm of the Night' – Corona (1993)"),
    _q("Ki az előadó a 'Femme Like You' című dalban?", 0, ["K'maro", 'Rohff', 'Booba', 'Sinik'], "'Femme Like You' – K'maro (2004)"),
    _q("Ki az előadó a 'Missing' című dalban?", 0, ['Everything but the Girl', 'Portishead', 'Sneaker Pimps', 'Lamb'], "'Missing' – Everything but the Girl (1994)"),
]

# Export alias for quiz_app
QUESTIONS = ONE_HIT_WONDERS_QUESTIONS