# politika kvíz kérdések

_TOPIC = "politika"


def _q(question, correct, options, explanation, topic=_TOPIC):
    """Segédfüggvény: kompakt kérdés létrehozása."""
    return {"question": question, "options": options, "correct": correct, "explanation": explanation, "topic": topic}


POLITIKA_QUESTIONS = [
    _q('1939. november 1-jén csatolták Németországhoz Auschwitz (Oświęcim) városát, az itt felépített koncentrációs táborban pedig pontosan öt évvel később történt az utolsó elgázosítás, amikor is az elhurcolt, főként zsidó embereket Zyklon-B gázzal megölték. A gázkamrákat a németek 1944 novemberében felrobbantották, mivel igyekeztek elrejteni tetteiket a közeledő szovjet csapatok elől. A koncentrációs táborokat az SS működtette. Ki volt ennek parancsnoka?', 0, ['Heinrich Himmler', 'Reinhard Heydrich', 'Hermann Göring', 'Joseph Goebbels'], 'Helyes válasz: Heinrich Himmler'),
    _q('November 9-e Németország sorsnapja: az ország évezredes történelme során több jelentős esemény is ezen a napon történt. Az alábbiak közül melyik nem?', 1, ['A müncheni sörpuccs (1923) – Hitler sikertelen hatalomátvételi kísérlete', 'Az 1. világháború kitörése: Németország hadat üzen Oroszországnak és Franciaországnak (1914)', 'Kristályéjszaka (1938) – központilag szervezett, országos zsidóellenes pogromok', 'A berlini fal ledöntése (1989)'], 'Helyes válasz: Az 1. világháború kitörése: Németország hadat üzen Oroszországnak és Franciaországnak (1914)'),
    _q('1938. november 10-én hunyt el Mustafa Kemal Atatürk török katonatiszt, politikus, államférfi, a modern Törökország megalapítója. Emlékének megsértését Törökországban törvény bünteti. Számos építmény viseli nevét és a török pénzeken is az ő arcképe látható. Mi a fizetőeszköz Törökországban?', 2, ['török dínár', 'sékel', 'török líra', 'török dollár'], 'Helyes válasz: török líra'),
    _q('1982. november 10-én hunyt el Leonyid Iljics Brezsnyev szovjet politikus, aki 1964. október 14-étől haláláig az SZKP főtitkáraként a Szovjetunió vezetője volt. Két szenvedélye volt, az egyik a vadászat (több alkalommal is vadászott Magyarországon Kádár Jánossal). Mi volt a másik?', 0, ['autók gyűjtése', 'horgászat', 'repülés', 'éremgyűjtés'], 'Helyes válasz: autók gyűjtése'),
    _q('1982. november 12-étől 15 hónapon keresztül Jurij Andropov szovjet politikus töltötte be a Szovjetunió Kommunista Pártja főtitkári tisztségét. Az országban a párttagok sok mindenhez hozzájuthattak, amihez a közönséges szovjet polgárok nem, például jobban ellátott üzletekben vásárolhattak és számukra, illetve gyermekeik számára voltak fenntartva a presztízzsel rendelkező állások. Az 1980-as években a felnőtt lakosság hány százaléka volt párttag?', 0, ['kb. 10%', 'kb. 25%', 'kb. 40%', 'kb. 65%'], 'Helyes válasz: kb. 10%'),
    _q('1988. november 13-án alakult meg a Szabad Demokraták Szövetsége, amely 1990 és 2010 között parlamenti párt volt. Politikai ideológiáját liberálisként határozta meg. 1994–1998 és 2002–2008 között a kormánykoalíció kisebbségi tagja volt. Ki volt a párt első elnöke, 1990-től?', 1, ['Demszky Gábor', 'Kis János', 'Kuncze Gábor', 'Tölgyessy Péter'], 'Helyes válasz: Kis János'),
    _q('1942. november 20-án született Joe Biden, az Amerikai Egyesült Államok jelenlegi, 46. elnöke. 2009–2017 között az ország alelnöke volt Barack Obama elnöksége alatt. Korábban három évtizeden keresztül az egyik amerikai állam szenátora volt, hatszor választották újra. Melyik államé?', 3, ['Texas', 'Dél-Dakota', 'Arkansas', 'Delaware'], 'Helyes válasz: Delaware'),
    _q('1945. november 20-án kezdődött meg a nürnbergi per, az első olyan per, amelyben a szövetséges hatalmak a Német Birodalom politikai, katonai és gazdasági vezetői felett ítélkeztek a második világháború során elkövetett bűneik miatt. Ki volt az a német vezető, akit a perben kötél általi halálra ítéltek, de az ítélet végrehajtása előtt öngyilkosságot követett el?', 0, ['Hermann Göring', 'Rudolf Heß', 'Joachim von Ribbentrop', 'Arthur Seyß-Inquart'], 'Helyes válasz: Hermann Göring'),
    _q('1890. november 22-én született Charles de Gaulle francia tábornok, államférfi, az Ötödik Francia Köztársaság első elnöke. A 2. világháborúban a francia nemzeti függetlenség feltétlen híveként szervezte és irányította a francia ellenállási mozgalmat. Melyik város repülőterét nevezték el róla?', 1, ['Nizza (Côte d’Azur)', 'Párizs', 'Marseille', 'Lyon'], 'Helyes válasz: Párizs'),
    _q('November 25-e a nők elleni erőszak felszámolásának világnapja. 1960-ban ezen a napon gyilkoltak meg három nővért, Minerva, Patria és Teresa Mirabalt, akik feminista aktivisták és Trujillo diktátor politikai ellenfelei voltak. Melyik latin-amerikai országban történt ez?', 2, ['Haiti', 'Venezuela', 'Dominikai Köztársaság', 'Guatemala'], 'Helyes válasz: Dominikai Köztársaság'),
    _q('2006. december 10-én hunyt el Augusto Pinochet tábornok, a hadsereg főparancsnoka, 1973 és 1990 között országának vezetője, majd haláláig szenátor. A hatalmat puccsal ragadta magához. Melyik ország diktátora volt?', 2, ['Bolívia', 'Paraguay', 'Chile', 'Peru'], 'Helyes válasz: Chile'),
    _q('2007-ben ezen a napon szűnt meg az Ikarus gyár. Az állami autóbuszgyártó cég elődje az 1895-ben alapított Uhry Imre Kovács- és Kocsigyártó Üzeme volt. Komplett autóbuszokat csak a 2. világháború után kezdtek gyártani. A rendszerváltást követően a korábban sikeres vállalat hanyatlásnak indult. Milyen nemzetiségű volt a vállalat utolsó tulajdonosa?', 3, ['holland', 'német', 'orosz', 'francia'], 'Helyes válasz: francia'),
    _q('1974-ben ezen a napon kiáltották ki a köztársaságot Máltán. 1964-ben váltak függetlenné Nagy-Britanniától, de 10 évig még II. Erzsébet brit királynő volt Málta államfője. Melyik állítás NEM igaz Máltával kapcsolatban?', 1, ['Málta az Európai Unió legkisebb tagállama', 'Az ország élővilága igen gazdag, különösen sokféle emlős él a szigeteken', 'Az ország egyik legnagyobb problémája az ivóvíz hiánya', 'Málta legmagasabb pontja csupán 253 méteres'], 'Helyes válasz: Az ország élővilága igen gazdag, különösen sokféle emlős él a szigeteken'),
    _q('1830. december 17-én, 47 éves korában hunyt el Simón Bolívar, a dél-amerikai függetlenségi mozgalom vezetője, később Nagy-Kolumbia elnöke, Venezuela elnöke, majd Peru és Venezuela diktátora. Róla kapta nevét Bolívia, illetve az egyik dél-amerikai ország pénze. Melyik országban fizetnek bolívarral?', 1, ['Ecuador', 'Venezuela', 'Kuba', 'Peru'], 'Helyes válasz: Venezuela'),
    _q('1878. december 18-án született Joszif Visszarionovics Sztálin, születési nevén Ioszeb Dzsugasvili. Apai ágon oszét, anyai ágon grúz származású volt. A Sztálin nevet először a Szociál-demokratában 1913. január 12-én megjelent cikkében használta; a névválasztást sehol nem indokolta. A név az orosz „acél” szóból származik. Melyik évben halt meg Sztálin?', 1, ['1946', '1953', '1956', '1962'], 'Helyes válasz: 1953'),
    _q('1906. december 19-én született Leonyid Iljics Brezsnyev szovjet politikus, aki 1964. október 14-étől haláláig az SZKP főtitkáraként a Szovjetunió vezetője volt. Két szenvedélye volt, az egyik a vadászat (több alkalommal is vadászott Magyarországon Kádár Jánossal). Mi volt a másik?', 1, ['éremgyűjtés', 'autók gyűjtése', 'horgászat', 'repülés'], 'Helyes válasz: autók gyűjtése'),
    _q('1949. december 21-én nyitották meg az első pesti trolibusz-vonalat, amely Sztálin iránti tiszteletből a 70-es számot kapta. Az első budapesti troli még a 2. világháború előtt indult  Óbudán, a Vörösvári út és az Óbudai temető között, 7-es jelzéssel. Melyik évben?', 2, ['1923', '1928', '1933', '1938'], 'Helyes válasz: 1933'),
    _q('1989-ben, 30 év után, újra megnyitották a Brandenburgi kaput. A Berlin központjában levő korai klasszicista építmény jelentette a határt Kelet-Berlin és Nyugat-Berlin között és egyúttal a Varsói Szerződés és a NATO országai között. A német újraegyesítésig a hidegháború jelképe volt, majd 1990 után Németország és Európa újraegyesítésének szimbóluma lett. Kinek az alakja látható a kapu tetején, a négylovas ókori díszkocsin?', 3, ['Minerva, a kézművesség és az ipar védője', 'Mars, a háborúk istene', 'Zeusz, görög főisten', 'Niké, a győzelem istennője'], 'Helyes válasz: Niké, a győzelem istennője'),
    _q('1990. december 23-án tartották Szlovániában azt a népszavazást, amelynek eredményeképp az ország függetlenné vált Jugoszláviától. Mi történt a függetlenség 1991. június 25-i kikiáltását követően?', 3, ['Jugoszlávia a teljes felbomlásáig sem ismerte el az országot', 'A Jugoszláv vezetés gazdasági szankciókkal sújtották a területet', 'Európa vezető hatalmai azonnal elismerték a független Szlovéniát, ezért a jugoszláv vezetés sem tehetett mást', 'A Jugoszláv Hadsereg megtámadta az országot, a harcok kb. 10 napig tartottak'], 'Helyes válasz: A Jugoszláv Hadsereg megtámadta az országot, a harcok kb. 10 napig tartottak'),
    _q('2007. január 1-jén két új tagja is lett az Európai Uniónak. Az egyik Románia volt – és melyik volt a másik?', 3, ['Horvátország', 'Szerbia', 'Lettország', 'Bulgária'], 'Helyes válasz: Bulgária'),
    _q('1974. január 4-én tagadta meg az amerikai elnök a Watergate Bizottság által kért iratok átadását. Ki volt az az elnök, aki belebukott a Watergate-botrányba?', 1, ['Gerald Ford', 'Richard Nixon', 'Lyndon B. Johnson', 'Dwight D. Eisenhower'], 'Helyes válasz: Richard Nixon'),
    _q('1984-ben ezen a napon született Kim Dzsongun, aki 2011 óta Észak-Korea diktátora. Mi Észak-Korea fővárosa?', 0, ['Phenjan', 'Szöul', 'Hongkong', 'Peking'], 'Helyes válasz: Phenjan'),
    _q('1920-ban, a Versailles-i békeszerződés határozatának megfelelően megkezdte működését a Népszövetség. Melyik mai szervezet elődje volt?', 1, ['UNESCO', 'ENSZ', 'Európai Unió', 'WHO'], 'Helyes válasz: ENSZ'),
    _q('1969. január 16-án Jan Palach, a prágai Károly Egyetem 20 éves diákja a prágai Vencel téren felgyújtotta magát a Prágai tavasz Szovjetunió általi eltiprása elleni tiltakozásul. Ki volt ekkor a szovjet pártvezető?', 1, ['Nyikita Szergejevics Hruscsov', 'Leonyid Brezsnyev', 'Jurij Andropov', 'Konsztantyin Csernyenko'], 'Helyes válasz: Leonyid Brezsnyev'),
    _q('Ezen a napon tartották Horvátországban azt a népszavazást, amelyen az ország lakosságának kétharmada támogatta, hogy csatlakozzanak az Európai Unióhoz. Melyik évben volt a csatlakozás?', 2, ['2005', '2009', '2013', '2017'], 'Helyes válasz: 2013'),
    _q('1918. január 26-án született Nicolae Ceauşescu, aki 1989-es kivégzéséig a Román Kommunista Párt vezetőjeként Románia vezetője volt. Mikortól, vagyis mikor került a párt élére?', 2, ['1945', '1955', '1965', '1975'], 'Helyes válasz: 1965'),
    _q('Január 28-a az adatvédelem nemzetközi napja. Melyik állítás NEM igaz az alábbiak közül?', 3, ['Az info@vallalkozasnev.hu típusú email cím nem személyes adat', 'Személyes adat csak a cél megvalósulásához szükséges mértékben és ideig kezelhető', '2018-tól egységes adatvédelmi rendelkezések érvényesek az Európai Unióban', 'A cégek csak akkor kezelhetik magánszemélyek adatait, ha az érintettek hozzájárultak'], 'Helyes válasz: A cégek csak akkor kezelhetik magánszemélyek adatait, ha az érintettek hozzájárultak'),
    _q('Az Egyesült Királyság 2020. január 31-én kilépett az Európai Unióból. Melyik évben tartották a népszavazást, ami alapján megtörtént a Brexit?', 2, ['2010', '2013', '2016', '2019'], 'Helyes válasz: 2016'),
    _q('1992. február 7-én írták alá a maastrichti szerződést. Minek a megalakulását jelentette ez?', 0, ['Európai Unió', 'NATO', 'Egészségügyi Világszerveze (WHO)', 'Természetvédelmi Világalap (WWF)'], 'Helyes válasz: Európai Unió'),
    _q('1957. február 9-én hunyt el Horthy Miklós ellentengernagy, 1944. október 16-ig Magyarország kormányzója. Mi történt vele ezt követően?', 1, ['Öngyilkosságot követett el', 'Német, majd amerikai fogságot követően Bajorországban, később Portugáliában élt', 'Szovjet hadifogságba került', 'A nürnbergi perben elítélték'], 'Helyes válasz: Német, majd amerikai fogságot követően Bajorországban, később Portugáliában élt'),
    _q('1807. február 10-én született Batthyány Lajos gróf, Magyarország első alkotmányos miniszterelnöke. Melyik évben alakított kormányt?', 1, ['1836', '1848', '1856', '1867'], 'Helyes válasz: 1848'),
    _q('1990. február 11-én, 27 évnyi fogság után szabadon bocsátották Nelson Mandela dél-afrikai fekete aktivistát (később Nobel-békedíjas, dél-afrikai elnök). Az apartheid, a faji megkülönböztetés 1994-ben megszűnt Dél-Afrikában. Melyik állítás NEM igaz?', 0, ['Az apartheid bevezetése idején Dél-Afrikában kb. fele-fele arányban éltek fehérek és feketék', 'Az apartheid idején a fehérek kezében volt a gazdasági és a politikai hatalom', 'Az apartheid idején külön parkokat hoztak létre a feketéknek és a fehéreknek', 'Az apartheid idején ha egy fehér megvert egy helyi lakost, az utóbbi nem üthetett vissza, különben bíróság elé került'], 'Helyes válasz: Az apartheid bevezetése idején Dél-Afrikában kb. fele-fele arányban éltek fehérek és feketék'),
    _q('1893. február 14-én az USA annektálta Hawaii-t, azóta a szigetcsoport is az Egyesült Államok része, 1959 óta pedig az 50. tagállama. Hawaii exklávé tagállam. Mit jelent ez?', 0, ['Azt jelenti, hogy a területe nem kapcsolódik az anyaországhoz', 'Hawaii-nak saját kormányzata van, nem ismeri el az USA elnökét', 'Nem szabad akaratából csatlakozott az Egyesült Államokhoz', 'Földrajzilag nem Amerikához, hanem Óceániához tartozik'], 'Helyes válasz: Azt jelenti, hogy a területe nem kapcsolódik az anyaországhoz'),
    _q('2008. február 19-én Fidel Castro lemondott a kubai államtanács elnöki (államfői) tisztségéről. Melyik évben győzött a kubai forradalom, amely Castro vezetésével megdöntötte Fulgencio Batista diktatúráját?', 1, ['1949', '1959', '1969', '1979'], 'Helyes válasz: 1959'),
]