# Auto-generated questions file
# Generated on: 2026-02-06 12:48:02

QUESTIONS = [
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Game of Thrones",
            "The Witcher",
            "Stranger Things",
            "Vikings",
        ],
        "correct": 0,
        "explanation": "GameofThrones - Official Opening Credits: Game of Thrones",
        "audio_file": "01. GameofThrones - Game of Thrones.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Stranger Things",
            "Black Mirror",
            "Walking Dead",
            "Breaking Bad",
        ],
        "correct": 0,
        "explanation": "Stranger Things - Title Sequence | Netflix",
        "audio_file": "02. Stranger Things - Stranger Things.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Friends",
            "How I met your mother",
            "Stranger Things",
            "The Boys",
        ],
        "correct": 0,
        "explanation": "Friends - 'I'll Be There For You'",
        "audio_file": "03. Friends - Friends.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The Office",
            "Fargo",
            "Breakin Bad",
            "Friends",
        ],
        "correct": 0,
        "explanation": "The Office - Intro",
        "audio_file": "04. The Office - The Office.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The Fresh Prince of Bel-Air",
            "How I met your mother",
            "The Sopranos",
            "Friends",
        ],
        "correct": 0,
        "explanation": "AnissaRaquel - The Fresh Prince Of Bel Air Theme Song",
        "audio_file": "05. AnissaRaquel - The Fresh Prince of Bel-Air.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Breaking Bad",
            "Money Heist",
            "Narcos",
            "Fargo",
        ],
        "correct": 0,
        "explanation": "Dave Porter - Topic - Breaking Bad Main Title Theme",
        "audio_file": "06. Breaking Bad - Breaking Bad.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Better Call Saul",
            "Breaking Bad",
            "Peaky Blinders",
            "Fargo",
        ],
        "correct": 0,
        "explanation": "Pratik Vaidya - Better Call Saul Theme by Little Barrie Full Original Song",
        "audio_file": "07. Pratik Vaidya - Better Call Saul.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The X-files",
            "Ozark",
            "Stranger Things",
            "Black Mirror",
        ],
        "correct": 0,
        "explanation": "Emily Hinnekens - The X-Files Opening Credits",
        "audio_file": "08. Emily Hinnekens - The X-files.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Twin Peaks",
            "Ozark",
            "Stranger Things",
            "The 3 Body Problem",
        ],
        "correct": 0,
        "explanation": "kasper933 - Twin Peaks Intro",
        "audio_file": "09. kasper933 - Twin Peaks.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The Sopranos ",
            "Brooklyn 99",
            "Narcos",
            "Fargo",
        ],
        "correct": 0,
        "explanation": "The Sopranos Opening Credits Theme Song - The Sopranos | HBO",
        "audio_file": "10. The Sopranos Opening Credits Theme Song - The Sopranos Opening Credits Theme Song.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Mad Men",
            "Game of Thrones",
            "Stranger Things",
            "The Wire",
        ],
        "correct": 0,
        "explanation": "Joel Troughton - Mad Men Opening Credits HD",
        "audio_file": "11. Joel Troughton - Mad Men.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The Wire",
            "Fargo",
            "Peaky Blinders",
            "Breaking Bad",
        ],
        "correct": 0,
        "explanation": "authwiretap - The Wire Intro Theme [Season 1]",
        "audio_file": "12. authwiretap - The Wire.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Dexter",
            "True Detective",
            "Sherlock Holmes",
            "The Sopranos",
        ],
        "correct": 0,
        "explanation": "Morning Routine' Title Sequence - Morning Routine' Title Sequence | Dexter | SHOWTIME",
        "audio_file": "13. Morning Routine Title Sequence - Morning Routine Title Sequence - Dexter.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Sherlock",
            "Breaking Bad",
            "Dexter",
            "Narcos",
        ],
        "correct": 0,
        "explanation": "hrisince - Sherlock Intro Season 1",
        "audio_file": "14. hrisince - Sherlock.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Doctor Who",
            "Ozark",
            "Stranger Things",
            "Dark",
        ],
        "correct": 0,
        "explanation": "All Doctor Who Title Sequences: 1963-2023 - All Doctor Who Title Sequences: 1963-2023 | Doctor Who",
        "audio_file": "15. All Doctor Who Title Sequences 1963-2023 - Doctor Who.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The Crown",
            "Game of Thrones",
            "Westworld",
            "The Good Place",
        ],
        "correct": 0,
        "explanation": "Hans Zimmer - The Crown Main Title| The Crown: Season One (Soundtrack from the Netflix Original Series)",
        "audio_file": "16. Hans Zimmer - The Crown.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The Mandalorian",
            "Game of Thrones",
            "Dark",
            "Loki",
        ],
        "correct": 0,
        "explanation": "The Mandalorian - The Mandalorian  - Main Theme Ludwig Göransson",
        "audio_file": "17. The Mandalorian -  The Mandalorian Main Theme.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Loki",
            "Ozark",
            "The Mandalorian",
            "Black Mirror",
        ],
        "correct": 0,
        "explanation": "The Smoking Skull - LOKI Opening Theme",
        "audio_file": "18. The Smoking Skull - The Smoking Skull.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The Witcher",
            "Game of Thrones",
            "Vikings",
            "The Mandalorian",
        ],
        "correct": 0,
        "explanation": "Netflix's THE WITCHER - Netflix's THE WITCHER (OST) - Geralt Of Rivia | Main Theme Song - FINAL TRAILER Music",
        "audio_file": "19. Netflixs THE WITCHER - The Witcher.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "House of Dragons",
            "Game of Thrones",
            "The Witcher",
            "Loki",
        ],
        "correct": 0,
        "explanation": "Season 2 Opening Credits - Season 2 Opening Credits | House of The Dragon | Season 2 | HBO",
        "audio_file": "20. Season 2 Opening Credits - House of Dragons.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The Last of Us",
            "Game of Thrones",
            "Westworld",
            "Ozark",
        ],
        "correct": 0,
        "explanation": "The Last of Us - The Last of Us | Opening Credits | Max",
        "audio_file": "21. The Last of Us - The Last of Us.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Wednesday",
            "Sherlock",
            "Dexter",
            "Seinfeld",
        ],
        "correct": 0,
        "explanation": "Danny Elfman - Wednesday Main Titles",
        "audio_file": "22. Danny Elfman - Wednesday.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The Boys",
            "Mandalorian",
            "Loki",
            "Prison Break",
        ],
        "correct": 0,
        "explanation": "THE BOYS - THE BOYS - ANIMATED OPENING SEQUENCE | 4K",
        "audio_file": "23. THE BOYS - The Boys.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Succession",
            "Suits",
            "Mad Men",
            "Seinfeld",
        ],
        "correct": 0,
        "explanation": "Succession Opening Credits Theme Song - Succession Opening Credits Theme Song | Succession | HBO",
        "audio_file": "24. Succession Opening Credits Theme Song - Succession Opening.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Westworld",
            "Ozark",
            "Stranger Things",
            "The 3 Body Problems",
        ],
        "correct": 0,
        "explanation": "Westworld S1 Official Soundtrack | Main Title Theme - Westworld S1 Official Soundtrack | Main Title Theme - Ramin Djawadi | WaterTower",
        "audio_file": "25. Westworld - Westworld S1 Official Soundtrack.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Chernobyl",
            "Westworld",
            "The Walking Dead",
            "The Expanse",
        ],
        "correct": 0,
        "explanation": "Equinox - HBO Chernobyl Opening Title",
        "audio_file": "26. Equinox - Chernobyl.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "True Detective",
            "Sherlock",
            "Suits",
            "Lincoln Lawyer",
        ],
        "correct": 0,
        "explanation": "True Detective - True Detective - Intro / Opening Song - Theme (The Handsome Family - Far From Any Road) + LYRICS",
        "audio_file": "27. True Detective - True Detective.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Fargo",
            "Peaky Blinders",
            "Sherlock",
            "The Boys",
        ],
        "correct": 0,
        "explanation": "SJ363 - Fargo Sountrack- Fargo, North Dakota",
        "audio_file": "28. SJ363 - Fargo.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Narcos",
            "Peaky Blinders",
            "The Boys",
            "Breaking Bad",
        ],
        "correct": 0,
        "explanation": "Narcos - Narcos | Opening Credits [HD] | Netflix",
        "audio_file": "29. Narcos - Narcos.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Peaky Blinders",
            "Fargo",
            "Narcos",
            "Breaking Bad",
        ],
        "correct": 0,
        "explanation": "Peaky Blinders Opening Title Sequence - Peaky Blinders Opening Title Sequence - Gold Open",
        "audio_file": "30. Peaky Blinders Opening Title Sequence - Peaky Blinders Opening Title Sequence.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Outlander",
            "Witcher",
            "Vikings",
            "Game Of Thrones",
        ],
        "correct": 0,
        "explanation": "BrokenHalo - Outlander Theme (Season 1)",
        "audio_file": "31. BrokenHalo - Outlander.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Black Mirror",
            "Stranger Things",
            "Ozark",
            "8 Senses",
        ],
        "correct": 0,
        "explanation": "Enzo Cicero - Black Mirror -- Opening title sequence",
        "audio_file": "32. Enzo Cicero - Black Mirror.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Lost",
            "The Boys",
            "Last of Us",
            "Westworld",
        ],
        "correct": 0,
        "explanation": "LOST - LOST - Opening Titles",
        "audio_file": "33. LOST - Lost.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Prison Break",
            "The Boys",
            "Money Heist",
            "Lost",
        ],
        "correct": 0,
        "explanation": "GandalfTheWhite - prison break intro season 1",
        "audio_file": "34. GandalfTheWhite - Prison Break.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "How I Met Your Mother",
            "Lincoln Lawyer",
            "The Umbrella Academy",
            "The Office",
        ],
        "correct": 0,
        "explanation": "MidnightMarathon - \"How I Met Your Mother\" Extended Theme Song",
        "audio_file": "35. MidnightMarathon - How I Met Your Mother.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The Bing Bang Theory",
            "The Umbrella Academy",
            "Money Heist",
            "The South Park",
        ],
        "correct": 0,
        "explanation": "SeriesFanatics - The Big Bang Theory Theme Song",
        "audio_file": "36. SeriesFanatics - The Bing Bang Theory.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Seinfeld",
            "Suites",
            "How I Met Your Mother",
            "Brooklyn 99",
        ],
        "correct": 0,
        "explanation": "Seinfeld - Seinfeld - Opening Intro",
        "audio_file": "37. Seinfeld - Seinfeld.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The Simpsons",
            "Beavis and Butthead",
            "Family Guy",
            "Garfield",
        ],
        "correct": 0,
        "explanation": "Steven - The Simpsons Opening Credits and Theme Song",
        "audio_file": "38. Steven - The Simpsons.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "South Park",
            "The Simpsons",
            "Family Guy",
            "Rick and Morty",
        ],
        "correct": 0,
        "explanation": "Season 17 - Season 17 (Intro) - SOUTH PARK",
        "audio_file": "39. Season 17 - South Park.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The Walking Dead",
            "Westworld",
            "Stranger Things",
            "The Last of Us",
        ],
        "correct": 0,
        "explanation": "The Walking Dead Original Soundtrack - The Walking Dead Original Soundtrack  - Theme Song",
        "audio_file": "40. The Walking Dead Original Soundtrack - The Walking Dead Original Soundtrack.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The Umbrella Academy",
            "Suites",
            "Mad Men",
            "Breaking Bad",
        ],
        "correct": 0,
        "explanation": "Jeff Russo - The Umbrella Academy",
        "audio_file": "41. Jeff Russo - Jeff Russo The Umbrella Academy.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Dark",
            "Lat of Us",
            "Westworld",
            "Black Mirror",
        ],
        "correct": 0,
        "explanation": "Dark : Season 1 - Dark : Season 1 - Opening Credits / Intro (Netflix' Series)",
        "audio_file": "42. Money Heist - Dark.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Money Heisttttt",
            "Lost",
            "Prison Break",
            "True Detective",
        ],
        "correct": 0,
        "explanation": "Magnificent Music - Money Heist Soundtrack- Theme Song",
        "audio_file": "43. Magnificent Music - Money Heist.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Ozark",
            "Narcos",
            "Fargo",
            "Loki",
        ],
        "correct": 0,
        "explanation": "Ozark - Ozark – Title Sequence (Season 1)",
        "audio_file": "44. Ozark - Ozark.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The Expanse ",
            "Ozark",
            "The 3 Body Problem",
            "Doctor Who",
        ],
        "correct": 0,
        "explanation": "The Expanse | Season 1 | Long Opening - The Expanse | Season 1 | Long Opening - Intro HD",
        "audio_file": "45. The Expanse Season 1 Long Opening - The Expanse Season 1 Long Opening.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Firefly",
            "The Boys",
            "Suits",
            "Brooklyn 99",
        ],
        "correct": 0,
        "explanation": "Mikey - Firefly Opening Theme",
        "audio_file": "46. Mikey - Firefly.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Vikings",
            "Game of Thrones",
            "Outlander",
            "Sherlock",
        ],
        "correct": 0,
        "explanation": "Fever Ray - Fever Ray - If I Had A Heart | The Vikings (Music from the TV Series)",
        "audio_file": "47. Fever Ray - Vikings.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The Good Place",
            "Brooklyn 99",
            "Stranger Things",
            "How I Met Your Mother",
        ],
        "correct": 0,
        "explanation": "The Good Place - The Good Place | Theme Song",
        "audio_file": "48. The Good Place - The Good Place.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Bridgerton",
            "Sex Education",
            "How to Sell Drugs Online",
            "The Crown",
        ],
        "correct": 0,
        "explanation": "Jovin Lau - 1 Hour Bridgerton Intro Theme Song / Opening Credits #bridgerton #netflix",
        "audio_file": "49. Jovin Lau - Bridgerton.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Petrocelli",
            "Kojak",
            "The A-Team",
            "San Fransisco utcáin",
        ],
        "correct": 0,
        "explanation": "Petrocelli theme - Petrocelli theme - the series intro and outro",
        "audio_file": "50. Petrocelli theme - Petrocelli theme.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Homeland",
            "The Diplomat",
            "Better Call Saul",
            "Breaking Bad",
        ],
        "correct": 0,
        "explanation": "Homeland - Homeland - Main Title Theme [Soundtrack HD]",
        "audio_file": "51. Homeland - Homeland.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "MASH",
            "The Boys",
            "Prison Break",
            "The Walking Dead",
        ],
        "correct": 0,
        "explanation": "Lathan Luu - Mash theme song",
        "audio_file": "52. Lathan Luu - MASH.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Brooklyn Nine-nine",
            "Lincoln Lawyer",
            "Suits",
            "Dexter",
        ],
        "correct": 0,
        "explanation": "Brooklyn Nine-nine - Brooklyn Nine-nine - Main Theme (Official Soundtrack)",
        "audio_file": "53. Brooklyn Nine-nine - Brooklyn 99.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Suits",
            "Lincoln Lawyer",
            "Brooklyn 99",
            "Seinfeld",
        ],
        "correct": 0,
        "explanation": "Christopher Tyng - Topic - Suits Theme",
        "audio_file": "54. Christopher Tyng - Topic - Suits.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Lincoln Lawyer",
            "Suits",
            "Brooklyn 99",
            "Seinfeld",
        ],
        "correct": 0,
        "explanation": "TV Themesongs - The Lincoln Lawyer Title Card",
        "audio_file": "55. TV Themesongs - Lincoln Lawyer.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The A-Team TV",
            "Kojak",
            "Petrocelli",
            "San Francisco utcáin",
        ],
        "correct": 0,
        "explanation": "The A-Team TV Theme Tune - The A-Team TV Theme Tune | The A-Team",
        "audio_file": "56. The A-Team TV Theme Tune - The A-Team TV.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "San Francisco utcáin",
            "Petrocelli",
            "Kojak",
            "The A-Team",
        ],
        "correct": 0,
        "explanation": "David Gideon - Classic TV Theme: The Streets of San Francisco",
        "audio_file": "57. David Gideon - San Francisco utcáin.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Squid Game",
            "Ozark",
            "Sense 8",
            "Doctor Who",
        ],
        "correct": 0,
        "explanation": "Plick Kick - Squid Game Theme",
        "audio_file": "58. Plick Kick - Squid Game.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "House",
            "Grey's Anathomy",
            "ER",
            "Good Doctor",
        ],
        "correct": 0,
        "explanation": "TheRLWS - All 3 House M.D openers/themes/intros (American, Singaporean and European)",
        "audio_file": "59. TheRLWS - House.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "ER",
            "House",
            "Grey's Anathomy",
            "Good Doctor",
        ],
        "correct": 0,
        "explanation": "TheAileeJ - ER Opening Theme",
        "audio_file": "60. TheAileeJ - ER.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Supernatural",
            "Loki",
            "Ozark",
            "The Mandalorian",
        ],
        "correct": 0,
        "explanation": "Supernatural - Supernatural - Carry On Wayward Son (Music Video)",
        "audio_file": "61. Supernatural - Supernatural.mp3",
        "song_title": "Supernatural",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Ted Lasso | Ted Lasso Theme",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "Ted Lasso | Ted Lasso Theme - Ted Lasso | Ted Lasso Theme - Marcus Mumford & Tom Howe | WaterTower",
        "audio_file": "AIcis7S-byg.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Lupin",
            "Lidia Poet",
            "Sherlock",
            "Enola Gay",
        ],
        "correct": 0,
        "explanation": "LUPIN THE 3rd PART 6 - LUPIN THE 3rd PART 6 | Official Opening Theme: \"THEME FROM LUPIN III 2021\"",
        "audio_file": "63. LUPIN THE 3rd PART 6 - Lupin.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Ella Rose",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "Ella Rose - Sex and the City Opening Credits",
        "audio_file": "X453aKQgob4.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The Osmonds",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "The Osmonds - The Osmonds - Having A Party (Sex Education S02x06 Soundtrack)",
        "audio_file": "The_Osmonds_The_Osmonds_Having_A_Party_S.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Labrinth",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "Labrinth - Labrinth – Forever (Official Audio) | euphoria (Original Score from the HBO Series)",
        "audio_file": "Labrinth_Labrinth_Forever_Official_Aud.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "VampireDiariesCWTV",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "VampireDiariesCWTV - The Vampire Diaries (Season 1) Opening Theme",
        "audio_file": "iu9VHrJWL6w.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Grey's Anatomy",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "Grey's Anatomy - Grey's Anatomy - Intro (Season 1) [1080p HD]",
        "audio_file": "GKyvMFkuCog.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The White Lotus Opening Credits Theme Song",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "The White Lotus Opening Credits Theme Song - The White Lotus Opening Credits Theme Song | The White Lotus | HBO",
        "audio_file": "l2wj6lJtg_8.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Caterina Cingolani",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "Caterina Cingolani - Desperate Housewives // opening credits",
        "audio_file": "vcCT_4Umufc.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "‘Yellowstone’ Official Theme Music Composed by Brian Tyler",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "‘Yellowstone’ Official Theme Music Composed by Brian Tyler - ‘Yellowstone’ Official Theme Music Composed by Brian Tyler | Paramount Network",
        "audio_file": "nIxPn7xWA_k.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Lazlo Bane",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "Lazlo Bane - Scrubs Theme Song “Superman” Lazlo Bane Official Video Remastered HD",
        "audio_file": "Lazlo_Bane_Scrubs_Theme_Song_Superman_Laz.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Veronique Laurent",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "Veronique Laurent - \"Big Little Lies\" Opening Titles",
        "audio_file": "T50K64QjaA8.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Atnv33",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "Atnv33 - Criminal Minds Theme Song",
        "audio_file": "JS70MFXbYEc.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Dav0tion",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "Dav0tion - Californication Opening Credits Season 1",
        "audio_file": "A6RVX-3wNnY.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "NCIS Season 1",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "NCIS Season 1 - NCIS Season 1 - Opening Credits (Titles)",
        "audio_file": "Osv0l1a0Msc.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "megsmeetsworld",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "megsmeetsworld - Where You Lead (full theme song from \"Gilmore Girls\") lyrics",
        "audio_file": "megsmeetsworld_Where_You_Lead_full_theme_song.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "24 Opening and Closing Theme 2001",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "24 Opening and Closing Theme 2001 - 24 Opening and Closing Theme 2001 - 2014 HD Surround",
        "audio_file": "24_Opening_and_Closi_24_Opening_and_Closing_Theme_2.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "OpeningThemeSongs",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "OpeningThemeSongs - Two And A Half Men Opening Theme Song",
        "audio_file": "bl5q4AIGGZQ.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Futurama",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "Futurama - Futurama (1999-2013) - Intro",
        "audio_file": "6F1QNfmiqHc.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Beverly Hills, 90210",
            "How I Met Your Mother",
            "Firefly",
            "Buffy the Vampire Slayer",
        ],
        "correct": 0,
        "explanation": "Beverly Hills, 90210 - Beverly Hills, 90210 - Intro [HQ]",
        "audio_file": "81. Beverly Hills 90210 - Beverly Hills 90210.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "MacGyver",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "MacGyver - MacGyver - Intro [HQ]",
        "audio_file": "yOEe1uzurKo.mp3",
        "topic": "sorozat_focimek",
    },
]

# Export alias for compatibility
SOROZAT_FOCIMEK_QUESTIONS = QUESTIONS
