# Auto-generated questions file
# Generated on: 2026-02-03 14:13:08

QUESTIONS = [
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Game of Thrones",
            "The Witcher",
            "Stranger Things",
            "Vikings",
        ],
        "correct": 0,
        "explanation": "GameofThrones - Official Opening Credits: Game of Thrones",
        "audio_file": "01. GameofThrones - Game of Thrones.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Stranger Things",
            "Black Mirror",
            "Walking Dead",
            "Breaking Bad",
        ],
        "correct": 0,
        "explanation": "Stranger Things - Title Sequence | Netflix",
        "audio_file": "02. Stranger Things - Stranger Things.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Friends",
            "How I met your mother",
            "Stranger Things",
            "The Boys",
        ],
        "correct": 0,
        "explanation": "Friends - 'I'll Be There For You'",
        "audio_file": "03. Friends - Friends.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The Office",
            "Fargo",
            "Breakin Bad",
            "Friends",
        ],
        "correct": 0,
        "explanation": "The Office - Intro",
        "audio_file": "04. The Office - The Office.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The Fresh Prince of Bel-Air",
            "How I met your mother",
            "The Sopranos",
            "Friends",
        ],
        "correct": 0,
        "explanation": "AnissaRaquel - The Fresh Prince Of Bel Air Theme Song",
        "audio_file": "05. AnissaRaquel - The Fresh Prince of Bel-Air.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Breaking Bad",
            "Money Heist",
            "Narcos",
            "Fargo",
        ],
        "correct": 0,
        "explanation": "Dave Porter - Topic - Breaking Bad Main Title Theme",
        "audio_file": "06. Breaking Bad - Breaking Bad.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Better Call Saul",
            "Breaking Bad",
            "Peaky Blinders",
            "Fargo",
        ],
        "correct": 0,
        "explanation": "Pratik Vaidya - Better Call Saul Theme by Little Barrie Full Original Song",
        "audio_file": "07. Pratik Vaidya - Better Call Saul.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The X-files",
            "Ozark",
            "Stranger Things",
            "Black Mirror",
        ],
        "correct": 0,
        "explanation": "Emily Hinnekens - The X-Files Opening Credits",
        "audio_file": "08. Emily Hinnekens - The X-files.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Twin Peaks",
            "Ozark",
            "Stranger Things",
            "The 3 Body Problem",
        ],
        "correct": 0,
        "explanation": "kasper933 - Twin Peaks Intro",
        "audio_file": "09. kasper933 - Twin Peaks.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The Sopranos ",
            "Brooklyn 99",
            "Narcos",
            "Fargo",
        ],
        "correct": 0,
        "explanation": "The Sopranos Opening Credits Theme Song - The Sopranos | HBO",
        "audio_file": "10. The Sopranos Opening Credits Theme Song - The Sopranos Opening Credits Theme Song.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Mad Men",
            "Game of Thrones",
            "Stranger Things",
            "The Wire",
        ],
        "correct": 0,
        "explanation": "Joel Troughton - Mad Men Opening Credits HD",
        "audio_file": "11. Joel Troughton - Mad Men.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The Wire",
            "Fargo",
            "Peaky Blinders",
            "Breaking Bad",
        ],
        "correct": 0,
        "explanation": "authwiretap - The Wire Intro Theme [Season 1]",
        "audio_file": "12. authwiretap - The Wire.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Dexter",
            "True Detective",
            "Sherlock Holmes",
            "The Sopranos",
        ],
        "correct": 0,
        "explanation": "Morning Routine' Title Sequence - Morning Routine' Title Sequence | Dexter | SHOWTIME",
        "audio_file": "13. Morning Routine Title Sequence - Morning Routine Title Sequence - Dexter.mp3",
        "song_title": "Morning Routine' Title Sequence - Dexter",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "hrisince",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "hrisince - Sherlock Intro Season 1",
        "audio_file": "Pk2FME6HVdA.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "All Doctor Who Title Sequences: 1963-2023",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "All Doctor Who Title Sequences: 1963-2023 - All Doctor Who Title Sequences: 1963-2023 | Doctor Who",
        "audio_file": "All_Doctor_Who_Title_All_Doctor_Who_Title_Sequences.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Hans Zimmer",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "Hans Zimmer - The Crown Main Title| The Crown: Season One (Soundtrack from the Netflix Original Series)",
        "audio_file": "EIEqXWHPf88.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The Mandalorian",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "The Mandalorian - The Mandalorian  - Main Theme Ludwig Göransson",
        "audio_file": "The_Mandalorian_The_Mandalorian_Main_Theme_.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The Smoking Skull",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "The Smoking Skull - LOKI Opening Theme",
        "audio_file": "3QdLGiW4joY.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Netflix's THE WITCHER",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "Netflix's THE WITCHER - Netflix's THE WITCHER (OST) - Geralt Of Rivia | Main Theme Song - FINAL TRAILER Music",
        "audio_file": "WdS4Z5Kfjgw.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Season 2 Opening Credits",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "Season 2 Opening Credits - Season 2 Opening Credits | House of The Dragon | Season 2 | HBO",
        "audio_file": "HIblsDVSq_k.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "The Last of Us",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "The Last of Us - The Last of Us | Opening Credits | Max",
        "audio_file": "8SWhBsbxmpk.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Danny Elfman",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "Danny Elfman - Wednesday Main Titles",
        "audio_file": "vhBHaz9SaLI.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "THE BOYS",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "THE BOYS - THE BOYS - ANIMATED OPENING SEQUENCE | 4K",
        "audio_file": "UFQs01jmvn0.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Succession Opening Credits Theme Song",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "Succession Opening Credits Theme Song - Succession Opening Credits Theme Song | Succession | HBO",
        "audio_file": "77PsqaWzwG0.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Westworld S1 Official Soundtrack | Main Title Theme",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "Westworld S1 Official Soundtrack | Main Title Theme - Westworld S1 Official Soundtrack | Main Title Theme - Ramin Djawadi | WaterTower",
        "audio_file": "rYelEUVQ50g.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Equinox",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "Equinox - HBO Chernobyl Opening Title",
        "audio_file": "2uoTIcHgXC4.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "True Detective",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "True Detective - True Detective - Intro / Opening Song - Theme (The Handsome Family - Far From Any Road) + LYRICS",
        "audio_file": "p4zluA60hjs.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "SJ363",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "SJ363 - Fargo Sountrack- Fargo, North Dakota",
        "audio_file": "W4NCC0dUXks.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Narcos",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "Narcos - Narcos | Opening Credits [HD] | Netflix",
        "audio_file": "PtJ6yAGjsIs.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Peaky Blinders Opening Title Sequence",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "Peaky Blinders Opening Title Sequence - Peaky Blinders Opening Title Sequence - Gold Open",
        "audio_file": "Be56k1Ui2Yg.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "BrokenHalo",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "BrokenHalo - Outlander Theme (Season 1)",
        "audio_file": "vUt0y29exX0.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "Enzo Cicero",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "Enzo Cicero - Black Mirror -- Opening title sequence",
        "audio_file": "jXq23Tq9FeU.mp3",
        "topic": "sorozat_focimek",
    },
    {
        "question": "Melyik sorozat főcímdala ez?",
        "options": [
            "LOST",
            "Game of Thrones",
            "Stranger Things",
            "Szerkeszthető opció",
        ],
        "correct": 0,
        "explanation": "LOST - LOST - Opening Titles",
        "audio_file": "9LDh8DefWpI.mp3",
        "topic": "sorozat_focimek",
    },
]

# Export alias for compatibility
SOROZAT_FOCIMEK_QUESTIONS = QUESTIONS
