# Auto-generated questions file
# Generated on: 2026-02-06 13:54:57

_DEFAULT_QUESTION = "Melyik sorozat főcímdala ez?"
_TOPIC = "sorozat_focimek"


def _q(audio_file, correct, options, explanation, question=_DEFAULT_QUESTION, **extra):
    """Segédfüggvény: kompakt kérdés létrehozása."""
    return {
        "question": question,
        "options": options,
        "correct": correct,
        "explanation": explanation,
        "audio_file": audio_file,
        "topic": _TOPIC,
        **extra,
    }


QUESTIONS = [
    _q("01. GameofThrones - Game of Thrones.mp3", 0, ["Game of Thrones", "The Witcher", "Stranger Things", "Vikings"], "GameofThrones - Official Opening Credits: Game of Thrones"),
    _q("02. Stranger Things - Stranger Things.mp3", 0, ["Stranger Things", "Black Mirror", "Walking Dead", "Breaking Bad"], "Stranger Things - Title Sequence | Netflix"),
    _q("03. Friends - Friends.mp3", 0, ["Friends", "How I met your mother", "Stranger Things", "The Boys"], "Friends - 'I'll Be There For You'"),
    _q("04. The Office - The Office.mp3", 0, ["The Office", "Fargo", "Breakin Bad", "Friends"], "The Office - Intro"),
    _q("05. AnissaRaquel - The Fresh Prince of Bel-Air.mp3", 0, ["The Fresh Prince of Bel-Air", "How I met your mother", "The Sopranos", "Friends"], "AnissaRaquel - The Fresh Prince Of Bel Air Theme Song"),
    _q("06. Breaking Bad - Breaking Bad.mp3", 0, ["Breaking Bad", "Money Heist", "Narcos", "Fargo"], "Dave Porter - Topic - Breaking Bad Main Title Theme"),
    _q("07. Pratik Vaidya - Better Call Saul.mp3", 0, ["Better Call Saul", "Breaking Bad", "Peaky Blinders", "Fargo"], "Pratik Vaidya - Better Call Saul Theme by Little Barrie Full Original Song"),
    _q("08. Emily Hinnekens - The X-files.mp3", 0, ["The X-files", "Ozark", "Stranger Things", "Black Mirror"], "Emily Hinnekens - The X-Files Opening Credits"),
    _q("09. kasper933 - Twin Peaks.mp3", 0, ["Twin Peaks", "Ozark", "Stranger Things", "The 3 Body Problem"], "kasper933 - Twin Peaks Intro"),
    _q("10. The Sopranos Opening Credits Theme Song - The Sopranos Opening Credits Theme Song.mp3", 0, ["The Sopranos ", "Brooklyn 99", "Narcos", "Fargo"], "The Sopranos Opening Credits Theme Song - The Sopranos | HBO"),
    _q("11. Joel Troughton - Mad Men.mp3", 0, ["Mad Men", "Game of Thrones", "Stranger Things", "The Wire"], "Joel Troughton - Mad Men Opening Credits HD"),
    _q("12. authwiretap - The Wire.mp3", 0, ["The Wire", "Fargo", "Peaky Blinders", "Breaking Bad"], "authwiretap - The Wire Intro Theme [Season 1]"),
    _q("13. Morning Routine Title Sequence - Morning Routine Title Sequence - Dexter.mp3", 0, ["Dexter", "True Detective", "Sherlock Holmes", "The Sopranos"], "Morning Routine' Title Sequence - Morning Routine' Title Sequence | Dexter | SHOWTIME"),
    _q("14. hrisince - Sherlock.mp3", 0, ["Sherlock", "Breaking Bad", "Dexter", "Narcos"], "hrisince - Sherlock Intro Season 1"),
    _q("15. All Doctor Who Title Sequences 1963-2023 - Doctor Who.mp3", 0, ["Doctor Who", "Ozark", "Stranger Things", "Dark"], "All Doctor Who Title Sequences: 1963-2023 - All Doctor Who Title Sequences: 1963-2023 | Doctor Who"),
    _q("16. Hans Zimmer - The Crown.mp3", 0, ["The Crown", "Game of Thrones", "Westworld", "The Good Place"], "Hans Zimmer - The Crown Main Title| The Crown: Season One (Soundtrack from the Netflix Original Series)"),
    _q("17. The Mandalorian -  The Mandalorian Main Theme.mp3", 0, ["The Mandalorian", "Game of Thrones", "Dark", "Loki"], "The Mandalorian - The Mandalorian  - Main Theme Ludwig Göransson"),
    _q("18. The Smoking Skull - The Smoking Skull.mp3", 0, ["Loki", "Ozark", "The Mandalorian", "Black Mirror"], "The Smoking Skull - LOKI Opening Theme"),
    _q("19. Netflixs THE WITCHER - The Witcher.mp3", 0, ["The Witcher", "Game of Thrones", "Vikings", "The Mandalorian"], "Netflix's THE WITCHER - Netflix's THE WITCHER (OST) - Geralt Of Rivia | Main Theme Song - FINAL TRAILER Music"),
    _q("20. Season 2 Opening Credits - House of Dragons.mp3", 0, ["House of Dragons", "Game of Thrones", "The Witcher", "Loki"], "Season 2 Opening Credits - Season 2 Opening Credits | House of The Dragon | Season 2 | HBO"),
    _q("21. The Last of Us - The Last of Us.mp3", 0, ["The Last of Us", "Game of Thrones", "Westworld", "Ozark"], "The Last of Us - The Last of Us | Opening Credits | Max"),
    _q("22. Danny Elfman - Wednesday.mp3", 0, ["Wednesday", "Sherlock", "Dexter", "Seinfeld"], "Danny Elfman - Wednesday Main Titles"),
    _q("23. THE BOYS - The Boys.mp3", 0, ["The Boys", "Mandalorian", "Loki", "Prison Break"], "THE BOYS - THE BOYS - ANIMATED OPENING SEQUENCE | 4K"),
    _q("24. Succession Opening Credits Theme Song - Succession Opening.mp3", 0, ["Succession", "Suits", "Mad Men", "Seinfeld"], "Succession Opening Credits Theme Song - Succession Opening Credits Theme Song | Succession | HBO"),
    _q("25. Westworld - Westworld S1 Official Soundtrack.mp3", 0, ["Westworld", "Ozark", "Stranger Things", "The 3 Body Problems"], "Westworld S1 Official Soundtrack | Main Title Theme - Westworld S1 Official Soundtrack | Main Title Theme - Ramin Djawadi | WaterTower"),
    _q("26. Equinox - Chernobyl.mp3", 0, ["Chernobyl", "Westworld", "The Walking Dead", "The Expanse"], "Equinox - HBO Chernobyl Opening Title"),
    _q("27. True Detective - True Detective.mp3", 0, ["True Detective", "Sherlock", "Suits", "Lincoln Lawyer"], "True Detective - True Detective - Intro / Opening Song - Theme (The Handsome Family - Far From Any Road) + LYRICS"),
    _q("28. SJ363 - Fargo.mp3", 0, ["Fargo", "Peaky Blinders", "Sherlock", "The Boys"], "SJ363 - Fargo Sountrack- Fargo, North Dakota"),
    _q("29. Narcos - Narcos.mp3", 0, ["Narcos", "Peaky Blinders", "The Boys", "Breaking Bad"], "Narcos - Narcos | Opening Credits [HD] | Netflix"),
    _q("30. Peaky Blinders Opening Title Sequence - Peaky Blinders Opening Title Sequence.mp3", 0, ["Peaky Blinders", "Fargo", "Narcos", "Breaking Bad"], "Peaky Blinders Opening Title Sequence - Peaky Blinders Opening Title Sequence - Gold Open"),
    _q("31. BrokenHalo - Outlander.mp3", 0, ["Outlander", "Witcher", "Vikings", "Game Of Thrones"], "BrokenHalo - Outlander Theme (Season 1)"),
    _q("32. Enzo Cicero - Black Mirror.mp3", 0, ["Black Mirror", "Stranger Things", "Ozark", "8 Senses"], "Enzo Cicero - Black Mirror -- Opening title sequence"),
    _q("33. LOST - Lost.mp3", 0, ["Lost", "The Boys", "Last of Us", "Westworld"], "LOST - LOST - Opening Titles"),
    _q("34. GandalfTheWhite - Prison Break.mp3", 0, ["Prison Break", "The Boys", "Money Heist", "Lost"], "GandalfTheWhite - prison break intro season 1"),
    _q("35. MidnightMarathon - How I Met Your Mother.mp3", 0, ["How I Met Your Mother", "Lincoln Lawyer", "The Umbrella Academy", "The Office"], "MidnightMarathon - \"How I Met Your Mother\" Extended Theme Song"),
    _q("36. SeriesFanatics - The Bing Bang Theory.mp3", 0, ["The Bing Bang Theory", "The Umbrella Academy", "Money Heist", "The South Park"], "SeriesFanatics - The Big Bang Theory Theme Song"),
    _q("37. Seinfeld - Seinfeld.mp3", 0, ["Seinfeld", "Suites", "How I Met Your Mother", "Brooklyn 99"], "Seinfeld - Seinfeld - Opening Intro"),
    _q("38. Steven - The Simpsons.mp3", 0, ["The Simpsons", "Beavis and Butthead", "Family Guy", "Garfield"], "Steven - The Simpsons Opening Credits and Theme Song"),
    _q("39. Season 17 - South Park.mp3", 0, ["South Park", "The Simpsons", "Family Guy", "Rick and Morty"], "Season 17 - Season 17 (Intro) - SOUTH PARK"),
    _q("40. The Walking Dead Original Soundtrack - The Walking Dead Original Soundtrack.mp3", 0, ["The Walking Dead", "Westworld", "Stranger Things", "The Last of Us"], "The Walking Dead Original Soundtrack - The Walking Dead Original Soundtrack  - Theme Song"),
    _q("41. Jeff Russo - Jeff Russo The Umbrella Academy.mp3", 0, ["The Umbrella Academy", "Suites", "Mad Men", "Breaking Bad"], "Jeff Russo - The Umbrella Academy"),
    _q("42. Money Heist - Dark.mp3", 0, ["Dark", "Lat of Us", "Westworld", "Black Mirror"], "Dark : Season 1 - Dark : Season 1 - Opening Credits / Intro (Netflix' Series)"),
    _q("43. Magnificent Music - Money Heist.mp3", 0, ["Money Heisttttt", "Lost", "Prison Break", "True Detective"], "Magnificent Music - Money Heist Soundtrack- Theme Song"),
    _q("44. Ozark - Ozark.mp3", 0, ["Ozark", "Narcos", "Fargo", "Loki"], "Ozark - Ozark – Title Sequence (Season 1)"),
    _q("45. The Expanse Season 1 Long Opening - The Expanse Season 1 Long Opening.mp3", 0, ["The Expanse ", "Ozark", "The 3 Body Problem", "Doctor Who"], "The Expanse | Season 1 | Long Opening - The Expanse | Season 1 | Long Opening - Intro HD"),
    _q("46. Mikey - Firefly.mp3", 0, ["Firefly", "The Boys", "Suits", "Brooklyn 99"], "Mikey - Firefly Opening Theme"),
    _q("47. Fever Ray - Vikings.mp3", 0, ["Vikings", "Game of Thrones", "Outlander", "Sherlock"], "Fever Ray - Fever Ray - If I Had A Heart | The Vikings (Music from the TV Series)"),
    _q("48. The Good Place - The Good Place.mp3", 0, ["The Good Place", "Brooklyn 99", "Stranger Things", "How I Met Your Mother"], "The Good Place - The Good Place | Theme Song"),
    _q("49. Jovin Lau - Bridgerton.mp3", 0, ["Bridgerton", "Sex Education", "How to Sell Drugs Online", "The Crown"], "Jovin Lau - 1 Hour Bridgerton Intro Theme Song / Opening Credits #bridgerton #netflix"),
    _q("50. Petrocelli theme - Petrocelli theme.mp3", 0, ["Petrocelli", "Kojak", "The A-Team", "San Fransisco utcáin"], "Petrocelli theme - Petrocelli theme - the series intro and outro"),
    _q("51. Homeland - Homeland.mp3", 0, ["Homeland", "The Diplomat", "Better Call Saul", "Breaking Bad"], "Homeland - Homeland - Main Title Theme [Soundtrack HD]"),
    _q("52. Lathan Luu - MASH.mp3", 0, ["MASH", "The Boys", "Prison Break", "The Walking Dead"], "Lathan Luu - Mash theme song"),
    _q("53. Brooklyn Nine-nine - Brooklyn 99.mp3", 0, ["Brooklyn Nine-nine", "Lincoln Lawyer", "Suits", "Dexter"], "Brooklyn Nine-nine - Brooklyn Nine-nine - Main Theme (Official Soundtrack)"),
    _q("54. Christopher Tyng - Topic - Suits.mp3", 0, ["Suits", "Lincoln Lawyer", "Brooklyn 99", "Seinfeld"], "Christopher Tyng - Topic - Suits Theme"),
    _q("55. TV Themesongs - Lincoln Lawyer.mp3", 0, ["Lincoln Lawyer", "Suits", "Brooklyn 99", "Seinfeld"], "TV Themesongs - The Lincoln Lawyer Title Card"),
    _q("56. The A-Team TV Theme Tune - The A-Team TV.mp3", 0, ["The A-Team TV", "Kojak", "Petrocelli", "San Francisco utcáin"], "The A-Team TV Theme Tune - The A-Team TV Theme Tune | The A-Team"),
    _q("57. David Gideon - San Francisco utcáin.mp3", 0, ["San Francisco utcáin", "Petrocelli", "Kojak", "The A-Team"], "David Gideon - Classic TV Theme: The Streets of San Francisco"),
    _q("58. Plick Kick - Squid Game.mp3", 0, ["Squid Game", "Ozark", "Sense 8", "Doctor Who"], "Plick Kick - Squid Game Theme"),
    _q("59. TheRLWS - House.mp3", 0, ["House", "Grey's Anathomy", "ER", "Good Doctor"], "TheRLWS - All 3 House M.D openers/themes/intros (American, Singaporean and European)"),
    _q("60. TheAileeJ - ER.mp3", 0, ["ER", "House", "Grey's Anathomy", "Good Doctor"], "TheAileeJ - ER Opening Theme"),
    _q("61. Supernatural - Supernatural.mp3", 0, ["Supernatural", "Loki", "Ozark", "The Mandalorian"], "Supernatural - Supernatural - Carry On Wayward Son (Music Video)"),
    _q("62. Ted Lasso Ted Lasso Theme - Ted Lasso Theme.mp3", 0, ["Ted Lasso", "How I Met Your Mother", "The Good Place", "The Queen's Gambit"], "Ted Lasso | Ted Lasso Theme - Ted Lasso | Ted Lasso Theme - Marcus Mumford & Tom Howe | WaterTower"),
    _q("63. LUPIN THE 3rd PART 6 - Lupin.mp3", 0, ["Lupin", "Lidia Poet", "Sherlock", "Enola Gay"], "LUPIN THE 3rd PART 6 - LUPIN THE 3rd PART 6 | Official Opening Theme: \"THEME FROM LUPIN III 2021\""),
    _q("64. Ella Rose - Sex And The City.mp3", 0, ["Sex And The City", "Ted Lasso", "Gilmore Girls", "Big Little Lies"], "Ella Rose - Sex and the City Opening Credits"),
    _q("65. The Osmonds - Sex Education.mp3", 0, ["Sex Education", "Euphoria", "Vampire Diaries", "Sex And The City"], "The Osmonds - The Osmonds - Having A Party (Sex Education S02x06 Soundtrack)"),
    _q("66. Labrinth - Euphoria.mp3", 0, ["Euphoria", "Sex Education", "Sex And The City", "Vampire Diaries"], "Labrinth - Labrinth – Forever (Official Audio) | euphoria (Original Score from the HBO Series)"),
    _q("67. VampireDiariesCWTV - Vampire Diaries.mp3", 0, ["Vampire Diaries", "Sex And The City", "Buffy The Vampire Slayer", "Gilmore Girls"], "VampireDiariesCWTV - The Vampire Diaries (Season 1) Opening Theme"),
    _q("68. Greys Anatomy - Greys Anatomy.mp3", 0, ["Grey's Anatomy", "House", "The Good Doctor", "ER"], "Grey's Anatomy - Grey's Anatomy - Intro (Season 1) [1080p HD]"),
    _q("69. The White Lotus Opening Credits Theme Song - The White Lotus Opening Credits Theme Song.mp3", 0, ["The White Lotus ", "Big Little Lies", "Suits", "The Crown"], "The White Lotus Opening Credits Theme Song - The White Lotus Opening Credits Theme Song | The White Lotus | HBO"),
    _q("70. Caterina Cingolani - Desperate Housewives.mp3", 0, ["Desperate Housewives", "Sex And The City", "How I Met Your Mother", "Mad Men"], "Caterina Cingolani - Desperate Housewives // opening credits"),
    _q("71. Yellowstone Official Theme Music Composed by Brian Tyler - Yellowstone Official Theme Music Composed by Brian Tyler.mp3", 0, ["Yellowstone", "Westworld", "Outlander", "True Detective"], "'Yellowstone' Official Theme Music Composed by Brian Tyler - 'Yellowstone' Official Theme Music Composed by Brian Tyler | Paramount Network"),
    _q("72. Lazlo Bane - Lazlo Bane - Scrubs Theme Song.mp3", 0, ["Scrubs", "House", "Good Doctor", "Brooklyn 99"], 'Lazlo Bane - Scrubs Theme Song "Superman" Lazlo Bane Official Video Remastered HD'),
    _q("73. Veronique Laurent - Big Little Lies.mp3", 0, ["Big Little Lies", "Sex And The City", "Vampire Diaries", "Gilmore Girls"], "Veronique Laurent - \"Big Little Lies\" Opening Titles"),
    _q("74. Atnv33 - Criminal Minds.mp3", 0, ["Criminal Minds", "NCIS", "The Boys", "Vikings"], "Atnv33 - Criminal Minds Theme Song"),
    _q("75. Dav0tion - Californication.mp3", 0, ["Californication", "House", "Euphoria", "Big Little Lies"], "Dav0tion - Californication Opening Credits Season 1"),
    _q("76. NCIS Season 1 - NCIS.mp3", 0, ["NCIS", "CSI", "Criminal Minds", "Dexter"], "NCIS Season 1 - NCIS Season 1 - Opening Credits (Titles)"),
    _q("77. megsmeetsworld - Gilmore Girls.mp3", 0, ["Gilmore Girls", "Sex And The City", "Desperate Housewives", "Big Little Lies"], "megsmeetsworld - Where You Lead (full theme song from \"Gilmore Girls\") lyrics"),
    _q("78. 24 Opening and Closing Theme 2001 - 24.mp3", 0, ["24", "NCIS", "CSI", "Criminal Minds"], "24 Opening and Closing Theme 2001 - 24 Opening and Closing Theme 2001 - 2014 HD Surround"),
    _q("79. OpeningThemeSongs - Two And A Half Men.mp3", 0, ["Two And A Half Men", "Ted Lasso", "Californication", "Lincoln Lawyer"], "OpeningThemeSongs - Two And A Half Men Opening Theme Song"),
    _q("80. Futurama - Futurama.mp3", 0, ["Futurama", "Euphoria", "Family Guy", "Rick And Morty"], "Futurama - Futurama (1999-2013) - Intro"),
    _q("81. Beverly Hills 90210 - Beverly Hills 90210.mp3", 0, ["Beverly Hills, 90210", "Gossip Girl", "Orange County", "Buffy the Vampire Slayer"], "Beverly Hills, 90210 - Beverly Hills, 90210 - Intro [HQ]"),
    _q("82. MacGyver - MacGyver.mp3", 0, ["MacGyver", "The A-Team", "Knight Rider", "Baywatch"], "MacGyver - MacGyver - Intro [HQ]", song_title="MacGyver"),
    _q("83. ALF - ALF.mp3", 0, ["ALF", "Mork & Mindy", "Family Ties", "The Golden Girls"], "ALF – főcímdal (NBC, 1986–1990)", song_title="ALF"),
]

# Export alias for compatibility
SOROZAT_FOCIMEK_QUESTIONS = QUESTIONS
