# sport kvíz kérdések

_TOPIC = "sport"


def _q(question, correct, options, explanation, topic=_TOPIC):
    """Segédfüggvény: kompakt kérdés létrehozása."""
    return {"question": question, "options": options, "correct": correct, "explanation": explanation, "topic": topic}


SPORT_QUESTIONS = [
    _q('1884-ben Washingtonban, a Nemzetközi Meridián Konferencián, 25 nemzet képviselője döntést hozott a világ időzónákra való felosztásáról. A kezdő délkört az angliai Greenwichben jelölték ki. Hány időzóna van összesen?', 3, ['12', '24', '36', '40'], 'Helyes válasz: 40'),
    _q('1897. november 1-jén alapították a Juventus Football Clubot, amelynek székhelye Olaszországban, Torinóban van. Mára a legsikeresebb olasz csapattá vált, de világviszonylatban is az egyik legjelentősebbnek számít. Hányszor szerezték meg az olasz bajnoki címet?', 2, ['16', '26', '36', '46'], 'Helyes válasz: 36'),
    _q('1981-ben született Talmácsi Gábor gyorsaságimotor-versenyző, aki 2007-ben a MotoGP 125 cm³-es kategóriájának világbajnoka volt. Melyik állítás nem igaz a MotoGP-versenyekkel kapcsolatban?', 2, ['MotoGP versenyen a legnagyobb mért sebesség 355 km/h volt, ami kb. 20 km/h-val gyorsabb a Formula–1-es autókénál', 'Magyarországon kétszer rendeztek futamot, 1990-ben és 1992-ben, a Hungaroringen', 'A versenyeken maximum 500 cm³-es hengerűrtartalmú motorok versenyeznek', 'A versenyen induló motorok két kerekének mérete között nem lehet különbség'], 'Helyes válasz: A versenyeken maximum 500 cm³-es hengerűrtartalmú motorok versenyeznek'),
    _q('November 5-e a Guy Fawkes-nap. A brit ünnepen arra emlékeznek, hogy 1605-ben ezen a napon leplezték le Londonban az I. Jakab angol király elleni lőporos összeesküvést (Gunpowder Plot), melynek egyik résztvevője volt a névadó. Ki volt Guy Fawkes, akinek karaktere az igazság megtestesítőjévé vált?', 2, ['ír pap', 'skót földesúr', 'angol katona', 'spanyol paraszt'], 'Helyes válasz: angol katona'),
    _q('1814. november 6-án született Ganz Ábrahám svájci származású vasöntőmester, gyáros, a magyar nehézipar egyik megteremtője. Az általa alapított öntödében 1969 óta az Öntödei Múzeum működik. Hol található?', 3, ['Győrben', 'Sopronban', 'Miskolcon', 'Budán'], 'Helyes válasz: Budán'),
    _q('1810. november 7-én született Erkel Ferenc zeneszerző, karmester, zongoraművész és sakkmester, a Pesti Sakk-kör első elnöke. Születésnapja a magyar opera napja is. Melyik NEM az ő operája?', 2, ['Dózsa György', 'Hunyadi László', 'Don Sanche, avagy a szerelem kastélya', 'Névtelen hősök'], 'Helyes válasz: Don Sanche, avagy a szerelem kastélya'),
    _q('1955. november 12-én hunyt el Hajós Alfréd sportoló, építészmérnök. Melyik állítás NEM igaz vele kapcsolatban?', 2, ['Ő szerezte meg a magyar sport első és második olimpiai győzelmét', 'Labdarúgó-játékvezetőként tevékenykedett 1897-től', 'Az általa tervezett épületekből ma már egy sem áll', 'Eredeti neve Guttmann Arnold, beceneve a „Magyar delfin” volt'], 'Helyes válasz: Az általa tervezett épületekből ma már egy sem áll'),
    _q('2006. november 17-én hunyt el Puskás Ferenc, becenevén Puskás Öcsi, a Nemzet Sportolója címmel kitüntetett, olimpiai arany- és világbajnoki ezüstérmes magyar labdarúgó, több klubcsapat és válogatott edzője. Melyik spanyol csapatban játszott 1958–1966 között?', 2, ['Hércules Alicante', 'Real Murcia', 'Real Madrid', 'FC Barcelona'], 'Helyes válasz: Real Madrid'),
    _q('November 25-e a magyar labdarúgás napja annak emlékére, hogy az Aranycsapat a londoni Wembley Stadionban 6:3 arányban legyőzte Angliát. Hány éve volt ekkor a kontinentális európai csapatokkal szemben veretlen hazai pályán az angol csapat?', 3, ['38', '52', '74', '90'], 'Helyes válasz: 90'),
    _q('305. november 25-én hunyt el Alexandriai Szent Katalin szűz és vértanú, aki keresztényként nem akart részt venni a bálványok tiszteletére rendezett áldozatokon. Ötven tanult férfi próbálta megtörni őt, de olyan bölcsességgel védelmezte hitét, hogy mind az ötvenen keresztényekké lettek. A magasabb iskolák, a filozófia és a filozófusok, ügyvédek, a könyvtárak és könyvtárosok és a nyomdászok, a kerékgyártók, a tanuló lányok, a fiatal diákok és nők, a dajkák védőszentje. Az egyik neki szentelt templom a Tabánban áll, Budapest I. kerületében. Mi volt eredetileg?', 0, ['dzsámi', 'katonai épület', 'lakóház', 'gabonaraktár'], 'Helyes válasz: dzsámi'),
    _q('1987. november 26-án hunyt el Rockenbauer Pál természetjáró, világutazó, televíziós szerkesztő, a magyar televíziós természetfilmezés egyik megteremtője. Legtöbben országjáró kéktúrafilmjeiről, a tévében többször is vetített Másfélmillió lépés Magyarországon, illetve …és még egymillió lépés című sorozatairól ismerik. A Kék Túra útvonala azóta többször változott; milyen hosszú jelenleg?', 2, ['768 km', '968 km', '1168 km', '1368 km'], 'Helyes válasz: 1168 km'),
    _q('1881. november 28-án született Stefan Zweig osztrák író, költő, műfordító. Egyik legismertebb műve az 1941-ben megjelent, antifasiszta tárgyú Sakknovella. Hol játszódik a története?', 0, ['egy óceánjáró fedélzetén', 'egy börtöncellában', 'egy előkelő étteremben', 'egy harctéren'], 'Helyes válasz: egy óceánjáró fedélzetén'),
    _q('1899. november 29-én alapították meg az FC Barcelona labdarúgúcsapatot. A spanyol labdarúgó-bajnokság első osztályát 26, a spanyol labdarúgókupát 30, a spanyol labdarúgó-szuperkupát 13 alkalommal nyerte meg a csapat. Melyik magyar játékos NEM játszott a Barçában?', 2, ['Czibor Zoltán', 'Kocsis Sándor', 'Puskás Ferenc', 'Kubala László'], 'Helyes válasz: Puskás Ferenc'),
    _q('1872. november 30-án játszották az első nemzetközinek minősített labdarúgó-mérkőzést: Anglia és Skócia mérte össze erejét. Hány gól született a meccsen?', 0, ['nulla', 'kettő', 'öt', 'kilenc'], 'Helyes válasz: nulla'),
    _q('1963. december 4-én született Szerhij Nazarovics Bubka ukrán rúdugró, sportvezető. 1991-ig a Szovjetunió, majd utána Ukrajna színeiben vett részt különböző világversenyeken, melyek során egy olimpiai és hat világbajnoki aranyérmet szerzett. Hányszor állított fel új világrekordot pályafutása során?', 3, ['négy', 'kilenc', 'tizenhét', 'harmincöt'], 'Helyes válasz: harmincöt'),
    _q('2017-ben ezen a napon döntött úgy a Nemzetközi Olimpiai Bizottság, hogy Oroszország doppingbotránya miatt csapatként nem vehet részt a 2018-as téli olimpián, sportolói csak az olimpiai mozgalom zászlaja alatt versenyezhetnek. Putyin elnök úgy határozott, hogy ennek ellenére sem bojkottálják az olimpiát. Hol rendezték a téli olimpiát 2018-ban?', 3, ['Peking (Kína)', 'Szocsi (Oroszország)', 'Vancouver (Kanada)', 'Phjongcshang (Dél-Korea)'], 'Helyes válasz: Phjongcshang (Dél-Korea)'),
    _q('A palástban, püspöksüvegben és pásztorbottal ajándékokat osztó Mikulás eredetileg a katolikus vallású vidékeken Szent Miklós népies alakja volt. Mára azonban globalizálódott és elvilágiasodott az alakja: a két világháború között a Mikulás a gyerekeket a mennyből figyelte, segítői pedig manók, angyalok vagy krampuszok voltak, manapság Mikulás Lappföldön vagy az Északi-sarkon él és szánját rénszarvasok húzzák. Piros ruhás, fehér szakállas alakként ábrázolása a Coca-Cola kampánya nyomán terjed el, bár az eredete korábbi. Melyik évből származik az első Coca-Cola Mikulás?', 0, ['1931', '1951', '1971', '1991'], 'Helyes válasz: 1931'),
    _q('1930. december 7-én adták át a közönségnek a Margit-szigeten a Nemzeti Sportuszodát, amely ma a tervező, Hajós Alfréd nevét viseli. Átadásakor Európa legnagyobb fedett úszócsarnokának számított, a maga 33 m hosszúságú és 18 m széles úszómedencéjével. Hajós Alfréd hazánk első úszó olimpiai bajnoka. Milyen úszásnemben győzedelmeskedett először?', 3, ['1000 méteres hátúszás', '200 méteres mellúszás', '2000 méteres gyorsúszás', '100 méteres gyorsúszás'], 'Helyes válasz: 100 méteres gyorsúszás'),
    _q('December 8-a Buddha megvilágosodásának napja Japánban. Buddha elsősorban Kelet-Indiában élt és tanított, valamikor az i.e. 6. és 4. század között. Nevének jelentése: megvilágosodott. A buddhizmusban melyik szín szimbolizálja a bölcsességet, Buddha tanításait?', 2, ['kék', 'zöld', 'narancssárga', 'fehér'], 'Helyes válasz: narancssárga'),
    _q('1859. december 11-én jelent meg először sakkfeladvány a magyar sajtóban: a Vasárnapi Ujság közölte Rozsnyay Mátyás fejtörőjét egy végjátékkal kapcsolatban. A következő évtől aztán rendszeressé váltak a feladványok, a lap 1921-es megszűnéséig több mint háromezer jelent meg. Mikor volt az első sakkvilágbajnokság?', 1, ['1866', '1886', '1906', '1926'], 'Helyes válasz: 1886'),
    _q('1675. december 15-én temették el a 43 éves korában elhunyt Jan Vermeer van Delft holland festőt. Rembrandt és ő voltak a holland aranykor legnagyobb művészei. Leghíresebb műve a Leány gyöngy fülbevalóval című festmény, amit az Észak Mona Lisájának neveznek. Hol tekinthető meg a mű?', 3, ['Párizsban', 'Londonban', 'New Yorkban', 'Hágában'], 'Helyes válasz: Hágában'),
    _q('1867. december 15-én, 53 éves korában hunyt el Ganz Ábrahám svájci származású vasöntőmester, gyáros, a magyar nehézipar egyik megteremtője. Az általa alapított öntödében 1969 óta az Öntödei Múzeum működik. Hol található?', 1, ['Miskolcon', 'Budán', 'Sopronban', 'Székesfehérváron'], 'Helyes válasz: Budán'),
    _q('2011. december 17-én, 69 éves korában hunyt el Kim Dzsongil észak-koreai politikus, a Koreai Népi Demokratikus Köztársaság legfelsőbb vezetője. Legismertebb megszólítása a Kedves Vezető volt, azonban időskorában már „Nagy Vezető”-ként szólították. Halálakor nemzeti gyászt hirdettek az országban. Mennyi ideig tartott?', 3, ['1 hétig', '1 hónapig', '1 évig', '3 évig'], 'Helyes válasz: 3 évig'),
    _q('1909. december 19-én alapították a Borussia Dortmund sportegyesületet, amely Németország egyik legsikeresebb klubja: a Bundesliga örökranglistáján a harmadik helyen áll. A csapatot nemcsak a múltja, hanem egyedülálló szurkolótábora miatt is Európa legnagyobb klubjai közé sorolják. A Signal Iduna Park stadion minden mérkőzésen megtelik, a dortmundi átlagnézőszám egyedülálló Európában. Hány fős a stadion?', 3, ['kb. húszezer', 'kb. negyvenezer', 'kb. hatvanezer', 'kb. nyolcvanezer'], 'Helyes válasz: kb. nyolcvanezer'),
    _q('2000. december 19-én, 67 éves korában hunyt el Végh Antal magyar író, szociográfus, pedagógus, újságíró. Mi a címe az 1986-ban megjelent művének, amely a magyar futballról szól és a mexikói világbajnokság után jelent meg?', 1, ['Szép volt, fiúk!', 'Gyógyít(6)atlan?', 'Könyörtelenül', 'Miért vesztettek Puskásék?'], 'Helyes válasz: Gyógyít(6)atlan?'),
    _q('1998. december 20-án született Kylian Mbappé Lottin világbajnok francia válogatott labdarúgó, a Paris Saint-Germain csatára. Apja kameruni, anyja algériai származású. Melyik országban nyert világbajnokságot, 2018-ban?', 2, ['Dél-afrikai Köztársaság', 'Franciaország', 'Oroszország', 'Németország'], 'Helyes válasz: Oroszország'),
    _q('1962. december 22-én született Ralph Fiennes angol színpadi, film- és szinkronszínész. Több magyar vonatkozású filmben is játszott. Melyik volt az, amelyben szerepe szerint a magyar csapat tagjaként vívó olimpiai bajnok lesz?', 3, ['Az angol beteg', 'Álmomban már láttalak', 'Vakok földjén', 'A napfény íze'], 'Helyes válasz: A napfény íze'),
    _q('1863. január 1-jén született Pierre de Coubertin, a Nemzetközi Olimpiai Bizottság egyik alapítója.Hol lett volna nyári olimpia 2020-ban?', 1, ['London', 'Tokió', 'Budapest', 'Párizs'], 'Helyes válasz: Tokió'),
    _q('1969-ben ezen a napon született Marilyn Manson amerikai énekes, dalszövegíró, zenész, zeneszerző, színész, festő, író és zenei újságíró. Neve két részből álló felvett név – kitől kölcsönözte a vezetéknevét?', 0, ['Egy gyilkos szektavezértől', 'Egy kábítószer feltalálójától', 'Egy hajléktalantól, aki a háza előtt szokott ücsörögni', 'Egy olimpiai bajnok sportolótól'], 'Helyes válasz: Egy gyilkos szektavezértől'),
    _q('2014-ben ezen a napon hunyt el Eusébio, aranylabdás portugál labdarúgó. Mi volt a beceneve?', 2, ['Kitörő Vulkán', 'Viharos Szél', 'Fekete Párduc', 'Sebes Gazella'], 'Helyes válasz: Fekete Párduc'),
    _q('1921. január 9-én született Keleti Ágnes, a Nemzet Sportolója címmel kitüntetett ötszörös olimpiai bajnok magyar tornász; a magyar tornasport legeredményesebb versenyzője. Melyik olimpián nyert négy aranyérmet?', 2, ['London, 1948', 'Helsinki, 1952', 'Melbourne, 1956', 'Róma, 1960'], 'Helyes válasz: Melbourne, 1956'),
    _q('2015. január 11-én hunyt el Buzánszky Jenő, a Nemzet Sportolója címmel kitüntetett 49-szeres magyar válogatott labdarúgó, az Aranycsapat tagja, edző, sportvezető. Milyen poszton játszott az Aranycsapatban?', 2, ['csatár', 'kapus', 'hátvéd', 'középpályás'], 'Helyes válasz: hátvéd'),
    _q('Évtizedeken keresztül január közepén rendezték a Formula–1 argentin nagydíját, Buenos Aires-ben.2025-ben hányadik szezonja lesz ennek az autós világbajnokság-sorozatnak?', 2, ['34.', '58.', '76.', '102.'], 'Helyes válasz: 76.'),
    _q('1933-ban ezen a napon született Rockenbauer Pál, természetjáró, világutazó, televíziós szerkesztő, a magyar televíziós természetfilmezés egyik megteremtője. Milyen útvonalat járt végig a Másfélmillió lépés Magyarországon sorozatában?', 2, ['Soprontól Békéscsabáig "átlósan" sétálta keresztbe az országot', 'Körbejárta Magyarországot a határ mellett', 'Az országos kék túra útvonalát', 'A Duna magyarországi szakasza mellett haladt végig'], 'Helyes válasz: Az országos kék túra útvonalát'),
    _q('1942. január 17-én született Muhammad Ali, olimpiai és világbajnok amerikai nehézsúlyú ökölvívó, polgárjogi aktivista, ENSZ-békenagykövet. Miért ítélték öt év börtönre 1967-ben?', 1, ['többször útlevél nélkül kelt át a határon', 'megtagadta a katonai szolgálatot', 'közlekedési balesetet okozott', 'verekedésbe keveredett egy kocsmában'], 'Helyes válasz: megtagadta a katonai szolgálatot'),
    _q('1901. január 19-én alakult meg a Magyar Labdarúgó-szövetség (MLSZ). Válogatottunk első mérkőzését 1902 októberében játszotta. Melyik ország csapatától kaptunk ki 5 – 0-ra?', 1, ['Anglia', 'Ausztria', 'Franciaország', 'Németország'], 'Helyes válasz: Ausztria'),
    _q('1734. január 23-án született Kempelen Farkas, akinek számtalan találmánya volt. Melyik NEM az ő nevéhez fűződik?', 0, ['villámhárító', 'nyomtatógép vakok számára', 'sakkozógép', 'beszédkeltő gép'], 'Helyes válasz: villámhárító'),
    _q('1994-ben Lékó Péter sakkozó minden idők legfiatalabb nemzetközi nagymestere lett. Hány éves volt ekkor?', 1, ['12', '14', '16', '18'], 'Helyes válasz: 14'),
    _q('1606. január 31-én végezték ki Londonban Guy Fawkest, aki I. Jakab angol király ellen tervezett merényletet elkövetni. Melyik állítás NEM igaz vele kapcsolatban?', 3, ['Maszkja napjainkban az Anonymous hackercsoport jelképe', '1605-től egészen 1859-ig minden évben örömtüzekkel ünnepelték, hogy I. Jakab megmenekült a merénylettől', 'Társaival együtt I. Jakab helyett katolikus uralkodót akart az angol trónra ültetni', 'A merénylet leleplezésekor elfogták, de nem árulta el társait'], 'Helyes válasz: A merénylet leleplezésekor elfogták, de nem árulta el társait'),
    _q('1878. február 1-jén született Hajós Alfréd sportoló, építészmérnök. Melyik állítás NEM igaz vele kapcsolatban?', 3, ['Eredeti neve Guttmann Arnold, beceneve a „Magyar delfin” volt', 'Ő szerezte meg a magyar sport első és második olimpiai győzelmét', 'Labdarúgó-játékvezetőként tevékenykedett 1897-től', 'Az általa tervezett épületekből ma már egy sem áll'], 'Helyes válasz: Az általa tervezett épületekből ma már egy sem áll'),
    _q('1977-ben ezen a napon született Shakira Grammy-díjas kolumbiai énekesnő. Melyik futball-világbajnokság hivatalos indulója volt Waka Waka című dala?', 1, ['2006-os labdarúgó-világbajnokság (Németország)', '2010-es labdarúgó-világbajnokság (Dél-Afrikai Köztársaság)', '2014-es labdarúgó-világbajnokság (Brazília)', '2018-as labdarúgó-világbajnokság (Oroszország)'], 'Helyes válasz: 2010-es labdarúgó-világbajnokság (Dél-Afrikai Köztársaság)'),
    _q('1985. február 5-én született Cristiano Ronaldo portugál labdarúgó. A Real Madridban töltött évei alatt megdöntötte Puskás Ferenc rekordját, aki egy idény alatt 49 gólt rúgott. Mennyi az új rekord?', 3, ['50', '53', '56', '61'], 'Helyes válasz: 61'),
    _q('1922. február 5-én született Szepesi György, „az Aranycsapat tizenkettedik játékosa”. Ő közvetítette az „évszázad mérkőzését”, amelyen a magyarok 6:3 arányban legyőzték az angolokat. Mikor is volt ez a mérkőzés?', 2, ['1951. április 25.', '1953. április 25.', '1953. november 25.', '1955. november 25.'], 'Helyes válasz: 1953. november 25.'),
    _q('1936. február 6-án  volt a téli olimpia megnyitója a németországi Garmisch-Partenkirchenben. Melyik állítás NEM igaz?', 0, ['A magyar versenyzők két arany és egy ezüst érmet szereztek', 'Az éremtáblázat első helyén Norvégia végzett 7 arannyal, 5 ezüsttel és 3 bronzéremmel', 'Az alpesisí első alkalommal szerepelt a téli olimpiai játékok programjában', 'A garmisch-partenkircheni olimpia volt az első, amelyről a Magyar Rádió is beszámolt'], 'Helyes válasz: A magyar versenyzők két arany és egy ezüst érmet szereztek'),
    _q('1898-ban ezen a napon született Bertolt Brecht német drámaíró, költő, rendező, a 20. századi színház egyik megújítója. Egyik legismertebb műve a Koldusopera. Hol játszódik a darab?', 1, ['New York-ban', 'Londonban', 'Berlinben', 'Párizsban'], 'Helyes válasz: Londonban'),
    _q('1917. február 13-án kémkedés vádjával párizsi hotelszobájában letartóztatták Mata Harit. Bíróság elé állították és kivégezték, 2001-ben azonban felülvizsgálták az ügyét. Mit állapítottak meg?', 2, ['Megállapították, hogy Mata Hari kettős ügynök volt, nemcsak a németeknek, hanem a francia hadseregnek is szállított információkat', 'Nem találtak hibát az 1917-es perben, de megállapították, hogy az akkori törvények alapján nem volt jogalap a kivégzésére', 'A vizsgálat megállapította, hogy Mata Hari ártatlan, a kémkedésért egy másik kémnő, a „Doktor kisasszony” a felelős', 'Megállapították, hogy az 1917-es perben a bizonyítékok egy részét szándékosan eltüntették, ezért nem vonták felelősségre minden tettéért'], 'Helyes válasz: A vizsgálat megállapította, hogy Mata Hari ártatlan, a kémkedésért egy másik kémnő, a „Doktor kisasszony” a felelős'),
    _q('1779. február 14-én hunyt el James Cook brit hajóskapitány, felfedező. Melyik állítás NEM igaz?', 1, ['Ő hajózta körül először az Antarktiszt', 'Három nagy expedíciót vezetett, majd Londonban hunyt el', 'Ő fedezte fel Hawaii-t', 'Az ő hajója lépte át először a déli sarkkört'], 'Helyes válasz: Három nagy expedíciót vezetett, majd Londonban hunyt el'),
    _q('Február 15-én indult el Budapesten a telefonhírmondó szolgáltatás, Puskás Tivadar találmánya alapján. „Üdvözöljük Budapest lakosságát. Üdvözöljük olyan szokatlan módon, amely páratlan az egész világon. Üdvözöljük az első várost, amelyből a Telefonhírmondó az egész világon győzedelmes útjára indul.” Melyik évben történt mindez?', 1, ['1877', '1893', '1918', '1923'], 'Helyes válasz: 1893'),
    _q('1963. február 17-én született Michael Jordan amerikai kosárlabdázó, aki óriási sikerek után 1993-ban bejelentette visszavonulását és a következő évtől kipróbálta magát egy másik sportágban. Melyikben?', 2, ['kézilabda', 'tenisz', 'baseball', 'futás'], 'Helyes válasz: baseball'),
]